CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.BUSINESS_ACTIVITY`
(
  BUSINESS_ACTIVITY_CDE STRING NOT NULL,
  BUSINESS_ACTIVITY_SUB_CDE STRING NOT NULL,
  BUSINESS_ACTIVITY_DESC_TXT STRING NOT NULL
);