CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_CV`
(
  KUNNR_KNA1 STRING OPTIONS(description="Customer Number"),
  VRSN_START_DTE DATE OPTIONS(description="Derived by data engineering"),
  VRSN_END_DTE DATE OPTIONS(description="Derived by data engineering"),
  CURR_VRSN_FLG STRING OPTIONS(description="Derived by data engineering"),
  NAME1_KNA1 STRING OPTIONS(description="Customer Name"),
  NAME2_KNA1 STRING OPTIONS(description="Customer License Name"),
  NAME3_KNA1 STRING OPTIONS(description="Customer DBA Name"),
  NAME4_KNA1 STRING OPTIONS(description="Customer Preferred Name"),
  STRAS_KNA1 STRING OPTIONS(description="Address Text"),
  ORT01_KNA1 STRING OPTIONS(description="City"),
  PSTLZ_KNA1 STRING OPTIONS(description="Zip"),
  REGIO_KNA1 STRING OPTIONS(description="State"),
  LAND1_KNA1 STRING OPTIONS(description="Country Code"),
  ORT02_KNA1 STRING OPTIONS(description="County"),
  PFACH_KNA1 STRING OPTIONS(description="PO Box"),
  PSTL2_KNA1 STRING OPTIONS(description="PO Box Zip"),
  TIME_ZONE_ADRC STRING OPTIONS(description="Time Zone"),
  TELF1_KNA1 STRING OPTIONS(description="Telephone Number"),
  TELFX_KNA1 STRING OPTIONS(description="Fax Number"),
  LOEVM_KNA1 STRING OPTIONS(description="Deletion Indicator Flag"),
  SORTL_KNA1 STRING OPTIONS(description="Sort Field Text"),
  AUFSD_KNA1 STRING OPTIONS(description="Central Order Block  ID"),
  VTEXT_TVAST_CENTRAL_ORDER_BLOCK STRING OPTIONS(description="Central Order Block Description Text;CENTRAL_ORDER_BLOCK.VTEXT_TVAST where CENTRAL_ORDER_BLOCK.AUFSP_TVAST = KNA1.AUFSD"),
  BBBNR_KNA1 INT64 OPTIONS(description="International Location Part 1 Number"),
  BBSNR_KNA1 INT64 OPTIONS(description="International Location Part 2 Number"),
  BRSCH_KNA1 STRING OPTIONS(description="Industry key  ID"),
  BRTXT_T016T_INDUSTRY_KEY STRING OPTIONS(description="Industry key Description Text;INDUSTRY_KEY.BRTXT_T016T where INDUSTRY_KEY.BRSCH_T016T = KNA1.BRSCH"),
  CALC_340B_CUSTOMER_FLG STRING OPTIONS(description="Calculated 340B Customer Flag;If LEFT(KNA1.BRSCH, 3) = 340, then Y else N"),
  CALC_GPO_CUSTOMER_FLG STRING OPTIONS(description="Calculated GPO Customer Flag;If KNA1.BRSCH = MA, then Y else N"),
  BUBKZ_KNA1 INT64 OPTIONS(description="International Location Checkdigit Number"),
  ERDAT_KNA1 DATE OPTIONS(description="Created On Date;Convert KNA1.ERDAT to ISO format, default for invalid date = 1900-01-01"),
  ERNAM_KNA1 STRING OPTIONS(description="Created By User ID"),
  FAKSD_KNA1 STRING OPTIONS(description="Central Billing Block  ID"),
  VTEXT_TVFST_CENTRAL_BILLING_BLOCK STRING OPTIONS(description="Central Billing Block Description Text;CENTRAL_BILLING_BLOCK.VTEXT_TVFST where CENTRAL_BILLING_BLOCK.FAKSP_TVFST = KNA1.FAKSD"),
  KTOKD_KNA1 STRING OPTIONS(description="Customer Account Group  ID"),
  TXT30_T077X_CUSTOMER_ACCOUNT_GROUP STRING OPTIONS(description="Customer Account Group Description Text;CUSTOMER_ACCOUNT_GROUP.TXT30_T077X where CUSTOMER_ACCOUNT_GROUP.KTOKD_T077X = KNA1.KTOKD"),
  KUKLA_KNA1 STRING OPTIONS(description="Customer Class Of Trade  ID"),
  VTEXT_TKUKT_CUSTOMER_CLASS_OF_TRADE STRING OPTIONS(description="Customer Class Of Trade Description Text;Customer_Class_Of_Trade.Customer_Class_Of_Trade_Description_Text where Customer_Class_Of_Trade.Customer_Class_Of_Trade_ID = KNA1.KUKLA"),
  LIFSD_KNA1 STRING OPTIONS(description="Central Delivery Block  ID"),
  VTEXT_TVLST_CENTRAL_DELIVERY_BLOCK STRING OPTIONS(description="Central Delivery Block Description Text;CENTRAL_DELIVERY_BLOCK.VTEXT_TVLST where CENTRAL_DELIVERY_BLOCK.LIFSP_TVLS = KNA1.LIFSD"),
  SPERR_KNA1 STRING OPTIONS(description="Central Posting Block Flag;If KNA1.SPERR = X then Y else N"),
  LZONE_KNA1 STRING OPTIONS(description="Transportation Zone ID"),
  VBUND_KNA1 STRING OPTIONS(description="Trading Partner Company  ID"),
  NAME1_T880_TRADING_PARTNER_COMPANY STRING OPTIONS(description="Trading Partner Company Name;TRADING_PARTNER_COMPANY.NAME1_T880 where TRADING_PARTNER_COMPANY.RCOMP_T880 = KNA1.VBUND"),
  GFORM_KNA1 STRING OPTIONS(description="Legal status  ID"),
  VTEXT_TVGFT_LEGAL_STATUS STRING OPTIONS(description="Legal status Description Text;LEGAL_STATUS.VTEXT_TVGFT where LEGAL_STATUS.GFORM_TVGFT = KNA1.GFORM"),
  KATR1_KNA1 STRING OPTIONS(description="EZ Cart Delivery Program Flag;If KNA1.KATR1 = 01 then Y else N"),
  KATR2_KNA1 STRING OPTIONS(description="Double QC Flag;If KNA1.KATR2 = 01 then Y else N"),
  KATR3_KNA1 STRING OPTIONS(description="OE replicate price catalog flag;If KNA1.KATR3 = X then N else Y"),
  KATR4_KNA1 STRING OPTIONS(description="eReceiver Customer Flag;If KNA1.KATR4 = 4A then Y else N"),
  KATR5_KNA1 STRING OPTIONS(description="SPD Material Special Payment Terms Exclusion Flag;If KNA1.KATR5 = MT then Y else N"),
  KATR6_KNA1 STRING OPTIONS(description="Backorder Restriction  ID"),
  VTEXT_TVK6T_BACKORDER_RESTRICTION STRING OPTIONS(description="Backorder Restriction Description Text;BACKORDER_RESTRICTION.VTEXT_TVK6T where BACKORDER_RESTRICTION.KATR6_TVK6T = KNA1.KATR6"),
  KATR7_KNA1 STRING OPTIONS(description="OTC Restriction  ID"),
  VTEXT_TVK7T_OTC_RESTRICTION STRING OPTIONS(description="OTC Restriction Description Text;OTC_RESTRICTION.VTEXT_TVK7T where OTC_RESTRICTION.VTEXT_TVK7T = KNA1.KATR7"),
  KATR8_KNA1 STRING OPTIONS(description="C2 Restriction  ID"),
  VTEXT_TVK8T_C2_RESTRICTION STRING OPTIONS(description="C2 Restriction Description Text;C2_RESTRICTION.VTEXT_TVK8T where C2_RESTRICTION.KATR8_TVK8T = KNA1.KATR8"),
  GENDA_EMBK DATE OPTIONS(description="Calculated DEA License Valid To Date;Convert EMBK.GENDA to ISO format, default for invalid date = 1900-01-01"),
  CALC_PHYSCN_STATE_LIC_ID STRING OPTIONS(description="Calculated Physician State License ID;EMBK.EXGEN where EMBK.GEGRU = ST and EMBK.GEART = PH and EMBK.GENST = C and EMBK.GENNR = T606Z.GENNR and KNA1.KUNNR = T606Z.KUNNR and CURRENT_DATE between EMBK.GANDA and EMBK.GENDA --ST = State Business Regulation; PH = Physicians License; C = Application accepted, license active"),
  CALC_PHYSCN_STATE_LIC_VALID_TO_DTE DATE OPTIONS(description="Calculated Physician State License Valid To Date;Convert EMBK.GENDA to ISO format, default for invalid date = 1900-01-01"),
  CALC_PHYSCN_DME_LIC_ID STRING OPTIONS(description="Calculated Physician DME License ID;EMBK.EXGEN where EMBK.GEGRU = DM and EMBK.GEART = DME and EMBK.GENST = C and EMBK.GENNR = T606Z.GENNR and KNA1.KUNNR = T606Z.KUNNR and CURRENT_DATE between EMBK.GANDA and EMBK.GENDA --DM = DME regulation; DME = Durable Medical Equipment License; C = Application accepted, license active"),
  CALC_PHYSCN_DME_LIC_VALID_TO_DTE DATE OPTIONS(description="Calculated Physician DME License Valid To Date;Convert EMBK.GENDA to ISO format, default for invalid date = 1900-01-01"),
  CALC_EXGEN_ST_PRIS_EMBK STRING OPTIONS(description="Calculated State Prescription License Number;GEART_EMBK ='RX' AND GENST_EMBK ='C' AND datenow >= CALC_GANDA_ST_PRIS_LIC_EMBK AND CURRENT_DATE between EMBK.GANDA and EMBK.GENDA"),
  CALC_GENDA_ST_PRIS_LIC_EMBK DATE OPTIONS(description="State Prescription License Validity End Date;Convert EMBK.GENDA to ISO format, default for invalid date = 1900-01-01"),
  CALC_EXGEN_ST_LIC_EMBK STRING OPTIONS(description="Calculated State License Number;GEART_EMBK ='RX' AND GENST_EMBK ='C' AND datenow >= CALC_GANDA_ST_LIC_EMBK AND CURRENT_DATE between EMBK.GANDA and EMBK.GENDA"),
  CALC_GENDA_ST_LIC_EMBK DATE OPTIONS(description="State License Validity End Date;Convert EMBK.GENDA to ISO format, default for invalid date = 1900-01-01"),
  TXJCD_KNA1 STRING OPTIONS(description="Tax Jurisdiction ID"),
  CIVVE_KNA1 STRING OPTIONS(description="Non Military Use Flag;If KNA1.CIVVE = X then Y else N"),
  YYPRIME_KNA1 STRING OPTIONS(description="Customer Primary BU  ID"),
  DESCR_YTSD_PRIMARY_BU_PRIMARY_BUSINESS_UNIT STRING OPTIONS(description="Customer Primary BU Description Text;PRIMARY_BUSINESS_UNIT.DESCR_YTSD_PRIMARY_BU where PRIMARY_BUSINESS_UNIT.YYPRIME_YTSD_PRIMARY_BU = KNA1.YYPRIME"),
  YYPGSTART_KNA1 DATE OPTIONS(description="Marketing Relationship Effective Date;Convert KNA1.YYPGSTART to ISO format, , default for invalid date = 1900-01-01"),
  YYPGEND_KNA1 DATE OPTIONS(description="Marketing Relationship End Date;Convert KNA1.YYPGEND to ISO format, default for invalid date = 1900-01-01"),
  YYOPDXMPT_KNA1 STRING OPTIONS(description="Opioid Exempt Flag;If KNA1.YYOPDXMPT = X then Y else N"),
  YYFRTMON_KNA1 STRING OPTIONS(description="Monday Free Shipping Day Flag;If KNA1.YYFRTMON = X then Y else N"),
  YYFRTTUE_KNA1 STRING OPTIONS(description="Tuesday Free Shipping Day Flag;If KNA1.YYFRTTUE = X then Y else N"),
  YYFRTWED_KNA1 STRING OPTIONS(description="Wednesday Free Shipping Day Flag;If KNA1.YYFRTWED = X then Y else N"),
  YYFRTTHU_KNA1 STRING OPTIONS(description="Thursday Free Shipping Day Flag;If KNA1.YYFRTTHU = X then Y else N"),
  YYFRTFRI_KNA1 STRING OPTIONS(description="Friday Free Shipping Day Flag;If KNA1.YYFRTFRI = X then Y else N"),
  YYFRTSAT_KNA1 STRING OPTIONS(description="Saturday Free Shipping Day Flag;If KNA1.YYFRTSAT = X then Y else N"),
  YYFRTSUN_KNA1 STRING OPTIONS(description="Sunday Free Shipping Day Flag;If KNA1.YYFRTSUN = X then Y else N"),
  TATYP_KNVI STRING OPTIONS(description="Tax Category ID;KNVI.TATYP where KNVI.KUNNR = KNA1.KUNNR --KNVI.ALAND = US for all records"),
  TAXKD_KNVI STRING OPTIONS(description="Tax Classification  ID;KNVI.TAXKD where KNVI.KUNNR = KNA1.KUNNR --KNVI.TATYP = UTXJ for all records"),
  VTEXT_TSKDT_TAX_CLASSIFICATION STRING OPTIONS(description="Tax Classification Description Text;TAX_CLASSIFICATION.VTEXT_TSKDT where TAX_CLASSIFICATION.TAXKD_TSKDT = KNVI.TAXKD"),
  ADRNR_KNA1 STRING OPTIONS(description="Address Reference Number ID"),
  BUILDING_ADRC STRING OPTIONS(description="Building ID;ADRC.BUILDING where KNA1.ADRNR = ADRC.ADDRNUMBER"),
  TXT30_T077X STRING OPTIONS(description="Customer Account Group Name"),
  LANDX50_T005T STRING OPTIONS(description="Country Name"),
  NATIO50_T005T STRING OPTIONS(description="Nationality"),
  VTEXT_TVAST STRING OPTIONS(description="Order Block ReasonText"),
  VTEXT_TVFST STRING OPTIONS(description="Billing Block Reason Text"),
  VTEXT_TVLST STRING OPTIONS(description="Delivery Block Reason Text"),
  COUNC_KNA1 STRING OPTIONS(description="Country Code"),
  EXABL_KNA1 STRING OPTIONS(description="Unloading Points Exist Flag"),
  KNAZK_KNA1 STRING OPTIONS(description="Working Time Calendar"),
  KNRZA_KNA1 STRING OPTIONS(description="Alternative Payer Account ID"),
  LIFNR_KNA1 STRING OPTIONS(description="Vendor Or Creditor Account ID"),
  STCD1_KNA1 STRING OPTIONS(description="Tax Number 1"),
  STCD2_KNA1 STRING OPTIONS(description="Tax Number 2"),
  STCD3_KNA1 STRING OPTIONS(description="Tax Number 3"),
  STCD4_KNA1 STRING OPTIONS(description="Tax Number 4"),
  SPERZ_KNA1 STRING OPTIONS(description="Payment Block Flag"),
  CASSD_KNA1 STRING OPTIONS(description="Central Sales Block ID"),
  NODEL_KNA1 STRING OPTIONS(description="Central Deletion Block ID"),
  MCOD1_KNA1 STRING OPTIONS(description="Search term for matchcode search"),
  MCOD2_KNA1 STRING OPTIONS(description="Search Term for Matchcode Search"),
  MCOD3_KNA1 STRING OPTIONS(description="Search term for matchcode search"),
  ANRED_KNA1 STRING OPTIONS(description="Title"),
  BAHNE_KNA1 STRING OPTIONS(description="Express train station"),
  BAHNS_KNA1 STRING OPTIONS(description="Train station"),
  BEGRU_KNA1 STRING OPTIONS(description="Authorization Group"),
  DATLT_KNA1 STRING OPTIONS(description="Data communication line no."),
  KONZS_KNA1 STRING OPTIONS(description="Group key"),
  NIELS_KNA1 STRING OPTIONS(description="Nielsen ID"),
  SPRAS_KNA1 STRING OPTIONS(description="Language Key"),
  TELF2_KNA1 STRING OPTIONS(description="Second telephone number"),
  XZEMP_KNA1 STRING OPTIONS(description="Indicator: Is an alternative payer allowed in document?"),
  STCEG_KNA1 STRING OPTIONS(description="VAT Registration Number"),
  BRAN1_KNA1 STRING OPTIONS(description="Industry Code 1"),
  KATR10_KNA1 STRING OPTIONS(description="Attribute 10"),
  WERKS_KNA1 STRING OPTIONS(description="Plant"),
  HZUOR_KNA1 STRING OPTIONS(description="Assignment to Hierarchy"),
  PFORT_KNA1 STRING OPTIONS(description="PO Box city"),
  MILVE_KNA1 STRING OPTIONS(description="ID for mainly military use"),
  FITYP_KNA1 STRING OPTIONS(description="Tax type"),
  KNURL_KNA1 STRING OPTIONS(description="Uniform Resource Locator"),
  J_1KFTBUS_KNA1 STRING OPTIONS(description="Type of Business"),
  J_1KFTIND_KNA1 STRING OPTIONS(description="Type of Industry"),
  YYHRSA_KNA1 STRING OPTIONS(description="HRSA ID"),
  YYHIN_KNA1 STRING OPTIONS(description="Health Industry Number"),
  PARTNER_UKMBP_CMS STRING OPTIONS(description="Business Partner ID"),
  CREDIT_GROUP_UKMBP_CMS STRING OPTIONS(description="Customer Credit Group Code"),
  YNAT_ACC_YTSD_NAT_ACCOUNT STRING OPTIONS(description="National Account ID"),
  YNAME_YTSD_NAT_ACCOUNT STRING OPTIONS(description="National Account Name"),
  FAUSA_T077D STRING OPTIONS(description="Customer General Data Field Status"),
  FAUSF_T077D STRING OPTIONS(description="Customer Company Code Data Field Status"),
  FAUSV_T077D STRING OPTIONS(description="Customer Sales Area Data Field Status"),
  XCPDS_T077D STRING OPTIONS(description="Account Group For One Time Account Flag"),
  DEAR1_T077D STRING OPTIONS(description="Competitor Flag"),
  DEAR2_T077D STRING OPTIONS(description="Sales Partner Flag"),
  DEAR3_T077D STRING OPTIONS(description="Sales Prospect Flag"),
  DEAR4_T077D STRING OPTIONS(description="Customer Type4 Flag"),
  DEAR5_T077D STRING OPTIONS(description="Default Sold To Party ID"),
  DEAR6_T077D STRING OPTIONS(description="Consumer Flag"),
  STREET_ADRC STRING OPTIONS(description="Address Street"),
  POST_CODE1_ADRC STRING OPTIONS(description="Address City Postal Code"),
  CITY1_ADRC STRING OPTIONS(description="Address City"),
  COUNTRY_ADRC STRING OPTIONS(description="Address Country ID"),
  REGION_ADRC STRING OPTIONS(description="Address Region"),
  TEXJURCODE_ADRC STRING OPTIONS(description="Address Tax Jurisdiction"),
  PO_BOX_ADRC STRING OPTIONS(description="Adddress PO Box"),
  POST_CODE2_ADRC STRING OPTIONS(description="Postal Code Address"),
  POST_CODE3_ADRC STRING OPTIONS(description="Address Company Postal Code"),
  LANGU_ADRC STRING OPTIONS(description="Communication Language ID"),
  TELNR_LONG_ADRC STRING OPTIONS(description="Complete Telephone Number"),
  SMTP_ADDR_ADRC STRING OPTIONS(description="EMail Address"),
  FAXNR_LONG_ADRC STRING OPTIONS(description="Complete Fax Number"),
  BRTXT_T016T STRING OPTIONS(description="Description of the Industry Key"),
  VTEXT_TKUKT STRING OPTIONS(description="Customer Classification Text"),
  HOUSE_NUM1_ADRC STRING OPTIONS(description="Address House Number"),
  CALC_BRSCH_KNA1 STRING OPTIONS(description="340B Customer Flag"),
  TITLE_MEDI_TSAD3T STRING OPTIONS(description="Form Of Address Title Text"),
  ZSLTSTMP STRING OPTIONS(description="ZSLTSTMP"),
  STR_SUPPL1_ADRC STRING OPTIONS(description="Address Street2"),
  CALC_GPO_CUST_FLAG STRING OPTIONS(description="GPO Customer Flag"),
  CALC_WAC_CUST_FLAG STRING OPTIONS(description="WAC Cstomer Flag"),
  COMPOSITE_KEY STRING OPTIONS(description="Composite key to identify records in initial load"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Indicates date the row was inserted"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Indicates by which job the row was inserted"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Indicates date the row was updated"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Indicates by which job the row was updated")
)
PARTITION BY VRSN_START_DTE
CLUSTER BY KUNNR_KNA1, VRSN_START_DTE, CURR_VRSN_FLG;