CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_EDI832_PARAMETER_CV`
(
  KUNNR_CHPDPE_CD_PARAM STRING NOT NULL OPTIONS(description="Customer Number"),
  VKORG_CHPDPE_CD_PARAM STRING NOT NULL OPTIONS(description="Sales Organization ID"),
  VTWEG_CHPDPE_CD_PARAM STRING NOT NULL OPTIONS(description="Distribution Channel ID"),
  SPART_CHPDPE_CD_PARAM STRING NOT NULL OPTIONS(description="Division ID"),
  TRADING_PTR_CHPDPE_CD_PARAM STRING NOT NULL OPTIONS(description="EDI832 Trading Partner ID"),
  ACTIVE_CHPDPE_CD_PARAM STRING OPTIONS(description="Active Flag"),
  NHIN_FLG_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Customer Flag"),
  AWP_FLG_CHPDPE_CD_PARAM STRING OPTIONS(description="AWP Flag"),
  INV_FLG_CHPDPE_CD_PARAM STRING OPTIONS(description="Invoice Only Flag"),
  SUP_340B_FLG_CHPDPE_CD_PARAM STRING OPTIONS(description="Suppress Price 340B Flag"),
  PRIORITY_CHPDPE_CD_PARAM INT64 OPTIONS(description="EDI 832 Catalog Priority Code"),
  INCODE_CHPDPE_CD_PARAM STRING OPTIONS(description="Inclusion Code"),
  DESCR_CHPDPE_IN_CDT STRING OPTIONS(description="Inclusion Description Text; CHPDPE_IN_CDT.DESCR where CHPDPE_IN_CDT.INCODE = CHPDPE_CD_PARAM.INCODE"),
  SINCODE_CHPDPE_CD_PARAM STRING OPTIONS(description="Status Inclusion Code"),
  DESCR_CHPDPE_SIN_CDT STRING OPTIONS(description="Status Inclusion Description Text; CHPDPE_SIN_CDT.DESCR where CHPDPE_SIN_CDT.SINCODE = CHPDPE_CD_PARAM.SINCODE"),
  SI_TWCODE_CHPDPE_CD_PARAM STRING OPTIONS(description="Status Inclusion Time Window Code"),
  SI_NOOFDAY_CHPDPE_CD_PARAM INT64 OPTIONS(description="Status Inclusion Days Quantity"),
  SI_NOOFMTH_CHPDPE_CD_PARAM INT64 OPTIONS(description="Status Inclusion Months Quantity"),
  INV_DAYS_CHPDPE_CD_PARAM INT64 OPTIONS(description="Invoices Lookback Days Quantity"),
  CAT_TYPE1_CHPDPE_CD_PARAM STRING OPTIONS(description="Catalog Type 1 ID"),
  SCOPT1_CHPDPE_CD_PARAM STRING OPTIONS(description="Catalog Distribution Scheduling Option 1 ID"),
  DESCR_CHPDPE_SCOPT1 STRING OPTIONS(description="Catalog Distribution Scheduling Option 1 Description Text; CHPDPE_SCOPT.DESCR where CHPDPE_SCOPT.SCOPT1 = CHPDPE_CD_PARAM.SCOPT1"),
  PROFILE_ID1_CHPDPE_CD_PARAM STRING OPTIONS(description="Output Profile 1 ID"),
  DEF_EXEC1_CHPDPE_CD_PARAM STRING OPTIONS(description="Default Execution 1 Flag"),
  CAT_TYPE2_CHPDPE_CD_PARAM STRING OPTIONS(description="Catalog Type 2 ID"),
  SCOPT2_CHPDPE_CD_PARAM STRING OPTIONS(description="Catalog Distribution Scheduling Option 2 ID"),
  DESCR_CHPDPE_SCOPT2 STRING OPTIONS(description="Catalog Distribution Scheduling Option 2 Description Text; CHPDPE_SCOPT.DESCR where CHPDPE_SCOPT.SCOPT2 = CHPDPE_CD_PARAM.SCOPT2"),
  PROFILE_ID2_CHPDPE_CD_PARAM STRING OPTIONS(description="Output Profile 2 ID"),
  DEF_EXEC2_CHPDPE_CD_PARAM STRING OPTIONS(description="Default Execution 2 Flag"),
  ERDAT_CHPDPE_CD_PARAM DATE OPTIONS(description="Created On Date"),
  ERNAM_CHPDPE_CD_PARAM STRING OPTIONS(description="Created By User ID"),
  ERZET_CHPDPE_CD_PARAM TIME OPTIONS(description="Created On Time"),
  AEDAT_CHPDPE_CD_PARAM DATE OPTIONS(description="Changed On Date"),
  AENAM_CHPDPE_CD_PARAM STRING OPTIONS(description="Changed By User ID"),
  AEZET_CHPDPE_CD_PARAM TIME OPTIONS(description="Changed On Time"),
  CAT_ACC_TYPE_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Catalog Account Type ID"),
  NHIN_SORT_OPT_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Sorting Options ID"),
  BASE_PRICE_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Base Price Flag"),
  CONT_PRICE_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Contract Price Flag"),
  CATLG_PRICE_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Catalog Price Flag"),
  MSRP_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN MSRP Flag"),
  NDC_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN NDC Flag"),
  NDC_IND_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN NDC Indicator Flag"),
  PACK_QTY_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Pack Quantity Flag"),
  ONE_CIN_PER_NDC_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN One Material Per NDC Flag"),
  NDC_SORT_ORDER_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN NDC Sort Order Code"),
  SEND_SUBS_INFO_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Send Substitution Information Flag"),
  CUST_TZONE_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Customer Time Zone ID"),
  CUST_FNAME_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Customer Local File Name"),
  DELVRY_IND_CHPDPE_CD_PARAM STRING OPTIONS(description="NHIN Delivery Indicator ID"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Added Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Added User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY KUNNR_CHPDPE_CD_PARAM, VKORG_CHPDPE_CD_PARAM, VTWEG_CHPDPE_CD_PARAM, SPART_CHPDPE_CD_PARAM
OPTIONS(
  description=""
);