CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_CODE_CV`
(
  KUNNR_YTSD_CUST_CODE STRING OPTIONS(description="Customer Number"),
  VKORG_YTSD_CUST_CODE STRING OPTIONS(description="Sales Organization ID"),
  VTWEG_YTSD_CUST_CODE STRING OPTIONS(description="Distribution Channel ID"),
  SPART_YTSD_CUST_CODE STRING OPTIONS(description="Division ID"),
  YYCODETYPE_YTSD_CUST_CODE STRING OPTIONS(description="Code Type ID"),
  YYCODETYPE_DES_YTSD_CODETYPETXT STRING OPTIONS(description="Code Type Description Text; YTSD_CODETYPETXT.YYCODETYPE_DES where SPRAS = E and YTSD_CODETYPETXT.YYCODETYPE = YTSD_CUST_CODE.YYCODETYPE"),
  YYCODENUM_YTSD_CUST_CODE STRING OPTIONS(description="Code Number ID"),
  YYCODENAME_YTSD_CODENUMTXT STRING OPTIONS(description="Code Number Description Text; YTSD_CODENUMTXT.YYCODENAME where YTSD_CODENUMTXT.SPRAS = E and YTSD_CUST_CODE.YYCODETYPE = YTSD_CODENUMTXT.YYCODETYPE and YTSD_CUST_CODE.YYCODENUM = YTSD_CODENUMTXT.YYCODENUM"),
  YYCODEVALNUM_YTSD_CUST_CODE STRING OPTIONS(description="Code Value ID"),
  YYCODESTRTDTE_YTSD_CUST_CODE DATE OPTIONS(description="Start Date"),
  YYCODEENDDTE_YTSD_CUST_CODE DATE OPTIONS(description="End Date"),
  YYCODECMNTS_YTSD_CUST_CODE STRING OPTIONS(description="Comment Text"),
  YYCODESOURCE_YTSD_CUST_CODE STRING OPTIONS(description="Code Source ID"),
  UPDKZ_YTSD_CUST_CODE STRING OPTIONS(description="Insert Delete Update Indicator ID"),
  CREATED_BY_YTSD_CUST_CODE STRING OPTIONS(description="Created By User ID"),
  CREATED_ON_YTSD_CUST_CODE DATE OPTIONS(description="Created On Date"),
  CHANGED_BY_YTSD_CUST_CODE STRING OPTIONS(description="Changed By User ID"),
  CHANGED_ON_YTSD_CUST_CODE DATE OPTIONS(description="Changed On Date"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User Id"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User Id")
)
CLUSTER BY KUNNR_YTSD_CUST_CODE, VKORG_YTSD_CUST_CODE, VTWEG_YTSD_CUST_CODE, SPART_YTSD_CUST_CODE
OPTIONS(
  description=""
);