CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DEA_REGISTRATION_VF`
(
  DEA_NUM_DEA_REGISTRATION STRING OPTIONS(description="DEA Registration Number"),
  CURR_VRSN_FLG STRING OPTIONS(description="Current Version Flag"),
  DEL_FLG STRING OPTIONS(description="Delete Flag"),
  VRSN_START_DTE DATE OPTIONS(description="Version Start Date"),
  VRSN_END_DTE DATE OPTIONS(description="Version End Date"),
  PYMT_IND_ID_DEA_REGISTRATION STRING OPTIONS(description="Payment Indicator ID"),
  PYMT_IND_DESC STRING OPTIONS(description="Payment Indicator Description"),
  BSNS_ACT_ID_DEA_REGISTRATION STRING OPTIONS(description="Business Activity Code"),
  BSNS_ACT_SUB_ID_DEA_REGISTRATION STRING OPTIONS(description="Business Activity Sub Code"),
  BSNS_ACT_DESC_BUSINESS_ACTIVITY STRING OPTIONS(description="Business Activity Description"),
  DEA_RGSTRN_EXP_DTE_DEA_REGISTRATION DATE OPTIONS(description="DEA Registration Expiration Date"),
  CMPNY_NAM_DEA_REGISTRATION STRING OPTIONS(description="Company Name"),
  ADDL_CMPNY_INFO_TXT_DEA_REGISTRATION STRING OPTIONS(description="Additional Company Info"),
  ADDR_LINE_1_TXT_DEA_REGISTRATION STRING OPTIONS(description="Address1"),
  ADDR_LINE_2_TXT_DEA_REGISTRATION STRING OPTIONS(description="Address2"),
  CITY_DEA_REGISTRATION STRING OPTIONS(description="City"),
  STATE_DEA_REGISTRATION STRING OPTIONS(description="State"),
  DEA_SCHED_1_FLG_DEA_REGISTRATION STRING OPTIONS(description="Drug Schedule 1 Flag"),
  DEA_SCHED_2_FLG_DEA_REGISTRATION STRING OPTIONS(description="Drug Schedule 2 Flag"),
  DEA_SCHED_3_FLG_DEA_REGISTRATION STRING OPTIONS(description="Drug Schedule 3 Flag"),
  DEA_SCHED_2N_FLG_DEA_REGISTRATION STRING OPTIONS(description="Drug Schedule 2N Flag"),
  DEA_SCHED_3N_FLG_DEA_REGISTRATION STRING OPTIONS(description="Drug Schedule 3N Flag"),
  DEA_SCHED_4_FLG_DEA_REGISTRATION STRING OPTIONS(description="Drug Schedule 4 Flag"),
  DEA_SCHED_5_FLG_DEA_REGISTRATION STRING OPTIONS(description="Drug Schedule 5 Flag"),
  DEA_SCHED_L1_FLG_DEA_REGISTRATION STRING OPTIONS(description="Drug Schedule L1 Flag"),
  PSTL_CDE_DEA_REGISTRATION STRING OPTIONS(description="Postal Code"),
  DEGREE_DEA_REGISTRATION STRING OPTIONS(description="Degree"),
  STATE_LICENSE_NUM_DEA_REGISTRATION STRING OPTIONS(description="State License Number"),
  STATE_CS_LICENSE_NUM_DEA_REGISTRATION STRING OPTIONS(description="State CS License Number"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Added Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Added User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
);