CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_CUSTOMER.340B_CONTRACT_FEE_POLICY_CV`(
  CONTRACT_FEE_POLICY_340B_ID OPTIONS(description="340B Contract Fee Policy ID"),
  CONTRACT_FEE_POLICY_340B_DESC_TXT OPTIONS(description="Contract Fee Policy 340B Description Text"),
  ROW_ADD_STP OPTIONS(description="Indicates date the row was inserted"),
  ROW_ADD_USER_ID OPTIONS(description="Indicates by which job the row was inserted"),
  ROW_UPDATE_STP OPTIONS(description="Indicates date the row was updated"),
  ROW_UPDATE_USER_ID OPTIONS(description="Indicates by which job the row was updated")
)
AS SELECT
 YY340BCONFEE_YTSD_340BCONFTXT     AS     CONTRACT_FEE_POLICY_340B_ID
,YY340BCONFEE_DES_YTSD_340BCONFTXT     AS     CONTRACT_FEE_POLICY_340B_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.340B_CONTRACT_FEE_POLICY_CV`;