CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_CUSTOMER.CUSTOMER_CODE_CV`(
  CUSTOMER_NUM OPTIONS(description="Customer Number"),
  SALE_ORG_ID OPTIONS(description="Sales Organization ID"),
  DIST_CHNL_ID OPTIONS(description="Distribution Channel ID"),
  DIV_ID OPTIONS(description="Division ID"),
  CDE_TYPE_ID OPTIONS(description="Code Type ID"),
  CDE_TYPE_DESC_TXT OPTIONS(description="Code Type Description Text"),
  CDE_NUM_ID OPTIONS(description="Code Number ID"),
  CDE_NUM_DESC_TXT OPTIONS(description="Code Number Description Text"),
  CDE_VALUE_ID OPTIONS(description="Code Value ID"),
  START_DTE OPTIONS(description="Start Date"),
  END_DTE OPTIONS(description="End Date"),
  CMNT_TXT OPTIONS(description="Comment Text"),
  CDE_SRC_ID OPTIONS(description="Code Source ID"),
  INSRT_DEL_UPDATE_IND_ID OPTIONS(description="Insert Delete Update Indicator ID"),
  CREATE_BY_USER_ID OPTIONS(description="Created By User ID"),
  CREATE_ON_DTE OPTIONS(description="Created On Date"),
  CHG_BY_USER_ID OPTIONS(description="Changed By User ID"),
  CHG_ON_DTE OPTIONS(description="Changed On Date"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User Id"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User Id")
)
OPTIONS(
  description=""
)
AS SELECT
	KUNNR_YTSD_CUST_CODE AS CUSTOMER_NUM,
	VKORG_YTSD_CUST_CODE AS SALE_ORG_ID,
	VTWEG_YTSD_CUST_CODE AS DIST_CHNL_ID,
	SPART_YTSD_CUST_CODE AS DIV_ID,
	YYCODETYPE_YTSD_CUST_CODE AS CDE_TYPE_ID,
	YYCODETYPE_DES_YTSD_CODETYPETXT AS CDE_TYPE_DESC_TXT,
	YYCODENUM_YTSD_CUST_CODE AS CDE_NUM_ID,
	YYCODENAME_YTSD_CODENUMTXT AS CDE_NUM_DESC_TXT,
	YYCODEVALNUM_YTSD_CUST_CODE AS CDE_VALUE_ID,
	YYCODESTRTDTE_YTSD_CUST_CODE AS START_DTE,
	YYCODEENDDTE_YTSD_CUST_CODE AS END_DTE,
	YYCODECMNTS_YTSD_CUST_CODE AS CMNT_TXT,
	YYCODESOURCE_YTSD_CUST_CODE AS CDE_SRC_ID,
	UPDKZ_YTSD_CUST_CODE AS INSRT_DEL_UPDATE_IND_ID,
	CREATED_BY_YTSD_CUST_CODE AS CREATE_BY_USER_ID,
	CREATED_ON_YTSD_CUST_CODE AS CREATE_ON_DTE,
	CHANGED_BY_YTSD_CUST_CODE AS CHG_BY_USER_ID,
	CHANGED_ON_YTSD_CUST_CODE AS CHG_ON_DTE,
	ROW_ADD_STP AS ROW_ADD_STP,
	ROW_ADD_USER_ID AS ROW_ADD_USER_ID,
	ROW_UPDATE_STP AS ROW_UPDATE_STP,
	ROW_UPDATE_USER_ID AS ROW_UPDATE_USER_ID
FROM
   `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_CODE_CV`;