CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_CUSTOMER.SUPPRESS_PRINTED_INVOICE_CV`(
  PRINTED_INVOICE_SUPPRESSION_ID OPTIONS(description="Printed Invoice Suppression ID"),
  PRINTED_INVOICE_SUPPRESSION_DESC_TXT OPTIONS(description="Printed Invoice Suppression Description Text"),
  ROW_ADD_STP OPTIONS(description="Indicates date the row was inserted"),
  ROW_ADD_USER_ID OPTIONS(description="Indicates by which job the row was inserted"),
  ROW_UPDATE_STP OPTIONS(description="Indicates date the row was updated"),
  ROW_UPDATE_USER_ID OPTIONS(description="Indicates by which job the row was updated")
)
AS SELECT
 YYSUPPRINV_KNVV     AS     PRINTED_INVOICE_SUPPRESSION_ID
,PRINTED_INVOICE_SUPPRESSION_DESC_TXT     AS     PRINTED_INVOICE_SUPPRESSION_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SUPPRESS_PRINTED_INVOICE_CV`;