CREATE VIEW `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_LINEAGE_COLLIBRA_V`
AS SELECT
    --- Fitler Fields - Remove from template
     TRGT_SCHEMA_NAME,
     TRGT_TABLE_NAME,
    --- Source Field Mapping
     --NULL AS SOURCE_ASSET_ID,
    SRC_COLUMN_NAME AS SOURCE_NAME,
    SRC_TABLE_NAME||" > "||SRC_COLUMN_NAME AS SOURCE_FULL_NAME,
     --NULL AS SOURCE_DOMAIN_ID,
    'EDNA_BQ_'||SRC_SCHEMA_NAME AS SOURCE_DOMAIN,
    --NULL  AS SOURCE_DOMAIN_TYPE_ID,
    'Physical Data Dictionary' AS SOURCE_DOMAIN_TYPE,
     --NULL AS SOURCE_COMMUNITY_ID,
    CASE
      WHEN SRC_SCHEMA_NAME LIKE 'D0_%' THEN 'D0 - Source Identical'
      WHEN SRC_SCHEMA_NAME LIKE 'D1_%' THEN 'D1 - Aggregation Layer'
      WHEN SRC_SCHEMA_NAME LIKE 'VW_%' THEN 'P1 - Presentation Layer'
      ELSE NULL
    END AS SOURCE_COMMUNITY,
    --- Target Field Mapping
     --NULL AS TARGET_ASSET_ID,
    TRGT_COLUMN_NAME AS TARGET_NAME,
    TRGT_TABLE_NAME||" > "||TRGT_COLUMN_NAME AS TARGET_FULL_NAME,
     --NULL AS TARGET_DOMAIN_ID,
    'EDNA_BQ_'||TRGT_SCHEMA_NAME AS TARGET_DOMAIN,
     --NULL  AS TARGET_DOMAIN_TYPE_ID,
    'Physical Data Dictionary' AS TARGET_DOMAIN_TYPE,
     --NULL AS TARGET_COMMUNITY_ID,
    'D1 - Aggregation Layer' AS TARGET_COMMUNITY,
    --- Mapping Specifications
     --NULL AS MAPPING_SPECIFICATION_ASSET_ID,
    'Pharma_Data_Warehouse'AS MAPPING_SPECIFICATION_NAME,
    'Pharma_Data_Warehouse'AS MAPPING_SPECIFICATION_FULL_NAME,
     --NULL AS MAPPING_SPECIFICATION_DOMAIN_ID,
    'EDnA'  AS MAPPING_SPECIFICATION_DOMAIN,
     --NULL AS MAPPING_SPECIFICATION_DOMAIN_TYPE_ID,
    'Mapping Domain' AS MAPPING_SPECIFICATION_DOMAIN_TYPE,
     --NULL AS MAPPING_SPECIFICATION_COMMUNITY_ID,
    'Mapping Catalog'  AS MAPPING_SPECIFICATION_COMMUNITY,
    CASE
     WHEN REGEXP_CONTAINS(TRGT_COLUMN_TECH_DESC, ';') THEN TRIM(REGEXP_EXTRACT(TRGT_COLUMN_TECH_DESC, r';(.*)')) --- Removing and text before the first semi colon
     ELSE 'Move as is.'
    END AS TRANSFORMATION_LOGIC,
    CASE
     WHEN TRGT_SCHEMA_NAME LIKE '%PR_SALES%' AND REGEXP_CONTAINS(TRGT_COLUMN_BUSINESS_DESC, ';') THEN TRIM(REGEXP_EXTRACT(TRGT_COLUMN_BUSINESS_DESC, r'^(.*?);')) -- Exception for Puerto Rico
     ELSE TRGT_COLUMN_BUSINESS_DESC
  END AS DESCRIPTION,

FROM `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_LINEAGE_T`
 WHERE TRGT_SCHEMA_NAME <> 'D1_PHM_DW_LOG';