CREATE VIEW `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_COLUMNS_V`
AS SELECT
CURRENT_DATE() AS snapshot_date,
CURRENT_TIMESTAMP() AS snapshot_timestamp,
FARM_FINGERPRINT(CONCAT(table_catalog, table_schema,TABLE_NAME,COLUMN_NAME,CURRENT_TIMESTAMP())) AS pk,
FARM_FINGERPRINT(CONCAT(table_catalog, table_schema,TABLE_NAME)) AS pk_table,
FARM_FINGERPRINT(CONCAT(table_catalog, table_schema,TABLE_NAME,COLUMN_NAME)) AS pk_table_column,
*,
FROM `PROJECT_ID.region-us`.INFORMATION_SCHEMA.COLUMNS;