CREATE VIEW `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_ROUTINES_V`
AS SELECT

CURRENT_DATE() AS snapshot_date,
CURRENT_TIMESTAMP() AS snapshot_timestamp,
FARM_FINGERPRINT(CONCAT(ROUTINE_CATALOG, ROUTINE_SCHEMA,ROUTINE_NAME,CURRENT_TIMESTAMP())) AS pk,
FARM_FINGERPRINT(CONCAT(ROUTINE_CATALOG, ROUTINE_SCHEMA,ROUTINE_NAME)) AS pk_table,
*,

FROM `PROJECT_ID.region-us`.INFORMATION_SCHEMA.ROUTINES;