CREATE VIEW `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_ROLES_V`
AS WITH ACC AS
(
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_CONFDIM_CONTRACT'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_CONFDIM_CUSTOMER'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_CONFDIM_MATERIAL'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_CONFDIM_PLANT'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_CONFDIM_SUPPLIER'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_CONFDIM_TIME'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_CONFFACT_BILLING'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_CONFFACT_INVENTORY'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_CONFFACT_PURCHASING'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_PR_SALES_CUBE'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_CONFDIM_CONTRACT'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_CONFDIM_CUSTOMER'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_CONFDIM_MATERIAL'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_CONFDIM_PLANT'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_CONFDIM_SUPPLIER'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_CONFDIM_TIME'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_CONFFACT_BILLING'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_CONFFACT_INVENTORY'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_CONFFACT_PURCHASING'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_PR_SALES_CUBE'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_CONFDIM_CONTRACT'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_CONFDIM_CUSTOMER'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_CONFDIM_MATERIAL'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_CONFDIM_PLANT'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_CONFDIM_SUPPLIER'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_CONFDIM_TIME'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_CONFFACT_BILLING'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_CONFFACT_INVENTORY'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_CONFFACT_PURCHASING'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_PR_SALES_CUBE'   UNION DISTINCT
-- logging table
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_DW_LOG'   UNION DISTINCT
-- invetory consumption layer access
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_HDG_INVENTORY'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_SC_LOGICAL_VIEWS_NP'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VW_PHM_SC_DIMENSION_NP'   UNION DISTINCT
-- not currently being promoted, next in line
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_PD_DSCSA_EPCIS'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_PD_DSCSA_EPCIS'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'V12_PHM_PD_GWSA_DMART'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_PD_GWSA_DMART'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_PD_DEA_RGSTRN'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_PD_DEA_RGSTRN'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'VI2_PHM_PD_CSL_RPT'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D1_PHM_PD_CSL_RPT'   UNION DISTINCT
SELECT * FROM PROJECT_ID.`region-us`.INFORMATION_SCHEMA.OBJECT_PRIVILEGES WHERE OBJECT_NAME = 'D2_PHM_PD_CSL_RPT'

)
SELECT * FROM ACC
ORDER BY 3,5 ASC;