CREATE SNAPSHOT TABLE `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_CUSTOM__CUSTOMERMASTER_SCD_CV`
CLONE `PROJECT_ID.D0_PHM_ORP_CUSTOM_NP.CUSTOMERMASTER_SCD_CV`
OPTIONS(
  description="Customer Slowly Changing Dimension",
  labels=[("refresh-frequency", "604800")]
)
FOR SYSTEM_TIME AS OF TIMESTAMP "2024-01-13T08:13:56.839Z";