CREATE SNAPSHOT TABLE `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_CUSTOM__CUSTOMERSALESDATA_SCD_CV`
CLONE `PROJECT_ID.D0_PHM_ORP_CUSTOM_NP.CUSTOMERSALESDATA_SCD_CV`
OPTIONS(
  labels=[("refresh-frequency", "604800")]
)
FOR SYSTEM_TIME AS OF TIMESTAMP "2024-01-13T08:14:23.929Z";