
    CREATE PROCEDURE  `PROJECT_ID.D1_PHM_DW_LOG.SP_ADMIN_LINEAGE_T_DELTA_LOAD`()
    BEGIN
    /***********************************************************************************************************************

    Author: <Automatically Written Using Code Generator>
    Creation Date: <Insert Date>
    Sproc Purpose: Delta Loading Merge Sproc for ADMIN_LINEAGE_T
    Data Sources:  See SQL Below

    ************************************************************************************************************************/
    DECLARE v_start_time timestamp;
    DECLARE v_start_stp timestamp;
    DECLARE v_end_stp timestamp;
    DECLARE v_stored_proc_name STRING;
    DECLARE last_load_timestamp timestamp;

    SET v_start_time = current_timestamp();
    SET v_start_stp = current_timestamp();
    SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
    SET v_stored_proc_name = 'D1_PHM_DW_LOG.ADMIN_LINEAGE_T_DELTA_LOAD';
    SET last_load_timestamp = (SELECT MAX(ROW_ADD_STP) FROM `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_LINEAGE_T`);


    MERGE INTO  `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_LINEAGE_T` AS target
     USING 
      (
     -- Developer's code goes here (SAMPLE CODE BELOW)

         --SELECT 
            a.column_1
            a.column_2
         --FROM 
         -- `PROJECT_ID.VI2_PHM_CONFFACT_BILLING.PHM_SDW__INVOICE_LINE_CV` il
         --JOIN
            --`PROJECT_ID.VI2_PHM_CONFDIM_TIME.PHM_SDW__TIME_DETAIL_CV` t
                --ON il.DTE_KEY_NUM = t.DTE_KEY_NUM
        --WHERE il.D0_UPDATE_STP > last_load_timestamp --- MOST IMPORTANT CONCEPT

      ) AS source
      ON TARGET.PRIMARY_KEY = SOURCE.PRIMARY_KEY
    WHEN MATCHED THEN
      UPDATE SET
        TARGET.SRC_SCHEMA_NAME = SOURCE.SRC_SCHEMA_NAME,
        TARGET.SRC_TABLE_NAME = SOURCE.SRC_TABLE_NAME,
        TARGET.SRC_COLUMN_NAME = SOURCE.SRC_COLUMN_NAME,
        TARGET.SRC_COLUMN_ORDINAL_POSITION = SOURCE.SRC_COLUMN_ORDINAL_POSITION,
        TARGET.TRGT_SCHEMA_NAME_PARENT = SOURCE.TRGT_SCHEMA_NAME_PARENT,
        TARGET.TRGT_SCHEMA_NAME = SOURCE.TRGT_SCHEMA_NAME,
        TARGET.TRGT_TABLE_NAME = SOURCE.TRGT_TABLE_NAME,
        TARGET.TRGT_COLUMN_NAME = SOURCE.TRGT_COLUMN_NAME,
        TARGET.TRGT_COLUMN_ORDINAL_POSITION = SOURCE.TRGT_COLUMN_ORDINAL_POSITION,
        TARGET.TRGT_COLUMN_TECH_DESC = SOURCE.TRGT_COLUMN_TECH_DESC,
        TARGET.TRGT_COLUMN_BUSINESS_DESC = SOURCE.TRGT_COLUMN_BUSINESS_DESC,
        TARGET.VW_SCHEMA_NAME = SOURCE.VW_SCHEMA_NAME,
        TARGET.VW_TABLE_NAME = SOURCE.VW_TABLE_NAME,
        TARGET.VW_COLUMN_NAME = SOURCE.VW_COLUMN_NAME,
        TARGET.MATCH_RANK_ID = SOURCE.MATCH_RANK_ID,
        TARGET.SORT_RANK_ID = SOURCE.SORT_RANK_ID,
        TARGET.TRGT_PDW_FLAG = SOURCE.TRGT_PDW_FLAG,
        TARGET.STORED_PROCEDURE_NAME = SOURCE.STORED_PROCEDURE_NAME,
        TARGET.DAG_NAME = SOURCE.DAG_NAME,
        TARGET.task_name = SOURCE.task_name,
        TARGET.DAG_LAST_RUN_DTE = SOURCE.DAG_LAST_RUN_DTE,
        TARGET.TRGT_TABLE_CREATE_DTE = SOURCE.TRGT_TABLE_CREATE_DTE,
        TARGET.TRGT_TABLE_LAST_MODIFY_DTE = SOURCE.TRGT_TABLE_LAST_MODIFY_DTE,
        TARGET.TRGT_TABLE_ROWS = SOURCE.TRGT_TABLE_ROWS,
        TARGET.TRGT_GITHUB_REPO = SOURCE.TRGT_GITHUB_REPO
    WHEN NOT MATCHED THEN
      INSERT VALUES
      (
        SOURCE.SRC_SCHEMA_NAME,
        SOURCE.SRC_TABLE_NAME,
        SOURCE.SRC_COLUMN_NAME,
        SOURCE.SRC_COLUMN_ORDINAL_POSITION,
        SOURCE.TRGT_SCHEMA_NAME_PARENT,
        SOURCE.TRGT_SCHEMA_NAME,
        SOURCE.TRGT_TABLE_NAME,
        SOURCE.TRGT_COLUMN_NAME,
        SOURCE.TRGT_COLUMN_ORDINAL_POSITION,
        SOURCE.TRGT_COLUMN_TECH_DESC,
        SOURCE.TRGT_COLUMN_BUSINESS_DESC,
        SOURCE.VW_SCHEMA_NAME,
        SOURCE.VW_TABLE_NAME,
        SOURCE.VW_COLUMN_NAME,
        SOURCE.MATCH_RANK_ID,
        SOURCE.SORT_RANK_ID,
        SOURCE.TRGT_PDW_FLAG,
        SOURCE.STORED_PROCEDURE_NAME,
        SOURCE.DAG_NAME,
        SOURCE.task_name,
        SOURCE.DAG_LAST_RUN_DTE,
        SOURCE.TRGT_TABLE_CREATE_DTE,
        SOURCE.TRGT_TABLE_LAST_MODIFY_DTE,
        SOURCE.TRGT_TABLE_ROWS,
        SOURCE.TRGT_GITHUB_REPO
      );
    END;
