CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.CROSS_DISTRIB_CHAIN_MTRL_STATUS_CV`(
  XDC_MTRL_STAT_ID OPTIONS(description="Cross Distribution Chain Material Status ID"),
  XDC_MTRL_STAT_DESC_TXT OPTIONS(description="Cross Distribution Chain Material Status Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 VMSTA_TVMST     AS     XDC_MTRL_STAT_ID
,VMSTB_TVMST     AS     XDC_MTRL_STAT_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.CROSS_DISTRIB_CHAIN_MTRL_STATUS_CV`;