CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.DANGEROUS_GOOD_INDICATOR_CV`(
  DGNR_GOODS_IND_PRFL_ID OPTIONS(description="Dangerous Goods Indicator Profile ID"),
  DGNR_GOODS_IND_PRFL_DESC_TXT OPTIONS(description="Dangerous Goods Indicator Profile Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 PROFL_TDG42     AS     DGNR_GOODS_IND_PRFL_ID
,PROFLD_TDG42     AS     DGNR_GOODS_IND_PRFL_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.DANGEROUS_GOOD_INDICATOR_CV`;