CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.EAN_CATEGORY_CV`(
  EAN_CTGRY_ID OPTIONS(description="EAN Category ID"),
  EAN_NUM_CTGRY_TXT OPTIONS(description="EAN Number category text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 NUMTP_TNTPB     AS     EAN_CTGRY_ID
,NTBEZ_TNTPB     AS     EAN_NUM_CTGRY_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.EAN_CATEGORY_CV`;