CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.FDB_MASTER_CV`(
  NDC OPTIONS(description="National Drug Code"),
  LBLRID OPTIONS(description="Labeler Identifier"),
  GCN_SEQNO OPTIONS(description="Clinical Formulation ID (Stable ID)"),
  PS OPTIONS(description="Package Size"),
  DF OPTIONS(description="Drug Form Code"),
  AD OPTIONS(description="Additional Descriptor"),
  LN OPTIONS(description="Label Name"),
  BN OPTIONS(description="Brand Name"),
  PNDC OPTIONS(description="Previous National Drug Code"),
  REPNDC OPTIONS(description="Replacement National Drug Code"),
  NDCFI OPTIONS(description="NDC Format Indicator"),
  DADDNC OPTIONS(description="Date of Add—NDC"),
  DUPDC OPTIONS(description="Date of Update—NDC"),
  DESI OPTIONS(description="DESI Drug Indicator"),
  DESDTEC OPTIONS(description="DESI Status Change Effective Date"),
  DESI2 OPTIONS(description="DESI2 Drug Indicator"),
  DES2DTEC OPTIONS(description="DESI2 Status Change Effective Date"),
  DEA OPTIONS(description="Drug Enforcement Administration Code"),
  CL OPTIONS(description="Drug Class"),
  GPI OPTIONS(description="This column is not currently being used."),
  HOSP OPTIONS(description="Hospital Selection Indicator"),
  INNOV OPTIONS(description="Innovator Indicator"),
  IPI OPTIONS(description="Institutional Product Indicator"),
  MINI OPTIONS(description="Mini Selection Indicator"),
  MAINT OPTIONS(description="Maintenance Drug Indicator"),
  OBC OPTIONS(description="Orange Book Code"),
  OBSDTEC OPTIONS(description="Obsolete Date"),
  PPI OPTIONS(description="Patient Package Insert Indicator"),
  STPK OPTIONS(description="Standard Package Indicator"),
  REPACK OPTIONS(description="Repackaged Indicator"),
  TOP200 OPTIONS(description="Top 200 Drugs Indicator"),
  UD OPTIONS(description="Unit Dose Indicator"),
  CSP OPTIONS(description="Case Pack"),
  NDL_GDGE OPTIONS(description="Needle Gauge"),
  NDL_LNGTH OPTIONS(description="Needle Length"),
  SYR_CPCTY OPTIONS(description="Syringe Capacity"),
  SHLF_PCK OPTIONS(description="Shelf Pack"),
  SHIPPER OPTIONS(description="Shipper Quantity"),
  HCFA_FDA OPTIONS(description="HCFA FDA Therapeutic Equivalency Code"),
  HCFA_UNIT OPTIONS(description="HCFA Unit Indicator"),
  HCFA_PS OPTIONS(description="HCFA Units Per Package"),
  HCFA_APPC OPTIONS(description="HCFA FDA Approval Date"),
  HCFA_MRKC OPTIONS(description="HCFA Market Entry Date"),
  HCFA_TRMC OPTIONS(description="HCFA Termination Date"),
  HCFA_TYP OPTIONS(description="HCFA Drug Type Code"),
  HCFA_DESC1 OPTIONS(description="HCFA DESI Effective Date"),
  HCFA_DESI1 OPTIONS(description="HCFA DESI Code"),
  UU OPTIONS(description="Unit of Use Indicator"),
  PD OPTIONS(description="Package Description"),
  LN25 OPTIONS(description="This column is not currently being used."),
  LN25I OPTIONS(description="Label Name - 25/Generic Name Use Indicator"),
  GPIDC OPTIONS(description="This column is not currently being used."),
  BBDC OPTIONS(description="This column is not currently being used."),
  HOME OPTIONS(description="Home Health Selection Indicator"),
  INPCKI OPTIONS(description="Inner Package Indicator"),
  OUTPCKI OPTIONS(description="Outer Package Indicator"),
  OBC_EXP OPTIONS(description="Expanded Orange Book Code"),
  PS_EQUIV OPTIONS(description="Package Size Equivalent Value"),
  PLBLR OPTIONS(description="Private Labeler Indicator"),
  TOP50GEN OPTIONS(description="Top 50 Generics"),
  GMI OPTIONS(description="Generic Manufacturer Indicator"),
  GNI OPTIONS(description="Generic Name Indicator"),
  GSI OPTIONS(description="This column is not currently being used."),
  GTI OPTIONS(description="Therapeutic Equivalence Indicator"),
  NDCGI1 OPTIONS(description="Multi-Source/Single Source Indicator (NDC-Level)"),
  HCFA_DC OPTIONS(description="HCFA Drug Category"),
  LN60 OPTIONS(description="Label Name - 60"),
  HICL_SEQNO OPTIONS(description="Ingredient List Identifier (formerly the Hierarchical Ingredient Code List Sequence Number) (Stable ID)"),
  GCDF OPTIONS(description="Dosage Form Code (2-character)"),
  GCRT OPTIONS(description="Route of Administration Code (1-character)"),
  STR OPTIONS(description="Drug Strength Description"),
  GTC OPTIONS(description="Therapeutic Class Code, Generic"),
  TC OPTIONS(description="Therapeutic Class Code, Standard"),
  DCC OPTIONS(description="Drug Category Code"),
  GCNSEQ_GI OPTIONS(description="GCN_SEQNO-Level Multi-Source/Single Source Indicator"),
  GENDER OPTIONS(description="Gender-Specific Drug Indicator"),
  HIC3_SEQN OPTIONS(description="Hierarchical Specific Therapeutic Class Code Sequence Number (Stable ID)"),
  STR60 OPTIONS(description="Drug Strength Description - 60"),
  RT OPTIONS(description="Route Description"),
  GCRT2 OPTIONS(description="Route of Administration Code (2-character)"),
  GCRT_DESC OPTIONS(description="Route Code Interpretation"),
  SYSTEMIC OPTIONS(description="Systemic Route Indicator"),
  MFG OPTIONS(description="Manufacturer Name"),
  LBLRIND OPTIONS(description="Labeler Indicator Code"),
  COLOR_TXT OPTIONS(description="FDB Color"),
  SHAPE_TXT OPTIONS(description="FDB Shape"),
  FLAVOR_TXT OPTIONS(description="FDB Flavor"),
  CHG_FLAG OPTIONS(description="Change Flag"),
  NDA_IND OPTIONS(description="NDA Status Indicator"),
  ANDA_IND OPTIONS(description="ANDA Status Indicator"),
  LISTING_SEQ_NO OPTIONS(description="FDA Listing Sequence Number"),
  TRADENAME OPTIONS(description="FDA Trade Name"),
  DOSE OPTIONS(description="Dosage Form Description"),
  GCDF_DESC OPTIONS(description="Dosage Form Code Description"),
  STRNUM OPTIONS(description="Drug Strength Number"),
  VOLNUM OPTIONS(description="Drug Strength Volume Number"),
  STRUN50 OPTIONS(description="Drug Strength Units - 50"),
  VOLUN50 OPTIONS(description="Drug Strength Volume Units - 50"),
  OBC_GCN OPTIONS(description="Formulation ID"),
  GNN OPTIONS(description="Generic Name - Short Version"),
  GNN60 OPTIONS(description="Generic Name - Long Version"),
  AHFS8 OPTIONS(description="Therapeutic Class, AHFS"),
  AHFS_DESC OPTIONS(description="American Hospital Formulary Service - Code Description"),
  GCN OPTIONS(description="Formulation ID"),
  DCC_DESC OPTIONS(description="Drug Category Code Description"),
  GTC_DESC OPTIONS(description="Generic Therapeutic Class Description"),
  HIC3 OPTIONS(description="Hierarchical Specific Therapeutic Class Code"),
  HIC3_DESC OPTIONS(description="Hierarchical Specific Therapeutic Class Code Description"),
  HIC3_GRPN OPTIONS(description="Hierarchical Specific Therapeutic Class Code Group ID"),
  HIC3_ROOT OPTIONS(description="Hierarchical Specific Therapeutic Class Parent HIC2 Sequence Number"),
  OBC_SN OPTIONS(description="Orange Book Text Sequence Number"),
  OBC_DESC OPTIONS(description="Orange Book Code Description"),
  MEDID OPTIONS(description="MED Medication ID (Stable ID)"),
  TM_SOURCE_ID OPTIONS(description="TM Editorial Source ID"),
  TM_IND OPTIONS(description="TM Indicator"),
  TM_ALT_MEDID_DESC OPTIONS(description="TM Altered Medication Description"),
  TC_DESC OPTIONS(description="Standard Therapeutic Class Description"),
  EFFECT_DTE OPTIONS(description="AMP Price Effective Dae"),
  AMP_PRICE OPTIONS(description="AMP Price"),
  HCPC OPTIONS(description="HCFA Common Procedure Code"),
  HCPC_PBC1 OPTIONS(description="HCPC Part B/NOC Price Effective Date"),
  HCPC_PBP1 OPTIONS(description="HCPC Part B/NOC Price"),
  HCPC_PBC2 OPTIONS(description="HCPC Part B/NOC Previous Price Effective Date"),
  HCPC_PBP2 OPTIONS(description="HCPC Part B/NOC Previous Price"),
  HCPC_PBC3 OPTIONS(description="HCPC Part B/NOC 2nd Previous Price Effective Date"),
  HCPC_PBP3 OPTIONS(description="HCPC Part B/NOC 2nd Previous Price"),
  HCPC_PBC4 OPTIONS(description="HCPC Part B/NOC 3rd Previous Price Effective Date"),
  HCPC_PBP4 OPTIONS(description="HCPC Part B/NOC 3rd Previous Price"),
  HCPC_PBC5 OPTIONS(description="HCPC Part B/NOC 4th Previous Price Effective Date"),
  HCPC_PBP5 OPTIONS(description="HCPC Part B/NOC 4th Previous Price"),
  HCPC_PBC6 OPTIONS(description="HCPC Part B/NOC 5th Previous Price Effective Date"),
  HCPC_PBP6 OPTIONS(description="HCPC Part B/NOC 5th Previous Price"),
  HCPC_PBC7 OPTIONS(description="HCPC Part B/NOC 6th Previous Price Effective Date"),
  HCPC_PBP7 OPTIONS(description="HCPC Part B/NOC 6th Previous Price"),
  HCPC_PBC8 OPTIONS(description="HCPC Part B/NOC 7th Previous Price Effective Date"),
  HCPC_PBP8 OPTIONS(description="HCPC Part B/NOC 7th Previous Price"),
  MCR_BCDESC OPTIONS(description="Medicare Billing Code Description"),
  OBC3 OPTIONS(description="Orange Book Code; Three-byte Version"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
NDC,
  LBLRID,
  GCN_SEQNO,
  PS,
  DF,
  AD,
  LN,
  BN,
  PNDC,
  REPNDC,
  NDCFI,
  DADDNC,
  DUPDC,
  DESI,
  DESDTEC,
  DESI2,
  DES2DTEC,
  DEA,
  CL,
  GPI,
  HOSP,
  INNOV,
  IPI,
  MINI,
  MAINT,
  OBC,
  OBSDTEC,
  PPI,
  STPK,
  REPACK,
  TOP200,
  UD,
  CSP,
  NDL_GDGE,
  NDL_LNGTH,
  SYR_CPCTY,
  SHLF_PCK,
  SHIPPER,
  HCFA_FDA,
  HCFA_UNIT,
  HCFA_PS,
  HCFA_APPC,
  HCFA_MRKC,
  HCFA_TRMC,
  HCFA_TYP,
  HCFA_DESC1,
  HCFA_DESI1,
  UU,
  PD,
  LN25,
  LN25I,
  GPIDC,
  BBDC,
  HOME,
  INPCKI,
  OUTPCKI,
  OBC_EXP,
  PS_EQUIV,
  PLBLR,
  TOP50GEN,
  GMI,
  GNI,
  GSI,
  GTI,
  NDCGI1,
  HCFA_DC,
  LN60,
  HICL_SEQNO,
  GCDF,
  GCRT,
  STR,
  GTC,
  TC,
  DCC,
  GCNSEQ_GI,
  GENDER,
  HIC3_SEQN,
  STR60,
  RT,
  GCRT2,
  GCRT_DESC,
  SYSTEMIC,
  MFG,
  LBLRIND,
  COLOR_TXT,
  SHAPE_TXT,
  FLAVOR_TXT,
  CHG_FLAG,
  NDA_IND,
  ANDA_IND,
  LISTING_SEQ_NO,
  TRADENAME,
  DOSE,
  GCDF_DESC,
  STRNUM,
  VOLNUM,
  STRUN50,
  VOLUN50,
  OBC_GCN,
  GNN,
  GNN60,
  AHFS8,
  AHFS_DESC,
  GCN,
  DCC_DESC,
  GTC_DESC,
  HIC3,
  HIC3_DESC,
  HIC3_GRPN,
  HIC3_ROOT,
  OBC_SN,
  OBC_DESC,
  MEDID,
  TM_SOURCE_ID,
  TM_IND,
  TM_ALT_MEDID_DESC,
  TC_DESC,
  EFFECT_DTE,
  AMP_PRICE,
  HCPC,
  HCPC_PBC1,
  HCPC_PBP1,
  HCPC_PBC2,
  HCPC_PBP2,
  HCPC_PBC3,
  HCPC_PBP3,
  HCPC_PBC4,
  HCPC_PBP4,
  HCPC_PBC5,
  HCPC_PBP5,
  HCPC_PBC6,
  HCPC_PBP6,
  HCPC_PBC7,
  HCPC_PBP7,
  HCPC_PBC8,
  HCPC_PBP8,
  MCR_BCDESC,
  OBC3,
  ROW_ADD_STP,
  ROW_ADD_USER_ID,
  ROW_UPDATE_STP,
  ROW_UPDATE_USER_ID

FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.FDB_MASTER_CV`;