CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.FORM_CV`(
  FORM_ID OPTIONS(description="Form ID"),
  FORM_DESC_TXT OPTIONS(description="Form Description Text"),
  LONG_FORM_ID OPTIONS(description="Long Form ID"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 YYFORM_YTMM_FORM_TEXT     AS     FORM_ID
,YYDESC_YTMM_FORM_TEXT     AS     FORM_DESC_TXT
,YYLFORM_YTMM_FORM_TEXT     AS     LONG_FORM_ID
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.FORM_CV`;