CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.ITEM_CATEGORY_GROUP_CV`(
  ITEM_CTGRY_GROUP_ID OPTIONS(description="Item Category Group ID"),
  ITEM_CTGRY_GROUP_DESC_TXT OPTIONS(description="Item Category Group Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 MTPOS_TPTMT     AS     ITEM_CTGRY_GROUP_ID
,BEZEI_TPTMT     AS     ITEM_CTGRY_GROUP_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.ITEM_CATEGORY_GROUP_CV`;