CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.LIST_1_CHEMICAL_CV`(
  LIST_1_CHEM_ID OPTIONS(description="List 1 Chemical ID"),
  LIST_1_CHEM_DESC_TXT OPTIONS(description="List 1 Chemical Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 YYLSTO_YTMM_LIST1_TEXT     AS     LIST_1_CHEM_ID
,YYDESC_YTMM_LIST1_TEXT     AS     LIST_1_CHEM_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.LIST_1_CHEMICAL_CV`;