CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.MATERIAL_GROUP_CV`(
  MTRL_GROUP_ID OPTIONS(description="Material Group ID"),
  MTRL_GROUP_DESC_TXT OPTIONS(description="Material Group Description Text"),
  MTRL_GROUP_DESC_2_TXT OPTIONS(description="Material Group Description 2 Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 MATKL_T023T     AS     MTRL_GROUP_ID
,WGBEZ_T023T     AS     MTRL_GROUP_DESC_TXT
,WGBEZ60_T023T     AS     MTRL_GROUP_DESC_2_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_GROUP_CV`;