CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.MATERIAL_PLANT_RLT_CV`(
  MTRL_NUM OPTIONS(description="Material Number"),
  PLANT_ID OPTIONS(description="Plant ID"),
  MAINT_STAT_ID OPTIONS(description="Maintenance Status ID"),
  PLANT_LEVEL_MTRL_DEL_IND_FLG OPTIONS(description="Plant Level Material Deletion Indicator Flag"),
  INTRNL_BATCH_MGMNT_IND_FLG OPTIONS(description="Internal Batch Management Indicator Flag"),
  PLANT_SPCFC_MTRL_STAT_ID OPTIONS(description="Plant Specific Material Status ID"),
  PLANT_SPCFC_MTRL_STAT_VALID_FROM_DTE OPTIONS(description="Plant Specific Material Status Valid From Date"),
  PURCH_GROUP_ID OPTIONS(description="Purchasing Group ID"),
  PURCH_GROUP_DESC_TXT OPTIONS(description="Purchasing Group Description Text"),
  MTRL_RQRMNT_PLAN_PRFL_ID OPTIONS(description="Material Requirements Planning (MRP) Profile ID"),
  MTRL_RQRMNT_PLAN_TYPE_ID OPTIONS(description="Material Requirements Planning (MRP) Type ID"),
  BATCH_MGMNT_RQRMNT_IND_FLG OPTIONS(description="Batch Management Requirement Indicator Flag"),
  AVAIL_CHK_GROUP_ID OPTIONS(description="Availability Check Group ID"),
  AVAIL_CHK_GROUP_DESC_TXT OPTIONS(description="Availability Check Group Description Text"),
  PRFT_CENTER_ID OPTIONS(description="Profit Center ID"),
  CYCLE_COUNT_PHYSCL_INVTRY_IND_ID OPTIONS(description="Cycle Counting Physical Inventory Indicator ID"),
  SERIAL_NUM_PRFL_ID OPTIONS(description="Serial Number Profile ID"),
  PLANT_NGTV_STOCKS_ALW_FLG OPTIONS(description="Plant Negative Stocks Allowed Flag"),
  FIXED_CC_IND_FLG OPTIONS(description="Fixed CC indicator Flag"),
  MTRL_FRT_GROUP_ID OPTIONS(description="Material Freight Group ID"),
  PTWY_TYPE_ID OPTIONS(description="Putaway Type ID"),
  PLANT_MTRL_DIST_PRFL_ID OPTIONS(description="Plant Material Distribution Profile ID"),
  CURR_PSTNG_PERIOD_MTH_NUM OPTIONS(description="Current Posting Period Month Number"),
  CURR_PERIOD_FISCAL_YR_NUM OPTIONS(description="Current Period Fiscal Year Number"),
  VLT_GR_BLCK_STOCK_QTY OPTIONS(description="Valuated Goods Receipt Blocked Stock Quantity"),
  NO_INVTRY_FLG OPTIONS(description="No Inventory Flag"),
  CALL_TO_ORDER_FLG OPTIONS(description="Call To Order Flag"),
  LOT_MNG_FLG OPTIONS(description="Lot Managed Flag"),
  PLANT_START_DTE OPTIONS(description="Plant Start Date"),
  ROW_ADD_STP OPTIONS(description="Row Added Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Added User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
	MATNR_MARC        			AS MTRL_NUM,
	WERKS_MARC        			AS PLANT_ID,
	PSTAT_MARC        			AS MAINT_STAT_ID,
	LVORM_MARC        			AS PLANT_LEVEL_MTRL_DEL_IND_FLG,
	XCHAR_MARC        			AS INTRNL_BATCH_MGMNT_IND_FLG,
	MMSTA_MARC        			AS PLANT_SPCFC_MTRL_STAT_ID,
	MMSTD_MARC        			AS PLANT_SPCFC_MTRL_STAT_VALID_FROM_DTE,
	EKGRP_MARC        			AS PURCH_GROUP_ID,
	EKNAM_T024        			AS PURCH_GROUP_DESC_TXT,
	DISPR_MARC        			AS MTRL_RQRMNT_PLAN_PRFL_ID,
	DISMM_MARC        			AS MTRL_RQRMNT_PLAN_TYPE_ID,
	XCHPF_MARC        			AS BATCH_MGMNT_RQRMNT_IND_FLG,
	MTVFP_MARC        			AS AVAIL_CHK_GROUP_ID,
	BEZEI_TMVFT       			AS AVAIL_CHK_GROUP_DESC_TXT,
	PRCTR_MARC        			AS PRFT_CENTER_ID,
	ABCIN_MARC        			AS CYCLE_COUNT_PHYSCL_INVTRY_IND_ID,
	SERNP_MARC        			AS SERIAL_NUM_PRFL_ID,
	XMCNG_MARC        			AS PLANT_NGTV_STOCKS_ALW_FLG,
	CCFIX_MARC        			AS FIXED_CC_IND_FLG,
	MFRGR_MARC        			AS MTRL_FRT_GROUP_ID,
	LOGGR_MARC        			AS PTWY_TYPE_ID,
	FPRFM_MARC        			AS PLANT_MTRL_DIST_PRFL_ID,
	LFMON_MARC        			AS CURR_PSTNG_PERIOD_MTH_NUM,
	LFGJA_MARC        			AS CURR_PERIOD_FISCAL_YR_NUM,
	BWESB_MARC        			AS VLT_GR_BLCK_STOCK_QTY,
	YYNOINVENTORY_MARC			AS NO_INVTRY_FLG,
	YYCALLTO_MARC     			AS CALL_TO_ORDER_FLG,
	YYLOTM_MARC       			AS LOT_MNG_FLG,
	ZSLTSTMP_MARC 				AS PLANT_START_DTE,
	ROW_ADD_STP       			AS ROW_ADD_STP,
	ROW_ADD_USER_ID   			AS ROW_ADD_USER_ID,
	ROW_UPDATE_STP    			AS ROW_UPDATE_STP,
	ROW_UPDATE_USER_ID			AS ROW_UPDATE_USER_ID
FROM
   PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_PLANT_RLT_CV;