CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.MATERIAL_CLASS_RLT_CV`(
  MTRL_NUM OPTIONS(description="Material Number"),
  CALC_CLASS_TYPE_ID OPTIONS(description="Material Classification ID"),
  CALC_CLASS_CRCTRSTC_VALUE_ID OPTIONS(description="Material Classification Characteristic Value"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 MATNR_MARA     AS     MTRL_NUM
,CALC_CLASS_TYPE_ID     AS     CALC_CLASS_TYPE_ID
,CALC_CLASS_CRCTRSTC_VALUE_ID     AS     CALC_CLASS_CRCTRSTC_VALUE_ID
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_CLASS_RLT_CV`;