CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.MATERIAL_LEGAL_CONTROL_CV`(
  MTRL_NUM OPTIONS(description="Material Number"),
  LGL_REGULATION_ID OPTIONS(description="Legal Regulation ID"),
  LGL_REGULATION_DESC_TXT OPTIONS(description="Legal Regulation Description Text"),
  EXPORT_CNTRL_CLASS_ID OPTIONS(description="Export Control Class ID"),
  EXPORT_CNTRL_CLASS_DESC_TXT OPTIONS(description="Export Control Class Description Text"),
  LGL_CNTRL_GROUP_ID OPTIONS(description="Legal Control Grouping ID"),
  LGL_CNTRL_GROUP_DESC_TXT OPTIONS(description="Legal Control Grouping Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Added Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Added User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
OPTIONS(
  description=""
)
AS SELECT
	MATNR_MAEX 			AS MTRL_NUM,
	GEGRU_MAEX 			AS LGL_REGULATION_ID,
	BEZEI_T606R			AS LGL_REGULATION_DESC_TXT,
	ALNUM_MAEX 			AS EXPORT_CNTRL_CLASS_ID,
	BEZEI_T606V			AS EXPORT_CNTRL_CLASS_DESC_TXT,
	EMBGR_MAEX 			AS LGL_CNTRL_GROUP_ID,
	BEZEI_T606U			AS LGL_CNTRL_GROUP_DESC_TXT,
	ROW_ADD_STP			AS ROW_ADD_STP,
	ROW_ADD_USER_ID		AS ROW_ADD_USER_ID,
	ROW_UPDATE_STP		AS ROW_UPDATE_STP,
	ROW_UPDATE_USER_ID	AS ROW_UPDATE_USER_ID
FROM
   PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_LEGAL_CONTROL_CV;