CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.MTRL_GRP_PACKAGING_MATERIALS_CV`(
  MTRL_GROUP_PACK_MTRL_ID OPTIONS(description="Material Group Packaging Materials ID"),
  MTRL_GROUP_PACK_MTRL_DESC_TXT OPTIONS(description="Material Group Packaging Materials Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 MAGRV_TVEGRT     AS     MTRL_GROUP_PACK_MTRL_ID
,BEZEI_TVEGRT     AS     MTRL_GROUP_PACK_MTRL_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MTRL_GRP_PACKAGING_MATERIALS_CV`;