CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.PRICING_USAGE_CV`(
  PRICE_USAGE_ID OPTIONS(description="Pricing Usage ID"),
  PRICE_USAGE_DESC_TXT OPTIONS(description="Pricing Usage Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 YYPRIU_YTMM_PRIU_T     AS     PRICE_USAGE_ID
,YYDESC_YTMM_PRIU_T     AS     PRICE_USAGE_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.PRICING_USAGE_CV`;