CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.PRODUCT_HIERARCHY_CV`(
  PROD_HRCHY_ID OPTIONS(description="Product hierarchy ID"),
  LEVEL_NUM OPTIONS(description="Level Number"),
  PROD_HRCHY_DESC_TXT OPTIONS(description="Product Hierarchy Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 PRODH_T179     AS     PROD_HRCHY_ID
,STUFE_T179     AS     LEVEL_NUM
,VTEXT_T179T     AS     PROD_HRCHY_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.PRODUCT_HIERARCHY_CV`;