CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.STORAGE_CONDITION_CV`(
  STRG_CNDTN_ID OPTIONS(description="Storage conditions ID"),
  STRG_CNDTN_DESC_TXT OPTIONS(description="Storage conditions Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 RAUBE_T142T     AS     STRG_CNDTN_ID
,RBTXT_T142T     AS     STRG_CNDTN_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.STORAGE_CONDITION_CV`;