CREATE VIEW `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.VARIABLE_PO_UNIT_ACTIVITY_CV`(
  VRBL_PURCH_ORDER_UNIT_ACT_ID OPTIONS(description="Variable Purchase Order Unit Activity ID"),
  VRBL_PURCH_ORDER_UNIT_ACT_DESC_TXT OPTIONS(description="Variable Purchase Order Unit Activity Description Text"),
  ROW_ADD_STP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID OPTIONS(description="Row Update User ID")
)
AS SELECT
 VABME_MARA     AS     VRBL_PURCH_ORDER_UNIT_ACT_ID
,VRBL_PURCH_ORDER_UNIT_ACT_DESC_TXT     AS     VRBL_PURCH_ORDER_UNIT_ACT_DESC_TXT
,ROW_ADD_STP     AS     ROW_ADD_STP
,ROW_ADD_USER_ID     AS     ROW_ADD_USER_ID
,ROW_UPDATE_STP     AS     ROW_UPDATE_STP
,ROW_UPDATE_USER_ID     AS     ROW_UPDATE_USER_ID
FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.VARIABLE_PO_UNIT_ACTIVITY_CV`;