CREATE TABLE `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_GWSA_COLUMN_SECURITY_CV`
(
  BUSINESS_REVIEW BOOL,
  ADMIN_ENTITY_INVENTORY_ENTITY_SCHEMA STRING,
  ADMIN_ENTITY_INVENTORY_ENTITY_NAME STRING,
  PDW_COLUMNS_DATA_TYPE STRING,
  D1_COLUMN_NAME STRING,
  VW_COLUMN_NAME STRING,
  LOOKER_COLUMN_NAME STRING,
  GwsaPubRedOak STRING,
  GwsaPubOosSrc STRING,
  GwsaPubPricing STRING,
  GwsaPublished STRING,
  GwsaOperational STRING
);