CREATE TABLE `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_ENTITY_SUMMARY_T`
(
  snapshot_date DATE,
  snapshot_timestamp TIMESTAMP,
  pk INT64,
  pk_table INT64,
  table_catalog STRING,
  table_schema STRING,
  schema_name_group STRING,
  dataset_group STRING,
  dataset_group_ad_np STRING,
  TABLE_NAME STRING,
  table_type STRING,
  is_insertable_into STRING,
  is_typed STRING,
  creation_time TIMESTAMP,
  snapshot_time_ms TIMESTAMP,
  ddl STRING,
  view_definition STRING,
  upsert_stream_apply_watermark TIMESTAMP,
  total_columns INT64,
  total_rows INT64,
  total_partitions INT64,
  total_logical_bytes INT64,
  active_logical_bytes INT64,
  long_term_logical_bytes INT64,
  total_physical_bytes INT64,
  active_physical_bytes INT64,
  long_term_physical_bytes INT64,
  time_travel_physical_bytes INT64,
  total_logical_mb FLOAT64,
  active_logical_mb FLOAT64,
  long_term_logical_mb FLOAT64,
  total_physical_mb FLOAT64,
  active_physical_mb FLOAT64,
  long_term_physical_mb FLOAT64,
  time_travel_physical_mb FLOAT64,
  total_logical_gb FLOAT64,
  active_logical_gb FLOAT64,
  long_term_logical_gb FLOAT64,
  total_physical_gb FLOAT64,
  active_physical_gb FLOAT64,
  long_term_physical_gb FLOAT64,
  time_travel_physical_gb FLOAT64,
  active_logical_cost FLOAT64,
  long_term_logical_cost FLOAT64,
  active_physical_cost FLOAT64,
  long_term_physical_cost FLOAT64,
  storage_last_modified_time TIMESTAMP
)
PARTITION BY DATE(creation_time)
CLUSTER BY schema_name_group, dataset_group, TABLE_NAME, table_type;