CREATE TABLE `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_JOBS_T`
(
  snapshot_date DATE,
  snapshot_timestamp TIMESTAMP,
  creation_time TIMESTAMP,
  project_id STRING,
  project_number INT64,
  user_email STRING,
  job_id STRING,
  job_type STRING,
  statement_type STRING,
  priority STRING,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  query STRING,
  state STRING,
  reservation_id STRING,
  total_bytes_processed INT64,
  total_slot_ms INT64,
  error_result STRUCT<reason STRING, LOCATION STRING, debug_info STRING, message STRING>,
  cache_hit BOOL,
  destination_table STRUCT<project_id STRING, dataset_id STRING, table_id STRING>,
  referenced_tables ARRAY<STRUCT<project_id STRING, dataset_id STRING, table_id STRING>>,
  labels ARRAY<STRUCT<KEY STRING, value STRING>>,
  timeline ARRAY<STRUCT<elapsed_ms INT64, total_slot_ms INT64, pending_units INT64, completed_units INT64, active_units INT64, estimated_runnable_units INT64>>,
  job_stages ARRAY<STRUCT<name STRING, id INT64, start_ms INT64, end_ms INT64, input_stages ARRAY<INT64>, wait_ratio_avg FLOAT64, wait_ms_avg INT64, wait_ratio_max FLOAT64, wait_ms_max INT64, read_ratio_avg FLOAT64, read_ms_avg INT64, read_ratio_max FLOAT64, read_ms_max INT64, compute_ratio_avg FLOAT64, compute_ms_avg INT64, compute_ratio_max FLOAT64, compute_ms_max INT64, write_ratio_avg FLOAT64, write_ms_avg INT64, write_ratio_max FLOAT64, write_ms_max INT64, shuffle_output_bytes INT64, shuffle_output_bytes_spilled INT64, records_read INT64, records_written INT64, parallel_inputs INT64, completed_parallel_inputs INT64, status STRING, steps ARRAY<STRUCT<kind STRING, substeps ARRAY<STRING>>>, slot_ms INT64, compute_mode STRING>>,
  total_bytes_billed INT64,
  transaction_id STRING,
  parent_job_id STRING,
  session_info STRUCT<session_id STRING>,
  dml_statistics STRUCT<inserted_row_count INT64, deleted_row_count INT64, updated_row_count INT64>,
  total_modified_partitions INT64,
  bi_engine_statistics STRUCT<bi_engine_mode STRING, bi_engine_reasons ARRAY<STRUCT<code STRING, message STRING>>, acceleration_mode STRING>,
  query_info STRUCT<resource_warning STRING, optimization_details JSON, query_hashes STRUCT<normalized_literals STRING>, performance_insights STRUCT<avg_previous_execution_ms INT64, stage_performance_standalone_insights ARRAY<STRUCT<stage_id INT64, slot_contention BOOL, insufficient_shuffle_quota BOOL, bi_engine_reasons ARRAY<STRUCT<code STRING, message STRING>>, high_cardinality_joins ARRAY<STRUCT<left_rows INT64, right_rows INT64, output_rows INT64, step_index INT64>>>>, stage_performance_change_insights ARRAY<STRUCT<stage_id INT64, input_data_change STRUCT<records_read_diff_percentage FLOAT64>>>>>,
  transferred_bytes INT64,
  materialized_view_statistics STRUCT<materialized_view ARRAY<STRUCT<table_reference STRUCT<project_id STRING, dataset_id STRING, table_id STRING>, chosen BOOL, estimated_bytes_saved INT64, rejected_reason STRING>>>,
  edition STRING,
  job_creation_reason STRUCT<code STRING>
)
PARTITION BY DATE(creation_time);