CREATE TABLE `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_JOBS_PDW_TASK_T`
(
  snapshot_date DATE,
  snapshot_timestamp TIMESTAMP,
  creation_time TIMESTAMP,
  project_id STRING,
  project_number INT64,
  user_email STRING,
  job_id STRING,
  job_type STRING,
  statement_type STRING,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  excution_time_seconds INT64,
  excution_time_minutes INT64,
  query STRING,
  state STRING,
  reservation_id STRING,
  total_bytes_processed INT64,
  total_gigabytes_processed FLOAT64,
  total_gigabytes_billed FLOAT64,
  total_slot_ms INT64,
  slots FLOAT64,
  total_bytes_billed INT64,
  parent_job_id STRING,
  total_modified_partitions INT64,
  destination_table STRUCT<project_id STRING, dataset_id STRING, table_id STRING>,
  dml_statistics STRUCT<inserted_row_count INT64, deleted_row_count INT64, updated_row_count INT64>,
  error_result STRUCT<reason STRING, LOCATION STRING, debug_info STRING, message STRING>,
  logging_insert_flag BOOL,
  job_success_flag STRING
)
PARTITION BY DATE(creation_time);