CREATE TABLE `PROJECT_ID.D1_PHM_DW_LOG.ADMIN_ENTITY_LINEAGE_T`
(
  D0_Dataset STRING,
  D0_Entity STRING,
  VI2_Dataset STRING,
  VI2_Entity STRING,
  D1_Dataset STRING,
  D1_Entity STRING,
  VW_Dataset STRING,
  VW_Entity STRING
);