CREATE TABLE `PROJECT_ID.D1_PHM_DW_LOG.LOGTBL_DIMENSION`
(
  MODULE_NAME STRING,
  START_DATE DATETIME,
  END_DATE DATETIME,
  STATUS STRING,
  MERGE_ROWCOUNT INT64,
  INSERT_ROWCOUNT INT64,
  UPDATE_ROWCOUNT INT64,
  DELETE_ROWCOUNT INT64,
  MB_PROCESSED FLOAT64,
  MB_BILLED FLOAT64,
  JOB_ID STRING,
  CUSTOM1 STRING,
  CUSTOM2 STRING,
  ERR_MSG STRING,
  ERR_ST_TXT STRING,
  ERR_ST_TRC STRING
);