CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFFACT_PRICING.SP_CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF()
BEGIN
/*******************************************************************************************************************************************

Name: Shaik, Shareef
Date: Dec 23rd, 2023
Project: GPSC Iteration 2
Description: A717 from D0 to D1;
Marker :
--------------------------------------------------------------------------------------------------
********************************************************************************************************************************************************/
DECLARE v_start_time datetime;
DECLARE v_start_stp timestamp;
DECLARE v_end_stp timestamp;
DECLARE v_stored_proc_name string;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFFACT_PRICING.SP_CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF';

-- Select the latest record from the table

CREATE OR REPLACE TEMPORARY TABLE CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF_TEMP
AS
SELECT v_start_stp AS ROW_ADD_STP,
	v_stored_proc_name AS ROW_ADD_USER_ID,
	v_end_stp AS ROW_UPDATE_STP,
	v_stored_proc_name AS ROW_UPDATE_USER_ID,
a.* FROM (SELECT DISTINCT A717.KNUMA_AG AS KNUMA_AG_A717,
A717.VKORG AS VKORG_A717,
TV.VTEXT AS VTEXT_TVKOT,
A717.VTWEG AS VTWEG_A717,
WT.VTEXT AS VTEXT_TVTWT,
A717.SPART AS SPART_A717,
SP.VTEXT AS VTEXT_TSPAT,
A717.KUNAG AS KUNAG_A717
,A717.IRM_PCBGP_PRI AS IRM_PCBGP_PRI_A717
,A717.LIFNR AS LIFNR_A717
,PARSE_DATE('%Y%m%d', A717.DATBI ) AS DATBI_A717
,PARSE_DATE('%Y%m%d',A717.DATAB ) AS DATAB_A717
,CASE WHEN IFNULL(KONP.LOEVM_KO,'N') = 'X' THEN 'Y' ELSE 'N' END AS LOEVM_KO_KONP
 FROM `PROJECT_ID.VI2_PHM_CONFFACT_PRICING.PHM_ORP_PE1_PH1__A717_CV` A717
 JOIN `PROJECT_ID.VI2_PHM_CONFFACT_BILLING.PHM_ORP_PE1_PH1__TVKOT_CV` TV
 ON A717.VKORG=TV.VKORG AND TV.SPRAS='E'
 JOIN `PROJECT_ID.VI2_PHM_CONFFACT_BILLING.PHM_ORP_PE1_PH1__TVTWT_CV` WT
 ON A717.VTWEG = WT.VTWEG AND WT.SPRAS='E'
 JOIN `PROJECT_ID.VI2_PHM_CONFFACT_BILLING.PHM_ORP_PE1_PH1__TSPAT_CV` SP
 ON A717.SPART = SP.SPART AND SP.SPRAS='E'
 JOIN `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__KONP_CV` KONP
 ON A717.KNUMH=KONP.KNUMH)a ;

 -- Perform an UPSERT on the target table
-- Step 1: Identify records to be inserted

CREATE OR REPLACE TEMPORARY TABLE CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF_TEMP_INS
AS
SELECT
	TMP.KNUMA_AG_A717
	,TMP.VKORG_A717
	,TMP.VTEXT_TVKOT
	,TMP.VTWEG_A717
	,TMP.VTEXT_TVTWT
	,TMP.SPART_A717
	,TMP.VTEXT_TSPAT
	,TMP.KUNAG_A717
	,TMP.IRM_PCBGP_PRI_A717
	,'Y' AS CURR_VRSN_FLG
	,TMP.LIFNR_A717
	,TMP.DATBI_A717
	,TMP.DATAB_A717
	,TMP.ROW_ADD_STP ,
	TMP.ROW_ADD_USER_ID,
	TMP.ROW_UPDATE_STP,
	TMP.ROW_UPDATE_USER_ID,
  TMP.LOEVM_KO_KONP
FROM CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF_TEMP TMP
LEFT JOIN `PROJECT_ID.D1_PHM_CONFFACT_PRICING.CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF` A717
ON TMP.KNUMA_AG_A717 = A717.KNUMA_AG_A717 AND TMP.SPART_A717 = A717.SPART_A717 AND TMP.KUNAG_A717 = A717.KUNAG_A717 AND TMP.IRM_PCBGP_PRI_A717 = A717.IRM_PCBGP_PRI_A717
AND TMP.LIFNR_A717 = A717.LIFNR_A717 AND TMP.DATBI_A717 = A717.DATBI_A717 AND TMP.DATAB_A717 = A717.DATAB_A717
WHERE
A717.KNUMA_AG_A717 IS NULL AND A717.SPART_A717  IS NULL AND A717.KUNAG_A717  IS NULL AND A717.IRM_PCBGP_PRI_A717  IS NULL AND A717.LIFNR_A717  IS NULL AND A717.DATBI_A717  IS NULL AND
A717.DATAB_A717  IS NULL;

-- Step 2: Update records where the source and target match

UPDATE `PROJECT_ID.D1_PHM_CONFFACT_PRICING.CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF` A717
SET
	A717.KNUMA_AG_A717=TMP.KNUMA_AG_A717
	,A717.VKORG_A717=TMP.VKORG_A717
	,A717.VTEXT_TVKOT=TMP.VTEXT_TVKOT
	,A717.VTWEG_A717=TMP.VTWEG_A717
	,A717.VTEXT_TVTWT=TMP.VTEXT_TVTWT
	,A717.SPART_A717=TMP.SPART_A717
	,A717.VTEXT_TSPAT=TMP.VTEXT_TSPAT
	,A717.KUNAG_A717=TMP.KUNAG_A717
	,A717.IRM_PCBGP_PRI_A717=TMP.IRM_PCBGP_PRI_A717
	,A717.LIFNR_A717=TMP.LIFNR_A717
	,A717.DATBI_A717=TMP.DATBI_A717
	,A717.DATAB_A717=TMP.DATAB_A717
	,A717.ROW_UPDATE_USER_ID= v_stored_proc_name
FROM CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF_TEMP TMP
WHERE TMP.KNUMA_AG_A717 = A717.KNUMA_AG_A717 AND TMP.SPART_A717 = A717.SPART_A717 AND TMP.KUNAG_A717 = A717.KUNAG_A717 AND TMP.IRM_PCBGP_PRI_A717 = A717.IRM_PCBGP_PRI_A717
AND TMP.LIFNR_A717 = A717.LIFNR_A717 AND TMP.DATBI_A717 = A717.DATBI_A717 AND TMP.DATAB_A717 = A717.DATAB_A717 ;

-- Step 3: Insert records into the target

INSERT INTO `PROJECT_ID.D1_PHM_CONFFACT_PRICING.CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF`
SELECT
	KNUMA_AG_A717
	,VKORG_A717
  ,VTEXT_TVKOT
	,VTWEG_A717
  ,VTEXT_TVTWT
	,SPART_A717
  ,VTEXT_TSPAT
	,KUNAG_A717
	,IRM_PCBGP_PRI_A717
	,LIFNR_A717
	,DATAB_A717
	,DATBI_A717
	,CURR_VRSN_FLG
	,ROW_ADD_STP
	,ROW_ADD_USER_ID
	,ROW_UPDATE_STP
	,ROW_UPDATE_USER_ID
  ,LOEVM_KO_KONP
FROM CUSTOMER_BUY_GRP_SUPPLIER_BLOCK_VF_TEMP_INS;

END;