CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_CODE()
BEGIN

/***********************************************************************************************************************
Author: Debapriya Banerjee
Creation Date: 09/22/2023
Data Sources: VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__YTSD_CUST_CODE_CV
							VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__YTSD_CODETYPETXT_CV
							VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__YTSD_CODENUMTXT_CV
*************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
	<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time DATETIME;
DECLARE v_start_stp TIMESTAMP;
DECLARE v_end_stp TIMESTAMP;
DECLARE v_end_scd_stp TIMESTAMP;
DECLARE v_stored_proc_name STRING;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_CODE';

/* Truncate CUSTOMER_CODE_CV */

TRUNCATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_CODE_CV`;

/* Insert into CUSTOMER_CODE_CV */

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_CODE_CV`
SELECT
	 CC.KUNNR
	,CC.VKORG
	,CC.VTWEG
	,CC.SPART
	,CC.YYCODETYPE
	,'pending' AS YYCODETYPE_DES--,IFNULL(CTT.YYCODETYPE_DES, 'NOT_AVAILABLE') AS YYCODETYPE_DES
	,CC.YYCODENUM
	,IFNULL(CNT.YYCODENAME,  'NOT_AVAILABLE') AS YYCODENAME
	,CC.YYCODEVALNUM
	,IFNULL(SAFE_CAST(CC.YYCODESTRTDTE AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS YYCODESTRTDTE
	,IFNULL(SAFE_CAST(CC.YYCODEENDDTE AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS YYCODEENDDTE
	,CC.YYCODECMNTS
	,CC.YYCODESOURCE
	,CC.UPDKZ
	,CC.CREATED_BY
	,IFNULL(SAFE_CAST(CC.CREATED_ON AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS CREATED_ON
	,CC.CHANGED_BY
	,IFNULL(SAFE_CAST(CC.CHANGED_ON AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS CHANGED_ON
	,v_start_stp AS ROW_ADD_STP
	,v_stored_proc_name AS ROW_ADD_USER_ID
	,v_start_stp AS ROW_UPDATE_STP
	,v_stored_proc_name AS ROW_UPDATE_USER_ID
FROM `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__YTSD_CUST_CODE_CV` CC
--LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__YTSD_CODETYPETXT_CV` CTT ON CTT.YYCODETYPE = CC.YYCODETYPE AND CTT.SPRAS = 'E'
LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__YTSD_CODENUMTXT_CV` CNT ON CNT.YYCODETYPE = CC.YYCODETYPE AND CNT.YYCODENUM = CC.YYCODENUM AND CNT.SPRAS = 'E'
WHERE CC.D0_CURR_VRSN_FLG = 'Y'
AND TRIM(CC.KUNNR) <> '';

END;