CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_TRUNC_LOAD()
BEGIN

/***********************************************************************************************************************
Author: AKSHOBHYA S ACHAR
Creation Date: 05/15/2023
Data Sources:
*************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time DATETIME;
DECLARE v_start_stp TIMESTAMP;
DECLARE v_end_stp TIMESTAMP;
DECLARE v_end_scd_stp TIMESTAMP;
DECLARE v_stored_proc_name STRING;
DECLARE v_last_timestamp TIMESTAMP;
DECLARE v_proc_timestamp TIMESTAMP;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT SAFE_CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_INITIAL_LOAD';
SET v_last_timestamp = (SELECT MAX(D0_START_STP) FROM PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_CUSTOM__CUSTOMERMASTER_SCD_CV);

CREATE OR REPLACE TEMPORARY TABLE KNA1_TEMP
AS
SELECT
 CUST.KUNNR AS KUNNR_KNA1
,CUST.SORTL AS SORTL_KNA1
,IF (CUST.KATR3= 'X', 'Y', 'N') AS KATR3_KNA1
,IF (CUST.KATR4= '4A', 'Y', 'N') AS KATR4_KNA1
,IF (CUST.KATR5= 'MT', 'Y', 'N') AS KATR5_KNA1
,KATR6 AS KATR6_KNA1
,KATR7 AS KATR7_KNA1
,KATR8 AS KATR8_KNA1
,YYPRIME AS YYPRIME_KNA1
,IF(SAFE_CAST(CUST.YYPGSTART AS DATE FORMAT 'YYYYMMDD') IS NULL, SAFE_CAST('1900-01-01' AS DATE), SAFE_CAST(CUST.YYPGSTART AS DATE FORMAT 'YYYYMMDD')) AS YYPGSTART_KNA1
,IF(SAFE_CAST(CUST.YYPGEND AS DATE FORMAT 'YYYYMMDD') IS NULL, SAFE_CAST('1900-01-01' AS DATE), SAFE_CAST(CUST.YYPGEND AS DATE FORMAT 'YYYYMMDD')) AS YYPGEND_KNA1
,IF(CUST.YYOPDXMPT='X','Y','N') AS YYOPDXMPT_KNA1
--,TAXKD AS TAXKD_KNA1
FROM
PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__KNA1_CV CUST
WHERE CUST.D0_CURR_VRSN_FLG = 'Y';

TRUNCATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_CV`;

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_CV`
SELECT
CUST.KUNNR_KNA1
,CUST.START_DTE  AS VRSN_START_DTE
,CUST.END_DTE  AS VRSN_END_DTE
,CUST.CURR_VRSN_FLG
,CUST.NAME1_KNA1
,CUST.NAME2_KNA1
,CUST.NAME3_KNA1
,CUST.NAME4_KNA1
,CUST.STRAS_KNA1
,CUST.ORT01_KNA1
,CUST.PSTLZ_KNA1
,CUST.REGIO_KNA1
,CUST.LAND1_KNA1
,CUST.ORT02_KNA1
,CUST.PFACH_KNA1
,CUST.PSTL2_KNA1
,CUST.TIME_ZONE_ADRC
,CUST.TELF1_KNA1
,CUST.TELFX_KNA1
,CUST.LOEVM_KNA1
,KNA1.SORTL_KNA1
,SAFE_CAST(CUST.AUFSD_KNA1 AS STRING) AS AUFSD_KNA1
,COB.VTEXT_TVAST AS VTEXT_TVAST_CENTRAL_ORDER_BLOCK
,SAFE_CAST(CUST.BBBNR_KNA1 AS INT64) AS BBBNR_KNA1
,SAFE_CAST(CUST.BBSNR_KNA1 AS INT64) AS BBSNR_KNA1
,CUST.BRSCH_KNA1
,IKY.BRTXT_T016T AS BRTXT_T016T_INDUSTRY_KEY
,IF ( SAFE_CAST(LEFT(CUST.BRSCH_KNA1, 3) AS INT64) = 340, 'Y','N')  AS CALC_340B_CUSTOMER_FLG
,CUST.CALC_GPO_CUST_FLAG AS CALC_GPO_CUSTOMER_FLG
,SAFE_CAST(CUST.BUBKZ_KNA1 AS INT64) AS BUBKZ_KNA1
,SAFE_CAST(CUST.ERDAT_KNA1 AS DATE FORMAT 'YYYYMMDD') AS ERDAT_KNA1
,CUST.ERNAM_KNA1
,CUST.FAKSD_KNA1
,CBB.VTEXT_TVFST AS VTEXT_TVFST_CENTRAL_BILLING_BLOCK
,CUST.KTOKD_KNA1
,CAG.TXT30_T077X AS TXT30_T077X_CUSTOMER_ACCOUNT_GROUP
,CUST.KUKLA_KNA1
,CL1.VTEXT_TKUKT AS VTEXT_TKUKT_CUSTOMER_CLASS_OF_TRADE
,CUST.LIFSD_KNA1
,CDB.VTEXT_TVLST AS VTEXT_TVLST_CENTRAL_DELIVERY_BLOCK
,CUST.SPERR_KNA1
,CUST.LZONE_KNA1
,CUST.VBUND_KNA1
,TPC.NAME1_T880 AS NAME1_T880_TRADING_PARTNER_COMPANY
,CUST.GFORM_KNA1
,LST.VTEXT_TVGFT AS VTEXT_TVGFT_LEGAL_STATUS
,IF (CUST.KATR1_KNA1= '01', 'Y', 'N') AS KATR1_KNA1
,IF (CUST.KATR2_KNA1= '01', 'Y', 'N') AS KATR2_KNA1
,KNA1.KATR3_KNA1
,KNA1.KATR4_KNA1
,KNA1.KATR5_KNA1
,KNA1.KATR6_KNA1
,BRT.VTEXT_TVK6T AS VTEXT_TVK6T_BACKORDER_RESTRICTION
,KNA1.KATR7_KNA1
,OTC.VTEXT_TVK7T AS VTEXT_TVK7T_OTC_RESTRICTION
,KNA1.KATR8_KNA1
,C2R.VTEXT_TVK8T AS VTEXT_TVK8T_C2_RESTRICTION
,CUST.CALC_GENDA_EMBK AS GENDA_EMBK
,CUST.EXGEN_ST_PHY_EMBK AS CALC_PHYSCN_STATE_LIC_ID
,CUST.CALC_GENDA_ST_PHY_LIC_EMBK AS CALC_PHYSCN_STATE_LIC_VALID_TO_DTE
,CUST.EXGEN_DME_LIC_EMBK AS CALC_PHYSCN_DME_LIC_ID
,CUST.CALC_GENDA_DME_LIC_EMBK AS CALC_PHYSCN_DME_LIC_VALID_TO_DTE
,CUST.EXGEN_ST_PRIS_EMBK  AS CALC_EXGEN_ST_PRIS_EMBK
,CUST.CALC_GENDA_ST_PRIS_LIC_EMBK
,CUST.EXGEN_ST_LIC_EMBK  AS CALC_EXGEN_ST_LIC_EMBK
,CUST.CALC_GENDA_ST_LIC_EMBK
,CUST.TXJCD_KNA1
,CUST.CIVVE_KNA1
,KNA1.YYPRIME_KNA1
,PBU.DESCR_YTSD_PRIMARY_BU AS DESCR_YTSD_PRIMARY_BU_PRIMARY_BUSINESS_UNIT
,KNA1.YYPGSTART_KNA1
,KNA1.YYPGEND_KNA1
,KNA1.YYOPDXMPT_KNA1--,IF(CUST.YYOPDXMPT_KNA1='X','Y','N') AS YYOPDXMPT_KNA1
,'' AS YYFRTMON_KNA1--,IF(CUST.YYFRTMON_KNA1='X','Y','N') AS YYFRTMON_KNA1
,'' AS YYFRTTUE_KNA1--,IF(CUST.YYFRTTUE_KNA1='X','Y','N') AS YYFRTTUE_KNA1
,'' AS YYFRTWED_KNA1--,IF(CUST.YYFRTWED_KNA1='X','Y','N') AS YYFRTWED_KNA1
,'' AS YYFRTTHU_KNA1--,IF(CUST.YYFRTTHU_KNA1='X','Y','N') AS YYFRTTHU_KNA1
,'' AS YYFRTFRI_KNA1--,IF(CUST.YYFRTFRI_KNA1='X','Y','N') AS YYFRTFRI_KNA1
,'' AS YYFRTSAT_KNA1--,IF(CUST.YYFRTSAT_KNA1='X','Y','N') AS YYFRTSAT_KNA1
,'' AS YYFRTSUN_KNA1--,IF(CUST.YYFRTSUN_KNA1='X','Y','N') AS YYFRTSUN_KNA1
,KNVI.TATYP AS TATYP_KNVI
,KNVI.TAXKD AS TAXKD_KNVI
,TCL.VTEXT_TSKDT AS VTEXT_TSKDT_TAX_CLASSIFICATION
,CUST.ADRNR_KNA1
,ADRC.BUILDING AS BUILDING_ADRC
,CUST.TXT30_T077X
,CUST.LANDX50_T005T
,CUST.NATIO50_T005T
,CUST.VTEXT_TVAST
,CUST.VTEXT_TVFST
,CUST.VTEXT_TVLST
,CUST.COUNC_KNA1
,CUST.EXABL_KNA1
,CUST.KNAZK_KNA1
,CUST.KNRZA_KNA1
,CUST.LIFNR_KNA1
,CUST.STCD1_KNA1
,CUST.STCD2_KNA1
,CUST.STCD3_KNA1
,CUST.STCD4_KNA1
,CUST.SPERZ_KNA1
,CUST.CASSD_KNA1
,CUST.NODEL_KNA1
,CUST.MCOD1_KNA1
,CUST.MCOD2_KNA1
,CUST.MCOD3_KNA1
,CUST.ANRED_KNA1
,CUST.BAHNE_KNA1
,CUST.BAHNS_KNA1
,CUST.BEGRU_KNA1
,CUST.DATLT_KNA1
,CUST.KONZS_KNA1
,CUST.NIELS_KNA1
,CUST.SPRAS_KNA1
,CUST.TELF2_KNA1
,CUST.XZEMP_KNA1
,CUST.STCEG_KNA1
,CUST.BRAN1_KNA1
,CUST.KATR10_KNA1
,CUST.WERKS_KNA1
,CUST.HZUOR_KNA1
,CUST.PFORT_KNA1
,CUST.MILVE_KNA1
,CUST.FITYP_KNA1
,CUST.KNURL_KNA1
,CUST.J_1KFTBUS_KNA1
,CUST.J_1KFTIND_KNA1
,CUST.YYHRSA_KNA1
,CUST.YYHIN_KNA1
,CUST.PARTNER_UKMBP_CMS
,''AS CREDIT_GROUP_UKMBP
,'' AS YNAT_ACC_YTSD_NAT_A
,'' AS YNAME_YTSD_NAT_ACCO
,CUST.FAUSA_T077D
,CUST.FAUSF_T077D
,CUST.FAUSV_T077D
,CUST.XCPDS_T077D
,CUST.DEAR1_T077D
,CUST.DEAR2_T077D
,CUST.DEAR3_T077D
,CUST.DEAR4_T077D
,CUST.DEAR5_T077D
,CUST.DEAR6_T077D
,CUST.STREET_ADRC
,CUST.POST_CODE1_ADRC
,CUST.CITY1_ADRC
,CUST.COUNTRY_ADRC
,CUST.REGION_ADRC
,CUST.TEXJURCODE_ADRC
,CUST.PO_BOX_ADRC
,CUST.POST_CODE2_ADRC
,CUST.POST_CODE3_ADRC
,CUST.LANGU_ADRC
,CUST.TELNR_LONG_ADRC
,CUST.SMTP_ADDR_ADRC
,CUST.FAXNR_LONG_ADRC
,CUST.BRTXT_T016T
,CUST.VTEXT_TKUKT
,CUST.HOUSE_NUM1_ADRC
,CUST.CALC_BRSCH_KNA1
,CUST.TITLE_MEDI_TSAD3T
,CUST.ZSLTSTMP
,CUST.STR_SUPPL1_ADRC
,CUST.CALC_GPO_CUST_FLAG
,CUST.CALC_WAC_CUST_FLAG
,CONCAT(CUST.KUNNR_KNA1,CUST.START_DTE) AS COMPOSITE_KEY
,v_start_stp AS ROW_ADD_STP
,v_stored_proc_name AS ROW_ADD_USER_ID
,v_start_stp AS ROW_UPDATE_STP
,v_stored_proc_name AS ROW_UPDATE_USER_ID

FROM PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_CUSTOM__CUSTOMERMASTER_SCD_CV CUST

LEFT JOIN KNA1_TEMP KNA1 ON
CUST.KUNNR_KNA1 = KNA1.KUNNR_KNA1

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CENTRAL_ORDER_BLOCK_CV` COB ON
CUST.AUFSD_KNA1 = COB.AUFSP_TVAST
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.INDUSTRY_KEY_CV` IKY ON
CUST.BRSCH_KNA1=IKY.BRSCH_T016T
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CENTRAL_BILLING_BLOCK_CV` CBB ON
CUST.FAKSD_KNA1=CBB.FAKSP_TVFST
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_ACCOUNT_GROUP_CV` CAG ON
CUST.KTOKD_KNA1=CAG.KTOKD_T077X
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CLASS_OF_TRADE_LEVEL_ONE_CV` CL1 ON
CUST.KUKLA_KNA1=CL1.KUKLA_TKUKT
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CENTRAL_DELIVERY_BLOCK_CV` CDB ON
CUST.LIFSD_KNA1=CDB.LIFSP_TVLS
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.TRADING_PARTNER_COMPANY_CV` TPC ON
CUST.VBUND_KNA1=TPC.NAME1_T880
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.LEGAL_STATUS_CV` LST ON
CUST.GFORM_KNA1=LST.GFORM_TVGFT
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.BACKORDER_RESTRICTION_CV` BRT ON
KNA1.KATR6_KNA1=BRT.KATR6_TVK6T
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.OTC_RESTRICTION_CV` OTC ON
KNA1.KATR7_KNA1=OTC.VTEXT_TVK7T
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.C2_RESTRICTION_CV` C2R ON
KNA1.KATR8_KNA1=C2R.KATR8_TVK8T

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.PRIMARY_BUSINESS_UNIT_CV` PBU ON
KNA1.YYPRIME_KNA1=PBU.YYPRIME_YTSD_PRIMARY_BU
LEFT JOIN
`PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__ADRC_CV` ADRC ON
CUST.ADRNR_KNA1 = ADRC.ADDRNUMBER
LEFT JOIN
`PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__KNVI_CV` KNVI ON
CUST.KUNNR_KNA1 = KNVI.KUNNR
AND KNVI.ALAND = 'US'
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.TAX_CLASSIFICATION_CV` TCL ON
KNVI.TAXKD=TCL.TAXKD_TSKDT

WHERE CUST.D0_CURR_VRSN_FLG = 'Y' /* latest record only */
AND CUST.D0_START_STP <= v_last_timestamp;

-- UPDATE THE EVENT TABLE

UPDATE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.LAST_TIMESTAMP_CUSTOMER_EV` SET SP_CUSTOMER_DELTA_LOAD_STP = v_last_timestamp WHERE 1=1;

END;