CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_EDI832_PARAMETER()
BEGIN

/***********************************************************************************************************************
Author: Debapriya Banerjee
Creation Date: 10/23/2023
Data Sources:	VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__CHPDPE_CD_PARAM_CV
				VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__CHPDPE_IN_CDT_CV
                VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__CHPDPE_SIN_CDT_CV
                VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__CHPDPE_SCOPT_CV
*************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time datetime;
DECLARE v_start_stp timestamp;
DECLARE v_end_stp timestamp;
DECLARE v_stored_proc_name string;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_EDI832_PARAMETER';

--Flush the PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_EDI832_PARAMETER_CV table

TRUNCATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_EDI832_PARAMETER_CV`;

-- Insert into `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_EDI832_PARAMETER_CV`

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_EDI832_PARAMETER_CV`
SELECT DISTINCT
	CP.KUNNR AS KUNNR_CHPDPE_CD_PARAM,
	CP.VKORG AS VKORG_CHPDPE_CD_PARAM,
	CP.VTWEG AS VTWEG_CHPDPE_CD_PARAM,
	CP.SPART AS SPART_CHPDPE_CD_PARAM,
	CP.TRADING_PTR AS TRADING_PTR_CHPDPE_CD_PARAM,
	CP.ACTIVE AS ACTIVE_CHPDPE_CD_PARAM,
	CP.NHIN_FLG AS NHIN_FLG_CHPDPE_CD_PARAM,
	CP.AWP_FLG AS AWP_FLG_CHPDPE_CD_PARAM,
	CP.INV_FLG AS INV_FLG_CHPDPE_CD_PARAM,
	CP.SUP_340B_FLG AS SUP_340B_FLG_CHPDPE_CD_PARAM,
	SAFE_CAST(CP.PRIORITY AS INT64) AS PRIORITY_CHPDPE_CD_PARAM,
	CP.INCODE AS INCODE_CHPDPE_CD_PARAM,
	'PENDING' AS DESCR_CHPDPE_IN_CDT,  --IFNULL(CIC.DESCR, 'NOT_AVAILABLE')
	CP.SINCODE AS SINCODE_CHPDPE_CD_PARAM,
	'PENDING' AS DESCR_CHPDPE_SIN_CDT,  --IFNULL(CSC.DESCR, 'NOT_AVAILABLE')
	CP.SI_TWCODE AS SI_TWCODE_CHPDPE_CD_PARAM,
	SAFE_CAST(CP.SI_NOOFDAY AS INT64) AS SI_NOOFDAY_CHPDPE_CD_PARAM,
	SAFE_CAST(CP.SI_NOOFMTH AS INT64) AS SI_NOOFMTH_CHPDPE_CD_PARAM,
	SAFE_CAST(CP.INV_DAYS AS INT64) AS INV_DAYS_CHPDPE_CD_PARAM,
	CP.CAT_TYPE1 AS CAT_TYPE1_CHPDPE_CD_PARAM,
	CP.SCOPT1 AS SCOPT1_CHPDPE_CD_PARAM,
	'PENDING' AS DESCR_CHPDPE_SCOPT1,   --IFNULL(CS1.DESCR, 'NOT_AVAILABLE')
	CP.PROFILE_ID1 AS PROFILE_ID1_CHPDPE_CD_PARAM,
	CP.DEF_EXEC1 AS DEF_EXEC1_CHPDPE_CD_PARAM,
	CP.CAT_TYPE2 AS CAT_TYPE2_CHPDPE_CD_PARAM,
	CP.SCOPT2 AS SCOPT2_CHPDPE_CD_PARAM,
	'PENDING' AS DESCR_CHPDPE_SCOPT2,  --IFNULL(CS2.DESCR, 'NOT_AVAILABLE')
	CP.PROFILE_ID2 AS PROFILE_ID2_CHPDPE_CD_PARAM,
	CP.DEF_EXEC2 AS DEF_EXEC2_CHPDPE_CD_PARAM,
	IFNULL(SAFE_CAST(CP.ERDAT AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS ERDAT_CHPDPE_CD_PARAM,
	CP.ERNAM AS ERNAM_CHPDPE_CD_PARAM,
	SAFE_CAST(CP.ERZET AS TIME FORMAT 'HH24MISS') AS ERZET_CHPDPE_CD_PARAM,
	IFNULL(SAFE_CAST(CP.AEDAT AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS AEDAT_CHPDPE_CD_PARAM,
	CP.AENAM AS AENAM_CHPDPE_CD_PARAM,
	SAFE_CAST(CP.AEZET AS TIME FORMAT 'HH24MISS') AS AEZET_CHPDPE_CD_PARAM,
	'PENDING' AS CAT_ACC_TYPE_CHPDPE_CD_PARAM,  --CP.CAT_ACC_TYPE
	'PENDING' AS NHIN_SORT_OPT_CHPDPE_CD_PARAM,  --CP.NHIN_SORT_OPT
	'PENDING' AS BASE_PRICE_CHPDPE_CD_PARAM,  --CP.BASE_PRICE
	'PENDING' AS CONT_PRICE_CHPDPE_CD_PARAM,  --CP.CONT_PRICE
	'PENDING' AS CATLG_PRICE_CHPDPE_CD_PARAM,  --CP.CATLG_PRICE
	'PENDING' AS MSRP_CHPDPE_CD_PARAM,  --CP.MSRP
	'PENDING' AS NDC_CHPDPE_CD_PARAM,  --CP.NDC
	'PENDING' AS NDC_IND_CHPDPE_CD_PARAM,  --CP.NDC_IND
	'PENDING' AS PACK_QTY_CHPDPE_CD_PARAM,  --CP.PACK_QTY
	'PENDING' AS ONE_CIN_PER_NDC_CHPDPE_CD_PARAM,  --CP.ONE_CIN_PER_NDC
	'PENDING' AS NDC_SORT_ORDER_CHPDPE_CD_PARAM,  --CP.NDC_SORT_ORDER
	'PENDING' AS SEND_SUBS_INFO_CHPDPE_CD_PARAM,  --CP.SEND_SUBS_INFO
	'PENDING' AS CUST_TZONE_CHPDPE_CD_PARAM,  --CP.CUST_TZONE
	'PENDING' AS CUST_FNAME_CHPDPE_CD_PARAM,  --CP.CUST_FNAME
	'PENDING' AS DELVRY_IND_CHPDPE_CD_PARAM,  --CP.DELVRY_IND
	v_start_stp AS ROW_ADD_STP,
	v_stored_proc_name AS ROW_ADD_USER_ID,
	v_start_stp AS ROW_UPDATE_STP,
	v_stored_proc_name AS ROW_UPDATE_USER_ID
FROM `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_SAPERP__CHPDPE_CD_PARAM_CV` CP
--LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__CHPDPE_IN_CDT_CV` CIC ON CP.INCODE = CIC.INCODE
--LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__CHPDPE_SIN_CDT_CV` CSC ON CP.SINCODE = CSC.SINCODE
--LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__CHPDPE_SCOPT_CV` CS1 ON CP.SCOPT1 = CS1.SCOPT1
--LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__CHPDPE_SCOPT_CV` CS2 ON CP.SCOPT2 = CS2.SCOPT2
;

END;