CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_PARTNER_FUNCTION_RLT()
BEGIN

/***********************************************************************************************************************
Author: Akshobhya S Achar
Creation Date: 05/09/2023
Data Sources: VI0_PHM_ORP_PE1_PH1_NP.KNVP_CV
*************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
	<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time DATETIME;
DECLARE v_start_stp TIMESTAMP;
DECLARE v_end_stp TIMESTAMP;
DECLARE v_end_scd_stp TIMESTAMP;
DECLARE v_stored_proc_name STRING;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_PARTNER_FUNCTION_RLT';

/* Select the latest record from the table */

TRUNCATE TABLE D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_PARTNER_FUNCTION_RLT_CV;

CREATE OR REPLACE TEMPORARY TABLE KNVP_TEMP
AS
SELECT
 KNVP.KUNNR
,KNVP.VKORG
,KNVP.VTWEG
,KNVP.SPART
,KNVP.PARVW
,DATE(v_start_stp)  AS VRSN_START_DTE
,DATE(v_end_stp)   AS VRSN_END_DTE
,'Y'   AS  CURR_VRSN_FLG
,PFC.VTEXT_TPART AS VTEXT_TPART_PARTNER_FUNCTION_CODE
,KNVP.KUNN2
,CAST (KNVP.PARZA AS INT64) AS PARZA
FROM `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__KNVP_CV` KNVP
LEFT JOIN `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.PARTNER_FUNCTION_CODE_CV` PFC
ON KNVP.PARVW = PFC.PARVW_TPART
WHERE KNVP.D0_CURR_VRSN_FLG = 'Y';

/*Perform an UPSERT on the target table

Step 1: Identify records to be inserted */

CREATE OR REPLACE TEMPORARY TABLE KNVP_TEMP_INS
AS
SELECT
 KUNNR
,VKORG
,VTWEG
,SPART
,PARVW
,TMP.VRSN_START_DTE
,TMP.VRSN_END_DTE
,TMP.CURR_VRSN_FLG
,TMP.VTEXT_TPART_PARTNER_FUNCTION_CODE
,KUNN2
,PARZA
FROM KNVP_TEMP TMP
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_PARTNER_FUNCTION_RLT_CV` TGT
ON TMP.KUNNR=TGT.KUNNR_KNVP
AND TMP.VKORG=TGT.VKORG_KNVP
AND TMP.VTWEG=TGT.VTWEG_KNVP
AND TMP.SPART=TGT.SPART_KNVP
AND TMP.PARVW=TGT.PARVW_KNVP
AND TGT.VRSN_START_DTE = TMP.VRSN_START_DTE
WHERE TGT.KUNNR_KNVP IS NULL
AND TGT.VKORG_KNVP IS NULL
AND TGT.VTWEG_KNVP IS NULL
AND TGT.SPART_KNVP IS NULL
AND TGT.PARVW_KNVP IS NULL;

/*Step 2: Update records where the source and target match */

UPDATE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_PARTNER_FUNCTION_RLT_CV` TGT
SET
TGT.VRSN_END_DTE = TMP.VRSN_END_DTE
,TGT.CURR_VRSN_FLG = TMP.CURR_VRSN_FLG
,TGT.VTEXT_TPART_PARTNER_FUNCTION_CODE =   TMP.VTEXT_TPART_PARTNER_FUNCTION_CODE
,TGT.KUNN2_KNVP = TMP.KUNN2
,TGT.PARZA_KNVP = TMP.PARZA
,ROW_UPDATE_STP=v_start_stp
FROM KNVP_TEMP TMP
WHERE TMP.KUNNR=TGT.KUNNR_KNVP
AND TMP.VKORG=TGT.VKORG_KNVP
AND TMP.VTWEG=TGT.VTWEG_KNVP
AND TMP.SPART=TGT.SPART_KNVP
AND TMP.PARVW=TGT.PARVW_KNVP
AND TGT.VRSN_START_DTE = TMP.VRSN_START_DTE;

/*Step 3: Insert records into the target */

INSERT INTO D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_PARTNER_FUNCTION_RLT_CV
SELECT
KUNNR
,VKORG
,VTWEG
,SPART
,PARVW
,VRSN_START_DTE
,VRSN_END_DTE
,CURR_VRSN_FLG
,VTEXT_TPART_PARTNER_FUNCTION_CODE
,KUNN2
,PARZA
,v_start_stp AS ROW_ADD_STP
,v_stored_proc_name AS ROW_ADD_USER_ID
,v_start_stp AS ROW_UPDATE_STP
,v_stored_proc_name AS ROW_UPDATE_USER_ID
FROM KNVP_TEMP_INS;

END;