CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_SALES_AREA_RLT_DELTA_LOAD()
BEGIN

/***********************************************************************************************************************
Author: AKSHOBHYA S ACHAR
Creation Date: 05/15/2023
Data Sources: VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_CUSTOM__CUSTOMERSALESDATA_SCD_CV
Purpose: This is the Incremental load of theCustomer Sales Area Relationship Process. This is run to populate the CUSTOMER_SALES_AREA_RLT_CV With Daily Inserts and Updates.
*************************************************************************
Change History                  [DATE]               [CHANGED BY]    [JIRA#]     [CODE REVIEW BY]       [DESCRIPTION]
<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time DATETIME;
DECLARE v_start_stp TIMESTAMP;
DECLARE v_end_stp TIMESTAMP;
DECLARE v_end_scd_stp TIMESTAMP;
DECLARE v_stored_proc_name STRING;
DECLARE v_last_timestamp TIMESTAMP;
DECLARE v_proc_timestamp TIMESTAMP;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT SAFE_CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_SALES_AREA_RLT_DELTA_LOAD';

--STEP 1: Get the previous run timestamp from the event table.
SET v_proc_timestamp = (SELECT IFNULL(SP_CUSTOMER_SALES_AREA_RLT_DELTA_LOAD_STP, TIMESTAMP '1900-01-01 00:00:00') FROM `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.LAST_TIMESTAMP_CUSTOMER_EV`);

--STEP 2: Get the current run timestamp.
SET v_last_timestamp = (SELECT MAX(D0_START_STP) FROM `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_CUSTOM__CUSTOMERSALESDATA_SCD_CV` );

--STEP 3: Create a temporary table to get all records from KNA1 which is missing in source
CREATE OR REPLACE TEMPORARY TABLE KNVV_TEMP
AS
SELECT
KNVV.KUNNR
,KNVV.VKORG
,KNVV.VTWEG
,KNVV.SPART
,KNVV.CAT_IND
,KNVV.YYFUELCHG
,KNVV.YYEDRPSPD
,KNVV.YYMPN
,KNVV.YYGRANTN
,KNVV.YYNEMERBLK
,KNVV.YYCUSFREACC
,KNVV.YYDODPVC
,KNVV.YYSTOREFRONT
,KNVV.YYRETAILMASK
,KNVV.YYFULLELECT
,KNVV.YYRETMASK_LABEL
,KNVV.YYIMS
,KNVV.YYCUSMASKDSC
,KNVV.YYORIGORDMSK
,KNVV.YYOESLOPT
,KNVV.YYSTKSLOPT
,KNVV.YYRETAIL
,KNVV.YYGRNDSHPIND
,KNVV.YYPACKINGLIST
,KNVV.YYPOCHK24
,KNVV.YYMINORDVAL
,KNVV.YYSATMINVAL
,KNVV.YYPKSLCUSTPO
,KNVV.YYCOMMITMNT
,KNVV.YYTYPE
,KNVV.YYPRIAME
,KNVV.YYVALHRSA
,KNVV.YYPHYDISP

FROM
PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__KNVV_CV KNVV
WHERE KNVV.D0_CURR_VRSN_FLG = 'Y';
--ALso Create Temp table to fetch DEA and State LIC from HVD and PR

CREATE OR REPLACE TEMPORARY TABLE HVDPR AS (
SELECT
  ROW_NUMBER() OVER (PARTITION BY CUSTOMERCROSSREFERENCE ORDER BY D0_START_STP DESC) AS RANK_ID,
  DIVISIONNUMBER,
  CASE
    WHEN prhvd.DIVISIONNUMBER = '066' THEN '0066'||LPAD(SAFE_CAST(prhvd.CUSTOMERCROSSREFERENCE AS STRING),6,'0')
    WHEN prhvd.DIVISIONNUMBER = '079' THEN '0079'||LPAD(SAFE_CAST(prhvd.CUSTOMERCROSSREFERENCE AS STRING),6,'0')
  ELSE
  'NO VAILD CUSTOMERCROSSREFERENCE '
END
  AS KUNNR_KNVV,
  CUSTOMERCROSSREFERENCE AS cust_num,
  DEALICENSE,
  CASE WHEN DEAEXPIRATION like ('%/') THEN PARSE_DATE('%m/%d/%Y',DEAEXPIRATION)
  ELSE SAFE_CAST(DEAEXPIRATION AS DATE FORMAT 'YYYYMMDD') END AS DEAEXPIRATION,
  SBPLICENSE,
  CASE WHEN SBPEXPIRATION like ('%/') THEN PARSE_DATE('%m/%d/%Y',SBPEXPIRATION)
  ELSE SAFE_CAST(SBPEXPIRATION AS DATE FORMAT 'YYYYMMDD') END AS SBPEXPIRATION,
    OTHERLICENSE,
  CASE WHEN OTHEREXPIRATION like ('%/') THEN PARSE_DATE('%m/%d/%Y',OTHEREXPIRATION)
  ELSE SAFE_CAST(OTHEREXPIRATION AS DATE FORMAT 'YYYYMMDD') END AS OTHEREXPIRATION,
FROM
  PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_EDA_PRHVR_CUSTOMER_MSTR__CUSTOMER_MASTER_DELTA_CV prhvd

   );

CREATE OR REPLACE TEMPORARY TABLE HVDPR_DEA AS SELECT * FROM HVDPR WHERE RANK_ID=1;

--STEP 4: Create a temporary table to get a) PRIMARY KEY, B) ACTION ID TO IDENTIFY INSERTS AND UPDATES, C) ROW ADD TIMESTAMPS WHICH IS EXPECTED TO BE PRESERVED FOR UPDATED COLUMNS, From the source VI2 views. A join with Target D1  table is needed to preserve the record ADD information

CREATE OR REPLACE TEMPORARY TABLE CUST_LATEST_RECORDS_TEMP AS
SELECT
CONCAT(SRC.KUNNR_KNVV,SRC.VKORG_KNVV,SRC.VTWEG_KNVV,SRC.SPART_KNVV,SRC.START_DTE) AS COMPOSITE_KEY
, SRC.D0_ACTION_ID
, TGT.ROW_ADD_STP
, TGT.ROW_ADD_USER_ID
FROM
PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_CUSTOM__CUSTOMERSALESDATA_SCD_CV  SRC
LEFT JOIN `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_SALES_AREA_RLT_CV` TGT
ON CONCAT(SRC.KUNNR_KNVV,SRC.VKORG_KNVV,SRC.VTWEG_KNVV,SRC.SPART_KNVV,SRC.START_DTE) = TGT.COMPOSITE_KEY
WHERE D0_CURR_VRSN_FLG = 'Y'
AND D0_START_STP>v_proc_timestamp;

--STEP 5: delete al records from the target which has been updated in the latest batch

DELETE FROM `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_SALES_AREA_RLT_CV` WHERE COMPOSITE_KEY IN (SELECT COMPOSITE_KEY FROM CUST_LATEST_RECORDS_TEMP WHERE D0_ACTION_ID = 'UPDATE') ;

--STEP 6: Insert all records as part of current Load

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_SALES_AREA_RLT_CV`
( KUNNR_KNVV
,VKORG_KNVV
,VTWEG_KNVV
,SPART_KNVV
,VRSN_START_DTE
,VRSN_END_DTE
,CURR_VRSN_FLG
,ERNAM_KNVV
,ERDAT_KNVV
,LOEVM_KNVV
,AUFSD_KNVV
,VTEXT_TVAST_CENTRAL_ORDER_BLOCK
,KALKS_KNVV
,VTEXT_TVKDT
,KDGRP_KNVV
,KTEXT_T151T_CLASS_OF_TRADE_LEVEL_TWO
,AWAHR_KNVV
,INCO1_KNVV
,BEZEI_TINCT_INCOTERMS
,INCO2_KNVV
,LIFSD_KNVV
,VTEXT_TVLST_CENTRAL_DELIVERY_BLOCK
,AUTLF_KNVV
,ANTLF_KNVV
,KZTLF_KNVV
,ITEM_PRTL_DELIVERIES_ALW_DESC_TXT_ITEM_PARTIAL_DELIVERY
,KZAZU_KNVV
,LPRIO_KNVV
,BEZEI_TPRIT_DELIVERY_PRIORITY
,EIKTO_KNVV
,VSBED_KNVV
,VTEXT_TVSBT_SHIPPING_CONDITIONS
,FAKSD_KNVV
,VTEXT_TVFST_CENTRAL_BILLING_BLOCK
,KTGRD_KNVV
,VTEXT_TVKTT_ACCOUNT_ASSIGNMENT_GROUP
,ZTERM_KNVV
,VTEXT_TVZBT_PAYMENT_TERMS
,VWERK_KNVV
,NAME1_T001W
,BWKEY_T001W
,KUNNR_T001W
,LIFNR_T001W
,FABKL_T001W
,NAME2_T001W
,STRAS_T001W
,PFACH_T001W
,PSTLZ_T001W
,ORT01_T001W
,REGIO_T001W
,LAND1_T001W
,KVGR1_KNVV
,BEZEI_TVV1T_CLASS_OF_TRADE_LEVEL_THREE
,KVGR2_KNVV
,BEZEI_TVV2T_PARMED_CUSTOMER_CLASSIFICATION
,KVGR3_KNVV
,BEZEI_TVV3T_GPO_CLASS_OF_TRADE
,KVGR4_KNVV
,BEZEI_TVV4T_STORE_SIZE_SPECIAL_GROUPING_ALL
,KVGR5_KNVV
,BEZEI_TVV5T_FINANCIAL_REPORTING
,KKBER_KNVV
,KKBTX_T014T_CREDIT_CONTROL_AREA
,PODKZ_KNVV
,CAT_IND_KNVV
,YYMULTBO_KNVV
,YYBOPRE1_KNVV
,YYBOPRE1_DES_YTSD_BOPRE1_TEXT_PRIMARY_BACKORDER_SELECTION
,YYBOPRE2_KNVV
,YYBOPRE3_KNVV
,YYBOPRE4_KNVV
,YYBOPRE5_KNVV
,YYBOPRE6_KNVV
,YYBOPRE7_KNVV
,YYBOPRE8_KNVV
,YYPRISEC_KNVV
,YYPRISEC_DES_YTSD_PRISEC_TEXT_PRIMARY_SECONDARY_CODE
,YYCONSIGN_KNVV
,YYCONSIGN_DES_YTSD_CONSIGN_TXT_CONSIGNMENT_PROGRAM
,YYHIN_KNVV
,YYHRSA_KNVV
,YYP_HRSA_KNVV
,YYDODAAC_KNVV
,YY340BCRP_KNVV
,YYRETGRP_KNVV
,YYRETGRP_DES_YTSD_RETGRP_TEXT_RETURNS_GROUP
,YYCREDANALYST_KNVV
,YYASHCO_KNVV
,YYCRMEMO_KNVV
,YYCRMEMO_DES_YTSD_CRMEMO_TEXT_CREDIT_MEMO_PREFERENCES
,YYGPOCRDAYS_KNVV
,YYDODACN_KNVV
,YYCHAINSTORE_KNVV
,YY340BCONFEE_KNVV
,YY340BCONFEE_DES_YTSD_340BCONFTXT_340B_CONTRACT_FEE_POLICY
,YYPVAPRI_KNVV
,YYFSTPURC_KNVV
,YYCOMTIME_KNVV
,YYFUELCHG_KNVV
,YYFUELCHG_DES_YTSD_FUELCHG_TXT_FUEL_SURCHARGE
,YYEDRPSPD_KNVV
,YYEDRPSPD_DES_YTSD_EDRPSPD_TXT_EDRP_SITES
,YYMPN_KNVV
,YYGRANTN_KNVV
,YYNEMERBLK_KNVV
,YYCUSFREACC_KNVV
,YYDODPVC_KNVV
,YYSTOREFRONT_KNVV
,YYSTOREFRONT_DES_YTSD_STORFRNTTXT_CUSTOMER_STOREFRONT
,YYCRPO_KNVV
,YYOCBYPO_KNVV
,YYINVSEQ_KNVV
,YYINVSEQ_DES_YTSD_INVSEQ_TEXT_PRINTED_INVOICE_SEQUENCE
,YYBRKRX_KNVV
,YYBRKSUP_KNVV
,YYBRKDEP_KNVV
,YYBRKINSPL_KNVV
,YYBRKNONINSPL_KNVV
,YYMULTCOP_KNVV
,MULTI_COPY_CUSTOMER_PREFER_DESC_TXT_MULTIPLE_COPIES_PREFERENCE
,YYSUPZEROINV_KNVV
,SPRS_PRINTING_ALL_ZERO_DLR_INVOICE_DESC_TXT_SUPPRESS_ZERO_PRINTING
,YYSTMASKPRE_KNVV
,YYSTMASKPRE_DES_YTSD_STMASKPRETX_STICKERS_PRICE_MASKING
,YYSUPPRINV_KNVV
,PRINTED_INVOICE_SUPPRESSION_DESC_TXT_SUPPRESS_PRINTED_INVOICE
,YYPDMA_KNVV
,YYBRKCONT_KNVV
,YYSRCONOTES_KNVV
,YYCONITORNOTE_KNVV
,YYCONMARKNOTE_KNVV
,YYSTICKCS_KNVV
,YYOEINVAPP_KNVV
,YYCUSMASK_KNVV
,YYCUSMASK_DES_YTSD_CUSMASK_TXT_ITEM_STICKERS_COST_MASKING
,YYSHELFLAB_KNVV
,YYSHELFLAB_DES_YTSD_SHELFLABTXT_SHELF_LABEL
,YYLABELABB_KNVV
,YYRETAILMASK_KNVV
,YYFULLELECT_KNVV
,YYRETMASK_LABEL_KNVV
,YYIMS_KNVV
,YYIMS_DES_YTSD_IMS_CODETXT_IMS_CODE
,YYCUSMASKDSC_KNVV
,YYORIGORDMSK_KNVV
,YYOESLOPT_KNVV
,SHELF_LABEL_OPTIONS_DESC_TXT_SHELF_LABEL_OPTIONS
,YYNCPDP1_KNVV
,YYNPI1_KNVV
,YYNABP1_KNVV
,YYPRCSTKR_KNVV
,YYDES_YTSD_PRC_STKR_TX_PRICE_STICKER
,YYSTKSLOPT_KNVV
,YYSTKSLOPT_DES_YTSD_STKSLOPTTXT_SHELF_LABEL_STICKER_OPTIONS
,YYLOTEXP_KNVV
,YYDES_YTSD_LOT_EXP_TXT_LOT_EXPIRATION_PREFERENCE
,YYLOCKBOX_KNVV
,HBKID_T049L
,LCKNR_T049L
,ADRNR_T049L
,YYCOLLECTOR_KNVV
,YYCOLLGROUP_KNVV
,COLL_GROUP_TEXT_UDM_COLL_GRPT_COLLECTION_GROUP
,YYDUPORDER_KNVV
,YYWEBIND_KNVV
,YYSAMECUTOFF_KNVV
,YYNEXTCUTOFF_KNVV
,YYONBOARDID_KNVV
,YYLOTTRACK_KNVV
,YYNOPRINV_KNVV
,YYRETAIL_KNVV
,RETAIL_PRICE_IND_DESC_TXT_RETAIL_PRICING_INDICATOR
,YYINVBATCH_KNVV
,YYCOMMODITY_KNVV
,CUSTOMER_STOCK_NUM_DESC_TXT_CUSTOMER_STOCK_NUMBER_CODE
,YYPRICEMASKINV_KNVV
,YYPRICEMASKINV_DES_YTSD_PREMSKINVTX_INVOICE_PRICE_MASKING
,YYSTORESUP_KNVV
,YYHAMCHZ_KNVV
,YYRPRPT_DESC_YTSD_HAMACHER_ZL_RETAIL_PRICE_TIER
,YYPCDCHG_KNVV
,YYMARKETKEY_KNVV
,YYGRNDSHPIND_KNVV
,YYPACKINGLIST_KNVV
,YYPOREQ_KNVV
,YYPOCHK24_KNVV
,YYMINORDVAL_KNVV
,YYSATMINVAL_KNVV
,YYPKSLPOV_KNVV
,YYRTRNRFID_KNVV
,YYBLMSH_KNVV
,YYCGVLTCNS_KNVV
,YYRTNCRDPU_KNVV
,YYPKSLCUSTPO_KNVV
,YYCOMMITMNT_KNVV
,YYCOMMITMNT_DES_YTSD_COMMIT_TXT_COMMITMENT_LEVEL
,YYTYPE_KNVV
,YYTYPE_DES_YTSD_TYPE_TXT_SPD_VITALSOURCE_MEMBERSHIP_TYPE
,YYPRIAME_KNVV
,YYVALHRSA_KNVV
,YYPHYDISP_KNVV
,YYPHYDISP_DES_YTSD_PHYDIS_TEXT_SPD_PHYSICIAN_DISPENSING
,CALC_CUST_SALES_AREA_KEY
,CALC_SALES_AREA_KEY
,CALC_HIGHER_LVL_CUST_SALES_AREA_KEY
,CALC_BRSCH_KNA1
,CALC_GENDA_DEA_EMBK
,CALC_GENDA_ST_EMBK
,CALC_GENDA_ST_CTRL_EMBK
,CALC_GENDA_PHY_DEA_EMBK
,PODTG_KNVV
,AGREL_KNVV
,RDOFF_KNVV
,CASSD_KNVV
,KABSS_KNVV
,PRATA_KNVV
,PRAT3_KNVV
,PRAT2_KNVV
,PRAT1_KNVV
,PRFRE_KNVV
,BOIDT_KNVV
,BOKRE_KNVV
,KLABC_KNVV
,WAERS_KNVV
,PERRL_KNVV
,PERFK_KNVV
,MRNKZ_KNVV
,PLTYP_KNVV
,KONDA_KNVV
,BZIRK_KNVV
,VERSG_KNVV
,BEGRU_KNVV
,YYRETAIL__KNVV
,ZZ_SEND_EDI_KNVV
,ZZ_SH_COPY_KNVV
,ZZ_WEB_KNVV
,ZZ_PRINT_KNVV
,ZZ_FAX_KNVV
,ZZ_EMAIL_KNVV
,ZZ_PRICE_KNVV
,ZZ_RX_PATIENT_KNVV
,ZZ_INVOICE_SH_KNVV
,EXGEN_DEA_EMBK
,EXGEN_ST_EMBK
,EXGEN_ST_CTRL_SUB_EMBK
,EXGEN_PHY_DEA_EMBK
,NAME1_KNA1_SB
,KUNN2_KNVP_SB
,NAME1_KNA1_CN
,KUNN2_KNVP_CN
,NAME1_KNA1_CM
,KUNN2_KNVP_CM
,NAME1_KNA1_A3
,KUNN2_KNVP_A3
,NAME1_KNA1_A2
,KUNN2_KNVP_A2
,NAME1_KNA1_A1
,KUNN2_KNVP_A1
,YYCONSIGN_DES_YTSD_CONSIGN_TXT
,HSPART_KNVH
,HVTWEG_KNVH
,HVKORG_KNVH
,HKUNNR_KNVH
,YNAME_YTSD_NAT_ACCOUNT
,YNAT_ACC_YTSD_NAT_ACCOUNT
,VTEXT_TVSBT
,VTEXT_TKUKT
,BEZEI_TINCT
,VTEXT_TVTWT
,VTEXT_TSPAT
,VTEXT_TVKOT
,VTEXT_TVKTT
,VTEXT_TVAST
,BEZEI_TVV5T
,BEZEI_TVV3T
,BEZEI_TVV2T
,BEZEI_TVV1T
,KTEXT_T151T
,BRTXT_T016T
,KKBTX_T014T
,SMTP_ADDR_ADR6
,NODEL_KNA1
,J_1KFTIND_KNA1
,J_1KFTBUS_KNA1
,KNURL_KNA1
,CASSD_KNA1
,STCD4_KNA1
,STCD3_KNA1
,FITYP_KNA1
,CIVVE_KNA1
,SPERZ_KNA1
,WERKS_KNA1
,PFORT_KNA1
,KATR10_KNA1
,KATR1_KNA1
,BRAN1_KNA1
,GFORM_KNA1
,DEAR2_KNA1
,STCEG_KNA1
,VBUND_KNA1
,XZEMP_KNA1
,LZONE_KNA1
,TELF2_KNA1
,STCD2_KNA1
,SPRAS_KNA1
,SPERR_KNA1
,COUNC_KNA1
,PSTL2_KNA1
,PFACH_KNA1
,ORT02_KNA1
,NIELS_KNA1
,NAME4_KNA1
,NAME3_KNA1
,LIFSD_KNA1
,LOEVM_KNA1
,LIFNR_KNA1
,KUKLA_KNA1
,KTOKD_KNA1
,KNRZA_KNA1
,KNAZK_KNA1
,FAKSD_KNA1
,EXABL_KNA1
,DATLT_KNA1
,BUBKZ_KNA1
,BRSCH_KNA1
,BBSNR_KNA1
,BBBNR_KNA1
,BAHNS_KNA1
,BAHNE_KNA1
,AUFSD_KNA1
,ANRED_KNA1
,MCOD3_KNA1
,MCOD2_KNA1
,MCOD1_KNA1
,ADRNR_KNA1
,TELFX_KNA1
,TELF1_KNA1
,STRAS_KNA1
,SORTL_KNA1
,REGIO_KNA1
,PSTLZ_KNA1
,ORT01_KNA1
,NAME2_KNA1
,NAME1_KNA1
,LAND1_KNA1
,TATYP_KNVI
,TAXKD_KNVI
,VTEXT_TSKDT
,ZSLTSTMP_KNVV
,YACCRCYC_YTSDSOMCAL
,YCONSGRP_YTLE_CONSOLI_GRP
,BUILDING_ADRC
,PERSNUMBER_ADRP
,NAME_TEXT_ADRP
,YYRPRPT_DESC
,PARNR_KNVK
,TELF1_KNVK
,NAMEV_KNVK
,NAME1_KNVK
,VTEXT_TVFST
,VTEXT_TVLST
,TXJCD_KNA1
,STR_SUPPL1_ADRC
,CALC_GPO_CUST_FLAG
,CALC_WAC_CUST_FLAG
,CALC_ERDAT_KNVV
,EXGEN_PHY_ST_LIC_EMBK
,CALC_GENDA_ST_PHY_LIC_EMBK
,EXGEN_DME_LIC_EMBK
,CALC_GENDA_DME_LIC_EMBK
,KUNN2_KNVP
,NAME_USER
,OUT_EXT_SHIPTO_YTEDPAR
,CALC_BILLING_OUTBOUND_EDI_FLAG_YTSD_EDI_DUP
,CALC_SHIPTOCUSTOMERFLAG
,KUNNR_KNVP_SOLDTO
,NAME1_KNA1_SOLDTO
,CALC_YYFSTPURC_KNVV
,KUNN2_SOLD_KNVP
,ADRNR_PAYER_KNA1
,REGIO_PAYER_KNA1
,PSTLZ_PAYER_KNA1
,NAME1_PAYER_KNA1
,ORT01_PAYER_KNA1
,NAME2_PAYER_KNA1
,EXGEN_ST_PRIS_LIC_EMBK
,CALC_GENDA_ST_PRIS_LIC_EMBK
,BBBNR_PAYER_KNA1
,BBSNR_PAYER_KNA1
,BUBKZ_PAYER_KNA1
,KUNN2_KNVP_PAYTO
,BBBNR_SHIPTO_KNA1
,BBSNR_SHIPTO_KNA1
,BUBKZ_SHIPTO_KNA1
,KUNN2_KNVP_PG
,CALC_SGPO_1
,CALC_SGPO_2
,CALC_SGPO_3
,CALC_SGPO_4
,CALC_SGPO_5
,END_DTE
,KUNN2_KNVP_SALESREP
,NAME1_KNA1_SALESREP
,NAME2_KNA1_SALESREP
,CALC_SCHED_2_ITEM_ALLOW_FLG
,CALC_SCHED_3_ITEM_ALLOW_FLG
,CALC_SCHED_4_ITEM_ALLOW_FLG
,CALC_SCHED_5_ITEM_ALLOW_FLG
,CUSID_PCSBGC
,VWERK_KNVV_SOLDTO
,WERKS_KNA1_SOLDTO
,KUNN2_PAYER_KNVP
,KUNN2_BILLTO_KNVP
,NAME1_KNA1_BILLTO
,ADRNR_BILLTO_KNA1
,ORT01_BILLTO_KNA1
,PSTLZ_BILLTO_KNA1
,STRAS_BILLTO_KNA1
,REGIO_BILLTO_KNA1
,CALC_IS_SOLD_TO_FLAG
,CALC_IS_BILL_TO_FLAG
,CALC_IS_PAYER_FLAG
,COMPOSITE_KEY
,CALC_D0_START_STP
,PARNR_KNVK_SHIPPING
,TELF1_KNVK_SHIPPING
,NAMEV_KNVK_SHIPPING
,NAME1_KNVK_SHIPPING
,PARNR_KNVK_BILLING
,TELF1_KNVK_BILLING
,NAME1_KNVK_BILLING
,NAMEV_KNVK_BILLING
,CALC_SCHED_2N_ITEM_ALLOW_FLG
,CALC_SCHED_3N_ITEM_ALLOW_FLG
,ROW_ADD_STP
,ROW_ADD_USER_ID
,ROW_UPDATE_STP
,ROW_UPDATE_USER_ID
)
SELECT
 CUSA.KUNNR_KNVV
,CUSA.VKORG_KNVV
,CUSA.VTWEG_KNVV
,CUSA.SPART_KNVV
,CUSA.START_DTE AS VRSN_START_DTE
,CUSA.END_DTE  AS VRSN_END_DTE
,CUSA.CURR_VRSN_FLG
,CUSA.ERNAM_KNVV
,SAFE_CAST(CUSA.ERDAT_KNVV AS DATE FORMAT 'YYYYMMDD') AS ERDAT_KNVV
,IF(CUSA.LOEVM_KNVV ='X','Y','N')        AS LOEVM_KNVV
,CUSA.AUFSD_KNVV
,COB.VTEXT_TVAST AS VTEXT_TVAST_CENTRAL_ORDER_BLOCK
,CUSA.KALKS_KNVV
,CPP.VTEXT_TVKDT AS VTEXT_TVKDT_CUSTOMER_PRICING_PROCEDURE
,CUSA.KDGRP_KNVV
,COT2.KTEXT_T151T AS KTEXT_T151T_CLASS_OF_TRADE_LEVEL_TWO
,SAFE_CAST (CUSA.AWAHR_KNVV AS NUMERIC) AS AWAHR_KNVV
,CUSA.INCO1_KNVV
,INC.BEZEI_TINCT AS BEZEI_TINCT_INCOTERMS
,CUSA.INCO2_KNVV
,CUSA.LIFSD_KNVV
,CDB.VTEXT_TVLST AS VTEXT_TVLST_CENTRAL_DELIVERY_BLOCK
,IF(CUSA.AUTLF_KNVV = 'X', 'Y', 'N') AS AUTLF_KNVV
,SAFE_CAST(CUSA.ANTLF_KNVV AS INT64) AS ANTLF_KNVV
,CUSA.KZTLF_KNVV
,IPD.ITEM_PRTL_DELIVERIES_ALW_DESC_TXT AS ITEM_PRTL_DELIVERIES_ALW_DESC_TXT_ITEM_PARTIAL_DELIVERY
,IF(CUSA.KZAZU_KNVV = 'X', 'Y', 'N') AS KZAZU_KNVV
,SAFE_CAST(CUSA.LPRIO_KNVV AS INT64)
,DP.BEZEI_TPRIT AS BEZEI_TPRIT_DELIVERY_PRIORITY
,CUSA.EIKTO_KNVV
,CUSA.VSBED_KNVV
,SC.VTEXT_TVSBT AS VTEXT_TVSBT_SHIPPING_CONDITIONS
,CUSA.FAKSD_KNVV
,CBB.VTEXT_TVFST AS VTEXT_TVFST_CENTRAL_BILLING_BLOCK
,CUSA.KTGRD_KNVV
,AAG.VTEXT_TVKTT AS VTEXT_TVKTT_ACCOUNT_ASSIGNMENT_GROUP
,CUSA.ZTERM_KNVV
,PT.VTEXT_TVZBT AS VTEXT_TVZBT_PAYMENT_TERMS
,CASE WHEN VKORG_KNVV='4050' THEN 'P066'
      WHEN VKORG_KNVV='7370' THEN 'P079'
      ELSE CUSA.VWERK_KNVV END AS  VWERK_KNVV
,CUSA.NAME1_T001W
,T001W.BWKEY  AS BWKEY_T001W
,T001W.KUNNR  AS KUNNR_T001W
,T001W.LIFNR  AS LIFNR_T001W
,T001W.FABKL  AS FABKL_T001W
,T001W.NAME2  AS NAME2_T001W
,T001W.STRAS  AS STRAS_T001W
,T001W.PFACH  AS PFACH_T001W
,T001W.PSTLZ  AS PSTLZ_T001W
,T001W.ORT01  AS ORT01_T001W
,T001W.REGIO  AS REGIO_T001W
,T001W.LAND1  AS LAND1_T001W
,CUSA.KVGR1_KNVV
,COT3.BEZEI_TVV1T AS BEZEI_TVV1T_CLASS_OF_TRADE_LEVEL_THREE
,CUSA.KVGR2_KNVV
,PCC.BEZEI_TVV2T AS BEZEI_TVV2T_PARMED_CUSTOMER_CLASSIFICATION
,CUSA.KVGR3_KNVV
,GCOT.BEZEI_TVV3T AS BEZEI_TVV3T_GPO_CLASS_OF_TRADE
,CUSA.KVGR4_KNVV
,SAGA.BEZEI_TVV4T AS BEZEI_TVV4T_STORE_SIZE_SPECIAL_GROUPING_ALL
,CUSA.KVGR5_KNVV
,FR.BEZEI_TVV5T AS BEZEI_TVV5T_FINANCIAL_REPORTING
,CUSA.KKBER_KNVV
,CCA.KKBTX_T014T AS KKBTX_T014T_CREDIT_CONTROL_AREA
,IF(CUSA.PODKZ_KNVV = 'X', 'Y', 'N') AS PODKZ_KNVV
,IF(KNVV.CAT_IND = 'X', 'Y', 'N') AS CAT_IND_KNVV
,IF(CUSA.YYMULTBO_KNVV = 'X', 'Y', 'N') AS YYMULTBO_KNVV
,CUSA.YYBOPRE1_KNVV
,PBS.YYBOPRE1_DES_YTSD_BOPRE1_TEXT AS YYBOPRE1_DES_YTSD_BOPRE1_TEXT_PRIMARY_BACKORDER_SELECTION
,IF(CUSA.YYBOPRE2_KNVV = 'X', 'Y', 'N') AS YYBOPRE2_KNVV
,IF(CUSA.YYBOPRE3_KNVV = 'X', 'Y', 'N') AS YYBOPRE3_KNVV
,IF(CUSA.YYBOPRE4_KNVV = 'X', 'Y', 'N') AS YYBOPRE4_KNVV
,IF(CUSA.YYBOPRE5_KNVV = 'X', 'Y', 'N') AS YYBOPRE5_KNVV
,IF(CUSA.YYBOPRE6_KNVV = 'X', 'Y', 'N') AS YYBOPRE6_KNVV
,IF(CUSA.YYBOPRE7_KNVV = 'X', 'Y', 'N') AS YYBOPRE7_KNVV
,IF(CUSA.YYBOPRE8_KNVV = 'X', 'Y', 'N') AS YYBOPRE8_KNVV
,CUSA.YYPRISEC_KNVV
,PSC.YYPRISEC_DES_YTSD_PRISEC_TEXT AS YYPRISEC_DES_YTSD_PRISEC_TEXT_PRIMARY_SECONDARY_CODE
,CUSA.YYCONSIGN_KNVV
,CP.YYCONSIGN_DES_YTSD_CONSIGN_TXT AS YYCONSIGN_DES_YTSD_CONSIGN_TXT_CONSIGNMENT_PROGRAM
,CUSA.YYHIN_KNVV
,CUSA.YYHRSA_KNVV
,CUSA.YYP_HRSA_KNVV
,CUSA.YYDODAAC_KNVV
,IF(CUSA.YY340BCRP_KNVV = 'X', 'Y', 'N') AS YY340BCRP_KNVV
,CUSA.YYRETGRP_KNVV
,RG.YYRETGRP_DES_YTSD_RETGRP_TEXT AS YYRETGRP_DES_YTSD_RETGRP_TEXT_RETURNS_GROUP
,CUSA.YYCREDANALYST_KNVV
,IF(CUSA.YYASHCO_KNVV = 'X', 'Y', 'N') AS YYASHCO_KNVV
,CUSA.YYCRMEMO_KNVV
,CMP.YYCRMEMO_DES_YTSD_CRMEMO_TEXT AS YYCRMEMO_DES_YTSD_CRMEMO_TEXT_CREDIT_MEMO_PREFERENCES
,SAFE_CAST(CUSA.YYGPOCRDAYS_KNVV AS INT64) AS YYGPOCRDAYS_KNVV
,CUSA.YYDODACN_KNVV
,IF(CUSA.YYCHAINSTORE_KNVV = 'X', 'Y', 'N') AS YYCHAINSTORE_KNVV
,CUSA.YY340BCONFEE_KNVV
,CFP.YY340BCONFEE_DES_YTSD_340BCONFTXT AS YY340BCONFEE_DES_YTSD_340BCONFTXT_340B_CONTRACT_FEE_POLICY
,CUSA.YYPVAPRI_KNVV
,SAFE_CAST(CUSA.YYFSTPURC_KNVV AS DATE FORMAT 'YYYYMMDD') AS YYFSTPURC_KNVV
,SAFE_CAST(CUSA.YYCOMTIME_KNVV AS TIME) AS YYCOMTIME_KNVV
,KNVV.YYFUELCHG AS YYFUELCHG_KNVV
,FS.YYFUELCHG_DES_YTSD_FUELCHG_TXT AS YYFUELCHG_DES_YTSD_FUELCHG_TXT_FUEL_SURCHARGE
,KNVV.YYEDRPSPD AS YYEDRPSPD_KNVV
,ES.YYEDRPSPD_DES_YTSD_EDRPSPD_TXT AS YYEDRPSPD_DES_YTSD_EDRPSPD_TXT_EDRP_SITES
,KNVV.YYMPN AS YYMPN_KNVV
,KNVV.YYGRANTN AS  YYGRANTN_KNVV
,KNVV.YYNEMERBLK AS YYNEMERBLK_KNVV
,KNVV.YYCUSFREACC   AS  YYCUSFREACC_KNVV
,KNVV.YYDODPVC   AS  YYDODPVC_KNVV
,KNVV.YYSTOREFRONT AS YYSTOREFRONT_KNVV
,CS.YYSTOREFRONT_DES_YTSD_STORFRNTTXT AS YYSTOREFRONT_DES_YTSD_STORFRNTTXT_CUSTOMER_STOREFRONT
,IF(CUSA.YYCRPO_KNVV ='X','Y','N')       AS YYCRPO_KNVV
,IF(CUSA.YYOCBYPO_KNVV ='X','Y','N')     AS YYOCBYPO_KNVV
,CUSA.YYINVSEQ_KNVV
,PIS.YYINVSEQ_DES_YTSD_INVSEQ_TEXT AS YYINVSEQ_DES_YTSD_INVSEQ_TEXT_PRINTED_INVOICE_SEQUENCE
,IF(CUSA.YYBRKRX_KNVV = 'X', 'Y', 'N') AS YYBRKRX_KNVV
,IF(CUSA.YYBRKSUP_KNVV = 'X', 'Y', 'N') AS YYBRKSUP_KNVV
,IF(CUSA.YYBRKDEP_KNVV = 'X', 'Y', 'N') AS YYBRKDEP_KNVV
,IF(CUSA.YYBRKINSPL_KNVV = 'X', 'Y', 'N') AS YYBRKINSPL_KNVV
,IF(CUSA.YYBRKNONINSPL_KNVV = 'X', 'Y', 'N') AS YYBRKNONINSPL_KNVV
,SAFE_CAST(CUSA.YYMULTCOP_KNVV AS INT64) AS YYMULTCOP_KNVV
,MCP.MULTI_COPY_CUSTOMER_PREFER_DESC_TXT AS MULTI_COPY_CUSTOMER_PREFER_DESC_TXT_MULTIPLE_COPIES_PREFERENCE
,CUSA.YYSUPZEROINV_KNVV
,SZP.SPRS_PRINTING_ALL_ZERO_DLR_INVOICE_DESC_TXT AS SPRS_PRINTING_ALL_ZERO_DLR_INVOICE_DESC_TXT_SUPPRESS_ZERO_PRINTING
,CUSA.YYSTMASKPRE_KNVV
,SPM.YYSTMASKPRE_DES_YTSD_STMASKPRETX AS YYSTMASKPRE_DES_YTSD_STMASKPRETX_STICKERS_PRICE_MASKING
,CUSA.YYSUPPRINV_KNVV
,SPI.PRINTED_INVOICE_SUPPRESSION_DESC_TXT AS PRINTED_INVOICE_SUPPRESSION_DESC_TXT_SUPPRESS_PRINTED_INVOICE
,IF(CUSA.YYPDMA_KNVV = 'X', 'Y', 'N') AS YYPDMA_KNVV
,IF(CUSA.YYBRKCONT_KNVV = 'X', 'Y', 'N') AS YYBRKCONT_KNVV
,IF(CUSA.YYSRCONOTES_KNVV = 'X', 'Y', 'N') AS YYSRCONOTES_KNVV
,IF(CUSA.YYCONITORNOTE_KNVV = 'X', 'Y', 'N') AS YYCONITORNOTE_KNVV
,IF(CUSA.YYCONMARKNOTE_KNVV = 'X', 'Y', 'N') AS YYCONMARKNOTE_KNVV
,IF(CUSA.YYSTICKCS_KNVV = 'X', 'Y', 'N') AS YYSTICKCS_KNVV
,IF(CUSA.YYOEINVAPP_KNVV = 'X', 'Y', 'N') AS YYOEINVAPP_KNVV
,CUSA.YYCUSMASK_KNVV
,ISCM.YYCUSMASK_DES_YTSD_CUSMASK_TXT AS YYCUSMASK_DES_YTSD_CUSMASK_TXT_ITEM_STICKERS_COST_MASKING
,CUSA.YYSHELFLAB_KNVV
,SL.YYSHELFLAB_DES_YTSD_SHELFLABTXT AS YYSHELFLAB_DES_YTSD_SHELFLABTXT_SHELF_LABEL
,CUSA.YYLABELABB_KNVV
,IF(KNVV.YYRETAILMASK = 'X', 'Y', 'N') AS    YYRETAILMASK_KNVV
,IF(KNVV.YYFULLELECT = 'X', 'Y', 'N') AS     YYFULLELECT_KNVV
,IF(KNVV.YYRETMASK_LABEL = 'X', 'Y', 'N') AS YYRETMASK_LABEL_KNVV
,KNVV.YYIMS AS YYIMS_KNVV
,IC.YYIMS_DES_YTSD_IMS_CODETXT AS YYIMS_DES_YTSD_IMS_CODETXT_IMS_CODE
,KNVV.YYCUSMASKDSC AS YYCUSMASKDSC_KNVV
,IF(KNVV.YYORIGORDMSK = 'X', 'Y', 'N') AS YYORIGORDMSK_KNVV
,KNVV.YYOESLOPT AS YYOESLOPT_KNVV
,SLO.SHELF_LABEL_OPTIONS_DESC_TXT AS SHELF_LABEL_OPTIONS_DESC_TXT_SHELF_LABEL_OPTIONS
,CUSA.YYNCPDP1_KNVV
,CUSA.YYNPI1_KNVV
,CUSA.YYNABP1_KNVV
,CUSA.YYPRCSTKR_KNVV
,PS.YYDES_YTSD_PRC_STKR_TX AS YYDES_YTSD_PRC_STKR_TX_PRICE_STICKER
,KNVV.YYSTKSLOPT AS YYSTKSLOPT_KNVV
,SLSO.YYSTKSLOPT_DES_YTSD_STKSLOPTTXT AS YYSTKSLOPT_DES_YTSD_STKSLOPTTXT_SHELF_LABEL_STICKER_OPTIONS
,CUSA.YYLOTEXP_KNVV
,LEP.YYDES_YTSD_LOT_EXP_TXT AS YYDES_YTSD_LOT_EXP_TXT_LOT_EXPIRATION_PREFERENCE
,CUSA.YYLOCKBOX_KNVV
,T049L.HBKID AS HBKID_T049L
,SAFE_CAST(T049L.LOCKB AS INT64) AS LCKNR_T049L
,T049L.ADRNR AS ADRNR_T049L
,CUSA.YYCOLLECTOR_KNVV
,CUSA.YYCOLLGROUP_KNVV
,CG.COLL_GROUP_TEXT_UDM_COLL_GRPT AS COLL_GROUP_TEXT_UDM_COLL_GRPT_COLLECTION_GROUP
,IF(CUSA.YYDUPORDER_KNVV = 'X', 'Y', 'N') AS YYDUPORDER_KNVV
,IF(CUSA.YYWEBIND_KNVV = 'X', 'Y', 'N') AS YYWEBIND_KNVV
,SAFE_CAST(CUSA.YYSAMECUTOFF_KNVV AS TIME) AS YYSAMECUTOFF_KNVV
,SAFE_CAST(CUSA.YYNEXTCUTOFF_KNVV AS TIME) AS YYNEXTCUTOFF_KNVV
,CUSA.YYONBOARDID_KNVV
,IF(CUSA.YYLOTTRACK_KNVV = 'X', 'Y', 'N') AS YYLOTTRACK_KNVV
,IF(CUSA.YYNOPRINV_KNVV = 'X', 'Y', 'N') AS YYNOPRINV_KNVV
,KNVV.YYRETAIL AS YYRETAIL_KNVV
,RPI.RETAIL_PRICE_IND_DESC_TXT AS RETAIL_PRICE_IND_DESC_TXT_RETAIL_PRICING_INDICATOR
,IF(CUSA.YYINVBATCH_KNVV = 'X', 'Y', 'N') AS YYINVBATCH_KNVV
,CUSA.YYCOMMODITY_KNVV
,CSNC.CUSTOMER_STOCK_NUM_DESC_TXT AS CUSTOMER_STOCK_NUM_DESC_TXT_CUSTOMER_STOCK_NUMBER_CODE
,CUSA.YYPRICEMASKINV_KNVV
,IPM.YYPRICEMASKINV_DES_YTSD_PREMSKINVTX AS YYPRICEMASKINV_DES_YTSD_PREMSKINVTX_INVOICE_PRICE_MASKING
,IF(CUSA.YYSTORESUP_KNVV = 'X', 'Y', 'N') AS YYSTORESUP_KNVV
,CUSA.YYHAMCHZ_KNVV
,RPT.YYRPRPT_DESC_YTSD_HAMACHER_ZL AS YYRPRPT_DESC_YTSD_HAMACHER_ZL_RETAIL_PRICE_TIER
,SAFE_CAST(CUSA.YYPCDCHG_KNVV AS DATE FORMAT 'YYYYMMDD') AS YYPCDCHG_KNVV
,CUSA.YYMARKETKEY_KNVV
,IF(KNVV.YYGRNDSHPIND = 'X', 'Y', 'N') AS YYGRNDSHPIND_KNVV
,IF(KNVV.YYPACKINGLIST = 'X', 'Y', 'N') AS YYPACKINGLIST_KNVV
,IF(CUSA.YYPOREQ_KNVV = 'X', 'Y', 'N') AS YYPOREQ_KNVV
,IF(KNVV.YYPOCHK24 = 'X', 'Y', 'N') AS YYPOCHK24_KNVV
,KNVV.YYMINORDVAL  AS YYMINORDVAL_KNVV
,KNVV.YYSATMINVAL  AS YYSATMINVAL_KNVV
,IF(CUSA.YYPKSLPOV_KNVV = 'X', 'Y', 'N') AS YYPKSLPOV_KNVV
,IF(CUSA.YYRTRNRFID_KNVV = 'X', 'Y', 'N') AS YYYBLMSH_KNVVYRTRNRFID_KNVV
,IF(CUSA.YYBLMSH_KNVV = 'X', 'Y', 'N') AS YYBLMSH_KNVV
,IF(CUSA.YYCGVLTCNS_KNVV = 'X', 'Y', 'N') AS YYCGVLTCNS_KNVV
,IF(CUSA.YYRTNCRDPU_KNVV = 'X', 'Y', 'N') AS YYRTNCRDPU_KNVV
,IF(KNVV.YYPKSLCUSTPO = 'X', 'Y', 'N') AS YYPKSLCUSTPO_KNVVV
,KNVV.YYCOMMITMNT AS YYCOMMITMNT_KNVV
,CL.YYCOMMITMNT_DES_YTSD_COMMIT_TXT AS YYCOMMITMNT_DES_YTSD_COMMIT_TXT_COMMITMENT_LEVEL
,KNVV.YYTYPE AS YYTYPE_KNVV
,SVMT.YYTYPE_DES_YTSD_TYPE_TXT AS YYTYPE_DES_YTSD_TYPE_TXT_SPD_VITALSOURCE_MEMBERSHIP_TYPE
,KNVV.YYPRIAME AS YYPRIAME_KNVV
,IF(KNVV.YYVALHRSA ='X','Y','N')    AS YYVALHRSA_KNVV
,KNVV.YYPHYDISP AS YYPHYDISP_KNVV
,SPD.YYPHYDISP_DES_YTSD_PHYDIS_TEXT AS YYPHYDISP_DES_YTSD_PHYDIS_TEXT_SPD_PHYSICIAN_DISPENSING
,CUSA.CALC_CUST_SALES_AREA_KEY
,CUSA.CALC_SALES_AREA_KEY
,CUSA.CALC_HIGHER_LVL_CUST_SALES_AREA_KEY
,CUSA.CALC_BRSCH_KNA1
,CASE WHEN  CUSA.CALC_GENDA_DEA_EMBK IS NULL AND VKORG_KNVV IN('4050', '7370')
THEN DEA.DEAEXPIRATION ELSE CUSA.CALC_GENDA_DEA_EMBK END                           AS CALC_GENDA_DEA_EMBK
,CASE WHEN  CUSA.CALC_GENDA_ST_EMBK IS NULL AND VKORG_KNVV IN('4050', '7370')
THEN DEA.SBPEXPIRATION ELSE CUSA.CALC_GENDA_ST_EMBK END                            AS CALC_GENDA_ST_EMBK
,CASE WHEN  CUSA.CALC_GENDA_ST_CTRL_EMBK IS NULL AND VKORG_KNVV IN('4050', '7370')
THEN DEA.OTHEREXPIRATION ELSE CUSA.CALC_GENDA_ST_CTRL_EMBK END                            AS CALC_GENDA_ST_CTRL_EMBK
,CUSA.CALC_GENDA_PHY_DEA_EMBK
,CUSA.PODTG_KNVV
,CUSA.AGREL_KNVV
,CUSA.RDOFF_KNVV
,CUSA.CASSD_KNVV
,CUSA.KABSS_KNVV
,CUSA.PRATA_KNVV
,CUSA.PRAT3_KNVV
,CUSA.PRAT2_KNVV
,CUSA.PRAT1_KNVV
,CUSA.PRFRE_KNVV
,CUSA.BOIDT_KNVV
,CUSA.BOKRE_KNVV
,CUSA.KLABC_KNVV
,CUSA.WAERS_KNVV
,CUSA.PERRL_KNVV
,CUSA.PERFK_KNVV
,CUSA.MRNKZ_KNVV
,CUSA.PLTYP_KNVV
,CUSA.KONDA_KNVV
,CUSA.BZIRK_KNVV
,CUSA.VERSG_KNVV
,CUSA.BEGRU_KNVV
,CUSA.YYRETAIL__KNVV
,CUSA.ZZ_SEND_EDI_KNVV
,CUSA.ZZ_SH_COPY_KNVV
,CUSA.ZZ_WEB_KNVV
,CUSA.ZZ_PRINT_KNVV
,CUSA.ZZ_FAX_KNVV
,CUSA.ZZ_EMAIL_KNVV
,CUSA.ZZ_PRICE_KNVV
,CUSA.ZZ_RX_PATIENT_KNVV
,CUSA.ZZ_INVOICE_SH_KNVV
,CASE WHEN CUSA.EXGEN_DEA_EMBK IS NULL AND VKORG_KNVV IN('4050', '7370')
THEN DEA.DEALICENSE ELSE CUSA.EXGEN_DEA_EMBK END                                   AS EXGEN_DEA_EMBK
,CASE WHEN CUSA.EXGEN_ST_EMBK IS NULL AND VKORG_KNVV IN('4050', '7370')
THEN DEA.SBPLICENSE ELSE CUSA.EXGEN_ST_EMBK END                                    AS EXGEN_ST_EMBK
,CASE WHEN CUSA.EXGEN_ST_CTRL_SUB_EMBK IS NULL AND VKORG_KNVV IN('4050', '7370')
THEN DEA.OTHERLICENSE ELSE CUSA.EXGEN_ST_CTRL_SUB_EMBK END                                    AS EXGEN_ST_CTRL_SUB_EMBK
,CUSA.EXGEN_PHY_DEA_EMBK
,CUSA.NAME1_KNA1_SB
,CUSA.KUNN2_KNVP_SB
,CUSA.NAME1_KNA1_CN
,CUSA.KUNN2_KNVP_CN
,CUSA.NAME1_KNA1_CM
,CUSA.KUNN2_KNVP_CM
,CUSA.NAME1_KNA1_A3
,CUSA.KUNN2_KNVP_A3
,CUSA.NAME1_KNA1_A2
,CUSA.KUNN2_KNVP_A2
,CUSA.NAME1_KNA1_A1
,CUSA.KUNN2_KNVP_A1
,CUSA.YYCONSIGN_DES_YTSD_CONSIGN_TXT
,CUSA.HSPART_KNVH
,CUSA.HVTWEG_KNVH
,CUSA.HVKORG_KNVH
,CUSA.HKUNNR_KNVH
,CUSA.YNAME_YTSD_NAT_ACCOUNT
,CUSA.YNAT_ACC_YTSD_NAT_ACCOUNT
,CUSA.VTEXT_TVSBT
,CUSA.VTEXT_TKUKT
,CUSA.BEZEI_TINCT
,CUSA.VTEXT_TVTWT
,CUSA.VTEXT_TSPAT
,CUSA.VTEXT_TVKOT
,CUSA.VTEXT_TVKTT
,CUSA.VTEXT_TVAST
,CUSA.BEZEI_TVV5T
,CUSA.BEZEI_TVV3T
,CUSA.BEZEI_TVV2T
,CUSA.BEZEI_TVV1T
,CUSA.KTEXT_T151T
,CUSA.BRTXT_T016T
,CUSA.KKBTX_T014T
,CUSA.SMTP_ADDR_ADR6
,CUSA.NODEL_KNA1
,CUSA.J_1KFTIND_KNA1
,CUSA.J_1KFTBUS_KNA1
,CUSA.KNURL_KNA1
,CUSA.CASSD_KNA1
,CUSA.STCD4_KNA1
,CUSA.STCD3_KNA1
,CUSA.FITYP_KNA1
,IF(CUSA.CIVVE_KNA1 ='X','Y','N')        AS CIVVE_KNA1
,CUSA.SPERZ_KNA1
,CUSA.WERKS_KNA1
,CUSA.PFORT_KNA1
,CUSA.KATR10_KNA1
,IF(CUSA.KATR1_KNA1='X','Y','N')         AS KATR1_KNA1
,CUSA.BRAN1_KNA1
,CUSA.GFORM_KNA1
,CUSA.DEAR2_KNA1
,CUSA.STCEG_KNA1
,CUSA.VBUND_KNA1
,CUSA.XZEMP_KNA1
,CUSA.LZONE_KNA1
,CUSA.TELF2_KNA1
,CUSA.STCD2_KNA1
,CUSA.SPRAS_KNA1
,IF(KNVV.YYVALHRSA ='X','Y','N')    AS YYVALHRSA_KNVV
,CUSA.COUNC_KNA1
,CUSA.PSTL2_KNA1
,CUSA.PFACH_KNA1
,CUSA.ORT02_KNA1
,CUSA.NIELS_KNA1
,CUSA.NAME4_KNA1
,CUSA.NAME3_KNA1
,CUSA.LIFSD_KNA1
,IF(CUSA.LOEVM_KNA1 ='X','Y','N')        AS LOEVM_KNA1
,CUSA.LIFNR_KNA1
,CUSA.KUKLA_KNA1
,CUSA.KTOKD_KNA1
,CUSA.KNRZA_KNA1
,CUSA.KNAZK_KNA1
,CUSA.FAKSD_KNA1
,CUSA.EXABL_KNA1
,CUSA.DATLT_KNA1
,CUSA.BUBKZ_KNA1
,CUSA.BRSCH_KNA1
,CUSA.BBSNR_KNA1
,CUSA.BBBNR_KNA1
,CUSA.BAHNS_KNA1
,CUSA.BAHNE_KNA1
,CUSA.AUFSD_KNA1
,CUSA.ANRED_KNA1
,CUSA.MCOD3_KNA1
,CUSA.MCOD2_KNA1
,CUSA.MCOD1_KNA1
,CUSA.ADRNR_KNA1
,CUSA.TELFX_KNA1
,CUSA.TELF1_KNA1
,CUSA.STRAS_KNA1
,CUSA.SORTL_KNA1
,CUSA.REGIO_KNA1
,CUSA.PSTLZ_KNA1
,CUSA.ORT01_KNA1
,CUSA.NAME2_KNA1
,CUSA.NAME1_KNA1
,CUSA.LAND1_KNA1
,CUSA.TATYP_KNVI
,CUSA.TAXKD_KNVI
,CUSA.VTEXT_TSKDT
,CUSA.ZSLTSTMP_KNVV
,CUSA.YACCRCYC_YTSDSOMCAL
,CUSA.YCONSGRP_YTLE_CONSOLI_GRP
,CUSA.BUILDING_ADRC
,CUSA.PERSNUMBER_ADRP
,CUSA.NAME_TEXT_ADRP
,CUSA.YYRPRPT_DESC
,CUSA.PARNR_KNVK
,CUSA.TELF1_KNVK
,CUSA.NAMEV_KNVK
,CUSA.NAME1_KNVK
,CUSA.VTEXT_TVFST
,CUSA.VTEXT_TVLST
,CUSA.TXJCD_KNA1
,CUSA.STR_SUPPL1_ADRC
,CUSA.CALC_GPO_CUST_FLAG
,CUSA.CALC_WAC_CUST_FLAG
,CUSA.CALC_ERDAT_KNVV
,CUSA.EXGEN_PHY_ST_LIC_EMBK
,CUSA.CALC_GENDA_ST_PHY_LIC_EMBK
,CUSA.EXGEN_DME_LIC_EMBK
,CUSA.CALC_GENDA_DME_LIC_EMBK
,CUSA.KUNN2_KNVP
,CUSA.NAME_USER
,CUSA.OUT_EXT_SHIPTO_YTEDPAR
,CUSA.CALC_BILLING_OUTBOUND_EDI_FLAG_YTSD_EDI_DUP
,CUSA.CALC_SHIPTOCUSTOMERFLAG
,CUSA.KUNNR_KNVP_SOLDTO
,CUSA.NAME1_KNA1_SOLDTO
,CUSA.CALC_YYFSTPURC_KNVV
,CUSA.KUNN2_SOLD_KNVP
,CUSA.ADRNR_PAYER_KNA1
,CUSA.REGIO_PAYER_KNA1
,CUSA.PSTLZ_PAYER_KNA1
,CUSA.NAME1_PAYER_KNA1
,CUSA.ORT01_PAYER_KNA1
,CUSA.NAME2_PAYER_KNA1
,CUSA.EXGEN_ST_PRIS_LIC_EMBK
,CUSA.CALC_GENDA_ST_PRIS_LIC_EMBK
,CUSA.BBBNR_PAYER_KNA1
,CUSA.BBSNR_PAYER_KNA1
,CUSA.BUBKZ_PAYER_KNA1
,CUSA.KUNN2_KNVP_PAYTO
,CUSA.BBBNR_SHIPTO_KNA1
,CUSA.BBSNR_SHIPTO_KNA1
,CUSA.BUBKZ_SHIPTO_KNA1
,CUSA.KUNN2_KNVP_PG
,CUSA.CALC_SGPO_1
,CUSA.CALC_SGPO_2
,CUSA.CALC_SGPO_3
,CUSA.CALC_SGPO_4
,CUSA.CALC_SGPO_5
,CUSA.END_DTE
,CUSA.KUNN2_KNVP_SALESREP
,CUSA.NAME1_KNA1_SALESREP
,CUSA.NAME2_KNA1_SALESREP
,CUSA.CALC_SCHED_2_ITEM_ALLOW_FLG
,CUSA.CALC_SCHED_3_ITEM_ALLOW_FLG
,CUSA.CALC_SCHED_4_ITEM_ALLOW_FLG
,CUSA.CALC_SCHED_5_ITEM_ALLOW_FLG
,'' AS CUSID_PCSBGC  --,CUSA.CUSID_PCSBGC
,'' AS VWERK_KNVV_SOLDTO
,'' AS WERKS_KNA1_SOLDTO
,CUSA.KUNN2_PAYER_KNVP
,CUSA.KUNN2_BILLTO_KNVP
,CUSA.NAME1_KNA1_BILLTO
,CUSA.ADRNR_BILLTO_KNA1
,CUSA.ORT01_BILLTO_KNA1
,CUSA.PSTLZ_BILLTO_KNA1
,CUSA.STRAS_BILLTO_KNA1
,CUSA.REGIO_BILLTO_KNA1
,CUSA.CALC_IS_SOLD_TO_FLAG
,CUSA.CALC_IS_BILL_TO_FLAG
,CUSA.CALC_IS_PAYER_FLAG
,TEMPD.COMPOSITE_KEY
,CUSA.D0_START_STP AS CALC_D0_START_STP
,CUSA.PARNR_KNVK_SHIPPING
,CUSA.TELF1_KNVK_SHIPPING
,CUSA.NAMEV_KNVK_SHIPPING
,CUSA.NAME1_KNVK_SHIPPING
,CUSA.PARNR_KNVK_BILLING AS PARNR_KNVK_BILLING
,CUSA.TELF1_KNVK_BILLING AS TELF1_KNVK_BILLING
,CUSA.NAMEV_KNVK_BILLING AS NAMEV_KNVK_BILLING
,CUSA.NAME1_KNVK_BILLING AS NAME1_KNVK_BILLING
,CUSA.CALC_SCHED_2N_ITEM_ALLOW_FLG
,CUSA.CALC_SCHED_3N_ITEM_ALLOW_FLG
,CASE WHEN TEMPD.D0_ACTION_ID = 'UPDATE' AND TEMPD.ROW_ADD_STP IS NOT NULL THEN TEMPD.ROW_ADD_STP  -- Preserve the ROW_ADD_STP for updated records
         ELSE v_start_stp END AS ROW_ADD_STP
,CASE WHEN TEMPD.D0_ACTION_ID = 'UPDATE' AND TEMPD.ROW_ADD_STP IS NOT NULL THEN TEMPD.ROW_ADD_USER_ID -- Preserve the ROW_ADD_USER_ID for updated records
         ELSE v_stored_proc_name END AS ROW_ADD_USER_ID
,v_start_stp AS ROW_UPDATE_STP
,v_stored_proc_name AS ROW_UPDATE_USER_ID

FROM PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_CUSTOM__CUSTOMERSALESDATA_SCD_CV CUSA

INNER JOIN CUST_LATEST_RECORDS_TEMP  TEMPD   -- Join on the Temp table using the cmposite key to get the records
ON CONCAT(CUSA.KUNNR_KNVV,CUSA.VKORG_KNVV,CUSA.VTWEG_KNVV,CUSA.SPART_KNVV,CUSA.START_DTE) = TEMPD.COMPOSITE_KEY

INNER JOIN KNVV_TEMP KNVV ON
CUSA.KUNNR_KNVV = KNVV.KUNNR
AND CUSA.VKORG_KNVV = KNVV.VKORG
AND CUSA.VTWEG_KNVV = KNVV.VTWEG
AND CUSA.SPART_KNVV = KNVV.SPART

LEFT JOIN HVDPR_DEA DEA ON
CUSA.KUNNR_KNVV=DEA.KUNNR_KNVV

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CENTRAL_ORDER_BLOCK_CV` COB ON
CUSA.AUFSD_KNVV=COB.AUFSP_TVAST

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_PRICING_PROCEDURE_CV` CPP ON
CUSA.KALKS_KNVV=CPP.KALKS_TVKDT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CLASS_OF_TRADE_LEVEL_TWO_CV` COT2 ON
CUSA.KDGRP_KNVV=COT2.KDGRP_T151T

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.INCOTERMS_CV` INC ON
CUSA.INCO1_KNVV=INC.INCO1_TINCT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CENTRAL_DELIVERY_BLOCK_CV` CDB ON
CUSA.LIFSD_KNVV=CDB.LIFSP_TVLS

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.ITEM_PARTIAL_DELIVERY_CV` IPD ON
CUSA.KZTLF_KNVV=IPD.KZTLF_KNVV

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DELIVERY_PRIORITY_CV` DP ON
safe_cast(CUSA.LPRIO_KNVV AS int64)=safe_cast(DP.LPRIO_TPRIT AS int64)

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SHIPPING_CONDITIONS_CV` SC ON
CUSA.VSBED_KNVV=SC.VTEXT_TVSBT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CENTRAL_BILLING_BLOCK_CV` CBB ON
CUSA.FAKSD_KNVV=CBB.FAKSP_TVFST

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.ACCOUNT_ASSIGNMENT_GROUP_CV` AAG ON
CUSA.KTGRD_KNVV=AAG.VTEXT_TVKTT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.PAYMENT_TERMS_CV` PT ON
CUSA.ZTERM_KNVV=PT.ZTERM_TVZBT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CLASS_OF_TRADE_LEVEL_THREE_CV` COT3 ON
CUSA.KVGR1_KNVV=COT3.KVGR1_TVV1T

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.PARMED_CUSTOMER_CLASSIFICATION_CV` PCC ON
CUSA.KVGR2_KNVV=PCC.KVGR2_TVV2T

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.GPO_CLASS_OF_TRADE_CV` GCOT ON
CUSA.KVGR3_KNVV=GCOT.KVGR3_TVV3T

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.STORE_SIZE_SPECIAL_GROUPING_ALL_CV` SAGA ON
CUSA.KVGR4_KNVV=SAGA.KVGR4_TVV4T

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.FINANCIAL_REPORTING_CV` FR ON
CUSA.KVGR5_KNVV=FR.KVGR5_TVV5T

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CREDIT_CONTROL_AREA_CV` CCA ON
CUSA.KKBER_KNVV=CCA.KKBER_T014T

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.PRIMARY_BACKORDER_SELECTION_CV` PBS ON
CUSA.YYBOPRE1_KNVV=PBS.YYBOPRE1_YTSD_BOPRE1_TEXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.PRIMARY_SECONDARY_CODE_CV` PSC ON
CUSA.YYPRISEC_KNVV=PSC.YYPRISEC_YTSD_PRISEC_TEXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CONSIGNMENT_PROGRAM_CV` CP ON
CUSA.YYCONSIGN_KNVV=CP.YYCONSIGN_YTSD_CONSIGN_TXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.RETURNS_GROUP_CV` RG ON
CUSA.YYRETGRP_KNVV=RG.YYRETGRP_YTSD_RETGRP_TEXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CREDIT_MEMO_PREFERENCES_CV` CMP ON
CUSA.YYCRMEMO_KNVV=CMP.YYCRMEMO_YTSD_CRMEMO_TEXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.340B_CONTRACT_FEE_POLICY_CV` CFP ON
CUSA.YY340BCONFEE_KNVV=CFP.YY340BCONFEE_YTSD_340BCONFTXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.FUEL_SURCHARGE_CV` FS ON
KNVV.YYFUELCHG=FS.YYFUELCHG_YTSD_FUELCHG_TXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.EDRP_SITES_CV` ES ON
KNVV.YYEDRPSPD=ES.YYEDRPSPD_YTSD_EDRPSPD_TXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_STOREFRONT_CV` CS ON
KNVV.YYSTOREFRONT=CS.YYSTOREFRONT_YTSD_STORFRNTTXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.PRINTED_INVOICE_SEQUENCE_CV` PIS ON
CUSA.YYINVSEQ_KNVV=PIS.YYINVSEQ_YTSD_INVSEQ_TEXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.MULTIPLE_COPIES_PREFERENCE_CV` MCP ON
CUSA.YYMULTCOP_KNVV= SAFE_CAST ( MCP.YYMULTCOP_KNVV AS STRING)

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SUPPRESS_ZERO_PRINTING_CV` SZP ON
CUSA.YYSUPZEROINV_KNVV=SZP.YYSUPZEROINV_KNVV

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.STICKERS_PRICE_MASKING_CV` SPM ON
CUSA.YYSTMASKPRE_KNVV=SPM.YYSTMASKPRE_YTSD_STMASKPRETX

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SUPPRESS_PRINTED_INVOICE_CV` SPI ON
CUSA.YYSUPPRINV_KNVV=SPI.YYSUPPRINV_KNVV

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.ITEM_STICKERS_COST_MASKING_CV` ISCM ON
CUSA.YYCUSMASK_KNVV=ISCM.YYCUSMASK_YTSD_CUSMASK_TXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SHELF_LABEL_CV` SL ON
CUSA.YYSHELFLAB_KNVV=SL.YYSHELFLAB_YTSD_SHELFLABTXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.IMS_CODE_CV` IC ON
KNVV.YYIMS=IC.YYIMS_YTSD_IMS_CODETXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SHELF_LABEL_OPTIONS_CV` SLO ON
KNVV.YYOESLOPT=SLO.YYOESLOPT_KNVV

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.PRICE_STICKER_CV` PS ON
CUSA.YYPRCSTKR_KNVV=PS.YYPRCSTKR_YTSD_PRC_STKR_TX

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SHELF_LABEL_STICKER_OPTIONS_CV` SLSO ON
KNVV.YYSTKSLOPT=SLSO.YYSTKSLOPT_YTSD_STKSLOPTTXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.LOT_EXPIRATION_PREFERENCE_CV` LEP ON
CUSA.YYLOTEXP_KNVV=LEP.YYLOTEXP_YTSD_LOT_EXP_TXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.COLLECTION_GROUP_CV` CG ON
CUSA.YYCOLLGROUP_KNVV=CG.COLL_GROUP_UDM_COLL_GRP

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.RETAIL_PRICING_INDICATOR_CV` RPI ON
KNVV.YYRETAIL=RPI.YYRETAIL_KNVV

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_STOCK_NUMBER_CODE_CV` CSNC ON
CUSA.YYCOMMODITY_KNVV=CSNC.YYCOMMODITY_KNVV

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.INVOICE_PRICE_MASKING_CV` IPM ON
CUSA.YYPRICEMASKINV_KNVV=IPM.YYPRICEMASKINV_YTSD_PREMSKINVTX

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.RETAIL_PRICE_TIER_CV` RPT ON
CUSA.VKORG_KNVV=RPT.VKORG_YTSD_HAMACHER_ZL
AND CUSA.VTWEG_KNVV=RPT.VTWEG_YTSD_HAMACHER_ZL
AND SAFE_CAST(CUSA.SPART_KNVV AS STRING) = SAFE_CAST(RPT.SPART_YTSD_HAMACHER_ZL AS STRING)
AND CUSA.YYHAMCHZ_KNVV=RPT.YYRPRPT_YTSD_HAMACHER_ZL

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.COMMITMENT_LEVEL_CV` CL ON
KNVV.YYCOMMITMNT=CL.YYCOMMITMNT_YTSD_COMMIT_TXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SPD_VITALSOURCE_MEMBERSHIP_TYPE_CV` SVMT ON
KNVV.YYTYPE=SVMT.YYTYPE_YTSD_TYPE_TXT

LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SPD_PHYSICIAN_DISPENSING_CV` SPD ON
KNVV.YYPHYDISP=SPD.YYPHYDISP_YTSD_PHYDIS_TEXT

LEFT JOIN
`PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__T049L_CV` T049L ON
CUSA.YYLOCKBOX_KNVV = T049L.LOCKB
AND T049L.BUKRS = '2220'

LEFT JOIN
`PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__T001W_CV`  T001W ON
CUSA.VWERK_KNVV = T001W.WERKS;

-- UPDATE THE EVENT TABLE

UPDATE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.LAST_TIMESTAMP_CUSTOMER_EV` SET SP_CUSTOMER_SALES_AREA_RLT_DELTA_LOAD_STP = v_last_timestamp WHERE 1=1;

END;