CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_CUSTOMER.SP_DEA_REGISTRATION_DELTA_LOAD()
BEGIN

/***********************************************************************************************************************
Author: Rajesh Kumar
Creation Date: 11/07/2023
Data Sources: VI2_PHM_CONFDIM_CUSTOMER.PHM_BOT_DEA_RGSTRN_FEED_COMMON__DEA_REGISTRATION_CV
Change History    [DATE]      [CHANGED BY]  [JIRA#]   [CODE REVIEW BY]    [DESCRIPTION]
<#>         <MM/DD/YYYY>  <Name>      <ID>
************************************************************************************************************************/

DECLARE v_start_time datetime;
DECLARE v_start_stp timestamp;
DECLARE v_end_stp timestamp;
DECLARE v_stored_proc_name STRING;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_CUSTOMER.SP_DEA_REGISTRATION_DELTA_LOAD';

CREATE TEMP TABLE DEA_LATEST AS
SELECT * , RANK()OVER(PARTITION BY DEAREGISTRATIONNUMBER ORDER BY D0_UPDATE_STP DESC) R FROM `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_BOT_DEA_RGSTRN_FEED_COMMON__DEA_REGISTRATION_CV` WHERE D0_ADD_STP=(SELECT MAX(D0_ADD_STP) FROM `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_BOT_DEA_RGSTRN_FEED_COMMON__DEA_REGISTRATION_CV`);

CREATE TEMP TABLE DEA_SRC AS
 WITH SRC AS (
SELECT DISTINCT
    TRIM(DEAREGISTRATIONNUMBER) AS DEAREGISTRATIONNUMBER_DEA_REGISTRATION,
    'Y' AS CURR_VRSN_FLG,
    'N' AS DEL_FLG,
    EXTRACT (DATE FROM D0_ADD_STP) AS VRSN_START_DTE,
    CAST('2099-12-31' AS DATE) AS VRSN_END_DTE,
    TRIM(PAYMENTINDICATOR) AS PAYMENTINDICATOR_DEA_REGISTRATION,
    CASE WHEN TRIM(PAYMENTINDICATOR) ='E' THEN 'Exempt'
         WHEN TRIM(PAYMENTINDICATOR) ='P' THEN 'Paid' ELSE 'NOT_AVAILABLE' END AS PAYMENTINDICATORDESC,
    IFNULL(TRIM(BUSINESSACTIVITYCODE),'NOT_AVAILABLE') AS BUSINESSACTIVITYCODE_DEA_REGISTRATION,
    TRIM(BUSINESSACTIVITYSUBCODE) AS BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION,
    IFNULL(BUSINESS_ACTIVITY_DESC_TXT,'NOT_AVAILABLE') AS BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY,
    PARSE_DATE('%Y%m%d',TRIM(EXPIRATIONDATE)) AS EXPIRATIONDATE_DEA_REGISTRATION,
    TRIM(NAME) AS NAME_DEA_REGISTRATION,
    TRIM(ADDITIONALCOMPANYINFO) AS ADDITIONALCOMPANYINFO_DEA_REGISTRATION,
    TRIM(ADDRESS1) AS ADDRESS1_DEA_REGISTRATION,
    TRIM(ADDRESS2) AS ADDRESS2_DEA_REGISTRATION,
    TRIM(CITY) AS CITY_DEA_REGISTRATION,
    TRIM(STATE) AS STATE_DEA_REGISTRATION,
    CASE WHEN SUBSTR(TRIM(DRUGSCHEDULES),1,3)='1' THEN 'Y' ELSE 'N' END AS CALC_DEA_SCHED_1_FLG,
    CASE WHEN SUBSTR(DRUGSCHEDULES,4,1) ='2' THEN 'Y' ELSE 'N' END AS CALC_DEA_SCHED_2_FLG,
    CASE WHEN SUBSTR(DRUGSCHEDULES,8,1) ='3' THEN 'Y' ELSE 'N' END AS CALC_DEA_SCHED_3_FLG,
    CASE WHEN SUBSTR(DRUGSCHEDULES,5,2) ='2N' THEN 'Y' ELSE 'N' END AS CALC_DEA_SCHED_2N_FLG,
    CASE WHEN SUBSTR(DRUGSCHEDULES,9,2) ='3N' THEN 'Y' ELSE 'N' END AS CALC_DEA_SCHED_3N_FLG,
    CASE WHEN SUBSTR(DRUGSCHEDULES,12,1) ='4' THEN 'Y' ELSE 'N' END AS CALC_DEA_SCHED_4_FLG,
    CASE WHEN SUBSTR(DRUGSCHEDULES,14,1) ='5' THEN 'Y' ELSE 'N' END AS CALC_DEA_SCHED_5_FLG,
    CASE WHEN SUBSTR(DRUGSCHEDULES,-2,2) ='L1' THEN 'Y' ELSE 'N' END AS CALC_DEA_SCHED_L1_FLG,
    TRIM(ZIP) AS ZIP_DEA_REGISTRATION,
    IFNULL(TRIM(DEGREE),'NOT_AVAILABLE') AS DEGREE_DEA_REGISTRATION,
    IFNULL(TRIM(STATELICENSENUMBER),'NOT_AVAILABLE') AS STATELICENSENUMBER_DEA_REGISTRATION,
    IFNULL(TRIM(STATECSLICENSENUMBER),'NOT_AVAILABLE') AS STATECSLICENSENUMBER_DEA_REGISTRATION,
    v_start_stp AS ROW_ADD_STP,
    v_stored_proc_name AS ROW_ADD_USER_ID,
    v_start_stp AS ROW_UPDATE_STP,
    v_stored_proc_name AS ROW_UPDATE_USER_ID
FROM DEA_LATEST  DEA
JOIN `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.BUSINESS_ACTIVITY` BUS
ON TRIM(BUS.BUSINESS_ACTIVITY_CDE) = TRIM(DEA.BUSINESSACTIVITYCODE) AND TRIM(BUS.BUSINESS_ACTIVITY_SUB_CDE)=TRIM(DEA.BUSINESSACTIVITYSUBCODE) WHERE R=1)
SELECT * , SHA256 (CONCAT (IFNULL(PAYMENTINDICATOR_DEA_REGISTRATION,''), IFNULL(PAYMENTINDICATORDESC,''), IFNULL(BUSINESSACTIVITYCODE_DEA_REGISTRATION,''), IFNULL(BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION,''), IFNULL(BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY,''), IFNULL(EXPIRATIONDATE_DEA_REGISTRATION,CAST('1900-01-01' AS DATE)), IFNULL(NAME_DEA_REGISTRATION,''), IFNULL(ADDITIONALCOMPANYINFO_DEA_REGISTRATION,''), IFNULL(ADDRESS1_DEA_REGISTRATION,''), IFNULL(ADDRESS2_DEA_REGISTRATION,''), IFNULL(CITY_DEA_REGISTRATION,''), IFNULL(STATE_DEA_REGISTRATION,''), IFNULL(CALC_DEA_SCHED_1_FLG,''), IFNULL(CALC_DEA_SCHED_2_FLG,''), IFNULL(CALC_DEA_SCHED_3_FLG,''), IFNULL(CALC_DEA_SCHED_2N_FLG,''), IFNULL(CALC_DEA_SCHED_3N_FLG,''), IFNULL(CALC_DEA_SCHED_4_FLG,''), IFNULL(CALC_DEA_SCHED_5_FLG,''), IFNULL(CALC_DEA_SCHED_L1_FLG,''), IFNULL(ZIP_DEA_REGISTRATION,''), IFNULL(DEGREE_DEA_REGISTRATION,''), IFNULL(STATELICENSENUMBER_DEA_REGISTRATION,''), IFNULL(STATECSLICENSENUMBER_DEA_REGISTRATION,''))) AS SHAKEY FROM SRC;

CREATE TEMP TABLE DEA_TGT AS
SELECT DISTINCT * , SHA256 (CONCAT (IFNULL(PAYMENTINDICATOR_DEA_REGISTRATION,''), IFNULL(PAYMENTINDICATORDESC,''), IFNULL(BUSINESSACTIVITYCODE_DEA_REGISTRATION,''), IFNULL(BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION,''), IFNULL(BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY,''), IFNULL(EXPIRATIONDATE_DEA_REGISTRATION,CAST('1900-01-01' AS DATE)), IFNULL(NAME_DEA_REGISTRATION,''), IFNULL(ADDITIONALCOMPANYINFO_DEA_REGISTRATION,''), IFNULL(ADDRESS1_DEA_REGISTRATION,''), IFNULL(ADDRESS2_DEA_REGISTRATION,''), IFNULL(CITY_DEA_REGISTRATION,''), IFNULL(STATE_DEA_REGISTRATION,''), IFNULL(CALC_DEA_SCHED_1_FLG,''), IFNULL(CALC_DEA_SCHED_2_FLG,''), IFNULL(CALC_DEA_SCHED_3_FLG,''), IFNULL(CALC_DEA_SCHED_2N_FLG,''), IFNULL(CALC_DEA_SCHED_3N_FLG,''), IFNULL(CALC_DEA_SCHED_4_FLG,''), IFNULL(CALC_DEA_SCHED_5_FLG,''), IFNULL(CALC_DEA_SCHED_L1_FLG,''), IFNULL(ZIP_DEA_REGISTRATION,''), IFNULL(DEGREE_DEA_REGISTRATION,''), IFNULL(STATELICENSENUMBER_DEA_REGISTRATION,''), IFNULL(STATECSLICENSENUMBER_DEA_REGISTRATION,''))) AS SHAKEY FROM `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DEA_REGISTRATION_CV` WHERE CURR_VRSN_FLG='Y';

CREATE TEMP TABLE DEA_FINAL AS
SELECT
  SRC.DEAREGISTRATIONNUMBER_DEA_REGISTRATION AS	  DEAREGISTRATIONNUMBER_DEA_REGISTRATION_SRC,
  SRC.CURR_VRSN_FLG AS	  CURR_VRSN_FLG_SRC,
  SRC.DEL_FLG AS	  DEL_FLG_SRC,
  SRC.VRSN_START_DTE AS	  VRSN_START_DTE_SRC,
  SRC.VRSN_END_DTE AS	  VRSN_END_DTE_SRC,
  SRC.PAYMENTINDICATOR_DEA_REGISTRATION AS	  PAYMENTINDICATOR_DEA_REGISTRATION_SRC,
  SRC.PAYMENTINDICATORDESC AS	  PAYMENTINDICATORDESC_SRC,
  SRC.BUSINESSACTIVITYCODE_DEA_REGISTRATION AS	  BUSINESSACTIVITYCODE_DEA_REGISTRATION_SRC,
  SRC.BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION AS	  BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION_SRC,
  SRC.BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY AS	  BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY_SRC,
  SRC.EXPIRATIONDATE_DEA_REGISTRATION AS	  EXPIRATIONDATE_DEA_REGISTRATION_SRC,
  SRC.NAME_DEA_REGISTRATION AS	  NAME_DEA_REGISTRATION_SRC,
  SRC.ADDITIONALCOMPANYINFO_DEA_REGISTRATION AS	  ADDITIONALCOMPANYINFO_DEA_REGISTRATION_SRC,
  SRC.ADDRESS1_DEA_REGISTRATION AS	  ADDRESS1_DEA_REGISTRATION_SRC,
  SRC.ADDRESS2_DEA_REGISTRATION AS	  ADDRESS2_DEA_REGISTRATION_SRC,
  SRC.CITY_DEA_REGISTRATION AS	  CITY_DEA_REGISTRATION_SRC,
  SRC.STATE_DEA_REGISTRATION AS	  STATE_DEA_REGISTRATION_SRC,
  SRC.CALC_DEA_SCHED_1_FLG AS CALC_DEA_SCHED_1_FLG_SRC,
  SRC.CALC_DEA_SCHED_2_FLG AS CALC_DEA_SCHED_2_FLG_SRC,
  SRC.CALC_DEA_SCHED_3_FLG AS CALC_DEA_SCHED_3_FLG_SRC,
  SRC.CALC_DEA_SCHED_2N_FLG AS CALC_DEA_SCHED_2N_FLG_SRC,
  SRC.CALC_DEA_SCHED_3N_FLG AS CALC_DEA_SCHED_3N_FLG_SRC,
  SRC.CALC_DEA_SCHED_4_FLG AS CALC_DEA_SCHED_4_FLG_SRC,
  SRC.CALC_DEA_SCHED_5_FLG AS CALC_DEA_SCHED_5_FLG_SRC,
  SRC.CALC_DEA_SCHED_L1_FLG AS CALC_DEA_SCHED_L1_FLG_SRC,
  SRC.ZIP_DEA_REGISTRATION AS	  ZIP_DEA_REGISTRATION_SRC,
  SRC.DEGREE_DEA_REGISTRATION AS	  DEGREE_DEA_REGISTRATION_SRC,
  SRC.STATELICENSENUMBER_DEA_REGISTRATION AS	  STATELICENSENUMBER_DEA_REGISTRATION_SRC,
  SRC.STATECSLICENSENUMBER_DEA_REGISTRATION AS	  STATECSLICENSENUMBER_DEA_REGISTRATION_SRC,
  SRC.ROW_ADD_STP AS	  ROW_ADD_STP_SRC,
  SRC.ROW_ADD_USER_ID AS	  ROW_ADD_USER_ID_SRC,
  SRC.ROW_UPDATE_STP AS	  ROW_UPDATE_STP_SRC,
  SRC.ROW_UPDATE_USER_ID AS	  ROW_UPDATE_USER_ID_SRC,
  TGT.DEAREGISTRATIONNUMBER_DEA_REGISTRATION AS	  DEAREGISTRATIONNUMBER_DEA_REGISTRATION_TGT,
  TGT.CURR_VRSN_FLG AS	  CURR_VRSN_FLG_TGT,
  TGT.DEL_FLG AS	  DEL_FLG_TGT,
  TGT.VRSN_START_DTE AS	  VRSN_START_DTE_TGT,
  TGT.VRSN_END_DTE AS	  VRSN_END_DTE_TGT,
  TGT.PAYMENTINDICATOR_DEA_REGISTRATION AS	  PAYMENTINDICATOR_DEA_REGISTRATION_TGT,
  TGT.PAYMENTINDICATORDESC AS	  PAYMENTINDICATORDESC_TGT,
  TGT.BUSINESSACTIVITYCODE_DEA_REGISTRATION AS	  BUSINESSACTIVITYCODE_DEA_REGISTRATION_TGT,
  TGT.BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION AS	  BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION_TGT,
  TGT.BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY AS	  BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY_TGT,
  TGT.EXPIRATIONDATE_DEA_REGISTRATION AS	  EXPIRATIONDATE_DEA_REGISTRATION_TGT,
  TGT.NAME_DEA_REGISTRATION AS	  NAME_DEA_REGISTRATION_TGT,
  TGT.ADDITIONALCOMPANYINFO_DEA_REGISTRATION AS	  ADDITIONALCOMPANYINFO_DEA_REGISTRATION_TGT,
  TGT.ADDRESS1_DEA_REGISTRATION AS	  ADDRESS1_DEA_REGISTRATION_TGT,
  TGT.ADDRESS2_DEA_REGISTRATION AS	  ADDRESS2_DEA_REGISTRATION_TGT,
  TGT.CITY_DEA_REGISTRATION AS	  CITY_DEA_REGISTRATION_TGT,
  TGT.STATE_DEA_REGISTRATION AS	  STATE_DEA_REGISTRATION_TGT,
  TGT.CALC_DEA_SCHED_1_FLG AS CALC_DEA_SCHED_1_FLG_TGT,
  TGT.CALC_DEA_SCHED_2_FLG AS CALC_DEA_SCHED_2_FLG_TGT,
  TGT.CALC_DEA_SCHED_3_FLG AS CALC_DEA_SCHED_3_FLG_TGT,
  TGT.CALC_DEA_SCHED_2N_FLG AS CALC_DEA_SCHED_2N_FLG_TGT,
  TGT.CALC_DEA_SCHED_3N_FLG AS CALC_DEA_SCHED_3N_FLG_TGT,
  TGT.CALC_DEA_SCHED_4_FLG AS CALC_DEA_SCHED_4_FLG_TGT,
  TGT.CALC_DEA_SCHED_5_FLG AS CALC_DEA_SCHED_5_FLG_TGT,
  TGT.CALC_DEA_SCHED_L1_FLG AS CALC_DEA_SCHED_L1_FLG_TGT,
  TGT.ZIP_DEA_REGISTRATION AS ZIP_DEA_REGISTRATION_TGT,
  TGT.DEGREE_DEA_REGISTRATION AS DEGREE_DEA_REGISTRATION_TGT,
  TGT.STATELICENSENUMBER_DEA_REGISTRATION AS STATELICENSENUMBER_DEA_REGISTRATION_TGT,
  TGT.STATECSLICENSENUMBER_DEA_REGISTRATION AS STATECSLICENSENUMBER_DEA_REGISTRATION_TGT,
  TGT.ROW_ADD_STP AS	  ROW_ADD_STP_TGT,
  TGT.ROW_ADD_USER_ID AS	  ROW_ADD_USER_ID_TGT,
  TGT.ROW_UPDATE_STP AS	  ROW_UPDATE_STP_TGT,
  TGT.ROW_UPDATE_USER_ID AS	  ROW_UPDATE_USER_ID_TGT,
 CAST((  CASE
WHEN (SRC.DEAREGISTRATIONNUMBER_DEA_REGISTRATION IS NULL AND TGT.DEL_FLG = 'N') /* DEA physically deleted from source. DEA # is Present in target and DEL_FLG is from the Target */
THEN 'DEL'
WHEN TGT.DEAREGISTRATIONNUMBER_DEA_REGISTRATION IS NOT NULL AND SRC.DEAREGISTRATIONNUMBER_DEA_REGISTRATION IS NOT NULL /* Source and target record exist */
AND TGT.DEL_FLG = 'Y' /*AND TGT.VRSN_END_DTE = '2099-12-31'*/  /* But the target record is deleted and is the latest record */	/* DEA reactivated */
THEN 'RAC'
WHEN TGT.DEAREGISTRATIONNUMBER_DEA_REGISTRATION IS NULL /* Brand new DEA */
THEN 'INS'
WHEN (TGT.DEAREGISTRATIONNUMBER_DEA_REGISTRATION IS NOT NULL AND SRC.DEAREGISTRATIONNUMBER_DEA_REGISTRATION IS NOT NULL) /* DEA #'s Data' have changed */
AND SRC.SHAKEY <> TGT.SHAKEY
THEN 'UPD'
ELSE 'N_A' /* NA records will be filtered by ETL since there is no change at all */
END) AS STRING) AS CDC_TYPE
FROM DEA_SRC AS SRC
FULL OUTER JOIN DEA_TGT AS TGT
ON TRIM(TGT.DEAREGISTRATIONNUMBER_DEA_REGISTRATION) = TRIM(SRC.DEAREGISTRATIONNUMBER_DEA_REGISTRATION);

--INSERTING

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DEA_REGISTRATION_CV`
SELECT
  DEAREGISTRATIONNUMBER_DEA_REGISTRATION_SRC,
  CURR_VRSN_FLG_SRC,
  DEL_FLG_SRC,
  VRSN_START_DTE_SRC,
  VRSN_END_DTE_SRC,
  PAYMENTINDICATOR_DEA_REGISTRATION_SRC,
  PAYMENTINDICATORDESC_SRC,
  BUSINESSACTIVITYCODE_DEA_REGISTRATION_SRC,
  BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION_SRC,
  BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY_SRC,
  EXPIRATIONDATE_DEA_REGISTRATION_SRC,
  NAME_DEA_REGISTRATION_SRC,
  ADDITIONALCOMPANYINFO_DEA_REGISTRATION_SRC,
  ADDRESS1_DEA_REGISTRATION_SRC,
  ADDRESS2_DEA_REGISTRATION_SRC,
  CITY_DEA_REGISTRATION_SRC,
  STATE_DEA_REGISTRATION_SRC,
  CALC_DEA_SCHED_1_FLG_SRC,
  CALC_DEA_SCHED_2_FLG_SRC,
  CALC_DEA_SCHED_3_FLG_SRC,
  CALC_DEA_SCHED_2N_FLG_SRC,
  CALC_DEA_SCHED_3N_FLG_SRC,
  CALC_DEA_SCHED_4_FLG_SRC,
  CALC_DEA_SCHED_5_FLG_SRC,
  CALC_DEA_SCHED_L1_FLG_SRC,
  ZIP_DEA_REGISTRATION_SRC,
  DEGREE_DEA_REGISTRATION_SRC,
  STATELICENSENUMBER_DEA_REGISTRATION_SRC,
  STATECSLICENSENUMBER_DEA_REGISTRATION_SRC,
  ROW_ADD_STP_SRC,
  ROW_ADD_USER_ID_SRC,
  ROW_UPDATE_STP_SRC,
  ROW_UPDATE_USER_ID_SRC,
  FROM DEA_FINAL WHERE CDC_TYPE = 'INS';

--UPDATE

CREATE TEMP TABLE DEA_UPD
AS
SELECT
  DEAREGISTRATIONNUMBER_DEA_REGISTRATION_TGT,
  'N' CURR_VRSN_FLG_TGT,
  DEL_FLG_TGT,
  VRSN_START_DTE_TGT,
  (VRSN_START_DTE_SRC-1) VRSN_START_DTE_SRC,
  PAYMENTINDICATOR_DEA_REGISTRATION_TGT,
  PAYMENTINDICATORDESC_TGT,
  BUSINESSACTIVITYCODE_DEA_REGISTRATION_TGT,
  BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION_TGT,
  BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY_TGT,
  EXPIRATIONDATE_DEA_REGISTRATION_TGT,
  NAME_DEA_REGISTRATION_TGT,
  ADDITIONALCOMPANYINFO_DEA_REGISTRATION_TGT,
  ADDRESS1_DEA_REGISTRATION_TGT,
  ADDRESS2_DEA_REGISTRATION_TGT,
  CITY_DEA_REGISTRATION_TGT,
  STATE_DEA_REGISTRATION_TGT,
  CALC_DEA_SCHED_1_FLG_TGT,
  CALC_DEA_SCHED_2_FLG_TGT,
  CALC_DEA_SCHED_3_FLG_TGT,
  CALC_DEA_SCHED_2N_FLG_TGT,
  CALC_DEA_SCHED_3N_FLG_TGT,
  CALC_DEA_SCHED_4_FLG_TGT,
  CALC_DEA_SCHED_5_FLG_TGT,
  CALC_DEA_SCHED_L1_FLG_TGT,
  ZIP_DEA_REGISTRATION_TGT,
  DEGREE_DEA_REGISTRATION_TGT,
  STATELICENSENUMBER_DEA_REGISTRATION_TGT,
  STATECSLICENSENUMBER_DEA_REGISTRATION_TGT,
  ROW_ADD_STP_TGT,
  ROW_ADD_USER_ID_TGT,
  v_start_stp ROW_UPDATE_STP,
  v_stored_proc_name ROW_UPDATE_USER_ID
FROM DEA_FINAL WHERE CDC_TYPE ='UPD' ;

DELETE FROM `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DEA_REGISTRATION_CV` TGT WHERE (DEAREGISTRATIONNUMBER_DEA_REGISTRATION)
IN (SELECT DEAREGISTRATIONNUMBER_DEA_REGISTRATION_TGT FROM DEA_FINAL WHERE CDC_TYPE='UPD' ) AND TGT.VRSN_END_DTE ='2099-12-31' AND TGT.CURR_VRSN_FLG='Y' AND TGT.DEL_FLG='N';

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DEA_REGISTRATION_CV`
SELECT * FROM DEA_UPD
UNION ALL
SELECT
  DEAREGISTRATIONNUMBER_DEA_REGISTRATION_SRC,
  CURR_VRSN_FLG_SRC,
  DEL_FLG_SRC,
  VRSN_START_DTE_SRC,
  VRSN_END_DTE_SRC,
  PAYMENTINDICATOR_DEA_REGISTRATION_SRC,
  PAYMENTINDICATORDESC_SRC,
  BUSINESSACTIVITYCODE_DEA_REGISTRATION_SRC,
  BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION_SRC,
  BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY_SRC,
  EXPIRATIONDATE_DEA_REGISTRATION_SRC,
  NAME_DEA_REGISTRATION_SRC,
  ADDITIONALCOMPANYINFO_DEA_REGISTRATION_SRC,
  ADDRESS1_DEA_REGISTRATION_SRC,
  ADDRESS2_DEA_REGISTRATION_SRC,
  CITY_DEA_REGISTRATION_SRC,
  STATE_DEA_REGISTRATION_SRC,
  CALC_DEA_SCHED_1_FLG_SRC,
  CALC_DEA_SCHED_2_FLG_SRC,
  CALC_DEA_SCHED_3_FLG_SRC,
  CALC_DEA_SCHED_2N_FLG_SRC,
  CALC_DEA_SCHED_3N_FLG_SRC,
  CALC_DEA_SCHED_4_FLG_SRC,
  CALC_DEA_SCHED_5_FLG_SRC,
  CALC_DEA_SCHED_L1_FLG_SRC,
  ZIP_DEA_REGISTRATION_SRC,
  DEGREE_DEA_REGISTRATION_SRC,
  STATELICENSENUMBER_DEA_REGISTRATION_SRC,
  STATECSLICENSENUMBER_DEA_REGISTRATION_SRC,
  ROW_ADD_STP_SRC,
  ROW_ADD_USER_ID_SRC,
  ROW_UPDATE_STP_SRC,
  ROW_UPDATE_USER_ID_SRC
 FROM DEA_FINAL WHERE CDC_TYPE ='UPD';

--DELETE

CREATE TEMP TABLE DEA_DEL
AS
SELECT
  DEAREGISTRATIONNUMBER_DEA_REGISTRATION_TGT,
  'N' CURR_VRSN_FLG_TGT,
  DEL_FLG_TGT,
  VRSN_START_DTE_TGT,
  CURRENT_DATE-1 VRSN_END_DTE,
  PAYMENTINDICATOR_DEA_REGISTRATION_TGT,
  PAYMENTINDICATORDESC_TGT,
  BUSINESSACTIVITYCODE_DEA_REGISTRATION_TGT,
  BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION_TGT,
  BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY_TGT,
  EXPIRATIONDATE_DEA_REGISTRATION_TGT,
  NAME_DEA_REGISTRATION_TGT,
  ADDITIONALCOMPANYINFO_DEA_REGISTRATION_TGT,
  ADDRESS1_DEA_REGISTRATION_TGT,
  ADDRESS2_DEA_REGISTRATION_TGT,
  CITY_DEA_REGISTRATION_TGT,
  STATE_DEA_REGISTRATION_TGT,
  CALC_DEA_SCHED_1_FLG_TGT,
  CALC_DEA_SCHED_2_FLG_TGT,
  CALC_DEA_SCHED_3_FLG_TGT,
  CALC_DEA_SCHED_2N_FLG_TGT,
  CALC_DEA_SCHED_3N_FLG_TGT,
  CALC_DEA_SCHED_4_FLG_TGT,
  CALC_DEA_SCHED_5_FLG_TGT,
  CALC_DEA_SCHED_L1_FLG_TGT,
  ZIP_DEA_REGISTRATION_TGT,
  DEGREE_DEA_REGISTRATION_TGT,
  STATELICENSENUMBER_DEA_REGISTRATION_TGT,
  STATECSLICENSENUMBER_DEA_REGISTRATION_TGT,
  ROW_ADD_STP_TGT,
  ROW_ADD_USER_ID_TGT,
  v_start_stp ROW_UPDATE_STP,
  v_stored_proc_name ROW_UPDATE_USER_ID
FROM DEA_FINAL WHERE CDC_TYPE ='DEL' ;

DELETE FROM `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DEA_REGISTRATION_CV` TGT WHERE (DEAREGISTRATIONNUMBER_DEA_REGISTRATION)
IN (SELECT DEAREGISTRATIONNUMBER_DEA_REGISTRATION_TGT FROM DEA_FINAL WHERE CDC_TYPE='DEL' ) AND TGT.VRSN_END_DTE ='2099-12-31' AND TGT.CURR_VRSN_FLG='Y' AND TGT.DEL_FLG='N';

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DEA_REGISTRATION_CV`
SELECT * FROM DEA_DEL
UNION ALL
SELECT
  DEAREGISTRATIONNUMBER_DEA_REGISTRATION_TGT,
  'Y' CURR_VRSN_FLG,
  'Y' DEL_FLG,
  CURRENT_DATE VRSN_START_DTE,
  CAST('2099-12-31' AS DATE)VRSN_END_DTE,
  PAYMENTINDICATOR_DEA_REGISTRATION_TGT,
  PAYMENTINDICATORDESC_TGT,
  BUSINESSACTIVITYCODE_DEA_REGISTRATION_TGT,
  BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION_TGT,
  BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY_TGT,
  EXPIRATIONDATE_DEA_REGISTRATION_TGT,
  NAME_DEA_REGISTRATION_TGT,
  ADDITIONALCOMPANYINFO_DEA_REGISTRATION_TGT,
  ADDRESS1_DEA_REGISTRATION_TGT,
  ADDRESS2_DEA_REGISTRATION_TGT,
  CITY_DEA_REGISTRATION_TGT,
  STATE_DEA_REGISTRATION_TGT,
  CALC_DEA_SCHED_1_FLG_TGT,
  CALC_DEA_SCHED_2_FLG_TGT,
  CALC_DEA_SCHED_3_FLG_TGT,
  CALC_DEA_SCHED_2N_FLG_TGT,
  CALC_DEA_SCHED_3N_FLG_TGT,
  CALC_DEA_SCHED_4_FLG_TGT,
  CALC_DEA_SCHED_5_FLG_TGT,
  CALC_DEA_SCHED_L1_FLG_TGT,
  ZIP_DEA_REGISTRATION_TGT,
  DEGREE_DEA_REGISTRATION_TGT,
  STATELICENSENUMBER_DEA_REGISTRATION_TGT,
  STATECSLICENSENUMBER_DEA_REGISTRATION_TGT,
  v_start_stp ROW_ADD_STP,
  v_stored_proc_name ROW_ADD_USER_ID,
  v_start_stp ROW_UPDATE_STP,
  v_stored_proc_name ROW_UPDATE_USER_ID
 FROM DEA_FINAL WHERE CDC_TYPE ='DEL';

--REACTIVATION

CREATE TEMP TABLE DEA_RAC
AS
SELECT
  DEAREGISTRATIONNUMBER_DEA_REGISTRATION_TGT,
  'N' CURR_VRSN_FLG_TGT,
  DEL_FLG_TGT,
  VRSN_START_DTE_TGT,
  (VRSN_START_DTE_SRC - 1) VRSN_START_DTE_SRC,
  PAYMENTINDICATOR_DEA_REGISTRATION_TGT,
  PAYMENTINDICATORDESC_TGT,
  BUSINESSACTIVITYCODE_DEA_REGISTRATION_TGT,
  BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION_TGT,
  BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY_TGT,
  EXPIRATIONDATE_DEA_REGISTRATION_TGT,
  NAME_DEA_REGISTRATION_TGT,
  ADDITIONALCOMPANYINFO_DEA_REGISTRATION_TGT,
  ADDRESS1_DEA_REGISTRATION_TGT,
  ADDRESS2_DEA_REGISTRATION_TGT,
  CITY_DEA_REGISTRATION_TGT,
  STATE_DEA_REGISTRATION_TGT,
  CALC_DEA_SCHED_1_FLG_TGT,
  CALC_DEA_SCHED_2_FLG_TGT,
  CALC_DEA_SCHED_3_FLG_TGT,
  CALC_DEA_SCHED_2N_FLG_TGT,
  CALC_DEA_SCHED_3N_FLG_TGT,
  CALC_DEA_SCHED_4_FLG_TGT,
  CALC_DEA_SCHED_5_FLG_TGT,
  CALC_DEA_SCHED_L1_FLG_TGT,
  ZIP_DEA_REGISTRATION_TGT,
  DEGREE_DEA_REGISTRATION_TGT,
  STATELICENSENUMBER_DEA_REGISTRATION_TGT,
  STATECSLICENSENUMBER_DEA_REGISTRATION_TGT,
  ROW_ADD_STP_TGT,
  ROW_ADD_USER_ID_TGT,
  v_start_stp ROW_UPDATE_STP,
  v_stored_proc_name ROW_UPDATE_USER_ID
FROM DEA_FINAL WHERE CDC_TYPE ='RAC' ;

--DELETING THE PREVIOUS VERSION

DELETE FROM `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DEA_REGISTRATION_CV` TGT WHERE (DEAREGISTRATIONNUMBER_DEA_REGISTRATION)
IN (SELECT DEAREGISTRATIONNUMBER_DEA_REGISTRATION_TGT FROM DEA_FINAL WHERE CDC_TYPE='RAC') /*AND TGT.VRSN_END_DTE ='2099-12-31'*/ AND TGT.CURR_VRSN_FLG='Y' AND TGT.DEL_FLG='Y';

--INSERTING THE UPDATED RECORD AND PREVIOUS VERSION RECORDS

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.DEA_REGISTRATION_CV`
SELECT * FROM DEA_RAC
UNION ALL
SELECT
  DEAREGISTRATIONNUMBER_DEA_REGISTRATION_SRC,
  'Y' CURR_VRSN_FLG,
  'N' DEL_FLG,
  VRSN_START_DTE_SRC,
  CAST('2099-12-31' AS DATE) VRSN_END_DTE,
  PAYMENTINDICATOR_DEA_REGISTRATION_SRC,
  PAYMENTINDICATORDESC_SRC,
  BUSINESSACTIVITYCODE_DEA_REGISTRATION_SRC,
  BUSINESSACTIVITYSUBCODE_DEA_REGISTRATION_SRC,
  BUSINESS_ACTIVITY_DESC_TXT_BUSINESS_ACTIVITY_SRC,
  EXPIRATIONDATE_DEA_REGISTRATION_SRC,
  NAME_DEA_REGISTRATION_SRC,
  ADDITIONALCOMPANYINFO_DEA_REGISTRATION_SRC,
  ADDRESS1_DEA_REGISTRATION_SRC,
  ADDRESS2_DEA_REGISTRATION_SRC,
  CITY_DEA_REGISTRATION_SRC,
  STATE_DEA_REGISTRATION_SRC,
  CALC_DEA_SCHED_1_FLG_SRC,
  CALC_DEA_SCHED_2_FLG_SRC,
  CALC_DEA_SCHED_3_FLG_SRC,
  CALC_DEA_SCHED_2N_FLG_SRC,
  CALC_DEA_SCHED_3N_FLG_SRC,
  CALC_DEA_SCHED_4_FLG_SRC,
  CALC_DEA_SCHED_5_FLG_SRC,
  CALC_DEA_SCHED_L1_FLG_SRC,
  ZIP_DEA_REGISTRATION_SRC,
  DEGREE_DEA_REGISTRATION_SRC,
  STATELICENSENUMBER_DEA_REGISTRATION_SRC,
  STATECSLICENSENUMBER_DEA_REGISTRATION_SRC,
  v_start_stp AS ROW_ADD_STP,
  v_stored_proc_name AS ROW_ADD_USER_ID,
  v_start_stp AS ROW_UPDATE_STP,
  v_stored_proc_name AS ROW_UPDATE_USER_ID
 FROM DEA_FINAL WHERE CDC_TYPE ='RAC';

END;