CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_CUSTOMER.SP_ITEM_PARTIAL_DELIVERY()
BEGIN

/***********************************************************************************************************************
Author: Akshobhya S Achar
Creation Date: 05/09/2023
Data Sources: VI0_PHM_ORP_PE1_PH1_NP.KNVV_CV
*************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
	<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_stp TIMESTAMP;
DECLARE v_stored_proc_name STRING;

SET v_start_stp = CURRENT_TIMESTAMP;
SET v_stored_proc_name = 'D1_PHM_CONFDIM_CUSTOMER.SP_ITEM_PARTIAL_DELIVERY';

/* Select the latest record from the table */

TRUNCATE TABLE PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.ITEM_PARTIAL_DELIVERY_CV;
INSERT INTO PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.ITEM_PARTIAL_DELIVERY_CV (KZTLF_KNVV, ITEM_PRTL_DELIVERIES_ALW_DESC_TXT,ROW_ADD_STP,ROW_ADD_USER_ID,ROW_UPDATE_STP,ROW_UPDATE_USER_ID) VALUES (' ','PARTIAL DELIVERIES ALLOWED',v_start_stp,v_stored_proc_name,v_start_stp,v_stored_proc_name);
INSERT INTO PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.ITEM_PARTIAL_DELIVERY_CV (KZTLF_KNVV, ITEM_PRTL_DELIVERIES_ALW_DESC_TXT,ROW_ADD_STP,ROW_ADD_USER_ID,ROW_UPDATE_STP,ROW_UPDATE_USER_ID) VALUES ('A','CREATE A DELIVERY WITH QTY GREATER THAN ZERO',v_start_stp,v_stored_proc_name,v_start_stp,v_stored_proc_name);
INSERT INTO PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.ITEM_PARTIAL_DELIVERY_CV (KZTLF_KNVV, ITEM_PRTL_DELIVERIES_ALW_DESC_TXT,ROW_ADD_STP,ROW_ADD_USER_ID,ROW_UPDATE_STP,ROW_UPDATE_USER_ID) VALUES ('B','CREATE ONLY ONE DELIVERY (ALSO WITH QUANTITY = 0)',v_start_stp,v_stored_proc_name,v_start_stp,v_stored_proc_name);
INSERT INTO PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.ITEM_PARTIAL_DELIVERY_CV (KZTLF_KNVV, ITEM_PRTL_DELIVERIES_ALW_DESC_TXT,ROW_ADD_STP,ROW_ADD_USER_ID,ROW_UPDATE_STP,ROW_UPDATE_USER_ID) VALUES ('C','ONLY COMPLETE DELIVERY ALLOWED',v_start_stp,v_stored_proc_name,v_start_stp,v_stored_proc_name);
INSERT INTO PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.ITEM_PARTIAL_DELIVERY_CV (KZTLF_KNVV, ITEM_PRTL_DELIVERIES_ALW_DESC_TXT,ROW_ADD_STP,ROW_ADD_USER_ID,ROW_UPDATE_STP,ROW_UPDATE_USER_ID) VALUES ('D','NO LIMIT TO SUBSEQUENT DELIVERIES',v_start_stp,v_stored_proc_name,v_start_stp,v_stored_proc_name);

END;