CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_CUSTOMER.SP_RETAIL_PRICE_TIER()
BEGIN

/***********************************************************************************************************************
Author: Akshobhya S Achar
Creation Date: 05/09/2023
Data Sources: VI0_PHM_ORP_PE1_PH1_NP.YTSD_HAMACHER_ZL_CV
*************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
	<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time DATETIME;
DECLARE v_start_stp TIMESTAMP;
DECLARE v_end_stp TIMESTAMP;
DECLARE v_end_scd_stp TIMESTAMP;
DECLARE v_stored_proc_name STRING;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_CUSTOMER.SP_RETAIL_PRICE_TIER';

/* Select the latest record from the table */

CREATE OR REPLACE TEMPORARY TABLE YTSD_HAMACHER_ZL_TEMP
AS
SELECT
 VKORG
,VTWEG
,SPART
,YYRPRPT
,YYRPRPT_DESC
,ERNAM
,IF(SAFE_CAST(ERDAT AS DATE FORMAT 'YYYYMMDD') IS NULL, CAST('1900-07-04' AS DATE), CAST(ERDAT AS DATE FORMAT 'YYYYMMDD'))  AS ERDAT
,AENAM
,IF(SAFE_CAST(AEDAT AS DATE FORMAT 'YYYYMMDD') IS NULL, CAST('1900-07-04' AS DATE), CAST(AEDAT AS DATE FORMAT 'YYYYMMDD'))   AS AEDAT
FROM `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_ORP_PE1_PH1__YTSD_HAMACHER_ZL_CV` YTSD_HAMACHER_ZL
WHERE D0_CURR_VRSN_FLG = 'Y';

/*Perform an UPSERT on the target table

Step 1: Identify records to be inserted */

CREATE OR REPLACE TEMPORARY TABLE YTSD_HAMACHER_ZL_TEMP_INS
AS
SELECT
 VKORG
,VTWEG
,SPART
,YYRPRPT
,YYRPRPT_DESC
,ERNAM
,ERDAT
,AENAM
,AEDAT
FROM YTSD_HAMACHER_ZL_TEMP TMP
LEFT JOIN
`PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.RETAIL_PRICE_TIER_CV` TGT
ON TMP.VKORG       = TGT.VKORG_YTSD_HAMACHER_ZL
AND TMP.VTWEG       = TGT.VTWEG_YTSD_HAMACHER_ZL
AND TMP.SPART       = TGT.SPART_YTSD_HAMACHER_ZL
AND TMP.YYRPRPT     = TGT.YYRPRPT_YTSD_HAMACHER_ZL

WHERE TGT.VKORG_YTSD_HAMACHER_ZL IS NULL
AND TGT.VTWEG_YTSD_HAMACHER_ZL  IS NULL
AND TGT.SPART_YTSD_HAMACHER_ZL  IS NULL
AND TGT.YYRPRPT_YTSD_HAMACHER_ZL IS NULL ;

/*Step 2: Update records where the source and target match */

UPDATE `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.RETAIL_PRICE_TIER_CV` TGT
SET
TGT.YYRPRPT_DESC_YTSD_HAMACHER_ZL =TMP.YYRPRPT_DESC
,TGT.ERNAM_YTSD_HAMACHER_ZL       =TMP.ERNAM
,TGT.ERDAT_YTSD_HAMACHER_ZL       =TMP.ERDAT
,TGT.AENAM_YTSD_HAMACHER_ZL       =TMP.AENAM
,TGT.AEDAT_YTSD_HAMACHER_ZL       =TMP.AEDAT
,ROW_UPDATE_STP=v_start_stp
FROM YTSD_HAMACHER_ZL_TEMP TMP
WHERE TMP.VKORG       = TGT.VKORG_YTSD_HAMACHER_ZL
AND TMP.VTWEG       = TGT.VTWEG_YTSD_HAMACHER_ZL
AND TMP.SPART       = TGT.SPART_YTSD_HAMACHER_ZL
AND TMP.YYRPRPT     = TGT.YYRPRPT_YTSD_HAMACHER_ZL ;

/*Step 3: Insert records into the target */

INSERT INTO D1_PHM_CONFDIM_CUSTOMER.RETAIL_PRICE_TIER_CV
SELECT
 VKORG
,VTWEG
,SPART
,YYRPRPT
,YYRPRPT_DESC
,ERNAM
,ERDAT
,AENAM
,AEDAT
,v_start_stp AS ROW_ADD_STP
,v_stored_proc_name AS ROW_ADD_USER_ID
,v_start_stp AS ROW_UPDATE_STP
,v_stored_proc_name AS ROW_UPDATE_USER_ID
FROM YTSD_HAMACHER_ZL_TEMP_INS;

/*Stored Proc execution logging for success or failure */

INSERT INTO
  `PROJECT_ID.D1_PHM_DW_LOG.LOGTBL_DIMENSION` (
  SELECT
    'D1_PHM_CONFDIM_CUSTOMER.SP_RETAIL_PRICE_TIER',
    v_start_time,
    current_datetime(),
    'SUCCESS',
    NULL,
    @@ROW_COUNT,
    NULL,
    NULL,
    @@script.bytes_processed/1024/1024,
    @@script.bytes_billed/1024/1024,
    @@script.job_id,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL); EXCEPTION
    WHEN ERROR THEN
	INSERT INTO `D1_PHM_DW_LOG.LOGTBL_DIMENSION`
	( module_name, start_date, end_date, status, err_msg, err_st_txt, err_st_trc )
	( SELECT 'D1_PHM_CONFDIM_CUSTOMER.SP_RETAIL_PRICE_TIER', current_datetime(), current_datetime(),
	'FAILED', @@error.message, @@error.statement_text, @@error.formatted_stack_trace );
END;