
    CREATE PROCEDURE  `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.SP_MATERIAL_REGULATION_BLOCK_CV_DELTA_LOAD`()
    BEGIN
    /***********************************************************************************************************************

    Author: <Automatically Written Using Code Generator>
    Creation Date: <Insert Date>
    Sproc Purpose: Delta Loading Merge Sproc for MATERIAL_REGULATION_BLOCK_CV
    Data Sources:  See SQL Below

    ************************************************************************************************************************/
    DECLARE v_start_time timestamp;
    DECLARE v_start_stp timestamp;
    DECLARE v_end_stp timestamp;
    DECLARE v_stored_proc_name STRING;
    DECLARE last_load_timestamp timestamp;

    SET v_start_time = current_timestamp();
    SET v_start_stp = current_timestamp();
    SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
    SET v_stored_proc_name = 'D1_PHM_CONFDIM_MATERIAL.MATERIAL_REGULATION_BLOCK_CV_DELTA_LOAD';
    SET last_load_timestamp = (SELECT MAX(ROW_ADD_STP) FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_REGULATION_BLOCK_CV`);


    MERGE INTO  `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_REGULATION_BLOCK_CV` AS target
     USING 
      (
     -- Developer's code goes here (SAMPLE CODE BELOW)

         --SELECT 
            a.column_1
            a.column_2
         --FROM 
         -- `PROJECT_ID.VI2_PHM_CONFFACT_BILLING.PHM_SDW__INVOICE_LINE_CV` il
         --JOIN
            --`PROJECT_ID.VI2_PHM_CONFDIM_TIME.PHM_SDW__TIME_DETAIL_CV` t
                --ON il.DTE_KEY_NUM = t.DTE_KEY_NUM
        --WHERE il.D0_UPDATE_STP > last_load_timestamp --- MOST IMPORTANT CONCEPT

      ) AS source
      ON TARGET.PRIMARY_KEY = SOURCE.PRIMARY_KEY
    WHEN MATCHED THEN
      UPDATE SET
        TARGET.YREGULATION_ID_YTMM_REGUL_BLOCK = SOURCE.YREGULATION_ID_YTMM_REGUL_BLOCK,
        TARGET.WERKS_YTMM_REGUL_BLOCK = SOURCE.WERKS_YTMM_REGUL_BLOCK,
        TARGET.MATNR_YTMM_REGUL_BLOCK = SOURCE.MATNR_YTMM_REGUL_BLOCK,
        TARGET.LIFNR_YTMM_REGUL_BLOCK = SOURCE.LIFNR_YTMM_REGUL_BLOCK,
        TARGET.YBLOCK_TYPE_YTMM_REGUL_BLOCK = SOURCE.YBLOCK_TYPE_YTMM_REGUL_BLOCK,
        TARGET.CALC_BLCK_TYPE_DESC_TXT = SOURCE.CALC_BLCK_TYPE_DESC_TXT,
        TARGET.YCHECK_LIC_YTMM_REGUL_BLOCK = SOURCE.YCHECK_LIC_YTMM_REGUL_BLOCK,
        TARGET.CALC_CHK_LIC_TABLE_IND_DESC_TXT = SOURCE.CALC_CHK_LIC_TABLE_IND_DESC_TXT,
        TARGET.YP_LICENSE_TYPE_YTMM_REGUL_BLOCK = SOURCE.YP_LICENSE_TYPE_YTMM_REGUL_BLOCK,
        TARGET.YP_LICENSE_DESC_YTMM_LICENSE_TYT = SOURCE.YP_LICENSE_DESC_YTMM_LICENSE_TYT,
        TARGET.YRECORDSTAT_YTMM_REGUL_BLOCK = SOURCE.YRECORDSTAT_YTMM_REGUL_BLOCK,
        TARGET.CALC_REC_STAT_DESC_TXT = SOURCE.CALC_REC_STAT_DESC_TXT,
        TARGET.Y3PLFLG_YTMM_REGUL_BLOCK = SOURCE.Y3PLFLG_YTMM_REGUL_BLOCK,
        TARGET.ERNAM_YTMM_REGUL_BLOCK = SOURCE.ERNAM_YTMM_REGUL_BLOCK,
        TARGET.ERDAT_YTMM_REGUL_BLOCK = SOURCE.ERDAT_YTMM_REGUL_BLOCK,
        TARGET.AENAM_YTMM_REGUL_BLOCK = SOURCE.AENAM_YTMM_REGUL_BLOCK,
        TARGET.AEDAT_YTMM_REGUL_BLOCK = SOURCE.AEDAT_YTMM_REGUL_BLOCK,
        TARGET.ROW_ADD_STP = SOURCE.ROW_ADD_STP,
        TARGET.ROW_ADD_USER_ID = SOURCE.ROW_ADD_USER_ID,
        TARGET.ROW_UPDATE_STP = SOURCE.ROW_UPDATE_STP,
        TARGET.ROW_UPDATE_USER_ID = SOURCE.ROW_UPDATE_USER_ID
    WHEN NOT MATCHED THEN
      INSERT VALUES
      (
        SOURCE.YREGULATION_ID_YTMM_REGUL_BLOCK,
        SOURCE.WERKS_YTMM_REGUL_BLOCK,
        SOURCE.MATNR_YTMM_REGUL_BLOCK,
        SOURCE.LIFNR_YTMM_REGUL_BLOCK,
        SOURCE.YBLOCK_TYPE_YTMM_REGUL_BLOCK,
        SOURCE.CALC_BLCK_TYPE_DESC_TXT,
        SOURCE.YCHECK_LIC_YTMM_REGUL_BLOCK,
        SOURCE.CALC_CHK_LIC_TABLE_IND_DESC_TXT,
        SOURCE.YP_LICENSE_TYPE_YTMM_REGUL_BLOCK,
        SOURCE.YP_LICENSE_DESC_YTMM_LICENSE_TYT,
        SOURCE.YRECORDSTAT_YTMM_REGUL_BLOCK,
        SOURCE.CALC_REC_STAT_DESC_TXT,
        SOURCE.Y3PLFLG_YTMM_REGUL_BLOCK,
        SOURCE.ERNAM_YTMM_REGUL_BLOCK,
        SOURCE.ERDAT_YTMM_REGUL_BLOCK,
        SOURCE.AENAM_YTMM_REGUL_BLOCK,
        SOURCE.AEDAT_YTMM_REGUL_BLOCK,
        SOURCE.ROW_ADD_STP,
        SOURCE.ROW_ADD_USER_ID,
        SOURCE.ROW_UPDATE_STP,
        SOURCE.ROW_UPDATE_USER_ID
      );
    END;
