
    CREATE PROCEDURE  `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.SP_MATERIAL_PRICING_VF_DELTA_LOAD`()
    BEGIN
    /***********************************************************************************************************************

    Author: <Automatically Written Using Code Generator>
    Creation Date: <Insert Date>
    Sproc Purpose: Delta Loading Merge Sproc for MATERIAL_PRICING_VF
    Data Sources:  See SQL Below

    ************************************************************************************************************************/
    DECLARE v_start_time timestamp;
    DECLARE v_start_stp timestamp;
    DECLARE v_end_stp timestamp;
    DECLARE v_stored_proc_name STRING;
    DECLARE last_load_timestamp timestamp;

    SET v_start_time = current_timestamp();
    SET v_start_stp = current_timestamp();
    SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
    SET v_stored_proc_name = 'D1_PHM_CONFDIM_MATERIAL.MATERIAL_PRICING_VF_DELTA_LOAD';
    SET last_load_timestamp = (SELECT MAX(ROW_ADD_STP) FROM `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_PRICING_VF`);


    MERGE INTO  `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_PRICING_VF` AS target
     USING 
      (
     -- Developer's code goes here (SAMPLE CODE BELOW)

         --SELECT 
            a.column_1
            a.column_2
         --FROM 
         -- `PROJECT_ID.VI2_PHM_CONFFACT_BILLING.PHM_SDW__INVOICE_LINE_CV` il
         --JOIN
            --`PROJECT_ID.VI2_PHM_CONFDIM_TIME.PHM_SDW__TIME_DETAIL_CV` t
                --ON il.DTE_KEY_NUM = t.DTE_KEY_NUM
        --WHERE il.D0_UPDATE_STP > last_load_timestamp --- MOST IMPORTANT CONCEPT

      ) AS source
      ON TARGET.PRIMARY_KEY = SOURCE.PRIMARY_KEY
    WHEN MATCHED THEN
      UPDATE SET
        TARGET.MATNR_A921 = SOURCE.MATNR_A921,
        TARGET.VRSN_START_DTE = SOURCE.VRSN_START_DTE,
        TARGET.VRSN_END_DTE = SOURCE.VRSN_END_DTE,
        TARGET.CURR_VRSN_FLG = SOURCE.CURR_VRSN_FLG,
        TARGET.ZBA0_KBETR_KONP = SOURCE.ZBA0_KBETR_KONP,
        TARGET.ZBA2_KBETR_KONP = SOURCE.ZBA2_KBETR_KONP,
        TARGET.ZTF0_KBETR_KONP = SOURCE.ZTF0_KBETR_KONP,
        TARGET.ZREF_KBETR_KONP = SOURCE.ZREF_KBETR_KONP,
        TARGET.ZMSR_KBETR_KONP = SOURCE.ZMSR_KBETR_KONP,
        TARGET.CALC_CORP_NIFO_AMT = SOURCE.CALC_CORP_NIFO_AMT,
        TARGET.CALC_PREV_ZBA0_KBETR_KONP = SOURCE.CALC_PREV_ZBA0_KBETR_KONP,
        TARGET.CALC_PREV_ZBA2_KBETR_KONP = SOURCE.CALC_PREV_ZBA2_KBETR_KONP,
        TARGET.CALC_PREV_ZTF0_KBETR_KONP = SOURCE.CALC_PREV_ZTF0_KBETR_KONP,
        TARGET.CALC_PREV_ZREF_KBETR_KONP = SOURCE.CALC_PREV_ZREF_KBETR_KONP,
        TARGET.CALC_PREV_ZMSR_KBETR_KONP = SOURCE.CALC_PREV_ZMSR_KBETR_KONP,
        TARGET.CALC_PREV_CORP_NIFO_AMT = SOURCE.CALC_PREV_CORP_NIFO_AMT,
        TARGET.PD_ZBA7_KBETR_KONP = SOURCE.PD_ZBA7_KBETR_KONP,
        TARGET.KINRAY_ZBA7_KBETR_KONP = SOURCE.KINRAY_ZBA7_KBETR_KONP,
        TARGET.CALC_PREV_PD_ZBA7_KBETR_KONP = SOURCE.CALC_PREV_PD_ZBA7_KBETR_KONP,
        TARGET.CALC_PREV_KINRAY_ZBA7_KBETR_KONP = SOURCE.CALC_PREV_KINRAY_ZBA7_KBETR_KONP,
        TARGET.CALC_BASE_COST_AMT = SOURCE.CALC_BASE_COST_AMT,
        TARGET.CALC_PREV_BASE_COST_AMT = SOURCE.CALC_PREV_BASE_COST_AMT,
        TARGET.ZBA0_CRT_DTE = SOURCE.ZBA0_CRT_DTE,
        TARGET.ZBA2_CRT_DTE = SOURCE.ZBA2_CRT_DTE,
        TARGET.ZTF0_CRT_DTE = SOURCE.ZTF0_CRT_DTE,
        TARGET.ZREF_CRT_DTE = SOURCE.ZREF_CRT_DTE,
        TARGET.ZMSR_CRT_DTE = SOURCE.ZMSR_CRT_DTE,
        TARGET.CALC_CORP_NIFO_CRT_DTE = SOURCE.CALC_CORP_NIFO_CRT_DTE,
        TARGET.ROW_ADD_STP = SOURCE.ROW_ADD_STP,
        TARGET.ROW_ADD_USER_ID = SOURCE.ROW_ADD_USER_ID,
        TARGET.ROW_UPDATE_STP = SOURCE.ROW_UPDATE_STP,
        TARGET.ROW_UPDATE_USER_ID = SOURCE.ROW_UPDATE_USER_ID,
        TARGET.MATNR_A921 = SOURCE.MATNR_A921,
        TARGET.VRSN_START_DTE = SOURCE.VRSN_START_DTE,
        TARGET.VRSN_END_DTE = SOURCE.VRSN_END_DTE,
        TARGET.CURR_VRSN_FLG = SOURCE.CURR_VRSN_FLG,
        TARGET.ZBA0_KBETR_KONP = SOURCE.ZBA0_KBETR_KONP,
        TARGET.ZBA2_KBETR_KONP = SOURCE.ZBA2_KBETR_KONP,
        TARGET.ZTF0_KBETR_KONP = SOURCE.ZTF0_KBETR_KONP,
        TARGET.ZREF_KBETR_KONP = SOURCE.ZREF_KBETR_KONP,
        TARGET.ZMSR_KBETR_KONP = SOURCE.ZMSR_KBETR_KONP,
        TARGET.CALC_CORP_NIFO_AMT = SOURCE.CALC_CORP_NIFO_AMT,
        TARGET.CALC_PREV_ZBA0_KBETR_KONP = SOURCE.CALC_PREV_ZBA0_KBETR_KONP,
        TARGET.CALC_PREV_ZBA2_KBETR_KONP = SOURCE.CALC_PREV_ZBA2_KBETR_KONP,
        TARGET.CALC_PREV_ZTF0_KBETR_KONP = SOURCE.CALC_PREV_ZTF0_KBETR_KONP,
        TARGET.CALC_PREV_ZREF_KBETR_KONP = SOURCE.CALC_PREV_ZREF_KBETR_KONP,
        TARGET.CALC_PREV_ZMSR_KBETR_KONP = SOURCE.CALC_PREV_ZMSR_KBETR_KONP,
        TARGET.CALC_PREV_CORP_NIFO_AMT = SOURCE.CALC_PREV_CORP_NIFO_AMT,
        TARGET.PD_ZBA7_KBETR_KONP = SOURCE.PD_ZBA7_KBETR_KONP,
        TARGET.KINRAY_ZBA7_KBETR_KONP = SOURCE.KINRAY_ZBA7_KBETR_KONP,
        TARGET.CALC_PREV_PD_ZBA7_KBETR_KONP = SOURCE.CALC_PREV_PD_ZBA7_KBETR_KONP,
        TARGET.CALC_PREV_KINRAY_ZBA7_KBETR_KONP = SOURCE.CALC_PREV_KINRAY_ZBA7_KBETR_KONP,
        TARGET.CALC_BASE_COST_AMT = SOURCE.CALC_BASE_COST_AMT,
        TARGET.CALC_PREV_BASE_COST_AMT = SOURCE.CALC_PREV_BASE_COST_AMT,
        TARGET.ZBA0_CRT_DTE = SOURCE.ZBA0_CRT_DTE,
        TARGET.ZBA2_CRT_DTE = SOURCE.ZBA2_CRT_DTE,
        TARGET.ZTF0_CRT_DTE = SOURCE.ZTF0_CRT_DTE,
        TARGET.ZREF_CRT_DTE = SOURCE.ZREF_CRT_DTE,
        TARGET.ZMSR_CRT_DTE = SOURCE.ZMSR_CRT_DTE,
        TARGET.CALC_CORP_NIFO_CRT_DTE = SOURCE.CALC_CORP_NIFO_CRT_DTE,
        TARGET.ROW_ADD_STP = SOURCE.ROW_ADD_STP,
        TARGET.ROW_ADD_USER_ID = SOURCE.ROW_ADD_USER_ID,
        TARGET.ROW_UPDATE_STP = SOURCE.ROW_UPDATE_STP,
        TARGET.ROW_UPDATE_USER_ID = SOURCE.ROW_UPDATE_USER_ID
    WHEN NOT MATCHED THEN
      INSERT VALUES
      (
        SOURCE.MATNR_A921,
        SOURCE.VRSN_START_DTE,
        SOURCE.VRSN_END_DTE,
        SOURCE.CURR_VRSN_FLG,
        SOURCE.ZBA0_KBETR_KONP,
        SOURCE.ZBA2_KBETR_KONP,
        SOURCE.ZTF0_KBETR_KONP,
        SOURCE.ZREF_KBETR_KONP,
        SOURCE.ZMSR_KBETR_KONP,
        SOURCE.CALC_CORP_NIFO_AMT,
        SOURCE.CALC_PREV_ZBA0_KBETR_KONP,
        SOURCE.CALC_PREV_ZBA2_KBETR_KONP,
        SOURCE.CALC_PREV_ZTF0_KBETR_KONP,
        SOURCE.CALC_PREV_ZREF_KBETR_KONP,
        SOURCE.CALC_PREV_ZMSR_KBETR_KONP,
        SOURCE.CALC_PREV_CORP_NIFO_AMT,
        SOURCE.PD_ZBA7_KBETR_KONP,
        SOURCE.KINRAY_ZBA7_KBETR_KONP,
        SOURCE.CALC_PREV_PD_ZBA7_KBETR_KONP,
        SOURCE.CALC_PREV_KINRAY_ZBA7_KBETR_KONP,
        SOURCE.CALC_BASE_COST_AMT,
        SOURCE.CALC_PREV_BASE_COST_AMT,
        SOURCE.ZBA0_CRT_DTE,
        SOURCE.ZBA2_CRT_DTE,
        SOURCE.ZTF0_CRT_DTE,
        SOURCE.ZREF_CRT_DTE,
        SOURCE.ZMSR_CRT_DTE,
        SOURCE.CALC_CORP_NIFO_CRT_DTE,
        SOURCE.ROW_ADD_STP,
        SOURCE.ROW_ADD_USER_ID,
        SOURCE.ROW_UPDATE_STP,
        SOURCE.ROW_UPDATE_USER_ID,
        SOURCE.MATNR_A921,
        SOURCE.VRSN_START_DTE,
        SOURCE.VRSN_END_DTE,
        SOURCE.CURR_VRSN_FLG,
        SOURCE.ZBA0_KBETR_KONP,
        SOURCE.ZBA2_KBETR_KONP,
        SOURCE.ZTF0_KBETR_KONP,
        SOURCE.ZREF_KBETR_KONP,
        SOURCE.ZMSR_KBETR_KONP,
        SOURCE.CALC_CORP_NIFO_AMT,
        SOURCE.CALC_PREV_ZBA0_KBETR_KONP,
        SOURCE.CALC_PREV_ZBA2_KBETR_KONP,
        SOURCE.CALC_PREV_ZTF0_KBETR_KONP,
        SOURCE.CALC_PREV_ZREF_KBETR_KONP,
        SOURCE.CALC_PREV_ZMSR_KBETR_KONP,
        SOURCE.CALC_PREV_CORP_NIFO_AMT,
        SOURCE.PD_ZBA7_KBETR_KONP,
        SOURCE.KINRAY_ZBA7_KBETR_KONP,
        SOURCE.CALC_PREV_PD_ZBA7_KBETR_KONP,
        SOURCE.CALC_PREV_KINRAY_ZBA7_KBETR_KONP,
        SOURCE.CALC_BASE_COST_AMT,
        SOURCE.CALC_PREV_BASE_COST_AMT,
        SOURCE.ZBA0_CRT_DTE,
        SOURCE.ZBA2_CRT_DTE,
        SOURCE.ZTF0_CRT_DTE,
        SOURCE.ZREF_CRT_DTE,
        SOURCE.ZMSR_CRT_DTE,
        SOURCE.CALC_CORP_NIFO_CRT_DTE,
        SOURCE.ROW_ADD_STP,
        SOURCE.ROW_ADD_USER_ID,
        SOURCE.ROW_UPDATE_STP,
        SOURCE.ROW_UPDATE_USER_ID
      );
    END;
