CREATE VIEW `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__MARD_CV`
OPTIONS(
  friendly_name="PHM_ORP_PE1_PH1__MARD_CV"
)
AS SELECT MANDT, MATNR, WERKS, LGORT, PSTAT, LVORM, LFGJA, LFMON, SPERR, LABST, UMLME, INSME, EINME, SPEME, RETME, VMLAB, VMUML, VMINS, VMEIN, VMSPE, VMRET, KZILL, KZILQ, KZILE, KZILS, KZVLL, KZVLQ, KZVLE, KZVLS, DISKZ, LSOBS, LMINB, LBSTF, HERKL, EXPPG, EXVER, LGPBE, KLABS, KINSM, KEINM, KSPEM, DLINL, PRCTL, ERSDA, VKLAB, VKUML, LWMKB, BSKRF, MDRUE, MDJIN, ZSLTSTMP, D0_START_STP, D0_END_STP, D0_ADD_STP, D0_ADD_USER_ID, D0_UPDATE_STP, D0_UPDATE_USER_ID, D0_ACTION_ID, D0_SOURCE_ID, D0_CURR_VRSN_FLG, D0_SEQ_NUM FROM VI0_PHM_ORP_PE1_PH1_NP.MARD_CV;