CREATE VIEW `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__MARM_CV`
OPTIONS(
  friendly_name="PHM_ORP_PE1_PH1__MARM_CV"
)
AS SELECT MANDT, MATNR, MEINH, UMREZ, UMREN, EANNR, EAN11, NUMTP, LAENG, BREIT, HOEHE, MEABM, VOLUM, VOLEH, BRGEW, GEWEI, MESUB, ATINN, MESRT, XFHDW, XBEWW, KZWSO, MSEHI, BFLME_MARM, GTIN_VARIANT, NEST_FTR, MAX_STACK, CAPAUSE, TY2TQ, ZSLTSTMP, D0_START_STP, D0_END_STP, D0_ADD_STP, D0_ADD_USER_ID, D0_UPDATE_STP, D0_UPDATE_USER_ID, D0_ACTION_ID, D0_SOURCE_ID, D0_CURR_VRSN_FLG, D0_SEQ_NUM FROM VI0_PHM_ORP_PE1_PH1_NP.MARM_CV;