CREATE TABLE `PROJECT_ID.D2_PHM_CONFDIM_CUSTOMER.CUSTOMER_SALES_AREA_RLT`
(
  KUNNR_KNVV STRING OPTIONS(description="Customer Number"),
  VKORG_KNVV STRING OPTIONS(description="Sales Organization ID"),
  VTWEG_KNVV STRING OPTIONS(description="Distribution Channel ID"),
  SPART_KNVV STRING OPTIONS(description="Division ID"),
  VRSN_START_DTE DATE OPTIONS(description="Derived by data engineering"),
  VRSN_END_DTE DATE OPTIONS(description="Derived by data engineering"),
  CURR_VRSN_FLG STRING OPTIONS(description="Derived by data engineering"),
  ERNAM_KNVV STRING OPTIONS(description="Created By User ID"),
  ERDAT_KNVV DATE OPTIONS(description="Created On Date"),
  LOEVM_KNVV STRING OPTIONS(description="Deletion Indicator Flag"),
  AUFSD_KNVV STRING OPTIONS(description="Central Order Block  ID"),
  VTEXT_TVAST_CENTRAL_ORDER_BLOCK STRING OPTIONS(description="Central Order Block Description Text;CENTRAL_ORDER_BLOCK.VTEXT_TVAST where CENTRAL_ORDER_BLOCK.AUFSP_TVAST = KNVV.AUFSD"),
  KALKS_KNVV STRING OPTIONS(description="Customer Pricing Procedure  ID"),
  VTEXT_TVKDT STRING OPTIONS(description="Customer Pricing Procedure Description Text;CUSTOMER_PRICING_PROCEDURE.VTEXT_TVKDT where CUSTOMER_PRICING_PROCEDURE.KALKS_TVKDT = KNVV.KALKS"),
  KDGRP_KNVV STRING OPTIONS(description="Class Of Trade Level 2  ID"),
  KTEXT_T151T_CLASS_OF_TRADE_LEVEL_TWO STRING OPTIONS(description="Class Of Trade Level 2 Description Text;CLASS_OF_TRADE_LEVEL_TWO.KTEXT_T151T where CLASS_OF_TRADE_LEVEL_TWO.KDGRP_T151T = KNVV.KDGRP"),
  AWAHR_KNVV NUMERIC OPTIONS(description="Item Order Probability Percentage"),
  INCO1_KNVV STRING OPTIONS(description="Incoterms Part 1  ID"),
  BEZEI_TINCT_INCOTERMS STRING OPTIONS(description="Incoterms Part 1 Description Text;INCOTERMS.BEZEI_TINCT where INCOTERMS.INCO1_TINCT = KNVV.INCO1"),
  INCO2_KNVV STRING OPTIONS(description="Incoterms Part 2 Text"),
  LIFSD_KNVV STRING OPTIONS(description="Central Delivery Block  ID"),
  VTEXT_TVLST_CENTRAL_DELIVERY_BLOCK STRING OPTIONS(description="Central Delivery Block Description Text;CENTRAL_DELIVERY_BLOCK.VTEXT_TVLST where CENTRAL_DELIVERY_BLOCK.LIFSP_TVLS = KNVV.LIFSD"),
  AUTLF_KNVV STRING OPTIONS(description="Complete Sales Order Delivery Flag;If KNVV.AUTLF = X then Y else N"),
  ANTLF_KNVV INT64 OPTIONS(description="Item Maximum Allowed Partial Deliveries Number"),
  KZTLF_KNVV STRING OPTIONS(description="Item Partial Deliveries Allowed  ID"),
  ITEM_PRTL_DELIVERIES_ALW_DESC_TXT_ITEM_PARTIAL_DELIVERY STRING OPTIONS(description="Item Partial Deliveries Allowed Description Text;ITEM_PARTIAL_DELIVERY.ITEM_PRTL_DELIVERIES_ALW_DESC_TXT where ITEM_PARTIAL_DELIVERY.KZTLF_KNVV = KNVV.KZTLF"),
  KZAZU_KNVV STRING OPTIONS(description="Sales Order Delivery Combination Flag;If KNVV.KZAZU = X then Y else N"),
  LPRIO_KNVV INT64 OPTIONS(description="Delivery Priority  Code"),
  BEZEI_TPRIT_DELIVERY_PRIORITY STRING OPTIONS(description="Delivery Priority Description Text;DELIVERY_PRIORITY.BEZEI_TPRIT where DELIVERY_PRIORITY.LPRIO_TPRIT = KNVV.LPRIO"),
  EIKTO_KNVV STRING OPTIONS(description="Customer Cardinal EDI Account Number"),
  VSBED_KNVV STRING OPTIONS(description="Shipping Conditions  ID"),
  VTEXT_TVSBT_SHIPPING_CONDITIONS STRING OPTIONS(description="Shipping Conditions Description Text;SHIPPING_CONDITIONS.VTEXT_TVSBT where SHIPPING_CONDITIONS.VTEXT_TVSBT = KNVV.VSBED"),
  FAKSD_KNVV STRING OPTIONS(description="Central Billing Block  ID"),
  VTEXT_TVFST_CENTRAL_BILLING_BLOCK STRING OPTIONS(description="Central Billing Block Description Text;CENTRAL_BILLING_BLOCK.VTEXT_TVFST where CENTRAL_BILLING_BLOCK.FAKSP_TVFST = KNVV.FAKSD"),
  KTGRD_KNVV STRING OPTIONS(description="Account Assignment Group  ID"),
  VTEXT_TVKTT_ACCOUNT_ASSIGNMENT_GROUP STRING OPTIONS(description="Account Assignment Group Description Text;ACCOUNT_ASSIGNMENT_GROUP.VTEXT_TVKTT where ACCOUNT_ASSIGNMENT_GROUP.VTEXT_TVKTT = KNVV.KTGRD"),
  ZTERM_KNVV STRING OPTIONS(description="Payment Terms  ID"),
  VTEXT_TVZBT_PAYMENT_TERMS STRING OPTIONS(description="Payment Terms Description Text;PAYMENT_TERMS.VTEXT_TVZBT where PAYMENT_TERMS.VTEXT_TVZBT = KNVV.ZTERM"),
  VWERK_KNVV STRING OPTIONS(description="Delivering Plant ID"),
  NAME1_T001W STRING OPTIONS(description="Delivering Plant Name"),
  BWKEY_T001W STRING OPTIONS(description="Delivering Plant Valuation Area"),
  KUNNR_T001W STRING OPTIONS(description="Delivering Plant Customer Number"),
  LIFNR_T001W STRING OPTIONS(description="Delivering Plant Vendor Number"),
  FABKL_T001W STRING OPTIONS(description="Delivering Plant Factory Calendar ID"),
  NAME2_T001W STRING OPTIONS(description="Delivering Plant Name2"),
  STRAS_T001W STRING OPTIONS(description="Delivering Plant Address"),
  PFACH_T001W STRING OPTIONS(description="Delivering Plant PO Box"),
  PSTLZ_T001W STRING OPTIONS(description="Delivering Plant Zip"),
  ORT01_T001W STRING OPTIONS(description="Delivering Plant City"),
  REGIO_T001W STRING OPTIONS(description="Delivering Plant State"),
  LAND1_T001W STRING OPTIONS(description="Delivering Plant Country"),
  KVGR1_KNVV STRING OPTIONS(description="Class Of Trade Level 3  ID"),
  BEZEI_TVV1T_CLASS_OF_TRADE_LEVEL_THREE STRING OPTIONS(description="Class Of Trade Level 3 Description Text;CLASS_OF_TRADE_LEVEL_THREE.BEZEI_TVV1T where CLASS_OF_TRADE_LEVEL_THREE.KVGR1_TVV1T = KNVV.KVGR1"),
  KVGR2_KNVV STRING OPTIONS(description="Parmed Customer Classification  ID"),
  BEZEI_TVV2T_PARMED_CUSTOMER_CLASSIFICATION STRING OPTIONS(description="Parmed Customer Classification Description Text;PARMED_CUSTOMER_CLASSIFICATION.BEZEI_TVV2T where PARMED_CUSTOMER_CLASSIFICATION.KVGR2_TVV2T = KNVV.KVGR2"),
  KVGR3_KNVV STRING OPTIONS(description="GPO Class Of Trade  ID"),
  BEZEI_TVV3T_GPO_CLASS_OF_TRADE STRING OPTIONS(description="GPO Class Of Trade Description Text;GPO_CLASS_OF_TRADE.BEZEI_TVV3T where GPO_CLASS_OF_TRADE.KVGR3_TVV3T = KNVV.KVGR3"),
  KVGR4_KNVV STRING OPTIONS(description="Store Size Special Grouping Allocation  ID"),
  BEZEI_TVV4T_STORE_SIZE_SPECIAL_GROUPING_ALL STRING OPTIONS(description="GPO Class Of Trade Description Text;GPO_CLASS_OF_TRADE.BEZEI_TVV3T where GPO_CLASS_OF_TRADE.KVGR3_TVV3T = KNVV.KVGR3"),
  KVGR5_KNVV STRING OPTIONS(description="Financial Reporting  ID"),
  BEZEI_TVV5T_FINANCIAL_REPORTING STRING OPTIONS(description="Financial Reporting Description_Text;FINANCIAL_REPORTING.BEZEI_TVV5T where FINANCIAL_REPORTING.KVGR5_TVV5T = KNVV.KVGR5"),
  KKBER_KNVV STRING OPTIONS(description="Credit Control Area  ID"),
  KKBTX_T014T_CREDIT_CONTROL_AREA STRING OPTIONS(description="Credit Control Area Description Text;CREDIT_CONTROL_AREA.KKBTX_T014T where CREDIT_CONTROL_AREA.KKBER_T014T = KNVV.KKBER"),
  PODKZ_KNVV STRING OPTIONS(description="Relevant For POD Processing Flag;If KNVV.PODKZ = X then Y else N"),
  CAT_IND_KNVV STRING OPTIONS(description="PDPE Active Indicator Flag;If KNVV.CAT_IND = X then Y else N"),
  YYMULTBO_KNVV STRING OPTIONS(description="Customer Allows Multiple Backorder Flag;If KNVV.YYMULTBO = X then Y else N"),
  YYBOPRE1_KNVV STRING OPTIONS(description="Primary Backorder Selection  ID"),
  YYBOPRE1_DES_YTSD_BOPRE1_TEXT_PRIMARY_BACKORDER_SELECTION STRING OPTIONS(description="Primary Backorder Selection Description Text;PRIMARY_BACKORDER_SELECTION.YYBOPRE1_DES_YTSD_BOPRE1_TEXT where PRIMARY_BACKORDER_SELECTION.YYBOPRE1_YTSD_BOPRE1_TEXT = KNVV.YYBOPRE1"),
  YYBOPRE2_KNVV STRING OPTIONS(description="Branded Rx Flag;If KNVV.YYBOPRE2 = X then Y else N"),
  YYBOPRE3_KNVV STRING OPTIONS(description="Generic Rx Flag;If KNVV.YYBOPRE3 = X then Y else N"),
  YYBOPRE4_KNVV STRING OPTIONS(description="Generic C2 Flag;If KNVV.YYBOPRE4 = X then Y else N"),
  YYBOPRE5_KNVV STRING OPTIONS(description="Branded C2 Flag;If KNVV.YYBOPRE5 = X then Y else N"),
  YYBOPRE6_KNVV STRING OPTIONS(description="Rx OTC Insulin Flag;If KNVV.YYBOPRE6 = X then Y else N"),
  YYBOPRE7_KNVV STRING OPTIONS(description="OTC Without Insulin Flag;If KNVV.YYBOPRE7 = X then Y else N"),
  YYBOPRE8_KNVV STRING OPTIONS(description="Blood Plasma Flag;If KNVV.YYBOPRE8 = X then Y else N"),
  YYPRISEC_KNVV STRING OPTIONS(description="Primary Secondary  ID"),
  YYPRISEC_DES_YTSD_PRISEC_TEXT_PRIMARY_SECONDARY_CODE STRING OPTIONS(description="Primary Secondary Description Text;PRIMARY_SECONDARY_CODE.YYPRISEC_DES_YTSD_PRISEC_TEXT where PRIMARY_SECONDARY_CODE.YYPRISEC_YTSD_PRISEC_TEXT = KNVV.YYPRISEC"),
  YYCONSIGN_KNVV STRING OPTIONS(description="Consignment Program  ID"),
  YYCONSIGN_DES_YTSD_CONSIGN_TXT_CONSIGNMENT_PROGRAM STRING OPTIONS(description="Consignment Program Description Text;CONSIGNMENT_PROGRAM.YYCONSIGN_DES_YTSD_CONSIGN_TXT where CONSIGNMENT_PROGRAM.YYCONSIGN_YTSD_CONSIGN_TXT = KNVV.YYCONSIGN"),
  YYHIN_KNVV STRING OPTIONS(description="Shipto HIN ID"),
  YYHRSA_KNVV STRING OPTIONS(description="Shipto HRSA ID"),
  YYP_HRSA_KNVV STRING OPTIONS(description="Parent HRSA ID"),
  YYDODAAC_KNVV STRING OPTIONS(description="DODAAC Number"),
  YY340BCRP_KNVV STRING OPTIONS(description="Credit Replenishment Program 340B Flag;If KNVV.YY340BCRP = X then Y else N"),
  YYRETGRP_KNVV STRING OPTIONS(description="Returns Group  ID"),
  YYRETGRP_DES_YTSD_RETGRP_TEXT_RETURNS_GROUP STRING OPTIONS(description="Returns Group Description Text;RETURNS_GROUP.YYRETGRP_DES_YTSD_RETGRP_TEXT where RETURNS_GROUP.YYRETGRP_YTSD_RETGRP_TEXT = KNVV.YYRETGRP"),
  YYCREDANALYST_KNVV STRING OPTIONS(description="Credit Analyst User ID"),
  YYASHCO_KNVV STRING OPTIONS(description="Ashco Logo Flag;If KNVV.YYASHCO = X then Y else N"),
  YYCRMEMO_KNVV STRING OPTIONS(description="Credit Memo Preferences  ID"),
  YYCRMEMO_DES_YTSD_CRMEMO_TEXT_CREDIT_MEMO_PREFERENCES STRING OPTIONS(description="Credit Memo Preferences Description Text;CREDIT_MEMO_PREFERENCES.YYCRMEMO_DES_YTSD_CRMEMO_TEXT where CREDIT_MEMO_PREFERENCES.YYCRMEMO_YTSD_CRMEMO_TEXT = KNVV.YYCRMEMO"),
  YYGPOCRDAYS_KNVV INT64 OPTIONS(description="GPO Credit Rebill Days Quantity"),
  YYDODACN_KNVV STRING OPTIONS(description="DOD Administrative Contract ID"),
  YYCHAINSTORE_KNVV STRING OPTIONS(description="Chain Warehouse Store Flag;If KNVV.YYCHAINSTORE = X then Y else N"),
  YY340BCONFEE_KNVV STRING OPTIONS(description="Contract Fee Policy 340B  ID"),
  YY340BCONFEE_DES_YTSD_340BCONFTXT_340B_CONTRACT_FEE_POLICY STRING OPTIONS(description="Contract Fee Policy 340B Description Text;340B_CONTRACT_FEE_POLICY.YY340BCONFEE_DES_YTSD_340BCONFTXT where 340B_CONTRACT_FEE_POLICY.YY340BCONFEE_YTSD_340BCONFTXT = KNVV.YY340BCONFEE"),
  YYPVAPRI_KNVV STRING OPTIONS(description="PVA Primary Idenftification Number"),
  YYFSTPURC_KNVV DATE OPTIONS(description="Estimated First Purchase Date"),
  YYCOMTIME_KNVV TIME OPTIONS(description="Commit Time"),
  YYFUELCHG_KNVV STRING OPTIONS(description="Fuel Surcharge  ID"),
  YYFUELCHG_DES_YTSD_FUELCHG_TXT_FUEL_SURCHARGE STRING OPTIONS(description="Fuel Surcharge Description Text;FUEL_SURCHARGE.YYFUELCHG_DES_YTSD_FUELCHG_TXT where FUEL_SURCHARGE.YYFUELCHG_YTSD_FUELCHG_TXT = KNVV.YYFUELCHG"),
  YYEDRPSPD_KNVV STRING OPTIONS(description="EDRP Sites  ID"),
  YYEDRPSPD_DES_YTSD_EDRPSPD_TXT_EDRP_SITES STRING OPTIONS(description="EDRP Sites Description Text;EDRP_SITES.YYEDRPSPD_DES_YTSD_EDRPSPD_TXT where EDRP_SITES.YYEDRPSPD_YTSD_EDRPSPD_TXT = KNVV.YYEDRPSPD"),
  YYMPN_KNVV STRING OPTIONS(description="Medical provider number"),
  YYGRANTN_KNVV STRING OPTIONS(description="Grant Number ID"),
  YYNEMERBLK_KNVV STRING OPTIONS(description="Master Data Emergency Account Block ID"),
  YYCUSFREACC_KNVV STRING OPTIONS(description="Customer Freight Account Number ID"),
  YYDODPVC_KNVV STRING OPTIONS(description="DOD Prime Vendor Contract ID"),
  YYSTOREFRONT_KNVV STRING OPTIONS(description="Customer Storefront  ID"),
  YYSTOREFRONT_DES_YTSD_STORFRNTTXT_CUSTOMER_STOREFRONT STRING OPTIONS(description="Customer Storefront Description Text;CUSTOMER_STOREFRONT.YYSTOREFRONT_DES_YTSD_STORFRNTTXT where CUSTOMER_STOREFRONT.YYSTOREFRONT_YTSD_STORFRNTTXT = KNVV.YYSTOREFRONT"),
  YYCRPO_KNVV STRING OPTIONS(description="PO Required Cancel Rebill Flag;If KNVV.YYCRPO = X then Y else N"),
  YYOCBYPO_KNVV STRING OPTIONS(description="Combine Order By PO Flag;IF KNVV.YYOCBYPO = X then Y else N"),
  YYINVSEQ_KNVV STRING OPTIONS(description="Printed Invoice Sequence  ID"),
  YYINVSEQ_DES_YTSD_INVSEQ_TEXT_PRINTED_INVOICE_SEQUENCE STRING OPTIONS(description="Printed Invoice Sequence Description Text;PRINTED_INVOICE_SEQUENCE.YYINVSEQ_DES_YTSD_INVSEQ_TEXT where PRINTED_INVOICE_SEQUENCE.YYINVSEQ_YTSD_INVSEQ_TEXT = KNVV.YYINVSEQ"),
  YYBRKRX_KNVV STRING OPTIONS(description="Invoice Break By Rx Flag;If KNVV.YYBRKRX = X then Y else N"),
  YYBRKSUP_KNVV STRING OPTIONS(description="Invoice Break By Supplies Flag;If KNVV.YYBRKSUP = X then Y else N"),
  YYBRKDEP_KNVV STRING OPTIONS(description="Tote Split By Department Flag;If KNVV.YYBRKDEP = X then Y else N"),
  YYBRKINSPL_KNVV STRING OPTIONS(description="Invoice Break By Insulin Split Ind Flag;If KNVV.YYBRKINSPL = X then Y else N"),
  YYBRKNONINSPL_KNVV STRING OPTIONS(description="Invoice Break By Non Insulin Split Ind Flag;If KNVV.YYBRKNONINSPL = X then Y else N"),
  YYMULTCOP_KNVV INT64 OPTIONS(description="Multiple Copies Customer Preference  Code"),
  MULTI_COPY_CUSTOMER_PREFER_DESC_TXT_MULTIPLE_COPIES_PREFERENCE STRING OPTIONS(description="Multiple Copies Customer Preference Description Text;MULTIPLE_COPIES_PREFERENCE.MULTI_COPY_CUSTOMER_PREFER_DESC_TXT where MULTIPLE_COPIES_PREFERENCE.YYMULTCOP_KNVV = KNVV.YYMULTCOP"),
  YYSUPZEROINV_KNVV STRING OPTIONS(description="Suppress Printing All Zero Dollar Invoices  ID"),
  SPRS_PRINTING_ALL_ZERO_DLR_INVOICE_DESC_TXT_SUPPRESS_ZERO_PRINTING STRING OPTIONS(description="Suppress Printing All Zero Dollar Invoices Description Text;SUPPRESS_ZERO_PRINTING.SPRS_PRINTING_ALL_ZERO_DLR_INVOICE_DESC_TXT where SUPPRESS_ZERO_PRINTING.YYSUPZEROINV_KNVV = KNVV.YYSUPZEROINV"),
  YYSTMASKPRE_KNVV STRING OPTIONS(description="Stickers Price Masking  ID"),
  YYSTMASKPRE_DES_YTSD_STMASKPRETX_STICKERS_PRICE_MASKING STRING OPTIONS(description="Stickers Price Masking Description Text;STICKERS_PRICE_MASKING.YYSTMASKPRE_DES_YTSD_STMASKPRETX where STICKERS_PRICE_MASKING.YYSTMASKPRE_YTSD_STMASKPRETX = KNVV.YYSTMASKPRE"),
  YYSUPPRINV_KNVV STRING OPTIONS(description="Printed Invoice Suppression  ID"),
  PRINTED_INVOICE_SUPPRESSION_DESC_TXT_SUPPRESS_PRINTED_INVOICE STRING OPTIONS(description="Printed Invoice Suppression Description Text;SUPPRESS_PRINTED_INVOICE.PRINTED_INVOICE_SUPPRESSION_DESC_TXT where SUPPRESS_PRINTED_INVOICE.YYSUPPRINV_KNVV = KNVV.YYSUPPRINV"),
  YYPDMA_KNVV STRING OPTIONS(description="PDMA Signed Flag;If KNVV.YYPDMA = X then Y else N"),
  YYBRKCONT_KNVV STRING OPTIONS(description="Invoice Break Split By Controls Flag;If KNVV.YYBRKCONT = X then Y else N"),
  YYSRCONOTES_KNVV STRING OPTIONS(description="Invoice Source Contract Notes Flag;If KNVV.YYSRCONOTES = X then Y else N"),
  YYCONITORNOTE_KNVV STRING OPTIONS(description="Invoice Contract Item Override Notes Flag;If KNVV.YYCONITORNOTE = X then Y else N"),
  YYCONMARKNOTE_KNVV STRING OPTIONS(description="Invoice Contract Markup Markdown Notes Flag;If KNVV.YYCONMARKNOTE = X then Y else N"),
  YYSTICKCS_KNVV STRING OPTIONS(description="Case Sticker Equivalent Flag;If KNVV.YYSTICKCS = X then Y else N"),
  YYOEINVAPP_KNVV STRING OPTIONS(description="OE Invoice Approval Flag;If KNVV.YYOEINVAPP = X then Y else N"),
  YYCUSMASK_KNVV STRING OPTIONS(description="Item Stickers Cost Masking  ID"),
  YYCUSMASK_DES_YTSD_CUSMASK_TXT_ITEM_STICKERS_COST_MASKING STRING OPTIONS(description="Item Stickers Cost Masking Description Text;ITEM_STICKERS_COST_MASKING.YYCUSMASK_DES_YTSD_CUSMASK_TXT where ITEM_STICKERS_COST_MASKING.YYCUSMASK_YTSD_CUSMASK_TXT = KNVV.YYCUSMASK"),
  YYSHELFLAB_KNVV STRING OPTIONS(description="Shelf Label  ID"),
  YYSHELFLAB_DES_YTSD_SHELFLABTXT_SHELF_LABEL STRING OPTIONS(description="Shelf Label Description Text;SHELF_LABEL.YYSHELFLAB_DES_YTSD_SHELFLABTXT where SHELF_LABEL.YYSHELFLAB_YTSD_SHELFLABTXT = KNVV.YYSHELFLAB"),
  YYLABELABB_KNVV STRING OPTIONS(description="Label Abbreviation ID"),
  YYRETAILMASK_KNVV STRING OPTIONS(description="OTC Item Sticker Retail Price Flag;If KNVV.YYRETAILMASK = X then Y else N"),
  YYFULLELECT_KNVV STRING OPTIONS(description="Fullly Electronic Output Flag;If KNVV.YYFULLELECT = X then Y else N"),
  YYRETMASK_LABEL_KNVV STRING OPTIONS(description="OTC Shelf Label Retail Price Flag;If KNVV.YYRETMASK_LABEL = X then Y else N"),
  YYIMS_KNVV STRING OPTIONS(description="IMS  ID"),
  YYIMS_DES_YTSD_IMS_CODETXT_IMS_CODE STRING OPTIONS(description="IMS Description Text;IMS_CODE.YYIMS_DES_YTSD_IMS_CODETXT where IMS_CODE.YYIMS_YTSD_IMS_CODETXT = KNVV.YYIMS"),
  YYCUSMASKDSC_KNVV STRING OPTIONS(description="Custom Mask Description ID"),
  YYORIGORDMSK_KNVV STRING OPTIONS(description="Invoice Form Display Original Order Quantity Flag;If KNVV.YYORIGORDMSK = X then Y else N"),
  YYOESLOPT_KNVV STRING OPTIONS(description="Shelf Label Options  ID"),
  SHELF_LABEL_OPTIONS_DESC_TXT_SHELF_LABEL_OPTIONS STRING OPTIONS(description="Shelf Label Options Description Text;SHELF_LABEL_OPTIONS.SHELF_LABEL_OPTIONS_DESC_TXT Case where SHELF_LABEL_OPTIONS.YYOESLOPT_KNVV = KNVV.YYOESLOPT"),
  YYNCPDP1_KNVV STRING OPTIONS(description="NCPDP ID"),
  YYNPI1_KNVV STRING OPTIONS(description="NPI ID"),
  YYNABP1_KNVV STRING OPTIONS(description="NABP ID"),
  YYPRCSTKR_KNVV STRING OPTIONS(description="Price Sticker  ID"),
  YYDES_YTSD_PRC_STKR_TX_PRICE_STICKER STRING OPTIONS(description="Price Sticker Description Text;PRICE_STICKER.YYDES_YTSD_PRC_STKR_TX where PRICE_STICKER.YYPRCSTKR_YTSD_PRC_STKR_TX = KNVV.YYPRCSTKR"),
  YYSTKSLOPT_KNVV STRING OPTIONS(description="Shelf Label Sticker Options  ID"),
  YYSTKSLOPT_DES_YTSD_STKSLOPTTXT_SHELF_LABEL_STICKER_OPTIONS STRING OPTIONS(description="Shelf Label Sticker Options Description Text;SHELF_LABEL_STICKER_OPTIONS.YYSTKSLOPT_DES_YTSD_STKSLOPTTXT where SHELF_LABEL_STICKER_OPTIONS.YYSTKSLOPT_YTSD_STKSLOPTTXT = KNVV.YYSTKSLOPT"),
  YYLOTEXP_KNVV STRING OPTIONS(description="Lot Expiration Preference  ID"),
  YYDES_YTSD_LOT_EXP_TXT_LOT_EXPIRATION_PREFERENCE STRING OPTIONS(description="Lot Expiration Preference Description Text;LOT_EXPIRATION_PREFERENCE.YYDES_YTSD_LOT_EXP_TXT where LOT_EXPIRATION_PREFERENCE.YYLOTEXP_YTSD_LOT_EXP_TXT = KNVV.YYLOTEXP"),
  YYLOCKBOX_KNVV STRING OPTIONS(description="Customer Payment Lockbox Key ID"),
  HBKID_T049L STRING OPTIONS(description="Lockbox House Bank Short Key ID;T049L.HBKID where T049L.LOCKB = KNVV.YYLOCKBOX"),
  LCKNR_T049L INT64 OPTIONS(description="Lockbox Number;T049L.LCKNR where T049L.LOCKB = KNVV.YYLOCKBOX"),
  ADRNR_T049L STRING OPTIONS(description="Lockbox Address Reference Number;T049L.ADRNR where T049L.LOCKB = KNVV.YYLOCKBOX"),
  YYCOLLECTOR_KNVV STRING OPTIONS(description="Collector Agent User ID"),
  YYCOLLGROUP_KNVV STRING OPTIONS(description="Collection Group  ID"),
  COLL_GROUP_TEXT_UDM_COLL_GRPT_COLLECTION_GROUP STRING OPTIONS(description="Collection Group Description Text;COLLECTION_GROUP.COLL_GROUP_TEXT_UDM_COLL_GRPT where COLLECTION_GROUP.COLL_GROUP_UDM_COLL_GRP = KNVV.YYCOLLGROUP"),
  YYDUPORDER_KNVV STRING OPTIONS(description="Duplicate Order Preference Flag;If KNVV.YYDUPORDER = X then Y else N"),
  YYWEBIND_KNVV STRING OPTIONS(description="Web Indicator Flag;If KNVV.YYWEBIND = X then Y else N"),
  YYSAMECUTOFF_KNVV TIME OPTIONS(description="Default Plant Same Day Cutoff Time"),
  YYNEXTCUTOFF_KNVV TIME OPTIONS(description="Default Plant Next Day Cutoff Time"),
  YYONBOARDID_KNVV STRING OPTIONS(description="Sales Force Onboarding ID"),
  YYLOTTRACK_KNVV STRING OPTIONS(description="Print Lot Number Flag;If KNVV.YYLOTTRACK = X then Y else N"),
  YYNOPRINV_KNVV STRING OPTIONS(description="Do Not Print Invoice Flag;IF KNVV.YYNOPRINV = X then Y else N"),
  YYRETAIL_KNVV STRING OPTIONS(description="Retail Pricing Indicator  ID"),
  RETAIL_PRICE_IND_DESC_TXT_RETAIL_PRICING_INDICATOR STRING OPTIONS(description="Retail Pricing Indicator Description Text;RETAIL_PRICING_INDICATOR.RETAIL_PRICE_IND_DESC_TXT where RETAIL_PRICING_INDICATOR.YYRETAIL_KNVV =  KNVV.YYRETAIL"),
  YYINVBATCH_KNVV STRING OPTIONS(description="Invoice Batching Flag;If KNVV.YYINVBATCH = X then Y else N"),
  YYCOMMODITY_KNVV STRING OPTIONS(description="Customer Stock Number  ID"),
  CUSTOMER_STOCK_NUM_DESC_TXT_CUSTOMER_STOCK_NUMBER_CODE STRING OPTIONS(description="Customer Stock Number Description Text;CUSTOMER_STOCK_NUMBER_CODE.CUSTOMER_STOCK_NUM_DESC_TXT where CUSTOMER_STOCK_NUMBER_CODE.YYCOMMODITY_KNVV = KNVV.YYCOMMODITY"),
  YYPRICEMASKINV_KNVV STRING OPTIONS(description="Invoice Price Masking  ID"),
  YYPRICEMASKINV_DES_YTSD_PREMSKINVTX_INVOICE_PRICE_MASKING STRING OPTIONS(description="Invoice Price Masking Description Text;INVOICE_PRICE_MASKING.YYPRICEMASKINV_DES_YTSD_PREMSKINVTX where INVOICE_PRICE_MASKING.YYPRICEMASKINV_YTSD_PREMSKINVTX = KNVV.YYPRICEMASKINV"),
  YYSTORESUP_KNVV STRING OPTIONS(description="Store Supplies Flag;If KNVV.YYSTORESUP = X then Y else N"),
  YYHAMCHZ_KNVV STRING OPTIONS(description="Retail Price Tier  ID"),
  YYRPRPT_DESC_YTSD_HAMACHER_ZL_RETAIL_PRICE_TIER STRING OPTIONS(description="Retail Price Tier Description Text;RETAIL_PRICE_TIER.YYRPRPT_DESC_YTSD_HAMACHER_ZL where RETAIL_PRICE_TIER.VKORG_YTSD_HAMACHER_ZL = KNVV.VKORG and RETAIL_PRICE_TIER.VTWEG_YTSD_HAMACHER_ZL = KNVV.VTWEG and RETAIL_PRICE_TIER.SPART_YTSD_HAMACHER_ZL = KNVV.SPART and RETAIL_PRICE_TIER.YYRPRPT_YTSD_HAMACHER_ZL = KNVV.YYHAMCHZ"),
  YYPCDCHG_KNVV DATE OPTIONS(description="Program System Code Change Date"),
  YYMARKETKEY_KNVV STRING OPTIONS(description="Marketing Key ID"),
  YYGRNDSHPIND_KNVV STRING OPTIONS(description="Ground Shipping Indicator Flag;If KNVV.YYGRNDSHPIND = X then Y else N"),
  YYPACKINGLIST_KNVV STRING OPTIONS(description="Packing List Flag;If KNVV.YYPACKINGLIST = X then Y else N"),
  YYPOREQ_KNVV STRING OPTIONS(description="PO Required On Order Flag;If KNVV.YYPOREQ = X then Y else N"),
  YYPOCHK24_KNVV STRING OPTIONS(description="Last 24 Hours Check Duplicate PO Flag;If KNVV.YYPOCHK24 = X then Y else N"),
  YYMINORDVAL_KNVV NUMERIC OPTIONS(description="Minimum Order Quantity"),
  YYSATMINVAL_KNVV NUMERIC OPTIONS(description="Saturday Minimum Order Quantity"),
  YYPKSLPOV_KNVV STRING OPTIONS(description="Pack Slip Override Flag;If KNVV.YYPKSLPOV = X then Y else N"),
  YYRTRNRFID_KNVV STRING OPTIONS(description="Returns RF Container Flag;If KNVV.YYRTRNRFID = X then Y else N"),
  YYBLMSH_KNVV STRING OPTIONS(description="Blemish Customer Flag;If KNVV.YYBLMSH = X then Y else N"),
  YYCGVLTCNS_KNVV STRING OPTIONS(description="Cage Vault Consolidation Flag;If KNVV.YYCGVLTCNS = X then Y else N"),
  YYRTNCRDPU_KNVV STRING OPTIONS(description="Return Credit At Pick Up Flag;If KNVV.YYRTNCRDPU = X then Y else N"),
  YYPKSLCUSTPO_KNVV STRING OPTIONS(description="Packing Slip By Customer PO Flag;If KNVV.YYPKSLCUSTPO = X then Y else N"),
  YYCOMMITMNT_KNVV STRING OPTIONS(description="Commitment Level  ID"),
  YYCOMMITMNT_DES_YTSD_COMMIT_TXT_COMMITMENT_LEVEL STRING OPTIONS(description="Commitment Level Description Text;COMMITMENT_LEVEL.YYCOMMITMNT_DES_YTSD_COMMIT_TXT where COMMITMENT_LEVEL.YYCOMMITMNT_YTSD_COMMIT_TXT = KNVV.YYCOMMITMNT"),
  YYTYPE_KNVV STRING OPTIONS(description="SPD Vitalsource Membership Type  ID"),
  YYTYPE_DES_YTSD_TYPE_TXT_SPD_VITALSOURCE_MEMBERSHIP_TYPE STRING OPTIONS(description="SPD Vitalsource Membership Type Description Text;SPD_VITALSOURCE_MEMBERSHIP_TYPE.YYTYPE_DES_YTSD_TYPE_TXT where SPD_VITALSOURCE_MEMBERSHIP_TYPE.YYTYPE_YTSD_TYPE_TXT = KNVV.YYTYPE"),
  YYPRIAME_KNVV STRING OPTIONS(description="PVA PRI Amendment Number"),
  YYVALHRSA_KNVV STRING OPTIONS(description="Valid HRSA ID Flag"),
  YYPHYDISP_KNVV STRING OPTIONS(description="SPD Physician Dispensing  ID"),
  YYPHYDISP_DES_YTSD_PHYDIS_TEXT_SPD_PHYSICIAN_DISPENSING STRING OPTIONS(description="SPD Physician Dispensing Description Text;SPD_PHYSICIAN_DISPENSING.YYPHYDISP_DES_YTSD_PHYDIS_TEXT where SPD_PHYSICIAN_DISPENSING.YYPHYDISP_YTSD_PHYDIS_TEXT = KNVV.YYPHYDISP"),
  CALC_CUST_SALES_AREA_KEY STRING OPTIONS(description="Customer Sales Area Key "),
  CALC_SALES_AREA_KEY STRING OPTIONS(description="Sales Area Key "),
  CALC_HIGHER_LVL_CUST_SALES_AREA_KEY STRING OPTIONS(description="Customer Sales Area Key "),
  CALC_BRSCH_KNA1 STRING OPTIONS(description="340B Customer Flag "),
  CALC_GENDA_DEA_EMBK DATE OPTIONS(description="DEA LIcense Validity End Date "),
  CALC_GENDA_ST_EMBK DATE OPTIONS(description="State LIcense Validity End Date "),
  CALC_GENDA_ST_CTRL_EMBK DATE OPTIONS(description="State Control Sub LIcense Validity End Date "),
  CALC_GENDA_PHY_DEA_EMBK DATE OPTIONS(description="Physician DEA LIcense Validity End Date "),
  PODTG_KNVV NUMERIC OPTIONS(description="Timeframe For Confirmation Of Pod "),
  AGREL_KNVV STRING OPTIONS(description="Relevant For Agency Business Flag "),
  RDOFF_KNVV STRING OPTIONS(description="Switch Off Rounding "),
  CASSD_KNVV STRING OPTIONS(description="Sales Block For Customer "),
  KABSS_KNVV STRING OPTIONS(description="Customer Payment Guarantee Procedure "),
  PRATA_KNVV STRING OPTIONS(description="Id For Product Attribute 10 "),
  PRAT3_KNVV STRING OPTIONS(description="Id For Product Attribute 3 "),
  PRAT2_KNVV STRING OPTIONS(description="Id For Product Attribute 2 "),
  PRAT1_KNVV STRING OPTIONS(description="Id For Product Attribute 1 "),
  PRFRE_KNVV STRING OPTIONS(description="Relevant For Price Determination Id "),
  BOIDT_KNVV STRING OPTIONS(description="Start Of Validity Per.For The Rebate Index For The Customer "),
  BOKRE_KNVV STRING OPTIONS(description="Customer Is Rebate Relevant Flag "),
  KLABC_KNVV STRING OPTIONS(description="Customer Classification ABC Analysis "),
  WAERS_KNVV STRING OPTIONS(description="Currency "),
  PERRL_KNVV STRING OPTIONS(description="Invoice List Schedule "),
  PERFK_KNVV STRING OPTIONS(description="Invoice Dates "),
  MRNKZ_KNVV STRING OPTIONS(description="Manual Invoice Maintenance "),
  PLTYP_KNVV STRING OPTIONS(description="Price List Type "),
  KONDA_KNVV STRING OPTIONS(description="Price Group "),
  BZIRK_KNVV STRING OPTIONS(description="Sales District "),
  VERSG_KNVV STRING OPTIONS(description="Customer Statistics Group "),
  BEGRU_KNVV STRING OPTIONS(description="Authorization Group "),
  YYRETAIL__KNVV STRING OPTIONS(description="Retail Pricing Indicator "),
  ZZ_SEND_EDI_KNVV STRING OPTIONS(description="Send To Edi "),
  ZZ_SH_COPY_KNVV STRING OPTIONS(description="Send Ship To Copy "),
  ZZ_WEB_KNVV STRING OPTIONS(description="Web "),
  ZZ_PRINT_KNVV STRING OPTIONS(description="Print "),
  ZZ_FAX_KNVV STRING OPTIONS(description="Fax "),
  ZZ_EMAIL_KNVV STRING OPTIONS(description="Email "),
  ZZ_PRICE_KNVV STRING OPTIONS(description="Display Price "),
  ZZ_RX_PATIENT_KNVV STRING OPTIONS(description="Display Rx Patient "),
  ZZ_INVOICE_SH_KNVV STRING OPTIONS(description="Invoiced By "),
  EXGEN_DEA_EMBK STRING OPTIONS(description="DEA License Number "),
  EXGEN_ST_EMBK STRING OPTIONS(description="State License Number "),
  EXGEN_ST_CTRL_SUB_EMBK STRING OPTIONS(description="State Control Sub License Number "),
  EXGEN_PHY_DEA_EMBK STRING OPTIONS(description="Physician DEA license Number "),
  NAME1_KNA1_SB STRING OPTIONS(description="Special Stock Partner Customer Name "),
  KUNN2_KNVP_SB STRING OPTIONS(description="Special Stock Partner Customer Number "),
  NAME1_KNA1_CN STRING OPTIONS(description="Consignment Network Customer Name "),
  KUNN2_KNVP_CN STRING OPTIONS(description="Consignment Network Customer Number "),
  NAME1_KNA1_CM STRING OPTIONS(description="Campus Customer Name "),
  KUNN2_KNVP_CM STRING OPTIONS(description="Campus Customer Number "),
  NAME1_KNA1_A3 STRING OPTIONS(description="Affiliation Level3 Customer Name "),
  KUNN2_KNVP_A3 STRING OPTIONS(description="Affiliation Level3 Customer Number "),
  NAME1_KNA1_A2 STRING OPTIONS(description="Affiliation Level2 Customer Name "),
  KUNN2_KNVP_A2 STRING OPTIONS(description="Affiliation Level2 Customer Number "),
  NAME1_KNA1_A1 STRING OPTIONS(description="Affiliation Level1 Customer Name "),
  KUNN2_KNVP_A1 STRING OPTIONS(description="Affiliation Level1 Customer Number "),
  YYCONSIGN_DES_YTSD_CONSIGN_TXT STRING OPTIONS(description="Name "),
  HSPART_KNVH STRING OPTIONS(description="Higher-level division "),
  HVTWEG_KNVH STRING OPTIONS(description="Higher-level distribution channel "),
  HVKORG_KNVH STRING OPTIONS(description="Higher-level sales organization "),
  HKUNNR_KNVH STRING OPTIONS(description="Customer number of the higher-level customer hierarchy "),
  YNAME_YTSD_NAT_ACCOUNT STRING OPTIONS(description="National Account Name "),
  YNAT_ACC_YTSD_NAT_ACCOUNT STRING OPTIONS(description="National Account ID "),
  VTEXT_TVSBT STRING OPTIONS(description="Shipping Condition Text "),
  VTEXT_TKUKT STRING OPTIONS(description="Customer classification Description "),
  BEZEI_TINCT STRING OPTIONS(description="Shipping Incoterm Text "),
  VTEXT_TVTWT STRING OPTIONS(description="Distribution Channel Name "),
  VTEXT_TSPAT STRING OPTIONS(description="Sales Division Name "),
  VTEXT_TVKOT STRING OPTIONS(description="Sales Org Name "),
  VTEXT_TVKTT STRING OPTIONS(description="Account Assignment Group Description "),
  VTEXT_TVAST STRING OPTIONS(description="Sales Area Order Block Reason Text "),
  BEZEI_TVV5T STRING OPTIONS(description="Customer Group 5 Name "),
  BEZEI_TVV3T STRING OPTIONS(description="Customer Group 3 Name "),
  BEZEI_TVV2T STRING OPTIONS(description="Customer Group 2 Name "),
  BEZEI_TVV1T STRING OPTIONS(description="Customer Group 1 Name "),
  KTEXT_T151T STRING OPTIONS(description="Customer Group Name "),
  BRTXT_T016T STRING OPTIONS(description="Industry Description "),
  KKBTX_T014T STRING OPTIONS(description="Credit Control Area Description "),
  SMTP_ADDR_ADR6 STRING OPTIONS(description="E Mail Address "),
  NODEL_KNA1 STRING OPTIONS(description="Central Deletion Block For Master Record "),
  J_1KFTIND_KNA1 STRING OPTIONS(description="Type Of Industry "),
  J_1KFTBUS_KNA1 STRING OPTIONS(description="Type Of Business "),
  KNURL_KNA1 STRING OPTIONS(description="Uniform Resource Locator "),
  CASSD_KNA1 STRING OPTIONS(description="Central Sales Block For Customer "),
  STCD4_KNA1 STRING OPTIONS(description="Tax Number 4 "),
  STCD3_KNA1 STRING OPTIONS(description="Tax Number 3 "),
  FITYP_KNA1 STRING OPTIONS(description="Tax Type "),
  CIVVE_KNA1 STRING OPTIONS(description="ID For Mainly Non-Military Use "),
  SPERZ_KNA1 STRING OPTIONS(description="PO Box city "),
  WERKS_KNA1 STRING OPTIONS(description="Plant "),
  PFORT_KNA1 STRING OPTIONS(description="PO Box city "),
  KATR10_KNA1 STRING OPTIONS(description="Attribute 10 "),
  KATR1_KNA1 STRING OPTIONS(description="Attribute 1 "),
  BRAN1_KNA1 STRING OPTIONS(description="Industry Code 1 "),
  GFORM_KNA1 STRING OPTIONS(description="Legal Status "),
  DEAR2_KNA1 STRING OPTIONS(description="Sales Partner Flag "),
  STCEG_KNA1 STRING OPTIONS(description="VAT Registration Number "),
  VBUND_KNA1 STRING OPTIONS(description="Company ID Of Trading Partner "),
  XZEMP_KNA1 STRING OPTIONS(description="Is An Alternative Payer Allowed In Document Flag "),
  LZONE_KNA1 STRING OPTIONS(description="Transportation Zone To Or From Which The Goods Are Delivered "),
  TELF2_KNA1 STRING OPTIONS(description="Second Telephone Number "),
  STCD2_KNA1 STRING OPTIONS(description="Tax Number 2 "),
  SPRAS_KNA1 STRING OPTIONS(description="Language Key "),
  SPERR_KNA1 STRING OPTIONS(description="Central Posting Block "),
  COUNC_KNA1 STRING OPTIONS(description="County Code "),
  PSTL2_KNA1 STRING OPTIONS(description="PO Box Postal Code "),
  PFACH_KNA1 STRING OPTIONS(description="PO Box "),
  ORT02_KNA1 STRING OPTIONS(description="District "),
  NIELS_KNA1 STRING OPTIONS(description="Nielsen Id "),
  NAME4_KNA1 STRING OPTIONS(description="Name 4 "),
  NAME3_KNA1 STRING OPTIONS(description="Name 3 "),
  LIFSD_KNA1 STRING OPTIONS(description="Central Delivery Block For The Customer "),
  LOEVM_KNA1 STRING OPTIONS(description="Central Deletion Flag For Master Record "),
  LIFNR_KNA1 STRING OPTIONS(description="Supplier Number "),
  KUKLA_KNA1 STRING OPTIONS(description="Customer Classification "),
  KTOKD_KNA1 STRING OPTIONS(description="Customer Account Group "),
  KNRZA_KNA1 STRING OPTIONS(description="Account Number Of An Alternative Payer KNA1 "),
  KNAZK_KNA1 STRING OPTIONS(description="Working Time Calender "),
  FAKSD_KNA1 STRING OPTIONS(description="Central Billing Block For Customer "),
  EXABL_KNA1 STRING OPTIONS(description="Unloading Points Exist Flag "),
  DATLT_KNA1 STRING OPTIONS(description="Data Communication Line No "),
  BUBKZ_KNA1 STRING OPTIONS(description="Check Digit For The International Location Number "),
  BRSCH_KNA1 STRING OPTIONS(description="Industry Key "),
  BBSNR_KNA1 STRING OPTIONS(description="International Location Number Part2 "),
  BBBNR_KNA1 STRING OPTIONS(description="International Location Number Part1 "),
  BAHNS_KNA1 STRING OPTIONS(description="Train Station "),
  BAHNE_KNA1 STRING OPTIONS(description="Express Train Station "),
  AUFSD_KNA1 STRING OPTIONS(description="Central Order Block For Customer "),
  ANRED_KNA1 STRING OPTIONS(description="Title "),
  MCOD3_KNA1 STRING OPTIONS(description="Search Term For Matchcode Search3 "),
  MCOD2_KNA1 STRING OPTIONS(description="Search Term For Matchcode Search2 "),
  MCOD1_KNA1 STRING OPTIONS(description="Search Term For Matchcode Search1 "),
  ADRNR_KNA1 STRING OPTIONS(description="Address "),
  TELFX_KNA1 STRING OPTIONS(description="Fax Number "),
  TELF1_KNA1 STRING OPTIONS(description="First Telephone Number "),
  STRAS_KNA1 STRING OPTIONS(description="House Number And Street "),
  SORTL_KNA1 STRING OPTIONS(description="Sort Field "),
  REGIO_KNA1 STRING OPTIONS(description="Region "),
  PSTLZ_KNA1 STRING OPTIONS(description="Postal Code "),
  ORT01_KNA1 STRING OPTIONS(description="City "),
  NAME2_KNA1 STRING OPTIONS(description="Name 2 "),
  NAME1_KNA1 STRING OPTIONS(description="Name 1 "),
  LAND1_KNA1 STRING OPTIONS(description="Country Key "),
  TATYP_KNVI STRING OPTIONS(description="Tax category"),
  TAXKD_KNVI STRING OPTIONS(description="Tax classification for customer "),
  VTEXT_TSKDT STRING OPTIONS(description="Tax Classification Description "),
  ZSLTSTMP_KNVV STRING OPTIONS(description="ZSLTSTMP "),
  YACCRCYC_YTSDSOMCAL STRING OPTIONS(description="Accrual Cycle "),
  YCONSGRP_YTLE_CONSOLI_GRP STRING OPTIONS(description="Consolidation Group ID "),
  BUILDING_ADRC STRING OPTIONS(description="Building "),
  PERSNUMBER_ADRP STRING OPTIONS(description="PERSNUMBER_ADRP "),
  NAME_TEXT_ADRP STRING OPTIONS(description="PMod Collector Agent Name "),
  YYRPRPT_DESC STRING OPTIONS(description="Hamacher Zone Description "),
  PARNR_KNVK STRING OPTIONS(description="First Contact Person Number "),
  TELF1_KNVK STRING OPTIONS(description="First Contact Person Telephone Number "),
  NAMEV_KNVK STRING OPTIONS(description="First Contact Person First Name "),
  NAME1_KNVK STRING OPTIONS(description="First Contact Person Last Name "),
  VTEXT_TVFST STRING OPTIONS(description="Sales Area Billing Block Reason Text "),
  VTEXT_TVLST STRING OPTIONS(description="Sales Area Delivery Block Reason Text "),
  TXJCD_KNA1 STRING OPTIONS(description="Tax Jurisdiction "),
  STR_SUPPL1_ADRC STRING OPTIONS(description="Street2 "),
  CALC_GPO_CUST_FLAG STRING OPTIONS(description="GPO Customer Flag "),
  CALC_WAC_CUST_FLAG STRING OPTIONS(description="WAC Cstomer Flag "),
  CALC_ERDAT_KNVV DATE OPTIONS(description="Record Created Date "),
  EXGEN_PHY_ST_LIC_EMBK STRING OPTIONS(description="Physician State License Number "),
  CALC_GENDA_ST_PHY_LIC_EMBK DATE OPTIONS(description="Physician State License Validity End Date "),
  EXGEN_DME_LIC_EMBK STRING OPTIONS(description="Physician DME License Number "),
  CALC_GENDA_DME_LIC_EMBK DATE OPTIONS(description="Physician DME License Validity End Date "),
  KUNN2_KNVP STRING OPTIONS(description="SalesRep Customer Num "),
  NAME_USER STRING OPTIONS(description="SalesRep Customer Name "),
  OUT_EXT_SHIPTO_YTEDPAR STRING OPTIONS(description="Outbound External Ship To Cust ID "),
  CALC_BILLING_OUTBOUND_EDI_FLAG_YTSD_EDI_DUP STRING OPTIONS(description="Billing Outbound EDI Flag "),
  CALC_SHIPTOCUSTOMERFLAG STRING OPTIONS(description="Is ShipTo Customer Flag"),
  KUNNR_KNVP_SOLDTO STRING OPTIONS(description="SoldTo Party Customer Number "),
  NAME1_KNA1_SOLDTO STRING OPTIONS(description="SoldTo Party Customer Name "),
  CALC_YYFSTPURC_KNVV DATE OPTIONS(description="First purchase date type "),
  KUNN2_SOLD_KNVP STRING OPTIONS(description="Sold To Customer Number "),
  ADRNR_PAYER_KNA1 STRING OPTIONS(description="Payer Customer Address"),
  REGIO_PAYER_KNA1 STRING OPTIONS(description="Payer Customer State "),
  PSTLZ_PAYER_KNA1 STRING OPTIONS(description="Payer Customer Postal Code"),
  NAME1_PAYER_KNA1 STRING OPTIONS(description="Payer Customer Name"),
  ORT01_PAYER_KNA1 STRING OPTIONS(description="Payer Customer City "),
  NAME2_PAYER_KNA1 STRING OPTIONS(description="Payer Customer Name 2 "),
  EXGEN_ST_PRIS_LIC_EMBK STRING OPTIONS(description="State Pharmacy License Number "),
  CALC_GENDA_ST_PRIS_LIC_EMBK DATE OPTIONS(description="State Pharmacy License Validity End Date"),
  BBBNR_PAYER_KNA1 STRING OPTIONS(description="International Location Number Part1"),
  BBSNR_PAYER_KNA1 STRING OPTIONS(description="International Location Number Part2"),
  BUBKZ_PAYER_KNA1 STRING OPTIONS(description="Check Digit For The International Location Number"),
  KUNN2_KNVP_PAYTO STRING OPTIONS(description="Payer Affiliation Number"),
  BBBNR_SHIPTO_KNA1 STRING OPTIONS(description="International Location Number Part1"),
  BBSNR_SHIPTO_KNA1 STRING OPTIONS(description="International Location Number Part2"),
  BUBKZ_SHIPTO_KNA1 STRING OPTIONS(description="Check Digit For The International Location Number"),
  KUNN2_KNVP_PG STRING OPTIONS(description="Primary GPO "),
  CALC_SGPO_1 STRING OPTIONS(description="Secondary GPO"),
  CALC_SGPO_2 STRING OPTIONS(description="Secondary GPO 2"),
  CALC_SGPO_3 STRING OPTIONS(description="Secondary GPO 3"),
  CALC_SGPO_4 STRING OPTIONS(description="Secondary GPO 4"),
  CALC_SGPO_5 STRING OPTIONS(description="Secondary GPO 5"),
  END_DTE DATE OPTIONS(description="EndDate"),
  KUNN2_KNVP_SALESREP STRING OPTIONS(description="SalesRep Customer Number"),
  NAME1_KNA1_SALESREP STRING OPTIONS(description="SalesRep Customer Name 1"),
  NAME2_KNA1_SALESREP STRING OPTIONS(description="SalesRep Customer Name 2"),
  CALC_SCHED_2_ITEM_ALLOW_FLG STRING OPTIONS(description="version flag"),
  CALC_SCHED_3_ITEM_ALLOW_FLG STRING OPTIONS(description="Exception flag"),
  CALC_SCHED_4_ITEM_ALLOW_FLG STRING OPTIONS(description="Process Name "),
  CALC_SCHED_5_ITEM_ALLOW_FLG STRING OPTIONS(description="User ID added Row "),
  CUSID_PCSBGC STRING OPTIONS(description="Customer Roster ID "),
  VWERK_KNVV_SOLDTO STRING OPTIONS(description="Delivering Plant "),
  WERKS_KNA1_SOLDTO STRING OPTIONS(description="sold to Plant"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Indicates date the row was inserted"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Indicates by which job the row was inserted"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Indicates date the row was updated"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Indicates by which job the row was updated")
)
PARTITION BY VRSN_START_DTE
CLUSTER BY KUNNR_KNVV, VKORG_KNVV, VTWEG_KNVV, SPART_KNVV;