CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.AHFS_CODE_CV`
(
  YYAHFS_YTMM_AHFS_TEXT STRING OPTIONS(description="AHFS ID; YTMM_AHFS_TEXT.YYAHFS where YTMM_AHFS_TEXT.SPRAS = E"),
  YYDESC_YTMM_AHFS_TEXT STRING OPTIONS(description="AHFS Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYAHFS_YTMM_AHFS_TEXT;