CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.DEA_BASE_CODE_CV`
(
  YYBASE_YTMM_DEA_TEXT STRING OPTIONS(description="DEA Base Code ID; YTMM_DEA_TEXT.YYBASE where YTMM_DEA_TEXT.SPRAS = E"),
  YYDESC_YTMM_DEA_TEXT STRING OPTIONS(description="DEA Base Code Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYBASE_YTMM_DEA_TEXT;