CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.FORM_CV`
(
  YYFORM_YTMM_FORM_TEXT STRING OPTIONS(description="Form ID; YTMM_FORM_TEXT.YYFORM where YTMM_FORM_TEXT.SPRAS = E"),
  YYDESC_YTMM_FORM_TEXT STRING OPTIONS(description="Form Description Text"),
  YYLFORM_YTMM_FORM_TEXT STRING OPTIONS(description="Long Form ID"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYFORM_YTMM_FORM_TEXT;