CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.HAMACHER_FINE_CLASS_CV`
(
  YYFINE_YTMM_FINE_TEXT STRING OPTIONS(description="Hamacher Fine Class ID; YTMM_FINE_TEXT.YYFINE where YTMM_FINE_TEXT = E"),
  YYDESC_YTMM_FINE_TEXT STRING OPTIONS(description="Hamacher Fine Class Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYFINE_YTMM_FINE_TEXT;