CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.HAMACHER_FINEST_CLASS_CV`
(
  YYFINEST_YTMM_FINEST_TEXT STRING OPTIONS(description="Hamacher Finest Class ID; YTMM_FINEST_TEXT.YYFINEST where YTMM_FINEST_TEXT.SPRAS = E"),
  YYDESC_YTMM_FINEST_TEXT STRING OPTIONS(description="Hamacher Finest Class Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYFINEST_YTMM_FINEST_TEXT;