CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.HAMACHER_FINER_CLASS_CV`
(
  YYFINER_YTMM_FINER_TEXT STRING OPTIONS(description="Hamacher Finer Class ID; YTMM_FINER_TEXT.YYFINER where YTMM_FINER_TEXT.SPRAS = E"),
  YYDESC_YTMM_FINER_TEXT STRING OPTIONS(description="Hamacher Finer Class Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYFINER_YTMM_FINER_TEXT;