CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_CV`
(
  MATNR_MARA STRING OPTIONS(description="Material Number"),
  VRSN_START_DTE DATE OPTIONS(description="Start Date: Version Start Date; Inserts: CURRENT_DATE, Updates: No Change"),
  VRSN_END_DTE DATE OPTIONS(description="End Date: Version End Date; Inserts: 9999-12-31, Updates: CURRENT_DATE - 1 DAY"),
  CURR_VRSN_FLG STRING OPTIONS(description="Current Version Flag; MATERIAL_SCD_CV.CURR_VRSN_FLG"),
  MAKTX_MAKT STRING OPTIONS(description="Material Description Text"),
  CALC_ERSDA_MARA DATE OPTIONS(description="Created On Date; If MARA.ERSDA is a valid date Then Convert MARA.ERSDA to ISO Date Else 1900-01-01"),
  ERNAM_MARA STRING OPTIONS(description="Created by User ID"),
  LAST_CHG_DTE DATE OPTIONS(description="Last Change Date; If MARA.LAEDA is a valid date Then Convert MARA.LAEDA to ISO Date Else 1900-01-01"),
  AENAM_MARA STRING OPTIONS(description="Changed by User ID"),
  LVORM_MARA STRING OPTIONS(description="Calculated Deletion Indicator Flag; If MARA.LVORM = X, then Y else N"),
  MTART_MARA STRING OPTIONS(description="Material Type Lookup ID"),
  MTBEZ_T134T_MATERIAL_TYPE STRING OPTIONS(description="Material Type Description Text; MATERIAL_TYPE.MTBEZ_T134T where MTART_MARA = MATERIAL_TYPE.MTART_T134T"),
  MBRSH_MARA STRING OPTIONS(description="Industry Sector Lookup ID"),
  MBBEZ_T137T_INDUSTRY_SECTOR STRING OPTIONS(description="Industry Sector Description Text; INDUSTRY_SECTOR.MBBEZ_T137T where INDUSTRY_SECTOR.MBRSH_T137T = MBRSH_MARA"),
  MATKL_MARA STRING OPTIONS(description="Material Group Lookup ID"),
  WGBEZ_T023T_MATERIAL_GROUP STRING OPTIONS(description="Material Group Description Text; MATERIAL_GROUP.WGBEZ_T023T where Material_GROUP.MATKL_T023T = MATKL_MARA"),
  MEINS_MARA STRING OPTIONS(description="Base UOM Lookup ID"),
  BASE_MSEHL_T006A_UNIT_OF_MEASURE STRING OPTIONS(description="Base UOM Description Text; UNIT_OF_MEASURE.MSEHL_T006A where UNIT_OF_MEASURE.MSEHI_T006A = MEINS_MARA"),
  BSTME_MARA STRING OPTIONS(description="Purchase Order UOM Lookup ID"),
  PURCH_ORDER_MSEHL_T006A_UNIT_OF_MEASURE STRING OPTIONS(description="Purchase Order UOM Description Text; UNIT_OF_MEASURE.MSEHL_T006A where UNIT_OF_MEASURE.MSEHI_T006A = BSTME_MARA"),
  GROES_MARA STRING OPTIONS(description="Size dimensions Text"),
  BRGEW_MARA NUMERIC OPTIONS(description="Gross Weight Number"),
  NTGEW_MARA NUMERIC OPTIONS(description="Net Weight Number"),
  GEWEI_MARA STRING OPTIONS(description="Weight UOM Lookup ID"),
  WEIGHT_MSEHL_T006A_UNIT_OF_MEASURE STRING OPTIONS(description="Weight UOM Description Text; UNIT_OF_MEASURE.MSEHL_T006A where UNIT_OF_MEASURE.MSEHI_T006A = GEWEI_MARA"),
  VOLUM_MARA NUMERIC OPTIONS(description="Volume Number"),
  VOLEH_MARA STRING OPTIONS(description="Volume UOM Lookup ID"),
  VOLUME_MSEHL_T006A_UNIT_OF_MEASURE STRING OPTIONS(description="Volume UOM Description Text; UNIT_OF_MEASURE.MSEHL_T006A where UNIT_OF_MEASURE.MSEHI_T006A = VOLEH_MARA"),
  RAUBE_MARA STRING OPTIONS(description="Storage conditions Code"),
  RBTXT_T142T_STORAGE_CONDITION STRING OPTIONS(description="Storage conditions Description Text; STORAGE_CONDITION.RBTXT_T142T where STORAGE_CONDITION.RAUBE_T142T = RAUBE_MARA"),
  TEMPB_MARA STRING OPTIONS(description="Temperature condition Code"),
  TBTXT_T143T_TEMPERATURE_CONDITION STRING OPTIONS(description="Temperature condition Description Text; TEMPERATURE_CONDITION.TBTXT_T143T where TEMPERATURE_CONDITION.TEMPB_T143T = TEMPB_MARA"),
  CALC_REFRIG_FLG STRING OPTIONS(description="Calculated Refrigeration Flag; If MARA.TEMPB in (01, 02, 03, 04, 05, 06, 07, 08, 09) then Y else N"),
  DISST_MARA STRING OPTIONS(description="Low Level Code Text"),
  TRAGR_MARA STRING OPTIONS(description="Transportation Group Code"),
  VTEXT_TTGRT_TRANSPORTATION_GROUP STRING OPTIONS(description="Transportation Group Description Text; TRANSPORTATION_GROUP.VTEXT_TTGRT where TRANSPORTATION_GROUP.TRAGR_TTGRT = TRAGR_MARA"),
  SPART_MARA STRING OPTIONS(description="Division ID"),
  CALC_NDC_ID STRING OPTIONS(description="Calculated NDC ID; MATERIAL_SCD_CV.EAN11_MEAN_1"),
  CALC_NDC_CTGRY_ID STRING OPTIONS(description="Calculated NDC Category ID; IFNULL(MEAN.EANTP, N/A) where EANTP in (N1, N2, N3, N4, N5) and MARA.MEINS = MEAN.MEINH and MARA.MATNR = MEAN.MATNR"),
  CALC_EACH_UPC_ID STRING OPTIONS(description="Calculated Each UPC ID; IFNULL(MEAN.EAN11, N/A) where EANTP in (UC, UX) and MEAN.MEINH = EA and MARA.MATNR = MEAN.MATNR"),
  CALC_EACH_UPC_CTGRY_ID STRING OPTIONS(description="Calculated Each UPC Category ID; IFNULL(MEAN.EANTP, N/A) where EANTP in (UC, UX) and MEAN.MEINH = EA and MARA.MATNR = MEAN.MATNR"),
  CALC_CSE_UPC_ID STRING OPTIONS(description="Calculated Case UPC ID; IFNULL(MEAN.EAN11, N/A) where EANTP in (UC, UX) and MEAN.MEINH = CS and MARA.MATNR = MEAN.MATNR"),
  CALC_CSE_UPC_CTGRY_ID STRING OPTIONS(description="Calculated Case UPC Category ID; IFNULL(MEAN.EANTP, N/A) where EANTP in (UC, UX) and MEAN.MEINH = CS and MARA.MATNR = MEAN.MATNR"),
  CALC_CTN_UPC_ID STRING OPTIONS(description="Calculated Carton UPC ID; IFNULL(MEAN.EAN11, N/A) where EANTP in (UC, UX) and MEAN.MEINH = KAR and MARA.MATNR = MEAN.MATNR"),
  CALC_CTN_UPC_CTGRY_ID STRING OPTIONS(description="Calculated Carton UPC Category ID; IFNULL(MEAN.EANTP, N/A) where EANTP in (UC, UX) and MEAN.MEINH = KAR and MARA.MATNR = MEAN.MATNR"),
  CALC_EACH_EAN_ID STRING OPTIONS(description="Calculated Each EAN ID; IFNULL(MEAN.EAN11, N/A) where EANTP = HE and MEAN.MEINH = EA and MARA.MATNR = MEAN.MATNR"),
  CALC_CSE_EAN_ID STRING OPTIONS(description="Calculated Case EAN ID; IFNULL(MEAN.EAN11, N/A) where EANTP = HE and MEAN.MEINH = CS and MARA.MATNR = MEAN.MATNR"),
  CALC_CTN_EAN_ID STRING OPTIONS(description="Calculated Carton EAN ID; IFNULL(MEAN.EAN11, N/A) where EANTP = HE and MEAN.MEINH = KAR and MARA.MATNR = MEAN.MATNR"),
  CALC_EACH_GTIN_ID STRING OPTIONS(description="Calculated Each GTIN ID; IFNULL(MEAN.EAN11, N/A) where EANTP = IC and MEAN.MEINH = EA and MARA.MATNR = MEAN.MATNR"),
  CALC_CSE_GTIN_ID STRING OPTIONS(description="Calculated Case GTIN ID; IFNULL(MEAN.EAN11, N/A) where EANTP = IC and MEAN.MEINH = CS and MARA.MATNR = MEAN.MATNR"),
  CALC_CTN_GTIN_ID STRING OPTIONS(description="Calculated Carton GTIN ID; IFNULL(MEAN.EAN11, N/A) where EANTP = IC and MEAN.MEINH = KAR and MARA.MATNR = MEAN.MATNR"),
  LAENG_MARA NUMERIC OPTIONS(description="Length Number"),
  BREIT_MARA NUMERIC OPTIONS(description="Width Number"),
  HOEHE_MARA NUMERIC OPTIONS(description="Height Number"),
  MEABM_MARA STRING OPTIONS(description="Dimension UOM Lookup ID"),
  DIM_MSEHL_T006A_UNIT_OF_MEASURE STRING OPTIONS(description="Dimension UOM Description Text; UNIT_OF_MEASURE.MSEHL_T006A where UNIT_OF_MEASURE.MSEHI_T006A = MEABM_MARA"),
  PRDHA_MARA STRING OPTIONS(description="Product hierarchy Lookup ID"),
  VTEXT_T179T_PRODUCT_HIERARCHY STRING OPTIONS(description="Product Hierarchy Description Text; PRODUCT_HIERARCHY.VTEXT_T179T where PRODUCT_HIERARCHY.PRODH_T179 = PRDHA_MARA"),
  VABME_MARA STRING OPTIONS(description="Variable Purchase Order Unit Activity Lookup ID"),
  VRBL_PURCH_ORDER_UNIT_ACT_DESC_TXT STRING OPTIONS(description="Variable Purchase Order Unit Activity Description Text; VARIABLE_PO_UNIT_ACTIVITY.Variable_Purchase_Order_Unit_Activity_Description_Text where VARIABLE_PO_UNIT_ACTIVITY.Variable_Purchase_Order_Unit_Activity_ID = MARA.VABME"),
  VHART_MARA STRING OPTIONS(description="Packaging material type Lookup ID"),
  VTEXT_TVTYT_PACKAGING_MATERIAL_TYPE STRING OPTIONS(description="Packaging Material Type Description Text; PACKAGING_MATERIAL_TYPE.VTEXT_TVTYT where PACKAGING_MATERIAL_TYPE.TRATY_TVTYT = VHART_MARA"),
  MAGRV_MARA STRING OPTIONS(description="Material Group Packaging Materials Lookup ID"),
  BEZEI_TVEGRT_MTRL_GRP_PACKAGING_MATERIALS STRING OPTIONS(description="Material Group Packaging Materials Description Text; MTRL_GRP_PACKAGING_MATERIALS.BEZEI_TVEGRT where MTRL_GRP_PACKAGING_MATERIALS.MAGRV_TVEGRT  = MAGRV_MARA"),
  EXTWG_MARA STRING OPTIONS(description="Ext Material Group ID"),
  MSTAE_MARA STRING OPTIONS(description="Cross Plant Material Status Lookup ID"),
  MTSTB_T141T_CROSS_PLANT_MATERIAL_STATUS STRING OPTIONS(description="Cross Plant Material Status Description Text; CROSS_PLANT_MATERIAL_STATUS.MTSTB_T141T where CROSS_PLANT_MATERIAL_STATUS.MMSTA_T141T = MSTAE_MARA"),
  MSTAV_MARA STRING OPTIONS(description="Cross Distribution Chain Material Status Lookup ID"),
  VMSTB_TVMST_CROSS_DISTRIB_CHAIN_MTRL_STATUS STRING OPTIONS(description="Cross Distribution Chain Material Status Description Text; CROSS_DISTRIB_CHAIN_MTRL_STATUS.VMSTB_TVMST where CROSS_DISTRIB_CHAIN_MTRL_STATUS.VMSTA_TVMST = MSTAV_MARA"),
  MSTDE_MARA DATE OPTIONS(description="Cross Plant Material Status Valid from Date"),
  MSTDV_MARA DATE OPTIONS(description="Cross Distribution Chain Status Valid from Date"),
  MHDRZ_MARA INT64 OPTIONS(description="Minimum Remaining Shelf Life Number"),
  KZUMW_MARA STRING OPTIONS(description="Environmentally Relevant Flag; If MARA.KZUMW = X then Y else N"),
  KOSCH_MARA STRING OPTIONS(description="Product Allocation Lookup ID"),
  VTEXT_T190ST_PRODUCT_ALLOCATION STRING OPTIONS(description="Product Allocation Description Text; PRODUCT_ALLOCATION.VTEXT_T190ST where PRODUCT_ALLOCATION.KOSCH_T190ST = KOSCH_MARA"),
  MFRPN_MARA STRING OPTIONS(description="Manufacturer Part ID"),
  MFRNR_MARA STRING OPTIONS(description="Manufacturer Number"),
  PROFL_MARA STRING OPTIONS(description="Dangerous Good indicator profile Lookup ID"),
  PROFLD_TDG42_DANGEROUS_GOODS_INDICATOR STRING OPTIONS(description="Dangerous Goods Indicator Profile Description Text; DANGEROUS_GOODS_INDICATOR.PROFLD_TDG42 where DANGEROUS_GOODS_INDICATOR.PROFL_TDG42 = PROFL_MARA"),
  MTPOS_MARA_MARA STRING OPTIONS(description="Item Category Group Lookup ID"),
  BEZEI_TPTMT_ITEM_ITEM_CATEGORY_GROUP STRING OPTIONS(description="Item Category Group Description Text; ITEM_CATEGORY_GROUP.BEZEI_TPTMT where ITEM_CATEGORY_GROUP.MTPOS_TPTMT = MTPOS_MARA_MARA"),
  SLED_BBD_MARA STRING OPTIONS(description="Expiration Date Indicator ID"),
  EXP_DTE_IND_DESC_TXT STRING OPTIONS(description="Expiration Date Indicator Description Text; Expiration_Date_Indicator.Expiration_Date_Indicator_Description_Text where Expiration_Date_Indicator.Expiration_Date_Indicator_ID = MARA.SLED_BBD"),
  CALC_GEN_OTC_FLG STRING OPTIONS(description="Calculated Generic OTC Flag; MATERIAL_SCD_CV.CALC_GENERIC_OTC_FLAG"),
  CALC_RX_FLG STRING OPTIONS(description="Calculated RX Flag; If MATERIAL_SCD_CV.ALNUM_MAEX_RX_IND = 'RX' then Y else N"),
  CALC_DEA_SCHED_ID STRING OPTIONS(description="Calculated DEA Schedule ID; MATERIAL_SCD_CV.ALNUM_MAEX"),
  BEZEI_T606V_LEGAL_CONTROL STRING OPTIONS(description="DEA Schedule Number Description Text; Legal_Control.BEZEI_T606V where Calculated_DEA_Schedule_ID = Legal_Control.ALNUM_T606V and Legal_Control.GEGRU_T606V = FD --Federal DEA reg"),
  YYBASE_MARA STRING OPTIONS(description="DEA Base Code Lookup ID"),
  YYDESC_YTMM_DEA_TEXT_DEA_BASE_CODE STRING OPTIONS(description="DEA Base Code Description Text; DEA_BASE_CODE.YYDESC_YTMM_DEA_TEXT where DEA_BASE_CODE.YYBASE_YTMM_DEA_TEXT = YYBASE_MARA"),
  YYSUBB_MARA STRING OPTIONS(description="DEA Sub Base Code Lookup ID"),
  YYDESC_YTMM_SUBBASETEXT_DEA_SUB_BASE_CODE STRING OPTIONS(description="DEA Sub Base Code Description Text; DEA_SUB_BASE_CODE.YYDESC_YTMM_SUBBASETEXT where DEA_SUB_BASE_CODE.YYSUBB_YTMM_SUBBASETEXT = YYSUBB_MARA"),
  YYLDESC_MARA STRING OPTIONS(description="Long Material Description Text"),
  YYAHFS_MARA STRING OPTIONS(description="AHFS Lookup ID"),
  YYDESC_YTMM_AHFS_TEXT_AHFS_CODE STRING OPTIONS(description="AHFS Description Text; AHFS_CODE.YYDESC_YTMM_AHFS_TEXT where AHFS_CODE.YYAHFS_YTMM_AHFS_TEXT = YYAHFS_MARA"),
  YYLSTO_MARA STRING OPTIONS(description="List 1 Chemical Lookup ID"),
  YYDESC_YTMM_LIST1_TEXT_LIST_1_CHEMICAL STRING OPTIONS(description="List 1 Chemical Description Text; LIST_1_CHEMICAL.YYDESC_YTMM_LIST1_TEXT where LIST_1_CHEMICAL.YYLSTO_YTMM_LIST1_TEXT = YYLSTO_MARA"),
  YYFORM_MARA STRING OPTIONS(description="Form Lookup ID"),
  YYDESC_YTMM_FORM_TEXT_FORM STRING OPTIONS(description="Form Description Text; FORM.YYDESC_YTMM_FORM_TEXT where FORM.YYFORM_YTMM_FORM_TEXT = YYFORM_MARA"),
  YYCGCN_MARA STRING OPTIONS(description="Generic Code Number"),
  YYGENN_MARA STRING OPTIONS(description="Generic Name Text"),
  YYSTRN_MARA STRING OPTIONS(description="Strength Text"),
  YYPCKG_MARA STRING OPTIONS(description="Packaging Indicator Lookup ID"),
  YYDESC_YTMM_PACK_TEXT_PACKAGING_INDICATOR STRING OPTIONS(description="Packaging Indicator Description Text; PACKAGING_INDICATOR.YYDESC_YTMM_PACK_TEXT where PACKAGING_INDICATOR.YYPCKG_YTMM_PACK_TEXT = YYPCKG_MARA"),
  UNIT_DOSE_FLG STRING OPTIONS(description="Unit Dose Flag; If MARA.YYPCKG = UD then Y else N"),
  YYSUPNR_MARA STRING OPTIONS(description="Supplier Number"),
  NAME1_LFA1 STRING OPTIONS(description="Supplier Name; NAME1_LFA1 where SUPPLIER_CV.LIFNR_LFA1 =  MATERIAL_CV.YYSUPNR_MARA"),
  YYHAZSC_MARA STRING OPTIONS(description="Hazmat Storage Lookup ID"),
  YYDESC_YTMM_HAZMAT_TEXT_HAZMAT_STORAGE STRING OPTIONS(description="Hazmat Storage Description Text; HAZMAT_STORAGE.YYDESC_YTMM_HAZMAT_TEXT where HAZMAT_STORAGE.YYHAZSC_YTMM_HAZMAT_TEXT = YYHAZSC_MARA"),
  YYSPHD_MARA STRING OPTIONS(description="Special Handling Lookup ID"),
  YYDESC_YTMM_SPECL_TEXT_SPECIAL_HANDLING STRING OPTIONS(description="Special Handling Description Text; SPECIAL_HANDLING.YYDESC_YTMM_SPECL_TEXT where SPECIAL_HANDLING.YYSPHD_YTMM_SPECL_TEXT = YYSPHD_MARA"),
  YYINJECT_MARA STRING OPTIONS(description="Injectable Flag"),
  YYFINE_MARA STRING OPTIONS(description="Hamacher Fine Class Lookup ID"),
  YYDESC_YTMM_FINE_TEXT_HAMACHER_FINE_CLASS STRING OPTIONS(description="Hamacher Fine Class Description Text; HAMACHER_FINE_CLASS.YYDESC_YTMM_FINE_TEXT where HAMACHER_FINE_CLASS.YYFINE_YTMM_FINE_TEXT = YYFINE_MARA"),
  YYFINER_MARA STRING OPTIONS(description="Hamacher Finer Class Code Lookup ID"),
  YYDESC_YTMM_FINER_TEXT_HAMACHER_FINER_CLASS STRING OPTIONS(description="Hamacher Finer Class Description Text; HAMACHER_FINER_CLASS.YYDESC_YTMM_FINER_TEXT where HAMACHER_FINER_CLASS.YYFINER_YTMM_FINER_TEXT = YYFINER_MARA"),
  YYFINEST_MARA STRING OPTIONS(description="Hamacher Finest Class Lookup ID"),
  YYDESC_YTMM_FINEST_TEXT_HAMACHER_FINEST_CLASS STRING OPTIONS(description="Hamacher Finest Class Description Text; HAMACHER_FINEST_CLASS.YYDESC_YTMM_FINEST_TEXT where HAMACHER_FINEST_CLASS.YYFINEST_YTMM_FINEST_TEXT = YYFINES_MARA"),
  YYFLASH_MARA STRING OPTIONS(description="Flash Point Text"),
  YYTNAM_MARA STRING OPTIONS(description="Technical Name Text"),
  YYCASN1_MARA STRING OPTIONS(description="CAS 1 Number"),
  YYCASP1_MARA NUMERIC OPTIONS(description="CAS 1 Percentage"),
  YYCASN2_MARA STRING OPTIONS(description="CAS 2 Number"),
  YYCASP2_MARA NUMERIC OPTIONS(description="CAS 2 Percentage"),
  YYCASN3_MARA STRING OPTIONS(description="CAS 3 Number"),
  YYCASP3_MARA NUMERIC OPTIONS(description="CAS 3 Percentage"),
  YYCASN4_MARA STRING OPTIONS(description="CAS 4 Number"),
  YYCASP4_MARA NUMERIC OPTIONS(description="CAS 4 Percentage"),
  YYCASN5_MARA STRING OPTIONS(description="CAS 5 Number"),
  YYCASP5_MARA NUMERIC OPTIONS(description="CAS 5 Percentage"),
  YYCASN6_MARA STRING OPTIONS(description="CAS 6 Number"),
  YYCASP6_MARA NUMERIC OPTIONS(description="CAS 6 Percentage"),
  YYDOTSP_MARA STRING OPTIONS(description="DOT Special Permit Text"),
  YYCMPTN_MARA STRING OPTIONS(description="Compare To Text"),
  YYHAZKEY_MARA INT64 OPTIONS(description="Hazmat Key Number"),
  YYGCNSQN_MARA STRING OPTIONS(description="GCN Sequence Number"),
  YYBOXSTYLE_MARA STRING OPTIONS(description="Box Style ID"),
  YYCHG3P_MARA INT64 OPTIONS(description="Third Party Data Change Num"),
  YYLOGGR_MARA STRING OPTIONS(description="Material Putaway ID"),
  YYPACREF_MARA STRING OPTIONS(description="Package Reference Guide Lookup ID"),
  YYDESC_YTMM_PACREF_TEXT_PACKAGE_REFERENCE STRING OPTIONS(description="Package Reference Guide Description Text; PACKAGE_REFERENCE.YYDESC_YTMM_PACREF_TEXT where PACKAGE_REFERENCE.YYPACREF_YTMM_PACREF_TEXT = YYPACREF_MARA"),
  YYFORMFAM_MARA STRING OPTIONS(description="Form Family ID"),
  YYNDCFDB_MARA INT64 OPTIONS(description="FDB NDC Code"),
  YYJCODEFDB_MARA STRING OPTIONS(description="FDB J Code"),
  YYJCODECAH_MARA STRING OPTIONS(description="CAH J Code"),
  YYHCPCFDB_MARA STRING OPTIONS(description="FDB HCPC Code"),
  YYHCPCCAH_MARA STRING OPTIONS(description="CAH HCPC Code"),
  YYHCPCDESC_MARA STRING OPTIONS(description="HCPC Description Text"),
  YYHCPCDOSVAL_MARA NUMERIC OPTIONS(description="HCPC Dosage Value Number"),
  YYHCPCDOSUOM_MARA STRING OPTIONS(description="HCPC Dosage UOM ID"),
  YYPAYLIMFDB_MARA NUMERIC OPTIONS(description="FDB Payment Limit Amount"),
  YYSTNGSP_MARA NUMERIC OPTIONS(description="Specialty Strength Value Number"),
  YYSTNGUOMSP_MARA STRING OPTIONS(description="Specialty Strength UOM ID"),
  YYVOLSP_MARA NUMERIC OPTIONS(description="Specialty Volume Value Number"),
  YYVOLUOMSP_MARA STRING OPTIONS(description="Specialty Volume UOM ID"),
  YYCONCNUM_MARA NUMERIC OPTIONS(description="Specialty Concentration Numerator Value Number"),
  YYCONCNUMUOM_MARA STRING OPTIONS(description="Specialty Concentration Numerator UOM ID"),
  YYCONCDEN_MARA NUMERIC OPTIONS(description="Specialty Concentration Denominator Value Number"),
  YYCONCDENUOM_MARA STRING OPTIONS(description="Specialty Concentration Denominator UOM ID"),
  YYBILLVLSP_MARA NUMERIC OPTIONS(description="Specialty Bill Units Vial Number"),
  YYBILLPKSP_MARA NUMERIC OPTIONS(description="Specialty Bill Units Package Number"),
  YYTAIDISP_MARA NUMERIC OPTIONS(description="Specialty Total Active Ingredient Disp Number"),
  YYTAIPRCH_MARA NUMERIC OPTIONS(description="Specialty Total Active Ingredient Purchase Number"),
  YYTAIUOM_MARA STRING OPTIONS(description="Specialty Total Active Ingredient UOM ID"),
  YYSTKRQTY_MARA INT64 OPTIONS(description="Sticker Quantity"),
  YYTRADNAME_MARA STRING OPTIONS(description="Trade Name"),
  YYCONKEY_MARA INT64 OPTIONS(description="Consumer Key Number"),
  YYSRCSKEY_MARA STRING OPTIONS(description="Sourcing Sub Key ID"),
  YYGCNSQNC_MARA STRING OPTIONS(description="Cardinal GCN Sequence Number"),
  YYAHFSC_MARA STRING OPTIONS(description="Cardinal AHFS Code"),
  CARD_AHFS_CDE_DESC_TXT STRING OPTIONS(description="Cardinal AHFS Code Description Text; YTMM_AHFS_TEXT.YYDESC based on MARA.YYSHFSC"),
  YYOBRAT_MARA STRING OPTIONS(description="FDB OBC Lookup ID"),
  FDB_YYDESC_YTMM_OBRAT_TEXT_ORANGE_BOOK_CODE STRING OPTIONS(description="FDB OBC Description Text; ORANGE_BOOK_CODE.YYDESC_YTMM_OBRAT_TEXT where ORANGE_BOOK_CODE.YYOBRAT_YTMM_OBRAT_TEXT = YYOBRAT_MARA"),
  YYPKGKEY_MARA STRING OPTIONS(description="Packaging Key ID"),
  YYPKGKEYC_MARA STRING OPTIONS(description="CAH Packaging Key ID"),
  YYREMSP_MARA STRING OPTIONS(description="REMS Program Lookup ID"),
  YYDESC_YTMM_REMS_PROG_T_REMS_PROGRAM STRING OPTIONS(description="REMS Program Description Text; REMS_PROGRAM.YYDESC_YTMM_REMS_PROG_T where REMS_PROGRAM.YYREMSP_YTMM_REMS_PROG_T = YYREMSP_MARA"),
  YYPKSZE_MARA NUMERIC OPTIONS(description="Pack Size Number"),
  CALC_PACK_QTY INT64 OPTIONS(description="Calculated Pack Quantity; SAFE_CAST(MATERIAL_SCD_CV.CALC_PACKQTYUOMDENOMINATOR AS INT64 ) /SAFE_CAST(MATERIAL_SCD_CV.CALC_PACKQTYUOMNUMERATOR AS INT64)"),
  CALC_ACCUNET_QTY NUMERIC OPTIONS(description="Calculated Accunet Quantity; MARA.YYPKSZE * (MARM.UMREN/MARM.UMREZ where MEINH = PQ)"),
  YYMLTSRCF_MARA STRING OPTIONS(description="FDB Multi Source Indicator ID"),
  YYAWPM_MARA NUMERIC OPTIONS(description="Medispan AWP Amount"),
  YYUOMM_MARA STRING OPTIONS(description="Medispan UOM ID"),
  YYPRIU_MARA STRING OPTIONS(description="Pricing Usage Lookup ID"),
  YYDESC_YTMM_PRIU_T_PRICING_USAGE STRING OPTIONS(description="Pricing Usage Description Text; PRICING_USAGE.YYDESC_YTMM_PRIU_T where PRICING_USAGE.YYPRIU_YTMM_PRIU_T = YYPRIU_MARA"),
  YYEDESC_MARA STRING OPTIONS(description="Expanded Material Description Text"),
  YYOBRATC_MARA STRING OPTIONS(description="Cardinal OBC Lookup ID"),
  CARD_YYDESC_YTMM_OBRAT_TEXT_ORANGE_BOOK_CODE STRING OPTIONS(description="Cardinal OBC Description Text; ORANGE_BOOK_CODE.YYDESC_YTMM_OBRAT_TEXT where ORANGE_BOOK_CODE.YYOBRAT_YTMM_OBRAT_TEXT = YYOBRATC_MARA"),
  YYREQG_MARA INT64 OPTIONS(description="Request Group Code ID"),
  YYMANOVR_MARA STRING OPTIONS(description="Manual Override Flag; If MARA.YYMANOVR = X then Y else N"),
  YYOVRREA_MARA STRING OPTIONS(description="Override Reason Text"),
  ZZTAXD_MARA STRING OPTIONS(description="Sales Tax Driver Lookup ID"),
  DESCRIPTION_ZMT_PTS_TAX_DRVR_SALES_TAX_DRIVER STRING OPTIONS(description="Sales Tax Driver Description Text; SALES_TAX_DRIVER.DESCRIPTION_ZMT_PTS_TAX_DRVR where SALES_TAX_DRIVER.ZZMTAXD_ZMT_PTS_TAX_DRVR = ZZTAXD_MARA"),
  ZZCALPROP65_MARA STRING OPTIONS(description="California Proposition 65 ID"),
  YYOPIOID_MARA STRING OPTIONS(description="Opiod Flag; If MARA.YYOPIOID = X then Y else N"),
  YYDEANAME_MARA STRING OPTIONS(description="DEA Name Text"),
  YYNIOSH_MARA STRING OPTIONS(description="NIOSH Key ID"),
  CALC_CARD_SBST_KEY_ID STRING OPTIONS(description="Calculated Cardinal Substitution Key ID; MATERIAL_SCD_CV.CALC_CARDINALKEY"),
  CALC_CSE_QTY INT64 OPTIONS(description="Calculated Case Quantity; SAFE_CAST(MAT.CALC_CASEUOMNUMERATOR AS INT64 ) /SAFE_CAST(MAT.CALC_CASEUOMDENOMINATOR AS INT64)"),
  CALC_DOSE_QTY INT64 OPTIONS(description="Calculated Dose Quantity; SAFE_CAST(MAT.CALC_DOSEUOMDENOMINATOR AS INT64 ) /SAFE_CAST(MAT.CALC_DOSEUOMNUMERATOR AS INT64)"),
  CALC_CTN_QTY INT64 OPTIONS(description="Calculated Carton Quantity; CASE MARA.MEINS, WHEN KAR /* ISO definition in BQ */ THEN 1, WHEN EA THEN UMREZ/UMREN, WHEN CS THEN UMREN/UMREZ ELSE -1 END where MEINH = KAR rounded to the nearest integer /* All ISO values will be converted back to SAP Display values in reports */"),
  CALC_EACH_QTY INT64 OPTIONS(description="Calculated Each Quantity; MARM.UMREN/MARM.UMREZ where MEINH = EA rounded to nearest integer"),
  CALC_RMBMT_UOM_CDE STRING OPTIONS(description="Calculated Reimbursement UOM Code; Either UNI or ML or GM from MARM.MEINH. The record must exist; "),
  CALC_RMBMT_UOM_TXT STRING OPTIONS(description="Calculated Reimbursement UOM Text; T006A.MSEHL where (Either UNI or ML or GM from MARM.MEINH) = T006.MSEHI. The MARM record must exist"),
  CALC_RMBMT_UOM_QTY INT64 OPTIONS(description="Calculated Reimbursement UOM Quantity; MARM.UMREN/MARM.UMREZ where MEINH in UNI, ML, GM rounded to nearest integer"),
  CALC_SHAPE STRING OPTIONS(description="Shape Text; MATERIAL_SCD_CV.CALC_SHAPE"),
  CALC_COLOR STRING OPTIONS(description="Color Text; MATERIAL_SCD_CV.CALC_COLOR"),
  CALC_FLAVOR STRING OPTIONS(description="Flavor Text; FDB_MASTER_CV.FLAVOR_TXT ON MAT.CALC_NDC_ID = FDBF.NDC"),
  DRUG_GROUP_ID_MEDISPAN_PROD STRING OPTIONS(description="Medispan Drug Group ID; MATERIAL_SCD_CV.DRUG_GROUP_ID_MEDISPAN_PROD"),
  DRUG_GROUP_DESC_MEDISPAN STRING OPTIONS(description="Medispan Drug Group Description Text; MATERIAL_SCD_CV.DRUG_GROUP_DESC_MEDISPAN"),
  DRUG_CLASS_ID_MEDISPAN_PROD STRING OPTIONS(description="Medispan Drug Class ID; MATERIAL_SCD_CV.DRUG_CLASS_ID_MEDISPAN_PROD"),
  DRUG_CLASS_DESC_MEDISPAN STRING OPTIONS(description="Medispan Drug Class Description Text; MATERIAL_SCD_CV.DRUG_CLASS_DESC_MEDISPAN"),
  DRUG_SUBCLS_ID_MEDISPAN_PROD STRING OPTIONS(description="Medispan Drug Subclass ID; MATERIAL_SCD_CV.DRUG_SUBCLS_ID_MEDISPAN_PROD"),
  DRUG_SUBCLASS_DESC_MEDISPAN STRING OPTIONS(description="Medispan Drug Subclass Description Text; MATERIAL_SCD_CV.DRUG_SUBCLASS_DESC_MEDISPAN"),
  GEN_PROD_ID_ARCH_MEDISPAN STRING OPTIONS(description="Medispan Generic Product ID; MATERIAL_SCD_CV.GEN_PROD_ID_ARCH_MEDISPAN"),
  TEE_ID_ARCH_MEDISPAN STRING OPTIONS(description="Medispan Therapeutic Equivalent ID; MATERIAL_SCD_CV.TEE_ID_ARCH_MEDISPAN"),
  YYBUNIT_MARA STRING OPTIONS(description="Billing UOM ID"),
  BILL_UNIT_MSEHL_T006A_UNIT_OF_MEASURE STRING OPTIONS(description="Billing UOM Description; UNIT_OF_MEASURE.MSEHL_T006A where UNIT_OF_MEASURE.MSEHI_T006A = YYBUNIT_MARA"),
  BILL_UNIT_MSEHT_T006A_UNIT_OF_MEASURE STRING OPTIONS(description="Billing UOM Short Description; UNIT_OF_MEASURE.MSEHT_T006A where UNIT_OF_MEASURE.MSEHI_T006A = YYBUNIT_MARA"),
  CALC_DSCSA_EXEMPT_ID STRING OPTIONS(description="Calculated DSCSA Exempt ID; AUSP.ATWRT where AUSP.ATINN = 0000000037 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_FOOD_FLG STRING OPTIONS(description="Calculated Food Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000038 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_EXP_DTE_FLG STRING OPTIONS(description="Calculated Expiration Date Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000039 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_VETERINARY_ID STRING OPTIONS(description="Calculated Veterinary ID; AUSP.ATWRT where AUSP.ATINN = 0000000040 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_CONTAINS_BPA_ID STRING OPTIONS(description="Calculated Contains BPA ID; AUSP.ATWRT where AUSP.ATINN = 0000000041 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_CONTAINS_DEHP_ID STRING OPTIONS(description="Calculated Contains DEHP ID; AUSP.ATWRT where AUSP.ATINN = 0000000042 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_EPA_REGISTERED_ID STRING OPTIONS(description="Calculated EPA Registered ID; AUSP.ATWRT where AUSP.ATINN = 0000000043 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_ETO_STERILIZED_ID STRING OPTIONS(description="Calculated ETO Sterilized ID; AUSP.ATWRT where AUSP.ATINN = 0000000044 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_DIR_SRC_FLG STRING OPTIONS(description="Calculated Direct Source Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000045 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_SERIAL_FLG STRING OPTIONS(description="Calculated Serialized Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000046 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_MED_FOOD_FLG STRING OPTIONS(description="Calculated Medical Food Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000047 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_KIT_WITH_DRUG_FLG STRING OPTIONS(description="Calculated Kit With Drug Flag; AUSP.ATWRT where AUSP.ATINN = 0000000048 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Clas"),
  CALC_CA_PRPS_65_ID STRING OPTIONS(description="Calculated California Proposition 65 ID; AUSP.ATWRT where AUSP.ATINN = 0000000049 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_PLASMA_ID STRING OPTIONS(description="Calculated Plasma ID; AUSP.ATWRT where AUSP.ATINN = 0000000055 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_TRADE_PRTNR_TYPE_ID STRING OPTIONS(description="Calculated Trading Partner Type ID; AUSP.ATWRT where AUSP.ATINN = 0000000056 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_NY_LAW_CDE_ID STRING OPTIONS(description="Calculated NY Law Code ID; AUSP.ATWRT where AUSP.ATINN = 0000000059 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_ADDL_MFG_INFO_FLG STRING OPTIONS(description="Calculated Additional Manufacturer Info Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000064 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_BONUS_PACK_MTRL_NUM STRING OPTIONS(description="Calculated Bonus Pack Material Number; AUSP.ATWRT where AUSP.ATINN = 0000000065 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_PURCH_BLCK_REVIEW_NEED_FLG STRING OPTIONS(description="Calculated Purchase Block Review Needed Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000066 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_STICKERS_ONLY_FLG STRING OPTIONS(description="Calculated Stickers Only Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000067 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_BRAND_GEN_EXCP_ID STRING OPTIONS(description="Calculated Brand Generic Exception ID; AUSP.ATWRT where AUSP.ATINN = 0000000068 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_DEMAND_FORECASTING_ALRG_FLG STRING OPTIONS(description="Calculated Demand Forecasting Allergy Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000069 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_DEMAND_FORECASTING_COUGH_COLD_FLG STRING OPTIONS(description="Calculated Demand Forecasting Cough Cold Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000070 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_FLU_ID STRING OPTIONS(description="Calculated Flu ID; AUSP.ATWRT where AUSP.ATINN = 0000000071 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class;"),
  CALC_MEDSURG_FLG STRING OPTIONS(description="Calculated Medsurg Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000074 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_MEDSURG_ID STRING OPTIONS(description="Calculated Medsurg ID;  AUSP.ATWRT where AUSP.ATINN = 0000000074 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_COVID_ID STRING OPTIONS(description="Calculated COVID ID; AUSP.ATWRT where AUSP.ATINN = 0000000076 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class;"),
  CALC_KINRAY_ITEM_FLG STRING OPTIONS(description="Calculated Kinray Item Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000079 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_PUERTO_RICO_ITEM_ID STRING OPTIONS(description="Calculated Puerto Rico Item ID; AUSP.ATWRT where AUSP.ATINN = 0000000080 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class;"),
  CALC_BIOLOGIC_BLA_TYPE_ID STRING OPTIONS(description="Calculated Biologic BLA Type ID; AUSP.ATWRT where AUSP.ATINN = 0000000082 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class;"),
  CALC_IB_SPECIAL_PROCESS_FLG STRING OPTIONS(description="Calculated IB Special Processing Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000085 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_CNSMR_HLTH_PLNGRM_FLG STRING OPTIONS(description="Calculated Consumer Health Planogram Flag; If AUSP.ATWRT = YES then Y else N, where AUSP.ATINN = 0000000088 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_VACCINE_PORTAL_ID STRING OPTIONS(description="Calculated Vaccine Portal ID; If AUSP.ATWRT where AUSP.ATINN = 0000000091 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  COMPOSITE_KEY STRING OPTIONS(description="Composite key to identify records in initial load"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID"),
  CALC_BASE_UOM_UPC_ID STRING OPTIONS(description="Base UoM UPC ID; IFNULL(MEAN.EAN11, N/A) where EANTP in (UC, IC, HE, UX) and MEAN.MEINH = MARA.MEINS and MARA.MATNR = MEAN.MATNR. Process EAN11 based on this sequence - UC, IC, HE, UX"),
  CALC_D0_START_STP TIMESTAMP OPTIONS(description="Indicates When The Record Was Added By Attinuity, Internal use only"),
  ENTERED_DTE_ITEM_MAST DATE OPTIONS(description="MIF Create Date"),
  CALC_MED_INTGRT_DSPNS_FLG STRING OPTIONS(description="Calculated Medically Integrated Dispensing Flag; If AUSP.ATWRT = YES then Y else N where AUSP.ATINN = 0000000094 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class"),
  CALC_ECOM_PROD_CTLG_FLG STRING OPTIONS(description="Calculated E-Commerce Product Catalog Flag; If AUSP.ATWRT = YES then Y else N where AUSP.ATINN = 0000000095 and AUSP.OBJEK = INOB.CUOBJ and AUSP.KLART = INOB.KLART and INOB.OBJEK = MARA.MATNR and INOB.OBTAB = MARA --Material Master AND AUSP.KLART = 001 --Material Class")
)
PARTITION BY VRSN_START_DTE
CLUSTER BY MATNR_MARA, VRSN_START_DTE, CURR_VRSN_FLG;