CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_EQUIVALENCE`
(
  MATNR_YTMM_EQV_ITEM STRING NOT NULL OPTIONS(description="Material Number"),
  MAKTX_MAKT STRING OPTIONS(description="Material Description Text;  MAKT.MAKTX where MAKT.MATNR = YTMM_EQV_ITEM.MATNR and MAKT.SPRAS = E"),
  YYEQVNUM_YTMM_EQV_ITEM STRING NOT NULL OPTIONS(description="Equivalent Material Number"),
  MAKTX_MAKT_EQV STRING OPTIONS(description="Equivalent Material Description Text; MAKT.MAKTX where MAKT.MATNR = YTMM_EQV_ITEM.YYEQVNUM and MAKT.SPRAS = E"),
  YYEQVTYP_YTMM_EQV_ITEM INT64 OPTIONS(description="Equivalence Type Code"),
  YYDESC_YTMM_EQVTYP_T STRING OPTIONS(description="Equivalence Type Description Text; YTMM_EQVTYP_T.YYDESC where YTMM_EQVTYP_T.YYEQVTYP = YTMM_EQV_ITEM.YYEQVTYP and YTMM_EQVTYP_T.SPRAS = E"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Added Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Added User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Updated Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Updated User ID")
)
CLUSTER BY MATNR_YTMM_EQV_ITEM, YYEQVNUM_YTMM_EQV_ITEM, YYEQVTYP_YTMM_EQV_ITEM
OPTIONS(
  description=""
);