CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_PLANT_RLT_CV`
(
  MATNR_MARC STRING NOT NULL OPTIONS(description="Material Number"),
  WERKS_MARC STRING NOT NULL OPTIONS(description="Plant ID"),
  PSTAT_MARC STRING OPTIONS(description="Maintenance Status ID"),
  LVORM_MARC STRING OPTIONS(description="Plant Level Material Deletion Indicator Flag"),
  XCHAR_MARC STRING OPTIONS(description="Internal Batch Management Indicator Flag"),
  MMSTA_MARC STRING OPTIONS(description="Plant Specific Material Status ID"),
  MMSTD_MARC DATE OPTIONS(description="Plant Specific Material Status Valid From Date"),
  EKGRP_MARC STRING OPTIONS(description="Purchasing Group ID"),
  EKNAM_T024 STRING OPTIONS(description="Purchasing Group Description Text; T024.EKNAM where T024.EKGRP = MARC.EKGRP"),
  DISPR_MARC STRING OPTIONS(description="Material Requirements Planning (MRP) Profile ID"),
  DISMM_MARC STRING OPTIONS(description="Material Requirements Planning (MRP) Type ID"),
  XCHPF_MARC STRING OPTIONS(description="Batch Management Requirement Indicator Flag"),
  MTVFP_MARC STRING OPTIONS(description="Availability Check Group ID"),
  BEZEI_TMVFT STRING OPTIONS(description="Availability Check Group Description Text; TMVFT.BEZEI where TMVFT.MTVFP = MARC.MTVFP and TMVFT.SPRAS = E"),
  PRCTR_MARC STRING OPTIONS(description="Profit Center ID"),
  ABCIN_MARC STRING OPTIONS(description="Cycle Counting Physical Inventory Indicator ID"),
  SERNP_MARC STRING OPTIONS(description="Serial Number Profile ID"),
  XMCNG_MARC STRING OPTIONS(description="Plant Negative Stocks Allowed Flag"),
  CCFIX_MARC STRING OPTIONS(description="Fixed CC indicator Flag"),
  MFRGR_MARC STRING OPTIONS(description="Material Freight Group ID"),
  LOGGR_MARC STRING OPTIONS(description="Putaway Type ID"),
  FPRFM_MARC STRING OPTIONS(description="Plant Material Distribution Profile ID"),
  LFMON_MARC INT64 OPTIONS(description="Current Posting Period Month Number"),
  LFGJA_MARC INT64 OPTIONS(description="Current Period Fiscal Year Number"),
  BWESB_MARC NUMERIC OPTIONS(description="Valuated Goods Receipt Blocked Stock Quantity"),
  YYNOINVENTORY_MARC STRING OPTIONS(description="No Inventory Flag"),
  YYCALLTO_MARC STRING OPTIONS(description="Call To Order Flag"),
  YYLOTM_MARC STRING OPTIONS(description="Lot Managed Flag"),
  ZSLTSTMP_MARC DATE OPTIONS(description="Plant Start Date; Date from MIN(MARC.ZSLTSTMP) where D0_ACTION_ID=INSERT"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Added Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Added User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY MATNR_MARC, WERKS_MARC, MMSTA_MARC, LVORM_MARC;