CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MEDISPAN_MODIFIER_CV`
(
  NDC_UPC_HRI_ID STRING OPTIONS(description=" NDC-UPC-HRI "),
  MDFY_ID STRING OPTIONS(description=" Modifier Code "),
  MODIFIER_DESCRIPTION STRING OPTIONS(description=" Modifier Description "),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
PARTITION BY DATE(ROW_UPDATE_STP)
CLUSTER BY NDC_UPC_HRI_ID, MDFY_ID;