CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.ORANGE_BOOK_CODE_CV`
(
  YYOBRAT_YTMM_OBRAT_TEXT STRING OPTIONS(description="OBC ID; YTMM_OBRAT_TEXT.YYOBRAT where YTMM_OBRAT_TEXT.SPRAS = E"),
  YYDESC_YTMM_OBRAT_TEXT STRING OPTIONS(description="OBC Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYOBRAT_YTMM_OBRAT_TEXT;