CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.PACKAGING_INDICATOR_CV`
(
  YYPCKG_YTMM_PACK_TEXT STRING OPTIONS(description="Packaging Indicator ID; YTMM_PACK_TEXT.YYPCKG where YTMM_PACK_TEXT.SPRAS = E"),
  YYDESC_YTMM_PACK_TEXT STRING OPTIONS(description="Packaging Indicator Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYPCKG_YTMM_PACK_TEXT;