CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.PACKAGE_REFERENCE_CV`
(
  YYPACREF_YTMM_PACREF_TEXT STRING OPTIONS(description="Package Reference Guide ID; YTMM_PACREF_TEXT.YYPACREF where YTMM_PACREF_TEXT.SPRAS = E"),
  YYDESC_YTMM_PACREF_TEXT STRING OPTIONS(description="Package Reference Guide Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYPACREF_YTMM_PACREF_TEXT;