CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.REMS_PROGRAM_CV`
(
  YYREMSP_YTMM_REMS_PROG_T STRING OPTIONS(description="REMS Program ID; YTMM_REMS_PROG_T.YYREMSP where YTMM_REMS_PROG_T.SPRAS = E"),
  YYDESC_YTMM_REMS_PROG_T STRING OPTIONS(description="REMS Program Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYREMSP_YTMM_REMS_PROG_T;