CREATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.SPECIAL_HANDLING_CV`
(
  YYSPHD_YTMM_SPECL_TEXT STRING OPTIONS(description="Special Handling ID; YTMM_SPECL_TEXT.YYSPHD where YTMM_SPECL_TEXT.SPRAS = E"),
  YYDESC_YTMM_SPECL_TEXT STRING OPTIONS(description="Special Handling Description Text"),
  ROW_ADD_STP TIMESTAMP OPTIONS(description="Row Add Timestamp"),
  ROW_ADD_USER_ID STRING OPTIONS(description="Row Add User ID"),
  ROW_UPDATE_STP TIMESTAMP OPTIONS(description="Row Update Timestamp"),
  ROW_UPDATE_USER_ID STRING OPTIONS(description="Row Update User ID")
)
CLUSTER BY YYSPHD_YTMM_SPECL_TEXT;