CREATE PROCEDURE `PROJECT_ID`.D2_PHM_CONFFACT_PRICING.SP_SEGMENT_MASTER_TEMP()
BEGIN
CREATE OR REPLACE TABLE `PROJECT_ID.D2_PHM_CONFFACT_PRICING.SEGMENT_MASTER_TEMP`
AS
SELECT DISTINCT
RIGHT(SHIP_TO.DLVR_PLANT_ID,3) AS division_number,
SHIP_TO.CUSTOMER_NUM AS ship_to_customer_number,
RLT_CV.BUY_GROUP_ID AS subgroup_number,
RLT_CV.VRSN_START_DTE AS attachment_effective_date,
RLT_CV.VRSN_END_DTE AS attachment_term_date,
1+(RLT_CV.MARKUP_FCTR_PCT/100) AS percent_1,
1+(RLT_CV.ADDL_MARKUP_PCT/100) AS percent_2,
RLT_CV.CNTRCT_RANK_PRTY_NUM AS group_number,
FORMAT_DATETIME('%x %X',current_datetime()) AS record_effective_date
FROM `PROJECT_ID.VW_PHM_CONFDIM_CONTRACT.BUYING_GROUP_CUSTOMER_RLT_CV` RLT_CV
JOIN `PROJECT_ID.VW_PHM_CONFDIM_CUSTOMER.CUSTOMER_CODE_CV` CUST_CODE ON
CUST_CODE.CUSTOMER_NUM = RLT_CV.CUSTOMER_NUM AND CUST_CODE.CUSTOMER_NUM = RLT_CV.CUSTOMER_NUM AND CUST_CODE.SALE_ORG_ID = RLT_CV.SALE_ORG_ID AND CUST_CODE.DIST_CHNL_ID = RLT_CV.DIST_CHNL_ID
AND CUST_CODE.DIV_ID = RLT_CV.DIV_ID
JOIN `PROJECT_ID.VW_PHM_CONFDIM_CUSTOMER.SHIPTO_CUSTOMER_SALES_AREA_RLT_CV` SHIP_TO ON SHIP_TO.SOLDTO_PARTY_CUSTOMER_NUM = RLT_CV.CUSTOMER_NUM AND SHIP_TO.CURR_VRSN_FLG ='Y'
AND CUST_CODE.SALE_ORG_ID = SHIP_TO.SALE_ORG_ID AND CUST_CODE.DIST_CHNL_ID = SHIP_TO.DIST_CHNL_ID
AND CUST_CODE.DIV_ID = SHIP_TO.DIV_ID
JOIN `PROJECT_ID.VW_PHM_CONFDIM_CONTRACT.CONTRACT_BUYING_GROUP_RLT_CV` BUY_GROUP_RLT ON BUY_GROUP_RLT.BUY_GROUP_ID = RLT_CV.BUY_GROUP_ID AND BUY_GROUP_RLT.CURR_VRSN_FLG ='Y'
JOIN `PROJECT_ID.VW_PHM_CONFDIM_CONTRACT.CONTRACT_CV` CNT_CV ON CNT_CV.CNTRCT_NUM = BUY_GROUP_RLT.CNTRCT_NUM AND CNT_CV.CURR_VRSN_FLG ='Y'
WHERE CUST_CODE.CDE_NUM_ID = '843' AND CUST_CODE.CDE_TYPE_ID ='P' AND CNT_CV.CNTRCT_TYPE_LKP_ID = 'P';
END;