CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_MATERIAL.SP_FDB_MASTER_CV()
BEGIN
CREATE OR REPLACE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.FDB_MASTER_CV`
(
  FDB_NDC STRING OPTIONS(DESCRIPTION='FDB_NDC'),
  FDB_MASTER STRUCT<NDC STRING, LBLRID STRING, GCN_SEQNO STRING, PS STRING, DF STRING, AD STRING, LN STRING, BN STRING, PNDC STRING, REPNDC STRING, NDCFI STRING, DADDNC STRING, DUPDC STRING, DESI STRING, DESDTEC STRING, DESI2 STRING, DES2DTEC STRING, DEA STRING, CL STRING, GPI STRING, HOSP STRING, INNOV STRING, IPI STRING, MINI STRING, MAINT STRING, OBC STRING, OBSDTEC STRING, PPI STRING, STPK STRING, REPACK STRING, TOP200 STRING, UD STRING, CSP STRING, NDL_GDGE STRING, NDL_LNGTH STRING, SYR_CPCTY STRING, SHLF_PCK STRING, SHIPPER STRING, HCFA_FDA STRING, HCFA_UNIT STRING, HCFA_PS STRING, HCFA_APPC STRING, HCFA_MRKC STRING, HCFA_TRMC STRING, HCFA_TYP STRING, HCFA_DESC1 STRING, HCFA_DESI1 STRING, UU STRING, PD STRING, LN25 STRING, LN25I STRING, GPIDC STRING, BBDC STRING, HOME STRING, INPCKI STRING, OUTPCKI STRING, OBC_EXP STRING, PS_EQUIV STRING, PLBLR STRING, TOP50GEN STRING, GMI STRING, GNI STRING, GSI STRING, GTI STRING, NDCGI1 STRING, HCFA_DC STRING, LN60 STRING, HICL_SEQNO STRING, GCDF STRING, GCRT STRING, STR STRING, GTC STRING, TC STRING, DCC STRING, GCNSEQ_GI STRING, GENDER STRING, HIC3_SEQN STRING, STR60 STRING, RT STRING, GCRT2 STRING, GCRT_DESC STRING, SYSTEMIC STRING, MFG STRING, LBLRIND STRING, COLOR_TXT STRING, SHAPE_TXT STRING, FLAVOR_TXT STRING, CHG_FLAG STRING, NDA_IND STRING, ANDA_IND STRING, LISTING_SEQ_NO STRING, TRADENAME STRING, DOSE STRING, GCDF_DESC STRING, STRNUM STRING, VOLNUM STRING, STRUN50 STRING, VOLUN50 STRING, OBC_GCN STRING, GNN STRING, GNN60 STRING, AHFS8 STRING, AHFS_DESC STRING, GCN STRING, DCC_DESC STRING, GTC_DESC STRING, HIC3 STRING, HIC3_DESC STRING, HIC3_GRPN STRING, HIC3_ROOT STRING, OBC_SN STRING, OBC_DESC STRING, MEDID STRING, TM_SOURCE_ID STRING, TM_IND STRING, TM_ALT_MEDID_DESC STRING, TC_DESC STRING, AMP_PRICE_EFFECTIVE_DATE STRING, AMP_PRICE STRING, HCPC STRING, HCPC_PBC1 STRING, HCPC_PBP1 STRING, HCPC_PBC2 STRING, HCPC_PBP2 STRING, HCPC_PBC3 STRING, HCPC_PBP3 STRING, HCPC_PBC4 STRING, HCPC_PBP4 STRING, HCPC_PBC5 STRING, HCPC_PBP5 STRING, HCPC_PBC6 STRING, HCPC_PBP6 STRING, HCPC_PBC7 STRING, HCPC_PBP7 STRING, HCPC_PBC8 STRING, HCPC_PBP8 STRING, MCR_BCDESC STRING, HIERARCHICAL_INGREDIENT ARRAY<STRUCT<HIC_SEQN STRING, HIC_REL_NO STRING, HIC STRING, HIC_DESC STRING, HIC_ROOT STRING, HIC_POTENTIALLY_INACTV_IND STRING, ING_STATUS_CD STRING, CAS9_TBL STRING>>, DRUG_DISEASE ARRAY<STRUCT<DDXCN STRING, DDXCN_SN STRING, FDBDX STRING, DDXCN_SL_DESC STRING, DDXCN_REF STRING, DXID STRING, DXID_DESC56 STRING, DXID_DESC100 STRING, DXID_STATUS STRING, DXID_DISEASE_DURATION_CD STRING>>, NDC_ATTRIBUTE ARRAY<STRUCT<NDC_ATTRIBUTE_TYPE_CD STRING, NDC_ATTRIBUTE_TYPE_DSC STRING, NDC_ATTRIBUTE_SN STRING, NDC_ATTRIBUTE_VALUE STRING, NDC_ATTRIBUTE_VALUE_DESC STRING>>, DRUG_IMPRINTS ARRAY<STRUCT<IPTUNIQID STRING, IPTDFID STRING, IPTMFGID STRING, IPTMFGNAME STRING, IPTDFDESC STRING, IPTPROPID STRING, IPTLBLID STRING, IPTSIDE1 STRING, IPTSIDE2 STRING, IPTTEXTID STRING, IPTLINENO STRING, IPTTEXT STRING, CHG_FLAG STRING>>, AUDIT STRUCT<EVENTID STRING, EVENNAME STRING, SOURCESYSTEM STRING, EVENTTYPE STRING, EVENTTIME STRING>> OPTIONS(DESCRIPTION='FDB MASTER JSON'),
  D0_START_STP TIMESTAMP OPTIONS(DESCRIPTION='START TIMESTAMP '),
  D0_END_STP TIMESTAMP  OPTIONS(DESCRIPTION='END TIMESTAMP '),
  D0_ADD_STP TIMESTAMP OPTIONS(DESCRIPTION='ROW ADD TIMESTAMP '),
  D0_ADD_USER_ID STRING OPTIONS(DESCRIPTION='ROW ADDED BY USER'),
  D0_UPDATE_STP TIMESTAMP OPTIONS(DESCRIPTION='ROW UPDATE TIMESTAMP'),
  D0_UPDATE_USER_ID STRING OPTIONS(DESCRIPTION='ROW UPDATE BY USER'),
  D0_ACTION_ID STRING OPTIONS(DESCRIPTION='ROW ACTION ID'),
  D0_SOURCE_ID STRING OPTIONS(DESCRIPTION='ROW SOURCE ID'),
  D0_CURR_VRSN_FLG STRING OPTIONS(DESCRIPTION='CURRENT VERSION FLAG'),
  D0_SEQ_NUM STRING OPTIONS(DESCRIPTION='SEQUENCE NUMBER'),
)
PARTITION BY DATE(D0_UPDATE_STP)
CLUSTER BY FDB_NDC;

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.FDB_MASTER_CV`
(
  FDB_NDC,
  FDB_MASTER,
  D0_START_STP,
  D0_END_STP,
  D0_ADD_STP,
  D0_ADD_USER_ID,
  D0_UPDATE_STP,
  D0_UPDATE_USER_ID,
  D0_ACTION_ID,
  D0_SOURCE_ID,
  D0_CURR_VRSN_FLG,
  D0_SEQ_NUM
)
SELECT FDB_NDC,
 FDB_MASTER,
  D0_START_STP,
  D0_END_STP,
  D0_ADD_STP,
  D0_ADD_USER_ID,
  D0_UPDATE_STP,
  D0_UPDATE_USER_ID,
  D0_ACTION_ID,
  D0_SOURCE_ID,
  D0_CURR_VRSN_FLG,
  D0_SEQ_NUM
  FROM `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_EDA_FDB__FDB_MASTER_CV`;

END;