CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_MATERIAL.SP_MATERIAL_REGULATION_BLOCK()
BEGIN

/***********************************************************************************************************************
Author: Gopalakrishnan Thangavel
Creation Date: 05/15/2023
Data Sources: VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__YTMM_REGUL_BLOCK_CV,VI2_PHM_CONFDIM_SUPPLIER.PHM_ORP_PE1_PH1__YTMM_LICENSE_TYT_CV

*************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
	<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time datetime;
DECLARE v_start_stp timestamp;
DECLARE v_end_stp timestamp;
DECLARE v_stored_proc_name string;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_MATERIAL.SP_MATERIAL_REGULATION_BLOCK';

-- Truncate MATERIAL_REGULATION_BLOCK_CV

TRUNCATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_REGULATION_BLOCK_CV`;

-- Insert into MATERIAL_REGULATION_BLOCK_CV

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_REGULATION_BLOCK_CV`
SELECT
REG.YREGULATION_ID,
REG.WERKS,
REG.MATNR,
REG.LIFNR,
REG.YBLOCK_TYPE,
CASE REG.YBLOCK_TYPE WHEN 'I' THEN 'Invalid'
WHEN 'P' THEN 'Purchase'
WHEN 'M' THEN 'Message'
WHEN 'R' THEN 'Receiving'
WHEN 'O' THEN 'Override'
WHEN 'Blank' THEN 'Valid License '
ELSE 'NOT_AVAILABLE' END AS CALC_BLCK_TYPE_DESC_TXT,
REG.YCHECK_LIC,
CASE REG.YCHECK_LIC WHEN 'Y' THEN 'Yes'
WHEN 'N' THEN 'No'
WHEN 'S' THEN 'Rule based on Ship From'
ELSE 'NOT_AVAILABLE' END AS CALC_CHK_LIC_TABLE_IND_DESC_TXT,
REG.YP_LICENSE_TYPE,
IF(TYT.YP_LICENSE_DESC IS NULL, 'NOT_AVAILABLE',TYT.YP_LICENSE_DESC) AS YP_LICENSE_DESC,
REG.YRECORDSTAT,
CASE REG.YRECORDSTAT WHEN 'A' THEN 'Approved'
WHEN 'P' THEN 'Pending'
WHEN 'D' THEN 'Deleted'
ELSE 'NOT_AVAILABLE' END AS CALC_REC_STAT_DESC_TXT,
REG.Y3PLFLG,
REG.ERNAM,
IFNULL(SAFE_CAST(REG.ERDAT AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS ERDAT,
REG.AENAM,
IFNULL(SAFE_CAST(REG.AEDAT AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS AEDAT,
v_start_stp 		AS ROW_ADD_STP,
v_stored_proc_name	AS ROW_ADD_USER_ID,
v_start_stp 		AS ROW_UPDATE_STP,
v_stored_proc_name	AS ROW_UPDATE_USER_ID

--FROM `PROJECT_ID.VI0_PHM_ORP_PE1_PH1_NP.YTMM_REGUL_BLOCK_CV` REG
FROM `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__YTMM_REGUL_BLOCK_CV` REG
LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__YTMM_LICENSE_TYT_CV` TYT ON
TYT.YP_LICENSE_TYPE = REG.YP_LICENSE_TYPE AND TYT.SPRAS = 'E'
;

END;