CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_MATERIAL.SP_MATERIAL_LEGAL_CONTROL()
BEGIN

/***********************************************************************************************************************
Author: Debapriya Banerjee
Creation Date: 08/16/2023
Data Sources:	VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__MAEX_CV
				VW_PHM_CONFDIM_MATERIAL.MATERIAL_CV
				VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__T606V_CV
				VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__T606U_CV
				VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__T606R_CV

*************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time datetime;
DECLARE v_start_stp timestamp;
DECLARE v_end_stp timestamp;
DECLARE v_stored_proc_name string;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_PLANT.SP_MATERIAL_LEGAL_CONTROL';

-- Truncate MATERIAL_LEGAL_CONTROL_CV

TRUNCATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_LEGAL_CONTROL_CV`;

-- Insert into MATERIAL_LEGAL_CONTROL_CV

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_LEGAL_CONTROL_CV`
SELECT
	MAEX.MATNR,
	MAEX.GEGRU,
	T606R.BEZEI,
	MAEX.ALNUM,
	T606V.BEZEI,
	MAEX.EMBGR,
	T606U.BEZEI,
	v_start_stp AS ROW_ADD_STP,
	v_stored_proc_name AS ROW_ADD_USER_ID,
	V_end_stp AS ROW_UPDATE_STP,
	v_stored_proc_name AS ROW_UPDATE_USER_ID
FROM `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__MAEX_CV` MAEX
	INNER JOIN `PROJECT_ID.VW_PHM_CONFDIM_MATERIAL.MATERIAL_CV` MTRL ON MAEX.MATNR = MTRL.MTRL_NUM
	LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__T606R_CV` T606R ON T606R.GEGRU = MAEX.GEGRU AND T606R.SPRAS = 'E'
	LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__T606V_CV` T606V ON T606V.ALNUM = MAEX.ALNUM AND T606V.GEGRU = MAEX.GEGRU AND T606V.SPRAS = 'E'
	LEFT JOIN `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__T606U_CV` T606U ON T606U.EMBGR = MAEX.EMBGR AND T606U.GEGRU = MAEX.GEGRU AND T606U.SPRAS = 'E'
WHERE MAEX.ALAND = 'US' /* United States only */
AND MTRL.CURR_VRSN_FLG = 'Y'
;

END;