CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_MATERIAL.SP_MEDISPAN_MASTER_CV()
OPTIONS(
  strict_mode=FALSE)
BEGIN
CREATE OR REPLACE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MEDISPAN_MASTER_CV`
(
  MDDB_NDC_ID STRING OPTIONS(DESCRIPTION='MDDB NDC ID'),
  MEDISPAN_MASTER STRUCT<NDC_UPC_HRI_ID STRING, CHG_FLAG STRING, SEQ_ID STRING, LABELE_CDE STRING, GEN_TYPE_ID STRING, GEN_ID_NUM STRING, DEA_CLASS_ID STRING, AHFS_THER_CLASS_CDE STRING, ITEM_STAT_FLG STRING, LOCAL_SYSTEM_FLG STRING, TEE_ID STRING, FMT_ID STRING, RX_OTC_ID STRING, THIRD_PARTY_RSTRCT_ID STRING, MAINT_DRUG_ID STRING, DSPNS_UNIT_ID STRING, UNIT_DOSE_PACK_ID STRING, ROUTE_OF_ADMIN_ID STRING, FORM_TYPE_ID STRING, DLR_RANK_ID STRING, RX_RANK_ID STRING, NUM_SYSTEM_CHAR_ID STRING, SCNDRY_FMT_ID STRING, SCNDRY_ID STRING, MULTI_SRC_ID STRING, BRAND_NAM_ID STRING, INTRNL_EXTRNL_ID STRING, SINGLE_CMBNTN_ID STRING, STRG_CNDTN_ID STRING, LMT_STBLTY_ID STRING, OLD_NDC_UPC_HRI_ID STRING, OLD_FMT_ID STRING, OLD_EFFECT_DTE STRING, NEW_NDC_UPC_HRI_ID STRING, NEW_FMT_ID STRING, NEW_EFFECT_DTE STRING, PROD_NAM STRING, PROD_EXTN_NAM STRING, ALRG_PTRN_CDE STRING, PPG_ID STRING, HFPG_ID STRING, LABELE_TYPE_ID STRING, PRICE_SPREAD_ID STRING, MFG_NAM STRING, MFG_ABBR_NAM STRING, PROD_ABBR_DESC STRING, DRUG_NAM_ID STRING, GEN_PROD_PACK_ID STRING, GEN_PROD_ID STRING, GPI_GEN_NAM STRING, GEN_PROD_PACK_SIZE_QTY STRING, GEN_PROD_PACK_SIZE_UOM_ID STRING, GEN_PROD_PACK_QTY STRING, GEN_PROD_UNIT_DOSE_USE_PACK_ID STRING, GEN_PROD_PACK_DESC_ID STRING, DOSAGE_FORM_ID STRING, PACK_SIZE_QTY STRING, PACK_SIZE_UOM_ID STRING, PACK_QTY STRING, REPACK_ID STRING, TOTAL_PACK_QTY STRING, DESI_ID STRING, PACK_DESC STRING, NEXT_SMALL_NDC_SUFFIX_ID STRING, NEXT_LARGE_NDC_SUFFIX_ID STRING, INNER_PACK_ID STRING, CLINIC_PACK_ID STRING, METRIC_STRGTH_ID STRING, STRGTH_UOM_ID STRING, LMT_DIST_ID STRING, EXT_AHFS_THER_CLASS_ID STRING, INACT_DTE STRING, CMS_FUL_PRICE_AMT STRING, CMS_FUL_EFFECT_DTE STRING, FIRST_OLD_CMS_FUL_PRICE_AMT STRING, FIRST_OLD_CMS_FUL_EFFECT_DTE STRING, SCND_OLD_CMS_FUL_LMT_PRICE_AMT STRING, SCND_OLD_CMS_FUL_EFFECT_DTE STRING, WAC_PACK_PRICE_AMT STRING, WAC_UNIT_PRICE_AMT STRING, WAC_EFFECT_DTE STRING, OLD_WAC_PACK_PRICE_AMT STRING, OLD_WAC_UNIT_PRICE_AMT STRING, OLD_WAC_EFFECT_DTE STRING, AWP_ID STRING, AWP_PACK_PRICE_AMT STRING, AWP_UNIT_PRICE_AMT STRING, AWP_EFFECT_DTE STRING, OLD_AWP_PACK_PRICE_AMT STRING, OLD_AWP_UNIT_PRICE_AMT STRING, OLD_AWP_EFFECT_DTE STRING, DP_PACK_PRICE_AMT STRING, DP_UNIT_PRICE_AMT STRING, DP_EFFECT_DTE STRING, OLD_DP_PACK_PRICE_AMT STRING, OLD_DP_UNIT_PRICE_AMT STRING, OLD_DP_EFFECT_DTE STRING, GPPC_UNIT_PRICE_AMT STRING, GPPC_EFFECT_DTE STRING, DRUG_GROUP_CDE STRING, DRUG_GROUP_DESCRIPTION STRING, DRUG_CLASS_CDE STRING, DRUG_CLASS_DESCRIPTION STRING, DRUG_SUB_CLASS_CDE STRING, DRUG_SUB_CLASS_DESCRIPTION STRING, DRUG_CDE STRING, DRUG_DESCRIPTION STRING, DEA_CLASS_DESCRIPTION STRING, TEE_DESCRIPTION STRING, RX_OTC_DESCRIPTION STRING, THIRD_PARTY_ID_DESCRIPTION STRING, UNIT_DOSE_PACK_ID_DESCRIPTION STRING, ROUTE_OF_ADMIN_ID_DESCRIPTION STRING, MULTI_SOURCE_ID_DESCRIPTION STRING, BRAND_NAME_ID_DESCRIPTION STRING, DOSAGE_FORM_ID_DESCRIPTION STRING, PACK_SIZE_UOM_ID_DESCRIPTION STRING, DESI_ID_DESCRIPTION STRING, INGREDIENT ARRAY<STRUCT<INGRED_GEN_ID STRING, INGRED_STRGTH_ID STRING, INGRED_STRGTH_UOM_ID STRING, GEN_INGRED_NAM STRING, ACTIVE_INGRED_FLG STRING, MDFY_ID STRING, MODIFIER_DESCRIPTION STRING>>, MODIFIER ARRAY<STRUCT<MDFY_ID STRING, MODIFIER_DESCRIPTION STRING>>, AUDIT STRUCT<EVENTID STRING, EVENTNAME STRING, SOURCESYSTEM STRING, EVENTTYPE STRING, EVENTTIME STRING>>OPTIONS(DESCRIPTION='MEDISPAN MASTER JSON'),
  D0_START_STP TIMESTAMP OPTIONS(DESCRIPTION='START TIMESTAMP '),
  D0_END_STP TIMESTAMP  OPTIONS(DESCRIPTION='END TIMESTAMP '),
  D0_ADD_STP TIMESTAMP OPTIONS(DESCRIPTION='ROW ADD TIMESTAMP '),
  D0_ADD_USER_ID STRING OPTIONS(DESCRIPTION='ROW ADDED BY USER'),
  D0_UPDATE_STP TIMESTAMP OPTIONS(DESCRIPTION='ROW UPDATE TIMESTAMP'),
  D0_UPDATE_USER_ID STRING OPTIONS(DESCRIPTION='ROW UPDATE BY USER'),
  D0_ACTION_ID STRING OPTIONS(DESCRIPTION='ROW ACTION ID'),
  D0_SOURCE_ID STRING OPTIONS(DESCRIPTION='ROW SOURCE ID'),
  D0_CURR_VRSN_FLG STRING OPTIONS(DESCRIPTION='CURRENT VERSION FLAG'),
  D0_SEQ_NUM STRING OPTIONS(DESCRIPTION='SEQUENCE NUMBER'),
)
PARTITION BY DATE(D0_UPDATE_STP)
CLUSTER BY MDDB_NDC_ID;

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MEDISPAN_MASTER_CV`
(
MDDB_NDC_ID,
MEDISPAN_MASTER,
D0_START_STP,
D0_END_STP,
D0_ADD_STP,
D0_ADD_USER_ID,
D0_UPDATE_STP,
D0_UPDATE_USER_ID,
D0_ACTION_ID,
D0_SOURCE_ID,
D0_CURR_VRSN_FLG,
D0_SEQ_NUM
)
SELECT
MDDB_NDC_ID,
MEDISPAN_MASTER,
D0_START_STP,
D0_END_STP,
D0_ADD_STP,
D0_ADD_USER_ID,
D0_UPDATE_STP,
D0_UPDATE_USER_ID,
D0_ACTION_ID,
D0_SOURCE_ID,
D0_CURR_VRSN_FLG,
D0_SEQ_NUM
FROM `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_EDA_MDSP__MEDISPAN_MASTER_CV`;
END;