CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_MATERIAL.SP_MATERIAL_RETAIL_TIER_PRICE_VF()
BEGIN

/***********************************************************************************************************************
Author: Debapriya Banerjee
Creation Date: 09/29/2023
Data Sources:	PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__A714_CV
				PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__YTSD_HAMACHER_ZL_CV
				PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__KONP_CV

*************************************************************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
	<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time datetime;
DECLARE v_start_stp timestamp;
DECLARE v_end_stp timestamp;
DECLARE v_stored_proc_name string;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_MATERIAL.SP_MATERIAL_RETAIL_TIER_PRICE_VF';

-- MATERIAL_RETAIL_TIER_PRICE_VF will be truncated and loaded daily with the rest of the Material objects

-- Truncate MATERIAL_RETAIL_TIER_PRICE_VF

TRUNCATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_RETAIL_TIER_PRICE_VF`;

-- Insert into MATERIAL_RETAIL_TIER_PRICE_VF
-- Convert DATAB, DATBI to DATE fields first

CREATE TEMP TABLE A714_TEMP
AS
SELECT
	A714.MATNR						AS MATNR_A714,
	A714.VKORG						AS VKORG_A714,
	A714.VTWEG						AS VTWEG_A714,
	A714.SPART						AS SPART_A714,
	A714.YYRPRPT					AS YYRPRPT_A714,
	TXT.YYRPRPT_DESC				AS YYRPRPT_DESC_YTSD_HAMACHER_ZL,
	IFNULL(SAFE_CAST(A714.DATAB AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS VRSN_START_DTE,
	IFNULL(SAFE_CAST(A714.DATBI AS DATE FORMAT 'YYYYMMDD'), DATE '1900-01-01') AS VRSN_END_DTE,
	KONP.KBETR						AS KBETR_KONP,
	v_start_stp						AS ROW_ADD_STP,
	v_stored_proc_name				AS ROW_ADD_USER_ID,
	v_start_stp						AS ROW_UPDATE_STP,
	v_stored_proc_name				AS ROW_UPDATE_USER_ID
FROM `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__A714_CV` A714
INNER JOIN	`PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__KONP_CV` KONP ON A714.KNUMH = KONP.KNUMH
INNER JOIN	`PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_ORP_PE1_PH1__YTSD_HAMACHER_ZL_CV` TXT
ON A714.YYRPRPT = TXT.YYRPRPT
AND A714.VKORG = TXT.VKORG AND A714.VTWEG = TXT.VTWEG AND A714.SPART = TXT.SPART
;

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MATERIAL_RETAIL_TIER_PRICE_VF`
SELECT
	MATNR_A714,
    VKORG_A714,
    VTWEG_A714,
    SPART_A714,
	YYRPRPT_A714,
	YYRPRPT_DESC_YTSD_HAMACHER_ZL,
	VRSN_START_DTE,
	VRSN_END_DTE,
	IF(VRSN_START_DTE = MAX(VRSN_START_DTE) OVER(PARTITION BY MATNR_A714, VKORG_A714, VTWEG_A714, SPART_A714, YYRPRPT_A714), 'Y', 'N') AS CURR_VRSN_FLG,
	KBETR_KONP,
	ROW_ADD_STP,
	ROW_ADD_USER_ID,
	ROW_UPDATE_STP,
	ROW_UPDATE_USER_ID
FROM A714_TEMP
;

END;