CREATE PROCEDURE `PROJECT_ID`.D1_PHM_CONFDIM_MATERIAL.SP_MEDISPAN_MASTER()
BEGIN

/***********************************************************************************************************************
Author: Gopalakrishnan Thangavel
Creation Date: 05/15/2023
Data Sources:

*************************************************************************
Change History		[DATE]			[CHANGED BY]	[JIRA#]		[CODE REVIEW BY]		[DESCRIPTION]
	<#>					<MM/DD/YYYY>	<Name>			<ID>

************************************************************************************************************************/

DECLARE v_start_time datetime;
DECLARE v_start_stp timestamp;
DECLARE v_end_stp timestamp;
DECLARE v_stored_proc_name string;

SET v_start_time = current_datetime();
SET v_start_stp = CURRENT_TIMESTAMP;
SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
SET v_stored_proc_name = 'D1_PHM_CONFDIM_MATERIAL.SP_MEDISPAN_MASTER';

--flush the data and insert
TRUNCATE TABLE `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MEDISPAN_MASTER_CV`;

--Create Temp table to get the data
CREATE OR REPLACE TEMPORARY TABLE MEDISPAN_TEMP
AS
SELECT
MEDISPAN_MASTER.NDC_UPC_HRI_ID
,MEDISPAN_MASTER.CHG_FLAG
,MEDISPAN_MASTER.SEQ_ID
,MEDISPAN_MASTER.LABELE_CDE
,MEDISPAN_MASTER.GEN_TYPE_ID
,MEDISPAN_MASTER.GEN_ID_NUM
,MEDISPAN_MASTER.DEA_CLASS_ID
,MEDISPAN_MASTER.AHFS_THER_CLASS_CDE
,MEDISPAN_MASTER.ITEM_STAT_FLG
,MEDISPAN_MASTER.LOCAL_SYSTEM_FLG
,MEDISPAN_MASTER.TEE_ID
,MEDISPAN_MASTER.FMT_ID
,MEDISPAN_MASTER.RX_OTC_ID
,MEDISPAN_MASTER.THIRD_PARTY_RSTRCT_ID
,MEDISPAN_MASTER.MAINT_DRUG_ID
,MEDISPAN_MASTER.DSPNS_UNIT_ID
,MEDISPAN_MASTER.UNIT_DOSE_PACK_ID
,MEDISPAN_MASTER.ROUTE_OF_ADMIN_ID
,MEDISPAN_MASTER.FORM_TYPE_ID
,MEDISPAN_MASTER.DLR_RANK_ID
,MEDISPAN_MASTER.RX_RANK_ID
,MEDISPAN_MASTER.NUM_SYSTEM_CHAR_ID
,MEDISPAN_MASTER.SCNDRY_FMT_ID
,MEDISPAN_MASTER.SCNDRY_ID
,MEDISPAN_MASTER.MULTI_SRC_ID
,MEDISPAN_MASTER.BRAND_NAM_ID
,MEDISPAN_MASTER.INTRNL_EXTRNL_ID
,MEDISPAN_MASTER.SINGLE_CMBNTN_ID
,MEDISPAN_MASTER.STRG_CNDTN_ID
,MEDISPAN_MASTER.LMT_STBLTY_ID
,MEDISPAN_MASTER.OLD_NDC_UPC_HRI_ID
,MEDISPAN_MASTER.OLD_FMT_ID
,MEDISPAN_MASTER.OLD_EFFECT_DTE
,MEDISPAN_MASTER.NEW_NDC_UPC_HRI_ID
,MEDISPAN_MASTER.NEW_FMT_ID
,MEDISPAN_MASTER.NEW_EFFECT_DTE
,MEDISPAN_MASTER.PROD_NAM
,MEDISPAN_MASTER.PROD_EXTN_NAM
,MEDISPAN_MASTER.ALRG_PTRN_CDE
,MEDISPAN_MASTER.PPG_ID
,MEDISPAN_MASTER.HFPG_ID
,MEDISPAN_MASTER.LABELE_TYPE_ID
,MEDISPAN_MASTER.PRICE_SPREAD_ID
,MEDISPAN_MASTER.MFG_NAM
,MEDISPAN_MASTER.MFG_ABBR_NAM
,MEDISPAN_MASTER.PROD_ABBR_DESC
,MEDISPAN_MASTER.DRUG_NAM_ID
,MEDISPAN_MASTER.GEN_PROD_PACK_ID
,MEDISPAN_MASTER.GEN_PROD_ID
,MEDISPAN_MASTER.GPI_GEN_NAM
,MEDISPAN_MASTER.GEN_PROD_PACK_SIZE_QTY
,MEDISPAN_MASTER.GEN_PROD_PACK_SIZE_UOM_ID
,MEDISPAN_MASTER.GEN_PROD_PACK_QTY
,MEDISPAN_MASTER.GEN_PROD_UNIT_DOSE_USE_PACK_ID
,MEDISPAN_MASTER.GEN_PROD_PACK_DESC_ID
,MEDISPAN_MASTER.DOSAGE_FORM_ID
,MEDISPAN_MASTER.PACK_SIZE_QTY
,MEDISPAN_MASTER.PACK_SIZE_UOM_ID
,MEDISPAN_MASTER.PACK_QTY
,MEDISPAN_MASTER.REPACK_ID
,MEDISPAN_MASTER.TOTAL_PACK_QTY
,MEDISPAN_MASTER.DESI_ID
,MEDISPAN_MASTER.PACK_DESC
,MEDISPAN_MASTER.NEXT_SMALL_NDC_SUFFIX_ID
,MEDISPAN_MASTER.NEXT_LARGE_NDC_SUFFIX_ID
,MEDISPAN_MASTER.INNER_PACK_ID
,MEDISPAN_MASTER.CLINIC_PACK_ID
,MEDISPAN_MASTER.METRIC_STRGTH_ID
,MEDISPAN_MASTER.STRGTH_UOM_ID
,MEDISPAN_MASTER.LMT_DIST_ID
,MEDISPAN_MASTER.EXT_AHFS_THER_CLASS_ID
,MEDISPAN_MASTER.INACT_DTE
,MEDISPAN_MASTER.CMS_FUL_PRICE_AMT
,MEDISPAN_MASTER.CMS_FUL_EFFECT_DTE
,MEDISPAN_MASTER.FIRST_OLD_CMS_FUL_PRICE_AMT
,MEDISPAN_MASTER.FIRST_OLD_CMS_FUL_EFFECT_DTE
,MEDISPAN_MASTER.SCND_OLD_CMS_FUL_LMT_PRICE_AMT
,MEDISPAN_MASTER.SCND_OLD_CMS_FUL_EFFECT_DTE
,MEDISPAN_MASTER.WAC_PACK_PRICE_AMT
,MEDISPAN_MASTER.WAC_UNIT_PRICE_AMT
,MEDISPAN_MASTER.WAC_EFFECT_DTE
,MEDISPAN_MASTER.OLD_WAC_PACK_PRICE_AMT
,MEDISPAN_MASTER.OLD_WAC_UNIT_PRICE_AMT
,MEDISPAN_MASTER.OLD_WAC_EFFECT_DTE
,MEDISPAN_MASTER.AWP_ID
,MEDISPAN_MASTER.AWP_PACK_PRICE_AMT
,MEDISPAN_MASTER.AWP_UNIT_PRICE_AMT
,MEDISPAN_MASTER.AWP_EFFECT_DTE
,MEDISPAN_MASTER.OLD_AWP_PACK_PRICE_AMT
,MEDISPAN_MASTER.OLD_AWP_UNIT_PRICE_AMT
,MEDISPAN_MASTER.OLD_AWP_EFFECT_DTE
,MEDISPAN_MASTER.DP_PACK_PRICE_AMT
,MEDISPAN_MASTER.DP_UNIT_PRICE_AMT
,MEDISPAN_MASTER.DP_EFFECT_DTE
,MEDISPAN_MASTER.OLD_DP_PACK_PRICE_AMT
,MEDISPAN_MASTER.OLD_DP_UNIT_PRICE_AMT
,MEDISPAN_MASTER.OLD_DP_EFFECT_DTE
,MEDISPAN_MASTER.GPPC_UNIT_PRICE_AMT
,MEDISPAN_MASTER.GPPC_EFFECT_DTE
,MEDISPAN_MASTER.DRUG_GROUP_CDE
,MEDISPAN_MASTER.DRUG_GROUP_DESCRIPTION
,MEDISPAN_MASTER.DRUG_CLASS_CDE
,MEDISPAN_MASTER.DRUG_CLASS_DESCRIPTION
,MEDISPAN_MASTER.DRUG_SUB_CLASS_CDE
,MEDISPAN_MASTER.DRUG_SUB_CLASS_DESCRIPTION
,MEDISPAN_MASTER.DRUG_CDE
,MEDISPAN_MASTER.DRUG_DESCRIPTION
,MEDISPAN_MASTER.DEA_CLASS_DESCRIPTION
,MEDISPAN_MASTER.TEE_DESCRIPTION
,MEDISPAN_MASTER.RX_OTC_DESCRIPTION
,MEDISPAN_MASTER.THIRD_PARTY_ID_DESCRIPTION
,MEDISPAN_MASTER.UNIT_DOSE_PACK_ID_DESCRIPTION
,MEDISPAN_MASTER.ROUTE_OF_ADMIN_ID_DESCRIPTION
,MEDISPAN_MASTER.MULTI_SOURCE_ID_DESCRIPTION
,MEDISPAN_MASTER.BRAND_NAME_ID_DESCRIPTION
,MEDISPAN_MASTER.DOSAGE_FORM_ID_DESCRIPTION
,MEDISPAN_MASTER.PACK_SIZE_UOM_ID_DESCRIPTION
,MEDISPAN_MASTER.DESI_ID_DESCRIPTION
,RANK() OVER(PARTITION BY MEDISPAN_MASTER.NDC_UPC_HRI_ID ORDER BY MEDISPAN_MASTER.AUDIT.EVENTTIME DESC) AS RANK_RN
FROM `PROJECT_ID.VI2_PHM_CONFDIM_MATERIAL.PHM_EDA_MDSP__MEDISPAN_MASTER_CV`
;

INSERT INTO `PROJECT_ID.D1_PHM_CONFDIM_MATERIAL.MEDISPAN_MASTER_CV`
SELECT
NDC_UPC_HRI_ID
,CHG_FLAG
,SEQ_ID
,LABELE_CDE
,GEN_TYPE_ID
,GEN_ID_NUM
,DEA_CLASS_ID
,AHFS_THER_CLASS_CDE
,ITEM_STAT_FLG
,LOCAL_SYSTEM_FLG
,TEE_ID
,FMT_ID
,RX_OTC_ID
,THIRD_PARTY_RSTRCT_ID
,MAINT_DRUG_ID
,DSPNS_UNIT_ID
,UNIT_DOSE_PACK_ID
,ROUTE_OF_ADMIN_ID
,FORM_TYPE_ID
,DLR_RANK_ID
,RX_RANK_ID
,NUM_SYSTEM_CHAR_ID
,SCNDRY_FMT_ID
,SCNDRY_ID
,MULTI_SRC_ID
,BRAND_NAM_ID
,INTRNL_EXTRNL_ID
,SINGLE_CMBNTN_ID
,STRG_CNDTN_ID
,LMT_STBLTY_ID
,OLD_NDC_UPC_HRI_ID
,OLD_FMT_ID
,OLD_EFFECT_DTE
,NEW_NDC_UPC_HRI_ID
,NEW_FMT_ID
,NEW_EFFECT_DTE
,PROD_NAM
,PROD_EXTN_NAM
,ALRG_PTRN_CDE
,PPG_ID
,HFPG_ID
,LABELE_TYPE_ID
,PRICE_SPREAD_ID
,MFG_NAM
,MFG_ABBR_NAM
,PROD_ABBR_DESC
,DRUG_NAM_ID
,GEN_PROD_PACK_ID
,GEN_PROD_ID
,GPI_GEN_NAM
,GEN_PROD_PACK_SIZE_QTY
,GEN_PROD_PACK_SIZE_UOM_ID
,GEN_PROD_PACK_QTY
,GEN_PROD_UNIT_DOSE_USE_PACK_ID
,GEN_PROD_PACK_DESC_ID
,DOSAGE_FORM_ID
,PACK_SIZE_QTY
,PACK_SIZE_UOM_ID
,PACK_QTY
,REPACK_ID
,TOTAL_PACK_QTY
,DESI_ID
,PACK_DESC
,NEXT_SMALL_NDC_SUFFIX_ID
,NEXT_LARGE_NDC_SUFFIX_ID
,INNER_PACK_ID
,CLINIC_PACK_ID
,METRIC_STRGTH_ID
,STRGTH_UOM_ID
,LMT_DIST_ID
,EXT_AHFS_THER_CLASS_ID
,INACT_DTE
,CMS_FUL_PRICE_AMT
,CMS_FUL_EFFECT_DTE
,FIRST_OLD_CMS_FUL_PRICE_AMT
,FIRST_OLD_CMS_FUL_EFFECT_DTE
,SCND_OLD_CMS_FUL_LMT_PRICE_AMT
,SCND_OLD_CMS_FUL_EFFECT_DTE
,WAC_PACK_PRICE_AMT
,WAC_UNIT_PRICE_AMT
,WAC_EFFECT_DTE
,OLD_WAC_PACK_PRICE_AMT
,OLD_WAC_UNIT_PRICE_AMT
,OLD_WAC_EFFECT_DTE
,AWP_ID
,AWP_PACK_PRICE_AMT
,AWP_UNIT_PRICE_AMT
,AWP_EFFECT_DTE
,OLD_AWP_PACK_PRICE_AMT
,OLD_AWP_UNIT_PRICE_AMT
,OLD_AWP_EFFECT_DTE
,DP_PACK_PRICE_AMT
,DP_UNIT_PRICE_AMT
,DP_EFFECT_DTE
,OLD_DP_PACK_PRICE_AMT
,OLD_DP_UNIT_PRICE_AMT
,OLD_DP_EFFECT_DTE
,GPPC_UNIT_PRICE_AMT
,GPPC_EFFECT_DTE
,DRUG_GROUP_CDE
,DRUG_GROUP_DESCRIPTION
,DRUG_CLASS_CDE
,DRUG_CLASS_DESCRIPTION
,DRUG_SUB_CLASS_CDE
,DRUG_SUB_CLASS_DESCRIPTION
,DRUG_CDE
,DRUG_DESCRIPTION
,DEA_CLASS_DESCRIPTION
,TEE_DESCRIPTION
,RX_OTC_DESCRIPTION
,THIRD_PARTY_ID_DESCRIPTION
,UNIT_DOSE_PACK_ID_DESCRIPTION
,ROUTE_OF_ADMIN_ID_DESCRIPTION
,MULTI_SOURCE_ID_DESCRIPTION
,BRAND_NAME_ID_DESCRIPTION
,DOSAGE_FORM_ID_DESCRIPTION
,PACK_SIZE_UOM_ID_DESCRIPTION
,DESI_ID_DESCRIPTION
,v_start_stp AS ROW_ADD_STP
,v_stored_proc_name AS ROW_ADD_USER_ID
,v_start_stp AS ROW_UPDATE_STP
,v_stored_proc_name AS ROW_UPDATE_USER_ID

FROM MEDISPAN_TEMP
WHERE RANK_RN = 1
;

END;