
    CREATE PROCEDURE  `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.SP_CUSTOMER_EDI832_PARAMETER_CV_DELTA_LOAD`()
    BEGIN
    /***********************************************************************************************************************

    Author: <Automatically Written Using Code Generator>
    Creation Date: <Insert Date>
    Sproc Purpose: Delta Loading Merge Sproc for CUSTOMER_EDI832_PARAMETER_CV
    Data Sources:  See SQL Below

    ************************************************************************************************************************/
    DECLARE v_start_time timestamp;
    DECLARE v_start_stp timestamp;
    DECLARE v_end_stp timestamp;
    DECLARE v_stored_proc_name STRING;
    DECLARE last_load_timestamp timestamp;

    SET v_start_time = current_timestamp();
    SET v_start_stp = current_timestamp();
    SET v_end_stp = (SELECT CAST('9999-12-31 23:59:59' AS TIMESTAMP));
    SET v_stored_proc_name = 'D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_EDI832_PARAMETER_CV_DELTA_LOAD';
    SET last_load_timestamp = (SELECT MAX(ROW_ADD_STP) FROM `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_EDI832_PARAMETER_CV`);


    MERGE INTO  `PROJECT_ID.D1_PHM_CONFDIM_CUSTOMER.CUSTOMER_EDI832_PARAMETER_CV` AS target
     USING 
      (
     -- Developer's code goes here (SAMPLE CODE BELOW)

         --SELECT 
            a.column_1
            a.column_2
         --FROM 
         -- `PROJECT_ID.VI2_PHM_CONFFACT_BILLING.PHM_SDW__INVOICE_LINE_CV` il
         --JOIN
            --`PROJECT_ID.VI2_PHM_CONFDIM_TIME.PHM_SDW__TIME_DETAIL_CV` t
                --ON il.DTE_KEY_NUM = t.DTE_KEY_NUM
        --WHERE il.D0_UPDATE_STP > last_load_timestamp --- MOST IMPORTANT CONCEPT

      ) AS source
      ON TARGET.PRIMARY_KEY = SOURCE.PRIMARY_KEY
    WHEN MATCHED THEN
      UPDATE SET
        TARGET.KUNNR_CHPDPE_CD_PARAM = SOURCE.KUNNR_CHPDPE_CD_PARAM,
        TARGET.VKORG_CHPDPE_CD_PARAM = SOURCE.VKORG_CHPDPE_CD_PARAM,
        TARGET.VTWEG_CHPDPE_CD_PARAM = SOURCE.VTWEG_CHPDPE_CD_PARAM,
        TARGET.SPART_CHPDPE_CD_PARAM = SOURCE.SPART_CHPDPE_CD_PARAM,
        TARGET.TRADING_PTR_CHPDPE_CD_PARAM = SOURCE.TRADING_PTR_CHPDPE_CD_PARAM,
        TARGET.ACTIVE_CHPDPE_CD_PARAM = SOURCE.ACTIVE_CHPDPE_CD_PARAM,
        TARGET.NHIN_FLG_CHPDPE_CD_PARAM = SOURCE.NHIN_FLG_CHPDPE_CD_PARAM,
        TARGET.AWP_FLG_CHPDPE_CD_PARAM = SOURCE.AWP_FLG_CHPDPE_CD_PARAM,
        TARGET.INV_FLG_CHPDPE_CD_PARAM = SOURCE.INV_FLG_CHPDPE_CD_PARAM,
        TARGET.SUP_340B_FLG_CHPDPE_CD_PARAM = SOURCE.SUP_340B_FLG_CHPDPE_CD_PARAM,
        TARGET.PRIORITY_CHPDPE_CD_PARAM = SOURCE.PRIORITY_CHPDPE_CD_PARAM,
        TARGET.INCODE_CHPDPE_CD_PARAM = SOURCE.INCODE_CHPDPE_CD_PARAM,
        TARGET.DESCR_CHPDPE_IN_CDT = SOURCE.DESCR_CHPDPE_IN_CDT,
        TARGET.SINCODE_CHPDPE_CD_PARAM = SOURCE.SINCODE_CHPDPE_CD_PARAM,
        TARGET.DESCR_CHPDPE_SIN_CDT = SOURCE.DESCR_CHPDPE_SIN_CDT,
        TARGET.SI_TWCODE_CHPDPE_CD_PARAM = SOURCE.SI_TWCODE_CHPDPE_CD_PARAM,
        TARGET.SI_NOOFDAY_CHPDPE_CD_PARAM = SOURCE.SI_NOOFDAY_CHPDPE_CD_PARAM,
        TARGET.SI_NOOFMTH_CHPDPE_CD_PARAM = SOURCE.SI_NOOFMTH_CHPDPE_CD_PARAM,
        TARGET.INV_DAYS_CHPDPE_CD_PARAM = SOURCE.INV_DAYS_CHPDPE_CD_PARAM,
        TARGET.CAT_TYPE1_CHPDPE_CD_PARAM = SOURCE.CAT_TYPE1_CHPDPE_CD_PARAM,
        TARGET.SCOPT1_CHPDPE_CD_PARAM = SOURCE.SCOPT1_CHPDPE_CD_PARAM,
        TARGET.DESCR_CHPDPE_SCOPT1 = SOURCE.DESCR_CHPDPE_SCOPT1,
        TARGET.PROFILE_ID1_CHPDPE_CD_PARAM = SOURCE.PROFILE_ID1_CHPDPE_CD_PARAM,
        TARGET.DEF_EXEC1_CHPDPE_CD_PARAM = SOURCE.DEF_EXEC1_CHPDPE_CD_PARAM,
        TARGET.CAT_TYPE2_CHPDPE_CD_PARAM = SOURCE.CAT_TYPE2_CHPDPE_CD_PARAM,
        TARGET.SCOPT2_CHPDPE_CD_PARAM = SOURCE.SCOPT2_CHPDPE_CD_PARAM,
        TARGET.DESCR_CHPDPE_SCOPT2 = SOURCE.DESCR_CHPDPE_SCOPT2,
        TARGET.PROFILE_ID2_CHPDPE_CD_PARAM = SOURCE.PROFILE_ID2_CHPDPE_CD_PARAM,
        TARGET.DEF_EXEC2_CHPDPE_CD_PARAM = SOURCE.DEF_EXEC2_CHPDPE_CD_PARAM,
        TARGET.ERDAT_CHPDPE_CD_PARAM = SOURCE.ERDAT_CHPDPE_CD_PARAM,
        TARGET.ERNAM_CHPDPE_CD_PARAM = SOURCE.ERNAM_CHPDPE_CD_PARAM,
        TARGET.ERZET_CHPDPE_CD_PARAM = SOURCE.ERZET_CHPDPE_CD_PARAM,
        TARGET.AEDAT_CHPDPE_CD_PARAM = SOURCE.AEDAT_CHPDPE_CD_PARAM,
        TARGET.AENAM_CHPDPE_CD_PARAM = SOURCE.AENAM_CHPDPE_CD_PARAM,
        TARGET.AEZET_CHPDPE_CD_PARAM = SOURCE.AEZET_CHPDPE_CD_PARAM,
        TARGET.CAT_ACC_TYPE_CHPDPE_CD_PARAM = SOURCE.CAT_ACC_TYPE_CHPDPE_CD_PARAM,
        TARGET.NHIN_SORT_OPT_CHPDPE_CD_PARAM = SOURCE.NHIN_SORT_OPT_CHPDPE_CD_PARAM,
        TARGET.BASE_PRICE_CHPDPE_CD_PARAM = SOURCE.BASE_PRICE_CHPDPE_CD_PARAM,
        TARGET.CONT_PRICE_CHPDPE_CD_PARAM = SOURCE.CONT_PRICE_CHPDPE_CD_PARAM,
        TARGET.CATLG_PRICE_CHPDPE_CD_PARAM = SOURCE.CATLG_PRICE_CHPDPE_CD_PARAM,
        TARGET.MSRP_CHPDPE_CD_PARAM = SOURCE.MSRP_CHPDPE_CD_PARAM,
        TARGET.NDC_CHPDPE_CD_PARAM = SOURCE.NDC_CHPDPE_CD_PARAM,
        TARGET.NDC_IND_CHPDPE_CD_PARAM = SOURCE.NDC_IND_CHPDPE_CD_PARAM,
        TARGET.PACK_QTY_CHPDPE_CD_PARAM = SOURCE.PACK_QTY_CHPDPE_CD_PARAM,
        TARGET.ONE_CIN_PER_NDC_CHPDPE_CD_PARAM = SOURCE.ONE_CIN_PER_NDC_CHPDPE_CD_PARAM,
        TARGET.NDC_SORT_ORDER_CHPDPE_CD_PARAM = SOURCE.NDC_SORT_ORDER_CHPDPE_CD_PARAM,
        TARGET.SEND_SUBS_INFO_CHPDPE_CD_PARAM = SOURCE.SEND_SUBS_INFO_CHPDPE_CD_PARAM,
        TARGET.CUST_TZONE_CHPDPE_CD_PARAM = SOURCE.CUST_TZONE_CHPDPE_CD_PARAM,
        TARGET.CUST_FNAME_CHPDPE_CD_PARAM = SOURCE.CUST_FNAME_CHPDPE_CD_PARAM,
        TARGET.DELVRY_IND_CHPDPE_CD_PARAM = SOURCE.DELVRY_IND_CHPDPE_CD_PARAM,
        TARGET.ROW_ADD_STP = SOURCE.ROW_ADD_STP,
        TARGET.ROW_ADD_USER_ID = SOURCE.ROW_ADD_USER_ID,
        TARGET.ROW_UPDATE_STP = SOURCE.ROW_UPDATE_STP,
        TARGET.ROW_UPDATE_USER_ID = SOURCE.ROW_UPDATE_USER_ID
    WHEN NOT MATCHED THEN
      INSERT VALUES
      (
        SOURCE.KUNNR_CHPDPE_CD_PARAM,
        SOURCE.VKORG_CHPDPE_CD_PARAM,
        SOURCE.VTWEG_CHPDPE_CD_PARAM,
        SOURCE.SPART_CHPDPE_CD_PARAM,
        SOURCE.TRADING_PTR_CHPDPE_CD_PARAM,
        SOURCE.ACTIVE_CHPDPE_CD_PARAM,
        SOURCE.NHIN_FLG_CHPDPE_CD_PARAM,
        SOURCE.AWP_FLG_CHPDPE_CD_PARAM,
        SOURCE.INV_FLG_CHPDPE_CD_PARAM,
        SOURCE.SUP_340B_FLG_CHPDPE_CD_PARAM,
        SOURCE.PRIORITY_CHPDPE_CD_PARAM,
        SOURCE.INCODE_CHPDPE_CD_PARAM,
        SOURCE.DESCR_CHPDPE_IN_CDT,
        SOURCE.SINCODE_CHPDPE_CD_PARAM,
        SOURCE.DESCR_CHPDPE_SIN_CDT,
        SOURCE.SI_TWCODE_CHPDPE_CD_PARAM,
        SOURCE.SI_NOOFDAY_CHPDPE_CD_PARAM,
        SOURCE.SI_NOOFMTH_CHPDPE_CD_PARAM,
        SOURCE.INV_DAYS_CHPDPE_CD_PARAM,
        SOURCE.CAT_TYPE1_CHPDPE_CD_PARAM,
        SOURCE.SCOPT1_CHPDPE_CD_PARAM,
        SOURCE.DESCR_CHPDPE_SCOPT1,
        SOURCE.PROFILE_ID1_CHPDPE_CD_PARAM,
        SOURCE.DEF_EXEC1_CHPDPE_CD_PARAM,
        SOURCE.CAT_TYPE2_CHPDPE_CD_PARAM,
        SOURCE.SCOPT2_CHPDPE_CD_PARAM,
        SOURCE.DESCR_CHPDPE_SCOPT2,
        SOURCE.PROFILE_ID2_CHPDPE_CD_PARAM,
        SOURCE.DEF_EXEC2_CHPDPE_CD_PARAM,
        SOURCE.ERDAT_CHPDPE_CD_PARAM,
        SOURCE.ERNAM_CHPDPE_CD_PARAM,
        SOURCE.ERZET_CHPDPE_CD_PARAM,
        SOURCE.AEDAT_CHPDPE_CD_PARAM,
        SOURCE.AENAM_CHPDPE_CD_PARAM,
        SOURCE.AEZET_CHPDPE_CD_PARAM,
        SOURCE.CAT_ACC_TYPE_CHPDPE_CD_PARAM,
        SOURCE.NHIN_SORT_OPT_CHPDPE_CD_PARAM,
        SOURCE.BASE_PRICE_CHPDPE_CD_PARAM,
        SOURCE.CONT_PRICE_CHPDPE_CD_PARAM,
        SOURCE.CATLG_PRICE_CHPDPE_CD_PARAM,
        SOURCE.MSRP_CHPDPE_CD_PARAM,
        SOURCE.NDC_CHPDPE_CD_PARAM,
        SOURCE.NDC_IND_CHPDPE_CD_PARAM,
        SOURCE.PACK_QTY_CHPDPE_CD_PARAM,
        SOURCE.ONE_CIN_PER_NDC_CHPDPE_CD_PARAM,
        SOURCE.NDC_SORT_ORDER_CHPDPE_CD_PARAM,
        SOURCE.SEND_SUBS_INFO_CHPDPE_CD_PARAM,
        SOURCE.CUST_TZONE_CHPDPE_CD_PARAM,
        SOURCE.CUST_FNAME_CHPDPE_CD_PARAM,
        SOURCE.DELVRY_IND_CHPDPE_CD_PARAM,
        SOURCE.ROW_ADD_STP,
        SOURCE.ROW_ADD_USER_ID,
        SOURCE.ROW_UPDATE_STP,
        SOURCE.ROW_UPDATE_USER_ID
      );
    END;
