CREATE PROCEDURE `PROJECT_ID`.D1_PHM_DW_LOG.SP_ADMIN_JOBS_INITIAL_LOAD()
BEGIN
TRUNCATE TABLE `PROJECT_ID`.D1_PHM_DW_LOG.ADMIN_JOBS_T;

INSERT INTO
    `PROJECT_ID`.D1_PHM_DW_LOG.ADMIN_JOBS_T
SELECT
    CURRENT_DATE() AS snapshot_date,
    CURRENT_TIMESTAMP() AS snapshot_timestamp,
    *,
FROM
    `ednacomp-phm-np-cah.region-us`.INFORMATION_SCHEMA.JOBS
WHERE DATE(creation_time) > '2023-09-01'
;

END;