CREATE TABLE `PROJECT_ID.D2_PHM_CONFFACT_PRICING.GRP_CURPRC_TEMP`
(
  group_number STRING,
  group_name STRING,
  group_type_id STRING,
  contract_description STRING,
  group_reference STRING,
  contract_number STRING,
  contract_effective_year INT64,
  contract_effective_month INT64,
  contract_effective_date INT64,
  contract_term_year INT64,
  contract_term_month INT64,
  contract_term_date INT64,
  vendor_number STRING,
  vendor_name STRING,
  parent_vendor_number STRING,
  parent_vendor_name STRING,
  corporate_item_number STRING,
  corporate_description STRING,
  national_drug_code STRING,
  contract_cost NUMERIC,
  contract_sell NUMERIC,
  parent_affiliation_id STRING,
  parent_affiliation STRING,
  vendor_reference STRING,
  item_effective_date STRING,
  record_effective_date STRING
);