CREATE VIEW `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_BOT_DEA_RGSTRN_FEED_COMMON__DEA_REGISTRATION_CV`
OPTIONS(
  friendly_name="PHM_BOT_DEA_RGSTRN_FEED_COMMON__DEA_REGISTRATION_CV"
)
AS SELECT DEAREGISTRATIONNUMBER, BUSINESSACTIVITYCODE, DRUGSCHEDULES, EXPIRATIONDATE, NAME, ADDITIONALCOMPANYINFO, ADDRESS1, ADDRESS2, CITY, STATE, ZIP, BUSINESSACTIVITYSUBCODE, PAYMENTINDICATOR, ACTIVITY, DEGREE, STATELICENSENUMBER, STATECSLICENSENUMBER, D0_START_STP, D0_END_STP, D0_ADD_STP, D0_ADD_USER_ID, D0_UPDATE_STP, D0_UPDATE_USER_ID, D0_ACTION_ID, D0_SOURCE_ID, D0_CURR_VRSN_FLG, D0_SEQ_NUM FROM VI0_PHM_BOT_DEA_RGSTRN_FEED_COMMON_NP.DEA_REGISTRATION_CV;