CREATE VIEW `PROJECT_ID.VI2_PHM_CONFDIM_CUSTOMER.PHM_EDA_PRHVR_CUSTOMER_MSTR__CUSTOMER_MASTER_DELTA_CV`
OPTIONS(
  friendly_name="PHM_EDA_PRHVR_CUSTOMER_MSTR__CUSTOMER_MASTER_DELTA_CV"
)
AS SELECT DIVISIONNUMBER, ADDRESS2, DEALICENSE, DEAEXPIRATION, POSTALCODE, ADDRESS1, CITY, NAME, CONTACTPHONE, ACCOUNTSTATUSFLAG, CUSTOMERCROSSREFERENCE, STATE, SBPEXPIRATION, FAXNUMBER, COUNTRY, SBPLICENSE, HINBASECODE, D0_START_STP, D0_END_STP, D0_ADD_STP, D0_ADD_USER_ID, D0_UPDATE_STP, D0_UPDATE_USER_ID, D0_ACTION_ID, D0_SOURCE_ID, D0_CURR_VRSN_FLG, D0_SEQ_NUM FROM VI0_PHM_EDA_PRHVR_CUSTOMER_MSTR_NP.CUSTOMER_MASTER_DELTA_CV;